Repository Budibase/budibase, pull requests merged in 2023-10, with the labels that each got.

#12048 Preparing develop master ci migration
  .github/workflows/budibase_ci.yml
  .github/workflows/close-featurebranch.yml
  .github/workflows/deploy-featurebranch.yml
  .github/workflows/deploy-preprod.yml
  .github/workflows/release-develop.yml
  .github/workflows/release-master.yml
  .github/workflows/tag-prerelease.yml
  .github/workflows/tag-release.yml
Labels: do not merge

#12033 [Added] New plan type BUSINESS_PLUS
  packages/types/src/sdk/featureFlag.ts
  packages/types/src/sdk/licensing/plan.ts
Labels: enhancement, account-portal

#12100 Improving typing of external row API
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/sdk/app/rows/external.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/internal.ts
Labels: firestorm

#12097 Added testimonial check to reset and forgot pages.
  packages/builder/src/pages/builder/auth/forgot.svelte
  packages/builder/src/pages/builder/auth/reset.svelte
Labels: premium-enterprise, bb-settings

#11981 Internal DB enrichment performance improvements
  packages/frontend-core/src/api/relationships.js
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/controllers/row/staticFormula.ts
  packages/server/src/api/controllers/row/utils.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/controllers/user.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/db/linkedRows/linkUtils.ts
  packages/server/src/middleware/tests/trimViewRowInfo.spec.ts
  packages/server/src/sdk/app/datasources/datasources.ts
  packages/server/src/sdk/app/rows/utils.ts
  packages/server/src/sdk/app/tables/index.ts
  packages/server/src/utilities/rowProcessor/index.ts
Labels: firestorm

#12118 Disable CLA bot on non-master PR merges
  .github/workflows/cla.yml
Labels: firestorm

#12106 Remove npm dependency from apps and worker docker images
  .github/workflows/budibase_ci.yml
  hosting/docker-compose.build.yaml
  hosting/single/Dockerfile.v2
  package.json
  packages/backend-core/package.json
  packages/server/Dockerfile.v2
  packages/server/package.json
  packages/string-templates/package.json
  packages/worker/Dockerfile.v2
  packages/worker/package.json
  scripts/removeWorkspaceDependencies.sh
  yarn.lock
Labels: firestorm

#12107 Fix budibase/couchdb multi-arch build
  hosting/couchdb/Dockerfile
Labels: firestorm

#12128 Reduce nx cloud usage
  .github/workflows/budibase_ci.yml
  nx.json
Labels: firestorm

#12126 Push QA on master commit
  .github/workflows/deploy-qa.yml
  .github/workflows/release-master.yml
Labels: firestorm

#12127 Datasource errors blocking full creation steps
  packages/builder/src/stores/backend/datasources.js
Labels: firestorm

#12129 CI fixes and tweaks
  .github/workflows/budibase_ci.yml
  .github/workflows/deploy-qa.yml
  hosting/single/Dockerfile.v2
Labels: firestorm

#12117 Many-to-many user relationship -> user column migration
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/tables/migration.ts
  packages/server/src/sdk/users/tests/utils.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
Labels: firestorm

#12151 Many-to-one user relationship -> user column migration
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/sdk/app/tables/migration.ts
Labels: firestorm

#12139 Package version from env instead of package.json
  .github/workflows/release-singleimage-test.yml
  hosting/docker-compose.build.yaml
  hosting/single/Dockerfile.v2
  packages/backend-core/src/environment.ts
  packages/server/Dockerfile.v2
  packages/server/package.json
  packages/server/scripts/dev/manage.js
  packages/server/src/api/routes/tests/debug.spec.ts
  packages/server/src/api/routes/tests/dev.spec.js
  packages/server/src/tests/jestEnv.ts
  packages/worker/Dockerfile.v2
  packages/worker/package.json
  packages/worker/scripts/dev/manage.js
  packages/worker/src/tests/jestEnv.ts
  scripts/build-single-image.sh
Labels: firestorm

#11980 Account Portal License Key - Activate & Manage Tests
  qa-core/package.json
  qa-core/src/account-api/api/AccountInternalAPI.ts
  qa-core/src/account-api/api/apis/LicenseAPI.ts
  qa-core/src/account-api/api/apis/StripeAPI.ts
  qa-core/src/account-api/api/apis/index.ts
  qa-core/src/account-api/tests/licensing/license.activate.spec.ts
  qa-core/src/internal-api/api/apis/LicenseAPI.ts
Labels: stale

#12163 Client library fetching through server
  packages/backend-core/src/objectStore/buckets/app.ts
  packages/backend-core/src/objectStore/buckets/plugins.ts
  packages/backend-core/src/objectStore/buckets/tests/app.spec.ts
  packages/backend-core/src/objectStore/objectStore.ts
  packages/server/src/api/controllers/static/index.ts
Labels: firestorm

#12172 [Changed] Reactivate sync quotas migration
  packages/types/src/sdk/migrations.ts
Labels: enhancement

#12158 Frontend changes for the user column migration work.
  packages/frontend-core/src/api/tables.js
  packages/frontend-core/src/components/grid/cells/HeaderCell.svelte
  packages/frontend-core/src/components/grid/controls/MigrationModal.svelte
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/integrations/utils.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/sdk/app/tables/migration.ts
  packages/server/src/tests/utilities/api/table.ts
  packages/server/src/websockets/builder.ts
  packages/server/src/websockets/websocket.ts
Labels: firestorm

#12181 Tweaks for single release pipeline
  .github/workflows/release-singleimage-test.yml
  package.json
  packages/server/Dockerfile.v2
  packages/worker/Dockerfile.v2
  scripts/updateWorkspaceVersions.V2.sh
Labels: firestorm

#12185 Replace several instances of `any` with `DatabaseQueryOpts`.
  packages/backend-core/package.json
  packages/backend-core/src/docIds/params.ts
  packages/backend-core/src/users/db.ts
  packages/backend-core/src/users/users.ts
  packages/server/src/db/linkedRows/linkUtils.ts
  packages/server/src/migrations/functions/backfill/global/configs.ts
  packages/server/src/sdk/app/links/links.ts
  packages/types/package.json
  packages/types/src/sdk/db.ts
  yarn.lock
Labels: firestorm

#12198 Remove APIDoc comments.
  packages/server/src/api/routes/row.ts
  packages/server/src/api/routes/table.ts
Labels: firestorm

#12212 Use docker image v2 for production
  .github/workflows/release-master.yml
  .github/workflows/release-singleimage.yml
  packages/server/Dockerfile
  packages/server/package.json
  packages/worker/Dockerfile
  packages/worker/package.json
Labels: firestorm

#12214 Fix pushing images v2
  .github/workflows/release-master.yml
  hosting/scripts/linux/release-to-docker-hub.sh
  package.json
  packages/server/package.json
  packages/worker/package.json
Labels: firestorm

#12202 Limit cloud uploads to a specific set of filetypes.
  packages/bbui/src/Form/Core/Dropzone.svelte
  packages/builder/src/components/common/Dropzone.svelte
  packages/frontend-core/src/components/grid/cells/AttachmentCell.svelte
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/tests/attachment.spec.ts
  packages/server/src/api/routes/tests/static.spec.js
  packages/server/src/api/routes/tests/webhook.spec.ts
  packages/server/src/integrations/tests/googlesheets.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/attachment.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/shared-core/src/constants.ts
  packages/types/src/api/web/app/attachment.ts
  packages/types/src/api/web/app/index.ts
Labels: firestorm

#12226 Removing automation logs from app backups
  packages/backend-core/__mocks__/aws-sdk.ts
  packages/backend-core/tests/core/utilities/mocks/date.ts
  packages/server/__mocks__/aws-sdk.ts
  packages/server/src/api/routes/tests/backup.spec.ts
  packages/server/src/sdk/app/backups/exports.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/backup.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/types/src/api/web/app/backup.ts
Labels: firestorm
