Repository Budibase/budibase, pull requests merged in 2023-11, with the labels that each got.

#12243 Single image build fixes
  hosting/scripts/install-minio.sh
  hosting/single/Dockerfile.v2
  hosting/single/runner.sh
  scripts/install-minio.sh
  scripts/install-node.sh
Labels: firestorm

#12237 Updating bull parameters - help queue stalling
  packages/backend-core/src/index.ts
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/backend-core/src/queue/queue.ts
  packages/backend-core/src/utils/Duration.ts
  packages/backend-core/src/utils/index.ts
  packages/backend-core/src/utils/tests/Duration.spec.ts
Labels: firestorm

#12196 Added selected class to data provider options.
  packages/builder/src/components/design/settings/componentSettings.js
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceCategory.svelte
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
  packages/builder/src/components/design/settings/controls/SchemaSelect.svelte
Labels: data provider, picker

#12233 Fix issue with directional relationship being swapped
  packages/builder/src/components/backend/Datasources/CreateEditRelationship.svelte
Labels: firestorm

#12283 [Changed] Posthog's feature flags Ids
  packages/types/src/sdk/featureFlag.ts
Labels: enhancement, account-portal

#12174 Automation naming and UX updates
  packages/builder/.gitignore
  packages/builder/src/builderStore/store/automation/index.js
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItem.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItemHeader.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/CodeEditorModal.svelte
  packages/builder/src/components/automation/SetupPanel/QueryParamSelector.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/builder/src/components/automation/SetupPanel/TableSelector.svelte
  packages/builder/src/components/common/bindings/DrawerBindableSlot.svelte
  packages/builder/src/pages/builder/app/[application]/automation/_layout.svelte
Labels: firestorm

#12280 Restore bull parameter changes + reduce Redis config complexity
  packages/backend-core/src/index.ts
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/backend-core/src/queue/queue.ts
  packages/backend-core/src/redis/redis.ts
  packages/backend-core/src/redis/utils.ts
  packages/backend-core/src/utils/Duration.ts
  packages/backend-core/src/utils/index.ts
  packages/backend-core/src/utils/tests/Duration.spec.ts
  packages/server/src/api/routes/public/index.ts
  packages/worker/src/index.ts
Labels: firestorm

#12320 Reduce the likelihood of collisions in table names by using a UUID instead of a random word.
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm

#12314 Ensure that the DB always returns Documents, and other type changes.
  packages/backend-core/src/constants/db.ts
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/views.ts
  packages/backend-core/src/users/db.ts
  packages/backend-core/src/users/users.ts
  packages/server/src/api/controllers/layout.ts
  packages/server/src/api/controllers/permission.ts
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/controllers/row/staticFormula.ts
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/api/controllers/view/utils.ts
  packages/server/src/api/controllers/view/viewBuilder.ts
  packages/server/src/api/controllers/view/views.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/db/inMemoryView.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/sdk/app/applications/import.ts
  packages/server/src/sdk/app/applications/sync.ts
  packages/server/src/sdk/app/datasources/datasources.ts
  packages/server/src/sdk/app/rows/search/internal.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/sdk/users/utils.ts
  packages/server/src/utilities/global.ts
  packages/server/src/utilities/routing/index.ts
  packages/types/src/documents/app/layout.ts
  packages/types/src/documents/app/user.ts
  packages/types/src/documents/app/view.ts
  packages/types/src/documents/pouch.ts
  packages/types/src/sdk/db.ts
  packages/worker/src/constants/templates/index.ts
  packages/worker/src/utilities/email.ts
Labels: firestorm

#12322 Convert user.spec.js to user.spec.ts
  packages/server/src/api/controllers/auth.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/controllers/user.ts
  packages/server/src/api/routes/tests/user.spec.js
  packages/server/src/api/routes/tests/user.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/user.ts
  packages/server/src/utilities/users.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/app/user.ts
  packages/types/src/documents/account/flag.ts
  packages/types/src/documents/account/index.ts
Labels: firestorm

#12301 Datasource plus formulas using relationships
  packages/backend-core/src/utils/tests/utils.spec.ts
  packages/backend-core/src/utils/utils.ts
  packages/server/src/api/controllers/deploy/index.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/staticFormula.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/db/linkedRows/linkUtils.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/tests/utilities/api/row.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/utils.ts
Labels: firestorm

#12338 Attempt to fix QA-core flaky tests
  packages/server/src/api/routes/public/index.ts
  packages/server/src/environment.ts
  qa-core/package.json
Labels: firestorm

#12354 Fix issues with data UI loading some tables
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/controllers/row/utils.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/db/utils.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/sdk/tests/tables.spec.ts
  packages/server/src/utilities/global.ts
  packages/types/src/sdk/db.ts
Labels: firestorm

#12355 Fix issue in relationship definitions where primary / foreign key selection didn't trigger properly
  packages/builder/src/components/backend/Datasources/CreateEditRelationship.svelte
Labels: firestorm

#12361 Further fixes for app user grid
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/redis/redis.ts
Labels: firestorm

#12346 Prevent sending invites to users who have already been invited.
  packages/backend-core/src/index.ts
  packages/backend-core/src/redis/index.ts
  packages/backend-core/src/redis/invite.ts
  packages/backend-core/src/redis/passwordReset.ts
  packages/backend-core/src/users/db.ts
  packages/backend-core/src/users/lookup.ts
  packages/backend-core/tests/core/utilities/structures/users.ts
  packages/types/src/api/web/user.ts
  packages/worker/src/api/controllers/global/users.ts
  packages/worker/src/api/routes/global/tests/users.spec.ts
  packages/worker/src/index.ts
  packages/worker/src/sdk/auth/auth.ts
  packages/worker/src/sdk/users/users.ts
  packages/worker/src/tests/api/users.ts
  packages/worker/src/utilities/email.ts
  packages/worker/src/utilities/redis.ts
  qa-core/yarn.lock
Labels: firestorm

#12401 [Chore] Lint js tests
  .prettierignore
  packages/backend-core/src/db/tests/index.spec.js
  packages/backend-core/tests/core/users/users.spec.js
  packages/server/src/api/controllers/query/import/sources/tests/curl/curl.spec.js
  packages/server/src/api/controllers/query/import/sources/tests/openapi2/openapi2.spec.js
  packages/server/src/api/controllers/query/import/tests/index.spec.js
  packages/server/src/api/controllers/view/tests/viewBuilder.spec.js
  packages/server/src/api/routes/public/tests/metrics.spec.js
  packages/server/src/api/routes/tests/analytics.spec.js
  packages/server/src/api/routes/tests/apikeys.spec.js
  packages/server/src/api/routes/tests/auth.spec.js
  packages/server/src/api/routes/tests/component.spec.js
  packages/server/src/api/routes/tests/dev.spec.js
  packages/server/src/api/routes/tests/integration.spec.js
  packages/server/src/api/routes/tests/layout.spec.js
  packages/server/src/api/routes/tests/metadata.spec.js
  packages/server/src/api/routes/tests/query.seq.spec.js
  packages/server/src/api/routes/tests/role.spec.js
  packages/server/src/api/routes/tests/routing.spec.js
  packages/server/src/api/routes/tests/screen.spec.js
  packages/server/src/api/routes/tests/templates.spec.js
  packages/server/src/api/routes/tests/view.spec.js
  packages/server/src/automations/tests/bash.spec.js
  packages/server/src/automations/tests/delay.spec.js
  packages/server/src/automations/tests/discord.spec.js
  packages/server/src/automations/tests/executeQuery.spec.js
  packages/server/src/automations/tests/executeScript.spec.js
  packages/server/src/automations/tests/outgoingWebhook.spec.js
  packages/server/src/automations/tests/serverLog.spec.js
  packages/server/src/db/tests/linkController.spec.js
  packages/server/src/db/tests/linkTests.spec.js
  packages/server/src/middleware/tests/resourceId.spec.js
  packages/server/src/middleware/tests/selfhost.spec.js
  packages/server/src/migrations/functions/tests/appUrls.spec.js
  packages/server/src/migrations/functions/tests/userEmailViewCasing.spec.js
  packages/string-templates/test/basic.spec.js
  packages/string-templates/test/escapes.spec.js
  packages/string-templates/test/hbsToJs.spec.js
  packages/string-templates/test/helpers.spec.js
  packages/string-templates/test/javascript.spec.js
Labels: firestorm

#12412 Improving redlock warning information
  packages/backend-core/src/redis/redlockImpl.ts
Labels: firestorm

#12411 Move from an allow list to a block list of file extensions.
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/tests/attachment.spec.ts
  packages/shared-core/src/constants.ts
Labels: firestorm

#12417 Allowing use of BB_ADMIN environment variables at all times
  packages/backend-core/src/users/db.ts
  packages/backend-core/src/users/users.ts
  packages/server/src/startup.ts
  packages/server/src/utilities/workerRequests.ts
  packages/worker/src/api/controllers/global/users.ts
Labels: firestorm

#12356 Add search capabilities to data section
  packages/builder/src/components/backend/DatasourceNavigator/DatasourceNavigator.svelte
  packages/builder/src/components/backend/DatasourceNavigator/datasourceUtils.js
  packages/builder/src/components/backend/DatasourceNavigator/tests/datasourceUtils.spec.js
  packages/builder/src/components/backend/TableNavigator/TableNavigator.svelte
  packages/builder/src/components/common/NavHeader.svelte
  packages/builder/src/components/common/NavItem.svelte
  packages/builder/src/components/design/Panel.svelte
  packages/builder/src/helpers/keyUtils.js
  packages/builder/src/pages/builder/app/[application]/data/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/index.svelte
  packages/builder/src/pages/builder/portal/apps/_components/PortalSideBar.svelte
Labels: firestorm

#12466 Remove codecov upload from PR CI
  .github/workflows/budibase_ci.yml
Labels: firestorm

#12469 fix: use /health and remove 301 from the ingress
  charts/budibase/templates/alb-ingress.yaml
Labels: devops

#12468 Fix relationship saving when both sides of relationship use same field name (internal)
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/db/linkedRows/LinkController.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/server/src/sdk/app/tables/external/utils.ts
Labels: firestorm
