Repository Budibase/budibase, pull requests merged in 2024-09, with the labels that each got.

#14411 Poc authenticated iframe
  packages/builder/src/dataBinding.js
  packages/client/src/components/ClientApp.svelte
  packages/client/src/components/context/EmbedProvider.svelte
Labels: size/m

#14486 Disable creation of createdAt and createdBy auto columns when default values is enabled.
  packages/backend-core/src/features/index.ts
  packages/builder/src/helpers/utils.js
Labels: firestorm, size/s

#14499 Add LICENSE_TYPE
  .github/workflows/deploy-featurebranch.yml
Labels: size/xs

#14500 Budi 8607 Fixes App-Preview z-index
  packages/builder/src/pages/builder/app/[application]/_components/PreviewOverlay.svelte
Labels: size/xs

#14501 Types for new view calculation feature.
  packages/types/src/documents/app/view.ts
Labels: firestorm, size/s

#14476 Row action view security
  packages/backend-core/src/docIds/params.ts
  packages/server/src/api/controllers/rowAction/crud.ts
  packages/server/src/api/routes/rowAction.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/middleware/triggerRowActionAuthorised.ts
  packages/server/src/sdk/app/automations/utils.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/server/src/tests/utilities/api/base.ts
  packages/server/src/tests/utilities/api/rowAction.ts
  packages/server/src/tests/utilities/structures.ts
  packages/types/src/api/web/app/rowAction.ts
  packages/types/src/documents/app/rowAction.ts
Labels: firestorm, size/l

#14461 Refactor automation orchestrator to support branching
  packages/server/src/automations/automationUtils.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/threads/automation.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/helpers/helpers.ts
  packages/worker/src/api/routes/global/tests/realEmail.spec.ts
Labels: firestorm, feature-branch, size/l

#14482 Display relationship fields
  packages/frontend-core/src/components/grid/cells/RelationshipCell.svelte
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/s

#14503 Support updating names
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/m

#14457 Pick relationship fields
  packages/backend-core/src/features/index.ts
  packages/builder/src/components/backend/DataTable/ViewV2DataTable.svelte
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/frontend-core/src/components/grid/cells/RelationshipCell.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingContent.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/frontend-core/src/components/grid/stores/cache.js
  packages/frontend-core/src/components/grid/stores/datasource.js
  packages/frontend-core/src/constants.js
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/controllers/row/staticFormula.ts
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/middleware/trimViewRowInfo.ts
  packages/server/src/sdk/app/rows/external.ts
  packages/server/src/sdk/app/rows/internal.ts
  packages/server/src/sdk/app/rows/rows.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/internal/internal.ts
  packages/server/src/sdk/app/rows/search/internal/lucene.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/server/src/sdk/app/rows/utils.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/sdk/app/tables/tests/tables.spec.ts
  packages/server/src/sdk/app/views/external.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/sdk/app/views/internal.ts
  packages/server/src/sdk/app/views/tests/views.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/types/src/documents/app/view.ts
  packages/types/src/sdk/featureFlag.ts
  packages/types/src/sdk/row.ts
  packages/types/src/sdk/view.ts
Labels: firestorm, feature-branch, size/xl

#14507 Run row action as sync
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/sdk/app/rowActions.ts
Labels: firestorm, size/s

#14512 Don't add PR message on XL PRs
  .github/workflows/pr-labeler.yml
Labels: size/xs

#14515 Test against SQL Server 2017, get JSON aggregation of relationships working under 2017.
  packages/backend-core/src/sql/sql.ts
  packages/server/datasource-sha.env
  packages/server/src/integrations/microsoftSqlServer.ts
Labels: firestorm, size/s

#14508 Add API validation and some tests for automation branching
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/tests/utilities/api/automation.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/m

#14514 fix issue with multiple loops breaking automation context
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/s

#14529 Fix issue with enriching screen definitions causing bad component instances to be parsed
  packages/client/src/components/Component.svelte
  packages/client/src/components/Screen.svelte
  packages/client/src/components/app/container/GridContainer.svelte
Labels: size/s

#14527 Fix: unable to upgrade plan
  packages/builder/src/pages/builder/portal/_components/LockedFeature.svelte
  packages/builder/src/pages/builder/portal/users/users/index.svelte
Labels: size/s

#14509 Apply new relationship retrieval to all SQL DBs
  packages/backend-core/src/sql/sql.ts
  packages/backend-core/src/sql/utils.ts
  packages/server/datasource-sha.env
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/microsoftSqlServer.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/l

#14538 Add old roles
  packages/frontend-core/src/constants.js
Labels: size/xs

#14522 Feature flag the branch action definition
  packages/backend-core/src/features/index.ts
  packages/server/src/automations/actions.ts
Labels: firestorm, size/xs

#14539 Fix relationship popover click behaviour
  packages/frontend-core/src/components/grid/overlays/GridPopover.svelte
Labels: firestorm, size/xs

#14540 Fix long popover for relationship column pickers
  packages/frontend-core/src/components/grid/controls/ColumnsSettingContent.svelte
Labels: firestorm, size/xs

#14542 Fix to accommodate filtering updates for GoogleSheets
  packages/server/src/integrations/googlesheets.ts
  packages/shared-core/src/filters.ts
Labels: size/s

#14535 [BUDI-8579] Create more realistic tests for Google Sheets
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/integrations/tests/googlesheets.spec.ts
  packages/server/src/integrations/tests/utils/googlesheets.ts
  packages/shared-core/src/filters.ts
Labels: firestorm, size/xl

#14548 More google sheets tests
  packages/server/src/integrations/tests/googlesheets.spec.ts
  packages/server/src/integrations/tests/utils/googlesheets.ts
Labels: firestorm, size/m

#14532 SQL - utilise JSON aggregations for relationships
  packages/backend-core/src/environment.ts
  packages/backend-core/src/sql/sql.ts
  packages/backend-core/src/sql/utils.ts
  packages/server/datasource-sha.env
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/environment.ts
  packages/server/src/integrations/microsoftSqlServer.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/sdk/app/applications/sync.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/xl

#14555 onEmptyFilter fixes for logical operators
  packages/server/src/api/routes/tests/search.spec.ts
  packages/shared-core/src/filters.ts
Labels: firestorm, size/s

#14562 Update logic when no branch condition is met
  packages/server/src/automations/tests/scenarios/branching.spec.ts
  packages/server/src/automations/tests/scenarios/looping.spec.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/threads/automation.ts
  packages/types/src/documents/app/automation/automation.ts
Labels: firestorm, size/l

#14564 updating budibase apps image to use alpine
  packages/server/Dockerfile
Labels: size/s

#14547 Allow an account holder to login to account-portal if the tenant has been deleted.
  .github/workflows/budibase_ci.yml
  packages/backend-core/src/cache/user.ts
  packages/backend-core/src/middleware/authenticated.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/threads/query.ts
  packages/server/src/utilities/global.ts
  packages/server/src/utilities/rowProcessor/bbReferenceProcessor.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/tests/bbReferenceProcessor.spec.ts
  packages/types/src/sdk/auth.ts
  packages/worker/src/sdk/auth/auth.ts
  packages/worker/src/tests/TestConfiguration.ts
Labels: size/m

#14565 Fixing role API validator (for saving)
  packages/backend-core/src/security/roles.ts
  packages/server/src/api/controllers/permission.ts
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/sdk/app/permissions/index.ts
  packages/types/src/documents/app/role.ts
  packages/types/src/documents/global/user.ts
Labels: firestorm, size/s

#14569 Re-add account-portal tests into Budibase CI
  .github/workflows/budibase_ci.yml
Labels: size/xs

#14368 Fix user access roles from displaying business
  packages/builder/src/components/common/RoleSelect.svelte
  packages/frontend-core/src/constants.js
Labels: size/s

#14570 Role metadata and view controls
  packages/backend-core/src/security/roles.ts
  packages/backend-core/tests/core/utilities/mocks/licenses.ts
  packages/server/src/api/controllers/permission.ts
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/routes/tests/permissions.spec.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/sdk/app/permissions/index.ts
  packages/server/src/sdk/app/permissions/tests/permissions.spec.ts
  packages/shared-core/src/constants/colors.ts
  packages/shared-core/src/constants/index.ts
  packages/types/src/api/web/app/permission.ts
  packages/types/src/api/web/role.ts
  packages/types/src/documents/app/role.ts
  packages/types/src/sdk/licensing/feature.ts
  packages/worker/src/api/routes/global/tests/roles.spec.ts
Labels: firestorm, size/m

#14572 updating JS dependencies to get rid of vulns
  package.json
  packages/server/package.json
  yarn.lock
Labels: size/xs

#14579 Role name and display name updates
  packages/backend-core/src/security/roles.ts
  packages/server/src/api/controllers/role.ts
  packages/worker/src/api/routes/global/tests/roles.spec.ts
Labels: size/s

#14581 Fix for row automation triggers when table deleted
  packages/server/src/automations/triggers.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/types/src/sdk/automations/index.ts
Labels: firestorm, size/s

#14586 More google sheets tests
  packages/server/src/integrations/tests/googlesheets.spec.ts
  packages/server/src/integrations/tests/utils/googlesheets.ts
Labels: firestorm, size/m

#14589 Fix Google Sheets pagination.
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/integrations/tests/googlesheets.spec.ts
Labels: firestorm, size/s

#14588 Fix Postgres "cannot pass more than 100 arguments" issue
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
Labels: firestorm, size/m

#14554 Update automations to default to using names for accessing context
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/helpers/automations/nameHelpers.js
  packages/builder/src/helpers/tests/nameHelpers.spec.js
  packages/builder/src/stores/builder/automations.js
  packages/server/src/automations/tests/scenarios/looping.spec.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/definitions/automations.ts
  packages/server/src/threads/automation.ts
  packages/types/src/documents/app/automation/automation.ts
Labels: firestorm, feature-branch, size/l

#14546 Filter groups
  packages/backend-core/src/users/users.ts
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
  packages/builder/src/components/backend/DataTable/buttons/TableFilterButton.svelte
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterBuilder.svelte
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterEditor.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/GridColumnConfiguration.svelte
  packages/builder/src/components/design/settings/controls/TableConditionEditor.svelte
  packages/builder/src/stores/builder/components.js
  packages/builder/src/stores/portal/featureFlags.js
  packages/builder/src/stores/portal/index.js
  packages/client/manifest.json
  packages/client/src/components/app/DataProvider.svelte
  packages/client/src/components/app/dynamic-filter/DynamicFilter.svelte
  packages/client/src/components/app/dynamic-filter/FilterModal.svelte
  packages/frontend-core/src/api/tables.js
  packages/frontend-core/src/components/CoreFilterBuilder.svelte
  packages/frontend-core/src/components/FilterBuilder.svelte
  packages/frontend-core/src/components/FilterField.svelte
  packages/frontend-core/src/components/FilterUsers.svelte
  packages/frontend-core/src/components/grid/stores/filter.js
  packages/frontend-core/src/components/index.js
  packages/frontend-core/src/constants.js
  packages/frontend-core/src/fetch/DataFetch.js
  packages/frontend-core/src/fetch/UserFetch.js
  packages/frontend-core/src/fetch/ViewV2Fetch.js
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/sdk/app/rows/queryUtils.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/utils.ts
  packages/types/src/api/web/searchFilter.ts
  packages/types/src/documents/app/view.ts
  packages/types/src/sdk/search.ts
  packages/worker/src/api/controllers/global/users.ts
  yarn.lock
Labels: size/xl

#14607 Require a flag to be set to query PostHog for feature flags.
  packages/backend-core/src/environment.ts
  packages/backend-core/src/features/index.ts
  packages/backend-core/src/features/tests/features.spec.ts
Labels: firestorm, size/xs

#14601 Add table ID to row deletion requests that only contain string IDs
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/routes/tests/row.spec.ts
Labels: size/s

#14606 Fix conditions with empty values falsely evaluating to true
  packages/client/src/utils/conditions.js
Labels: size/xs

#14610 `fetchSchema` tests for Google Sheets integration
  packages/server/package.json
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/integrations/tests/googlesheets.spec.ts
  packages/server/src/integrations/tests/utils/googlesheets.ts
  yarn.lock
Labels: firestorm, size/m

#14592 Make view readonly columns available for free
  packages/backend-core/tests/core/utilities/mocks/licenses.ts
  packages/builder/src/components/backend/DataTable/ViewV2DataTable.svelte
  packages/builder/src/stores/portal/licensing.js
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
Labels: size/m

#14614 Update view handling of filters
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.js
  packages/frontend-core/src/components/grid/stores/filter.js
  packages/frontend-core/src/fetch/DataFetch.js
  packages/frontend-core/src/fetch/ViewV2Fetch.js
Labels: size/m

#14616 Updating CouchDB image versions across the board to v3.3.3-sqs-v2.1.1
  .github/workflows/budibase_ci.yml
  charts/budibase/values.yaml
  globalSetup.ts
  hosting/single/Dockerfile
  scripts/build-single-image-sqs.sh
Labels: firestorm, size/s

#14627 Fixing AI test cases.
  packages/server/src/automations/tests/openai.spec.ts
  yarn.lock
Labels: firestorm, size/s

#14612 Google Sheets search tests.
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/integrations/tests/googlesheets.spec.ts
  packages/server/src/integrations/tests/utils/googlesheets.ts
Labels: firestorm, size/m

#14629 Some bug fixes
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItemHeader.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
Labels: firestorm, size/s

#14630 MariaDB - avoid using correlated sub-queries
  packages/backend-core/src/sql/sql.ts
  packages/backend-core/src/sql/sqlTable.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/mysql.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/server/src/sdk/app/tables/external/utils.ts
  packages/server/src/tests/utilities/structures.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/m

#14636 App metadata missing - temp fix
  packages/backend-core/src/cache/appMetadata.ts
  packages/backend-core/src/db/couch/DatabaseImpl.ts
Labels: firestorm, size/s

#14637 Enrich squashed links values
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/db/linkedRows/index.ts
Labels: firestorm, size/m

#14613 Shrink the size of the attachment fields set to "compact"
  packages/bbui/src/Form/Core/Dropzone.svelte
Labels: size/xs

#14634 More automation tests
  packages/server/src/automations/tests/scenarios/looping.spec.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
Labels: firestorm, size/m

#14646 Ai configs design updates
  packages/builder/src/pages/builder/portal/settings/ai/AIConfigTile.svelte
  packages/builder/src/pages/builder/portal/settings/ai/AISettings.spec.js
  packages/builder/src/pages/builder/portal/settings/ai/ConfigModal.svelte
  packages/builder/src/pages/builder/portal/settings/ai/constants.js
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
  packages/builder/src/pages/builder/portal/settings/ai/logos/AzureOpenAI.svelte
  packages/builder/src/pages/builder/portal/settings/index.svelte
Labels: feature-branch, size/m

#14649 Fix small issue with conditions in branches
  packages/server/src/automations/tests/scenarios/branching.spec.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/s

#14597 Default view permissions to parent table roles
  packages/server/src/api/controllers/permission.ts
  packages/server/src/api/routes/tests/permissions.spec.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/permissions/index.ts
  packages/server/src/sdk/app/views/index.ts
Labels: size/m

#14639 Display related columns in table
  packages/backend-core/src/features/index.ts
  packages/builder/src/components/backend/DataTable/Table.svelte
  packages/builder/src/components/backend/DataTable/ViewV2DataTable.svelte
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/components/backend/TableNavigator/TableDataImport.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/GridColumnConfiguration.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/getColumns.js
  packages/builder/src/components/design/settings/controls/SortableFieldSelect.svelte
  packages/client/src/components/app/deprecated/table/Table.svelte
  packages/frontend-core/src/components/grid/cells/AttachmentCell.svelte
  packages/frontend-core/src/components/grid/cells/HeaderCell.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingContent.svelte
  packages/frontend-core/src/components/grid/controls/SortButton.svelte
  packages/frontend-core/src/components/grid/lib/renderers.js
  packages/frontend-core/src/components/grid/stores/columns.js
  packages/frontend-core/src/components/grid/stores/datasource.js
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.js
  packages/frontend-core/src/components/grid/stores/reorder.js
  packages/frontend-core/src/components/grid/stores/resize.js
  packages/frontend-core/src/components/grid/stores/rows.js
  packages/frontend-core/src/utils/index.js
  packages/frontend-core/src/utils/relatedColumns.js
  packages/frontend-core/src/utils/table.js
  packages/server/src/api/routes/tests/row.spec.ts
Labels: feature-branch, size/m

#14650 Enriched relationship view performance improvement
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/utilities/rowProcessor/index.ts
Labels: firestorm, size/s

#14651 Fix OSS build issues
  yarn.lock
Labels: firestorm, size/xs

#14666 Fix broken trigger binding
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
Labels: firestorm, size/xs

#14667 Move isSupportedUserSearch from backend-core to shared-core.
  packages/backend-core/src/users/users.ts
  packages/shared-core/src/utils.ts
  packages/worker/src/api/controllers/global/users.ts
Labels: firestorm, size/s

#14668 Set view permissions to explicit roles from the parent table
  packages/server/src/api/controllers/permission.ts
  packages/server/src/api/routes/tests/permissions.spec.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/permissions/index.ts
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/m

#14669 Remove an implicit any from removeInvalidFilters.
  packages/server/src/sdk/app/rows/queryUtils.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/s
