Repository Budibase/budibase, pull requests merged in 2024-04, with the labels that each got.

#13386 Support for `oneOf` filter in user search API
  packages/backend-core/src/users/users.ts
  packages/worker/src/api/controllers/global/users.ts
  packages/worker/src/api/routes/global/tests/users.spec.ts
Labels: firestorm

#13391 Type frontend field types
  packages/builder/src/components/backend/DataTable/formula.js
  packages/builder/src/components/backend/Datasources/relationshipErrors.js
  packages/builder/src/components/backend/TableNavigator/utils.js
  packages/builder/src/components/design/settings/controls/FieldConfiguration/utils.js
  packages/builder/src/constants/backend/index.js
  packages/builder/src/helpers/schemaGenerator.js
  packages/builder/src/helpers/utils.js
  packages/builder/src/stores/builder/tables.js
  packages/builder/src/templates/commonComponents.js
  packages/client/src/components/app/blocks/FormBlockComponent.svelte
  packages/frontend-core/package.json
  packages/frontend-core/src/components/grid/lib/renderers.js
  packages/frontend-core/src/components/grid/lib/utils.js
Labels: firestorm, feature-branch

#13359 Change the way we manage `testcontainers`
  .github/workflows/budibase_ci.yml
  globalSetup.ts
  package.json
  packages/backend-core/tests/core/utilities/testContainerUtils.ts
  packages/server/scripts/test.sh
  packages/server/src/api/routes/public/tests/metrics.spec.js
  packages/server/src/api/routes/tests/appImport.spec.ts
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/api/routes/tests/queries/mongodb.spec.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/user.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/integration-test/mysql.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/tests/utils/index.ts
  packages/server/src/integrations/tests/utils/mariadb.ts
  packages/server/src/integrations/tests/utils/mongodb.ts
  packages/server/src/integrations/tests/utils/mssql.ts
  packages/server/src/integrations/tests/utils/mysql.ts
  packages/server/src/integrations/tests/utils/postgres.ts
  packages/server/src/migrations/tests/index.spec.ts
  packages/server/src/sdk/app/rows/search/tests/external.spec.ts
  packages/server/src/tests/jestSetup.ts
  packages/server/src/tests/utilities/api/base.ts
  yarn.lock
Labels: firestorm

#13398 Revert "Single attachment column type"
  packages/bbui/src/Form/Core/Dropzone.svelte
  packages/builder/src/components/backend/DataTable/formula.js
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/components/design/settings/controls/FieldConfiguration/utils.js
  packages/builder/src/constants/backend/index.js
  packages/builder/tsconfig.json
  packages/client/manifest.json
  packages/client/src/components/app/blocks/FormBlockComponent.svelte
  packages/client/src/components/app/forms/AttachmentField.svelte
  packages/client/src/components/app/forms/AttachmentSingleField.svelte
  packages/client/src/components/app/forms/index.js
  packages/client/src/components/app/forms/validation.js
  packages/frontend-core/src/components/grid/cells/AttachmentCell.svelte
  packages/frontend-core/src/components/grid/cells/AttachmentSingleCell.svelte
  packages/frontend-core/src/components/grid/lib/renderers.js
  packages/frontend-core/src/components/grid/lib/utils.js
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/db/defaultData/datasource_bb_default.ts
  packages/server/src/sdk/app/rows/attachments.ts
  packages/server/src/sdk/app/rows/utils.ts
  packages/server/src/utilities/rowProcessor/attachments.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/map.ts
  packages/server/src/utilities/rowProcessor/tests/attachments.spec.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
  packages/shared-core/src/table.ts
  packages/types/src/documents/app/row.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm

#13415 Fixing `BB_ADMIN` environment variable user creation
  packages/backend-core/src/users/db.ts
  packages/server/src/app.ts
  packages/server/src/startup/index.ts
  packages/server/src/startup/tests/startup.spec.ts
  packages/worker/src/api/controllers/global/users.ts
  yarn.lock
Labels: firestorm

#13419 [BUDI-8091] Fix renaming columns in SQL Server (and MySQL)
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/integrations/base/sqlTable.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/server/src/tests/utilities/api/table.ts
  packages/server/src/tests/utilities/structures.ts
Labels: firestorm

#13182 Data provider auto-refresh
  packages/builder/src/components/design/settings/componentSettings.js
  packages/builder/src/components/design/settings/controls/PaywalledSetting.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsSection.svelte
  packages/client/manifest.json
  packages/client/src/components/app/DataProvider.svelte
  packages/client/src/components/app/GridBlock.svelte
  packages/client/src/components/app/blocks/CardsBlock.svelte
  packages/client/src/components/app/blocks/ChartBlock.svelte
  packages/client/src/components/app/blocks/RepeaterBlock.svelte
  packages/client/src/components/app/blocks/RowExplorer.svelte
  packages/client/src/components/app/deprecated/TableBlock.svelte
Labels: feature-branch

#13430 Remove test container logs
  .github/workflows/budibase_ci.yml
  package.json
Labels: firestorm

#13432 [BUDI-7659] First end-to-end test for SQS functionality.
  .github/workflows/budibase_ci.yml
  globalSetup.ts
  packages/backend-core/tests/core/utilities/testContainerUtils.ts
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
Labels: firestorm

#13408 Tests and handle imports
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/sdk/app/backups/imports.ts
  packages/server/src/sdk/app/rows/attachments.ts
  packages/server/src/sdk/tests/attachments.spec.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
Labels: firestorm

#13407 Handle singleattachment on AttachmentCleanup
  packages/server/src/utilities/rowProcessor/attachments.ts
  packages/server/src/utilities/rowProcessor/tests/attachments.spec.ts
Labels: firestorm

#13444 Unify icons usage in builder
  packages/builder/src/constants/backend/index.js
  packages/builder/src/stores/builder/tests/sortedIntegrations.test.js
  packages/frontend-core/src/components/grid/lib/utils.js
  packages/frontend-core/src/constants.js
Labels: firestorm

#13445 Add number and date search tests.
  packages/server/src/api/routes/tests/search.spec.ts
Labels: firestorm

#13375 Nested nav links
  packages/bbui/src/Form/Core/Combobox.svelte
  packages/bbui/src/Form/Core/Picker.svelte
  packages/bbui/src/Popover/Popover.svelte
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/DrawerBindableCombobox.svelte
  packages/builder/src/components/design/settings/controls/ButtonConfiguration/ButtonConfiguration.svelte
  packages/builder/src/components/design/settings/controls/DraggableList/DraggableList.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/EditNavItemPopover.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/LinksDrawer.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/LinksEditor.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/NavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/NavItemConfiguration.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/SubLinksDrawer.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/stores/builder/navigation.js
  packages/builder/src/stores/builder/tests/navigation.test.js
  packages/client/src/components/app/Layout.svelte
  packages/client/src/components/app/NavItem.svelte
Labels: feature-branch

#13447 Improving public API documentation for row search
  packages/server/specs/openapi.json
  packages/server/specs/openapi.yaml
  packages/server/specs/resources/misc.ts
  packages/server/src/definitions/openapi.ts
Labels: firestorm

#13449 SQS prepared statement support
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/types/src/sdk/db.ts
Labels: firestorm

#13456 Assert length on search tests, fixes bug in SQS around `onEmptyReturn`
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/sdk/app/rows/search.ts
Labels: firestorm

#13467 Don't attempt account portal build if OSS
  .github/workflows/budibase_ci.yml
Labels: firestorm

#13459 Reduce duplication in search.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
Labels: firestorm

#13468 Use correct variable for checking OSS user (or fork) in CI build
  .github/workflows/budibase_ci.yml
Labels: firestorm

#13472 Increase the base Minio storage to 2Gi in Helm chart.
  charts/budibase/values.yaml
Labels: firestorm

#13348 "Download file" app action
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/DownloadFile.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/index.js
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/manifest.json
  packages/builder/src/components/start/ExportAppModal.svelte
  packages/client/src/utils/buttonActions.js
  packages/client/tsconfig.json
  packages/frontend-core/src/api/attachments.js
  packages/frontend-core/src/utils/download.js
  packages/server/package.json
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/routes/row.ts
  packages/string-templates/src/index.ts
  packages/string-templates/test/basic.spec.ts
  yarn.lock
Labels: do not merge, firestorm, feature-branch

#13476 Allow specifying extra volume mounts for containers in our Helm chart.
  charts/budibase/README.md
  charts/budibase/templates/app-service-deployment.yaml
  charts/budibase/templates/automation-worker-service-deployment.yaml
  charts/budibase/templates/minio-service-deployment.yaml
  charts/budibase/templates/proxy-service-deployment.yaml
  charts/budibase/templates/redis-service-deployment.yaml
  charts/budibase/templates/worker-service-deployment.yaml
  charts/budibase/values.yaml
Labels: firestorm

#13469 Add tests for sorting to search.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
Labels: firestorm

#13484 Rename `search.spec.ts` helpers to better reflect their purpose.
  packages/server/src/api/routes/tests/search.spec.ts
Labels: firestorm

#13485 Add some more range tests.
  packages/server/src/api/routes/tests/search.spec.ts
Labels: firestorm

#13489 Commenting `FieldType` enumeration
  packages/types/src/documents/app/row.ts
Labels: firestorm

#13491 Add tests for array column types, fixing some bugs along the way.
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/constants/index.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/sdk/app/rows/search.ts
Labels: firestorm

#13483 SQS relationship support
  hosting/.env
  packages/backend-core/src/environment.ts
  packages/server/package.json
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/db/utils.ts
  packages/server/src/environment.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/base/sqlTable.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/sdk/app/rows/index.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/internal.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/rows/search/tests/external.spec.ts
  packages/server/src/sdk/app/rows/search/tests/internal.spec.ts
  packages/server/src/sdk/app/rows/sqlAlias.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/types/src/documents/app/sqlite.ts
  yarn.lock
Labels: firestorm

#13501 Making `meta` required in `QueryJson`
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/table/ExternalRequest.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/tests/utilities/api/datasource.ts
  packages/types/src/sdk/search.ts
Labels: firestorm

#13479 Don't delete attachments directly from the frontend
  packages/builder/src/components/common/Dropzone.svelte
  packages/client/src/components/app/forms/AttachmentField.svelte
  packages/frontend-core/src/api/attachments.js
  packages/frontend-core/src/components/grid/cells/AttachmentCell.svelte
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/static.ts
Labels: firestorm, feature-branch

#13504 Update external types
  packages/server/src/integrations/utils.ts
  packages/server/src/sdk/app/datasources/datasources.ts
Labels: firestorm

#13500 Remove addcolumn api param
  .eslintrc.json
  packages/builder/src/stores/builder/tables.js
  packages/server/src/api/controllers/table/external.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/controllers/table/internal.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/integration-test/mysql.spec.ts
  packages/server/src/integrations/utils.ts
  packages/server/src/sdk/app/datasources/datasources.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/types/src/documents/app/table/table.ts
  packages/types/src/sdk/search.ts
Labels: firestorm

#13507 Search type updates
  packages/backend-core/src/users/users.ts
  packages/frontend-core/src/components/FilterBuilder.svelte
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search/tests/lucene.spec.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/tests/filters.test.ts
  packages/types/src/api/web/searchFilter.ts
  packages/types/src/api/web/user.ts
  packages/types/src/sdk/search.ts
  packages/worker/src/tests/api/users.ts
Labels: firestorm

#13509 [Fix] Datasource plus schema updates issues
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/constants/backend/index.js
  packages/builder/src/stores/builder/tables.js
  packages/server/src/api/controllers/table/external.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/controllers/table/internal.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/integration-test/mysql.spec.ts
  packages/server/src/integrations/utils.ts
  packages/server/src/sdk/app/datasources/datasources.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/shared-core/src/constants/fields.ts
  packages/shared-core/src/constants/index.ts
  packages/types/src/documents/app/table/table.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, feature-branch

#13514 Fix displaying user autocolums edition
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
Labels: firestorm

#13503 Add `search.spec.ts` tests for `FieldType.BIGINT` and some additional range query tests.
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/base/query.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/integrations/utils/index.ts
  packages/server/src/integrations/utils/sqlStatements.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/rows/utils.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/server/src/tests/utilities/api/datasource.ts
  packages/shared-core/src/filters.ts
  packages/types/src/sdk/datasources.ts
  packages/types/src/sdk/search.ts
Labels: firestorm

#13492 When sending a file attachment in email fetch it directly from our object store
  packages/backend-core/src/objectStore/objectStore.ts
  packages/worker/src/api/routes/global/tests/realEmail.spec.ts
  packages/worker/src/utilities/email.ts
Labels: firestorm

#13540 Fix docker-compose/docker compose error in Budibase CLI
  packages/cli/src/hosting/utils.ts
Labels: firestorm

#13531 Fix readable/runtime conversion with helpers
  packages/builder/src/dataBinding.js
  packages/string-templates/src/index.ts
Labels: firestorm

#13568 Rename and cleanups
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/components/backend/TableNavigator/ExistingTableDataImport.svelte
  packages/builder/src/constants/backend/index.js
  packages/frontend-core/src/components/grid/cells/BBReferenceCell.svelte
  packages/frontend-core/src/components/grid/controls/MigrationModal.svelte
  packages/frontend-core/src/constants.js
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/base/sqlTable.ts
  packages/server/src/sdk/app/rows/search/tests/utils.spec.ts
  packages/server/src/sdk/app/rows/search/utils.ts
  packages/server/src/sdk/app/tables/migration.ts
  packages/server/src/utilities/rowProcessor/bbReferenceProcessor.ts
  packages/server/src/utilities/rowProcessor/errors.ts
  packages/server/src/utilities/rowProcessor/tests/bbReferenceProcessor.spec.ts
  packages/server/src/utilities/rowProcessor/tests/inputProcessing.spec.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
  packages/server/src/utilities/schema.ts
  packages/shared-core/src/filters.ts
  packages/types/src/documents/app/row.ts
  packages/types/src/documents/app/table/constants.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm

#13569 Make REUSE_CONTAINERS the default for running tests.
  .github/workflows/budibase_ci.yml
  globalSetup.ts
  package.json
  packages/backend-core/tests/core/utilities/testContainerUtils.ts
  packages/server/src/integrations/tests/utils/index.ts
  scripts/killTestcontainers.sh
Labels: firestorm

#13564 Search tests for FieldType.AUTO
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
Labels: firestorm

#13572 Search test improvement - bulk import
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  yarn.lock
Labels: firestorm
