Repository Budibase/budibase, pull requests merged in 2024-03, with the labels that each got.

#13161 Reverting the revert of SQL aliasing
  packages/server/scripts/integrations/postgres/reset.sh
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/alias.ts
  packages/server/src/environment.ts
  packages/server/src/integrations/base/query.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/integrations/microsoftSqlServer.ts
  packages/server/src/integrations/mysql.ts
  packages/server/src/integrations/oracle.ts
  packages/server/src/integrations/postgres.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/integrations/tests/sqlQueryJson/basicFetchWithRelationships.json
  packages/server/src/integrations/tests/sqlQueryJson/createWithRelationships.json
  packages/server/src/integrations/tests/sqlQueryJson/deleteSimple.json
  packages/server/src/integrations/tests/sqlQueryJson/enrichRelationship.json
  packages/server/src/integrations/tests/sqlQueryJson/fetchManyToMany.json
  packages/server/src/integrations/tests/sqlQueryJson/filterByRelationship.json
  packages/server/src/integrations/tests/sqlQueryJson/manyRelationshipFilters.json
  packages/server/src/integrations/tests/sqlQueryJson/updateRelationship.json
  packages/server/src/integrations/tests/sqlQueryJson/updateSimple.json
  packages/server/src/sdk/app/datasources/plus.ts
  packages/server/src/sdk/app/rows/utils.ts
  packages/types/src/sdk/datasources.ts
  packages/types/src/sdk/search.ts
  yarn.lock
Labels: firestorm

#13157 Unifying how we send requests to the server in packages/server tests.
  packages/backend-core/src/middleware/errorHandling.ts
  packages/server/src/api/controllers/permission.ts
  packages/server/src/api/controllers/query/index.ts
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/tests/attachment.spec.ts
  packages/server/src/api/routes/tests/backup.spec.ts
  packages/server/src/api/routes/tests/permissions.spec.ts
  packages/server/src/api/routes/tests/queries/query.seq.spec.ts
  packages/server/src/api/routes/tests/role.spec.js
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/api/routes/tests/user.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/appMigrations/tests/migrations.spec.ts
  packages/server/src/automations/tests/createRow.spec.ts
  packages/server/src/automations/tests/updateRow.spec.ts
  packages/server/src/db/tests/linkController.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/sdk/app/rows/tests/internal.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/application.ts
  packages/server/src/tests/utilities/api/attachment.ts
  packages/server/src/tests/utilities/api/backup.ts
  packages/server/src/tests/utilities/api/base.ts
  packages/server/src/tests/utilities/api/datasource.ts
  packages/server/src/tests/utilities/api/legacyView.ts
  packages/server/src/tests/utilities/api/permission.ts
  packages/server/src/tests/utilities/api/query.ts
  packages/server/src/tests/utilities/api/row.ts
  packages/server/src/tests/utilities/api/screen.ts
  packages/server/src/tests/utilities/api/table.ts
  packages/server/src/tests/utilities/api/user.ts
  packages/server/src/tests/utilities/api/viewV2.ts
  packages/types/src/api/web/app/permission.ts
  packages/types/src/api/web/app/rows.ts
  packages/types/src/api/web/application.ts
  packages/types/src/api/web/index.ts
  packages/types/src/api/web/query.ts
  packages/types/src/documents/app/query.ts
Labels: firestorm

#13151 Fix single-character changes in grids not being saved
  packages/frontend-core/src/components/grid/cells/DataCell.svelte
  packages/frontend-core/src/components/grid/overlays/KeyboardManager.svelte
  packages/frontend-core/src/components/grid/stores/rows.js
  packages/frontend-core/src/components/grid/stores/ui.js
  packages/frontend-core/src/components/grid/stores/validation.js
Labels: feature-branch

#13187 Fix SQL aliasing issue when creating rows
  packages/server/scripts/integrations/mysql/init.sql
  packages/server/src/api/controllers/row/alias.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/integrations/tests/sqlQueryJson/basicFetchWithRelationships.json
  packages/server/src/integrations/tests/sqlQueryJson/createSimple.json
  packages/server/src/integrations/tests/sqlQueryJson/createWithRelationships.json
  packages/server/src/integrations/tests/sqlQueryJson/deleteSimple.json
  packages/server/src/integrations/tests/sqlQueryJson/enrichRelationship.json
  packages/server/src/integrations/tests/sqlQueryJson/fetchManyToMany.json
  packages/server/src/integrations/tests/sqlQueryJson/filterByRelationship.json
  packages/server/src/integrations/tests/sqlQueryJson/manyRelationshipFilters.json
  packages/server/src/integrations/tests/sqlQueryJson/updateRelationship.json
  packages/server/src/integrations/tests/sqlQueryJson/updateSimple.json
Labels: firestorm

#13175 Relationship picker incorrectly renders selections
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/tests/external.spec.ts
  packages/server/src/sdk/app/rows/search/utils.ts
Labels: feature-branch

#13198 Disable write aliasing (create, update and delete) for MySQL and MS-SQL
  packages/server/src/api/controllers/row/alias.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/index.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/sdk/app/rows/utils.ts
Labels: firestorm

#13052 Form screen template
  packages/bbui/src/Actions/position_dropdown.js
  packages/builder/src/analytics/index.js
  packages/builder/src/components/deploy/AppActions.svelte
  packages/builder/src/components/design/settings/controls/ButtonConfiguration/ButtonSetting.svelte
  packages/builder/src/components/design/settings/controls/EditComponentPopover/EditComponentPopover.svelte
  packages/builder/src/components/design/settings/controls/EditComponentPopover/index.js
  packages/builder/src/components/design/settings/controls/FieldConfiguration/FieldSetting.svelte
  packages/builder/src/components/design/settings/controls/FormStepConfiguration.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/FieldSetting.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/PrimaryColumnFieldSetting.svelte
  packages/builder/src/components/design/settings/controls/PropertyControl.svelte
  packages/builder/src/components/portal/onboarding/TourPopover.svelte
  packages/builder/src/components/portal/onboarding/TourWrap.svelte
  packages/builder/src/components/portal/onboarding/steps/NewFormSteps.svelte
  packages/builder/src/components/portal/onboarding/steps/NewViewUpdateFormRowId.svelte
  packages/builder/src/components/portal/onboarding/steps/index.js
  packages/builder/src/components/portal/onboarding/tours.js
  packages/builder/src/dataBinding.js
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsSection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPreview.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/DatasourceModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/FormTypeModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/ScreenRoleModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/blank.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/form.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/grid.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/table.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/index.svelte
  packages/builder/src/stores/builder/app.js
  packages/builder/src/stores/builder/builder.js
  packages/builder/src/stores/builder/tests/builder.test.js
  packages/builder/src/templates/formScreen.js
  packages/builder/src/templates/index.js
  packages/types/src/api/web/auth.ts
  packages/types/src/documents/global/user.ts
  packages/worker/src/api/routes/validation/users.ts
Labels: feature-branch

#13183 Fix issue with filtering client side docs using lucene
  packages/shared-core/src/filters.ts
  packages/shared-core/src/tests/filters.test.ts
Labels: feature-branch

#12624 Added icon to button component, reworked icon display code.
  packages/builder/src/components/design/settings/controls/IconSelect/IconSelect.svelte
  packages/client/manifest.json
  packages/client/src/components/app/Button.svelte
  packages/client/src/components/app/ButtonGroup.svelte
  packages/client/src/components/app/dynamic-filter/DynamicFilter.svelte
Labels: feature-branch

#13191 [fix] BUDI-7710: User groups do not fully support custom roles
  packages/backend-core/src/cache/user.ts
  packages/backend-core/src/db/Replication.ts
  packages/backend-core/src/security/roles.ts
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/controllers/user.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/role.ts
  packages/types/src/documents/app/role.ts
Labels: firestorm

#13097 Enforce using example.com as a domain for emails.
  .eslintrc.json
  eslint-local-rules/index.js
  packages/backend-core/tests/core/utilities/structures/accounts.ts
  packages/backend-core/tests/core/utilities/structures/scim.ts
  packages/server/__mocks__/node-fetch.ts
  packages/server/src/tests/jestEnv.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/worker/src/api/routes/global/tests/groups.spec.ts
  qa-core/src/account-api/tests/accounts/accounts.cloud.spec.ts
  qa-core/src/public-api/fixtures/users.ts
Labels: firestorm

#13163 Doc writethrough cache
  packages/backend-core/src/cache/base/index.ts
  packages/backend-core/src/cache/docWritethrough.ts
  packages/backend-core/src/cache/generic.ts
  packages/backend-core/src/cache/tests/docWritethrough.spec.ts
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/backend-core/src/db/tests/DatabaseImpl.spec.ts
  packages/backend-core/src/queue/constants.ts
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/backend-core/src/queue/listeners.ts
  packages/backend-core/src/queue/queue.ts
  packages/backend-core/src/redis/init.ts
  packages/backend-core/src/redis/redis.ts
  packages/backend-core/src/redis/utils.ts
  packages/types/src/sdk/db.ts
  packages/worker/src/initPro.ts
Labels: firestorm

#13141 Allow SCIM and non-SCIM users and groups
  packages/bbui/src/Icon/IconAvatar.svelte
  packages/bbui/src/Table/Table.svelte
  packages/builder/src/pages/builder/portal/users/_components/ActiveDirectoryInfo.svelte
  packages/builder/src/pages/builder/portal/users/_components/SCIMBanner.svelte
  packages/builder/src/pages/builder/portal/users/groups/[groupId].svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/CreateEditGroupModal.svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/EditUserPicker.svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/GroupIcon.svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/GroupNameTableRenderer.svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/GroupUsers.svelte
  packages/builder/src/pages/builder/portal/users/groups/index.svelte
  packages/builder/src/pages/builder/portal/users/users/[userId].svelte
  packages/builder/src/pages/builder/portal/users/users/_components/AddUserModal.svelte
  packages/builder/src/pages/builder/portal/users/users/_components/EmailTableRenderer.svelte
  packages/builder/src/pages/builder/portal/users/users/_components/ImportUsersModal.svelte
  packages/builder/src/pages/builder/portal/users/users/_components/RemoveGroupTableRenderer.svelte
  packages/builder/src/pages/builder/portal/users/users/index.svelte
  packages/builder/src/stores/portal/groups.js
Labels: firestorm

#13220 Init doc writethrough processor correctly
  packages/backend-core/src/cache/docWritethrough.ts
  packages/backend-core/src/cache/tests/docWritethrough.spec.ts
  packages/server/src/startup.ts
  packages/worker/src/index.ts
Labels: firestorm

#13217 Fix issue with invalid IDs leading to inability to emit rows when bulk deleting
  packages/server/src/api/controllers/public/utils.ts
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm

#13222 Fix query schema updating
  packages/builder/src/components/integration/QueryViewer.svelte
  packages/server/src/threads/query.ts
Labels: firestorm

#12933 Clean up isolates when a request is finished.
  packages/backend-core/src/context/types.ts
  packages/backend-core/src/timers/timers.ts
  packages/server/src/api/index.ts
  packages/server/src/jsRunner/index.ts
  packages/server/src/jsRunner/vm/isolated-vm.ts
  packages/server/src/middleware/cleanup.ts
  packages/types/src/sdk/vm.ts
Labels: firestorm

#12914 Plumbing for showing a maintenance page when SQS is required but missing.
  packages/builder/src/pages/builder/_layout.svelte
  packages/builder/src/pages/builder/maintenance/index.svelte
  packages/builder/src/pages/builder/portal/_components/BudibaseLogo.svelte
  packages/builder/src/stores/portal/admin.js
  packages/client/src/components/ClientApp.svelte
  packages/client/src/components/MaintenanceScreen.svelte
  packages/types/src/core/installation.ts
  packages/worker/src/api/controllers/system/environment.ts
  packages/worker/src/api/routes/system/tests/environment.spec.ts
Labels: firestorm

#13169 Live binding evaluation and drawer rework
  packages/bbui/src/Actions/click_outside.js
  packages/bbui/src/Actions/position_dropdown.js
  packages/bbui/src/Drawer/Drawer.svelte
  packages/bbui/src/Drawer/DrawerContent.svelte
  packages/bbui/src/Modal/Modal.svelte
  packages/bbui/src/Popover/Popover.svelte
  packages/builder/package.json
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationSelector.svelte
  packages/builder/src/components/automation/SetupPanel/QueryParamSelector.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/CodeEditor/index.js
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/BindingPicker.svelte
  packages/builder/src/components/common/bindings/BindingSidePanel.svelte
  packages/builder/src/components/common/bindings/ClientBindingPanel.svelte
  packages/builder/src/components/common/bindings/DrawerBindableCombobox.svelte
  packages/builder/src/components/common/bindings/DrawerBindableInput.svelte
  packages/builder/src/components/common/bindings/DrawerBindableSlot.svelte
  packages/builder/src/components/common/bindings/EvaluationSidePanel.svelte
  packages/builder/src/components/common/bindings/ModalBindableInput.svelte
  packages/builder/src/components/common/bindings/ServerBindingPanel.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/ButtonActionEditor.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/DeleteRow.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/FetchRow.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/SaveFields.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/ShowNotification.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/UpdateFieldValue.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/UpdateState.svelte
  packages/builder/src/components/design/settings/controls/ButtonConfiguration/ButtonConfiguration.svelte
  packages/builder/src/components/design/settings/controls/ColumnEditor/CellDrawer.svelte
  packages/builder/src/components/design/settings/controls/ColumnEditor/CellEditor.svelte
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterDrawer.svelte
  packages/builder/src/components/design/settings/controls/PropertyControl.svelte
  packages/builder/src/components/integration/KeyValueBuilder.svelte
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPreview.svelte
  packages/builder/src/stores/builder/preview.js
  packages/client/src/components/Component.svelte
  packages/client/src/components/app/GridBlock.svelte
  packages/client/src/components/app/blocks/CardsBlock.svelte
  packages/client/src/components/app/blocks/MultiStepFormblock.svelte
  packages/client/src/components/app/blocks/RepeaterBlock.svelte
  packages/client/src/components/app/blocks/RowExplorer.svelte
  packages/client/src/components/app/blocks/form/FormBlock.svelte
  packages/client/src/components/app/dynamic-filter/DynamicFilter.svelte
  packages/client/src/index.js
  packages/client/src/sdk.js
  packages/frontend-core/src/utils/index.js
  packages/frontend-core/src/utils/rows.js
  yarn.lock
Labels: feature-branch

#13116 App list actions
  packages/backend-core/src/events/publishers/app.ts
  packages/backend-core/tests/core/utilities/mocks/events.ts
  packages/bbui/src/ActionMenu/ActionMenu.svelte
  packages/builder/src/components/common/NavItem.svelte
  packages/builder/src/components/deploy/DeleteModal.svelte
  packages/builder/src/components/portal/licensing/AppLimitModal.svelte
  packages/builder/src/components/start/AppRow.svelte
  packages/builder/src/components/start/AppRowContext.svelte
  packages/builder/src/components/start/DuplicateAppModal.svelte
  packages/builder/src/components/start/ExportAppModal.svelte
  packages/builder/src/pages/builder/app/[application]/settings/_layout.svelte
  packages/builder/src/pages/builder/portal/apps/_components/PortalSideBar.svelte
  packages/frontend-core/src/api/app.js
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/routes/application.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/sdk/app/backups/imports.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/application.ts
  packages/types/src/api/web/application.ts
  packages/types/src/sdk/events/app.ts
  packages/types/src/sdk/events/event.ts
Labels: do not merge, feature-branch

#13205 App favourites
  packages/bbui/src/Icon/Icon.svelte
  packages/bbui/src/Tooltip/AbsTooltip.svelte
  packages/bbui/src/index.js
  packages/builder/src/components/common/NavHeader.svelte
  packages/builder/src/components/common/NavItem.svelte
  packages/builder/src/components/deploy/AppActions.svelte
  packages/builder/src/components/deploy/DeleteModal.svelte
  packages/builder/src/components/start/AppRow.svelte
  packages/builder/src/components/start/AppRowContext.svelte
  packages/builder/src/components/start/ChooseIconModal.svelte
  packages/builder/src/components/start/CreateAppModal.svelte
  packages/builder/src/components/start/DuplicateAppModal.svelte
  packages/builder/src/components/start/UpdateAppModal.svelte
  packages/builder/src/global.css
  packages/builder/src/pages/builder/app/[application]/_components/BuilderSidePanel.svelte
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/settings/automations/index.svelte
  packages/builder/src/pages/builder/app/[application]/settings/embed.svelte
  packages/builder/src/pages/builder/app/[application]/settings/exportImport.svelte
  packages/builder/src/pages/builder/app/[application]/settings/name-and-url.svelte
  packages/builder/src/pages/builder/apps/index.svelte
  packages/builder/src/pages/builder/portal/_layout.svelte
  packages/builder/src/pages/builder/portal/account/auditLogs/index.svelte
  packages/builder/src/pages/builder/portal/apps/FavouriteAppButton.svelte
  packages/builder/src/pages/builder/portal/apps/[appId]/_layout.svelte
  packages/builder/src/pages/builder/portal/apps/[appId]/index.svelte
  packages/builder/src/pages/builder/portal/apps/_components/PortalSideBar.svelte
  packages/builder/src/pages/builder/portal/apps/_layout.svelte
  packages/builder/src/pages/builder/portal/apps/create.svelte
  packages/builder/src/pages/builder/portal/apps/index.svelte
  packages/builder/src/pages/builder/portal/users/groups/[groupId].svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/AppAddModal.svelte
  packages/builder/src/pages/builder/portal/users/users/[userId].svelte
  packages/builder/src/pages/builder/portal/users/users/_components/AppsTableRenderer.svelte
  packages/builder/src/stores/BudiStore.js
  packages/builder/src/stores/builder/app.js
  packages/builder/src/stores/builder/builder.js
  packages/builder/src/stores/builder/components.js
  packages/builder/src/stores/builder/hover.js
  packages/builder/src/stores/builder/layouts.js
  packages/builder/src/stores/builder/navigation.js
  packages/builder/src/stores/builder/screens.js
  packages/builder/src/stores/builder/websocket.js
  packages/builder/src/stores/portal/apps.js
  packages/builder/src/stores/portal/index.js
  packages/server/src/api/controllers/application.ts
  packages/types/src/api/web/auth.ts
  packages/types/src/documents/global/user.ts
  packages/worker/src/api/controllers/global/self.ts
  packages/worker/src/api/routes/validation/users.ts
Labels: feature-branch

#13262 [CI] Remove pro step
  .github/workflows/budibase_ci.yml
Labels: firestorm

#13273 Fix buffer usage after string-templates refactor
  packages/string-templates/package.json
  packages/string-templates/rollup.config.js
  yarn.lock
Labels: feature-branch

#13253 Allow single attachment column
  packages/bbui/src/Form/Core/Dropzone.svelte
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/client/src/components/app/blocks/FormBlockComponent.svelte
  packages/client/src/components/app/blocks/MultiStepFormblock.svelte
  packages/client/src/components/app/blocks/form/InnerFormBlock.svelte
  packages/frontend-core/src/components/grid/cells/AttachmentCell.svelte
Labels: firestorm, feature-branch

#13292 Fix issue with old datasources not having 'isSQL' flag
  packages/server/src/api/routes/tests/__snapshots__/datasource.spec.ts.snap
  packages/server/src/integration-test/mysql.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/microsoftSqlServer.ts
  packages/server/src/integrations/mysql.ts
  packages/server/src/sdk/app/datasources/datasources.ts
  packages/server/src/sdk/app/rows/utils.ts
Labels: firestorm

#13299 Disabling aliasing for SQL table operations
  packages/server/src/api/controllers/row/alias.ts
Labels: firestorm

#13319 …
  packages/builder/src/components/backend/TableNavigator/popovers/EditTablePopover.svelte
  packages/server/src/api/controllers/table/external.ts
Labels: firestorm

#13317 BUDI-8084 - Single attachment binding as subtype
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/integrations/base/sqlTable.ts
  packages/server/src/sdk/app/rows/search/utils.ts
  packages/server/src/utilities/rowProcessor/bbReferenceProcessor.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/schema.ts
  packages/types/src/documents/app/row.ts
  packages/types/src/documents/app/table/schema.ts
Labels: feature-branch

#13331 Update isolated-vm bundler
  packages/server/src/jsRunner/bundles/index-helpers.ivm.bundle.js
  packages/server/src/jsRunner/bundles/index-helpers.ts
  packages/server/src/jsRunner/bundles/snippets.ivm.bundle.js
  packages/server/tsconfig.build.json
  packages/string-templates/src/helpers/list.ts
Labels: feature-branch

#13239 Table/Tableblock deprecated and replaced with Gridblock
  packages/builder/src/components/deploy/AppActions.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/tableDetails.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/tableInline.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/index.svelte
  packages/builder/src/templates/gridDetailsScreen.js
  packages/builder/src/templates/gridListScreen.js
  packages/builder/src/templates/index.js
  packages/builder/src/templates/rowListScreen.js
  packages/client/manifest.json
  packages/client/src/components/Component.svelte
  packages/client/src/components/app/blocks/index.js
  packages/client/src/components/app/deprecated/TableBlock.svelte
  packages/client/src/components/app/deprecated/table/SlotRenderer.svelte
  packages/client/src/components/app/deprecated/table/Table.svelte
  packages/client/src/components/app/deprecated/table/index.js
  packages/client/src/components/app/index.js
Labels: do not merge

#13342 Disabling single attachment column
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
Labels: firestorm

#13314 Fold MongoDB unit tests into integration tests, delete MongoDB mocks.
  packages/server/__mocks__/mongodb.ts
  packages/server/src/api/routes/tests/queries/mongodb.spec.ts
  packages/server/src/integrations/mongodb.ts
  packages/server/src/integrations/tests/mongo.spec.ts
  packages/server/src/tests/utilities/api/query.ts
Labels: firestorm

#13336 Allow SQL queries to pass null for empty bindings rather than empty string for new queries
  packages/server/src/api/controllers/query/index.ts
  packages/server/src/api/routes/tests/environmentVariables.spec.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/api/routes/tests/queries/mongodb.spec.ts
  packages/server/src/api/routes/tests/queries/query.seq.spec.ts
  packages/server/src/integrations/queries/sql.ts
  packages/server/src/sdk/app/queries/queries.ts
  packages/server/src/tests/utilities/api/query.ts
  packages/server/src/threads/definitions.ts
  packages/server/src/threads/query.ts
  packages/types/src/documents/app/query.ts
Labels: firestorm

#13180 Un-revert Skeleton Loader PR
  .eslintignore
  .gitignore
  package.json
  packages/builder/src/components/deploy/RevertModalVersionSelect.svelte
  packages/builder/src/components/deploy/VersionModal.svelte
  packages/builder/src/components/deploy/clientVersions.json
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPreview.svelte
  packages/builder/src/pages/builder/portal/apps/[appId]/index.svelte
  packages/client/manifest.json
  packages/client/src/components/ClientApp.svelte
  packages/client/src/components/FreeFooter.svelte
  packages/client/src/licensing/features.js
  packages/client/src/licensing/index.js
  packages/client/src/licensing/utils.js
  packages/client/src/stores/features.js
  packages/client/src/stores/index.js
  packages/frontend-core/src/api/app.js
  packages/frontend-core/src/components/ClientAppSkeleton.svelte
  packages/frontend-core/src/components/index.js
  packages/frontend-core/src/themes/midnight.css
  packages/server/package.json
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/controllers/static/templates/BudibaseApp.svelte
  packages/server/src/api/controllers/static/templates/app.hbs
  packages/server/src/api/routes/application.ts
  packages/server/src/api/routes/static.ts
  packages/server/src/constants/index.ts
  packages/server/src/constants/themes.ts
  packages/server/src/utilities/fileSystem/app.ts
  packages/server/src/utilities/fileSystem/clientLibrary.ts
  packages/types/src/documents/app/app.ts
  scripts/build.js
  scripts/getPastClientVersion.js
Labels: feature-branch

#13345 [Changed] Identity override for event publish + BPM literals
  packages/backend-core/src/events/events.ts
  packages/backend-core/src/events/publishers/account.ts
  packages/backend-core/src/users/db.ts
  packages/frontend-core/src/constants.js
  packages/shared-core/src/constants/index.ts
  packages/types/src/api/web/user.ts
  packages/worker/src/api/controllers/global/users.ts
  packages/worker/src/api/routes/global/users.ts
  qa-core/src/internal-api/tests/applications/create.spec.ts
  qa-core/src/internal-api/tests/applications/delete.spec.ts
  qa-core/src/internal-api/tests/applications/publish.spec.ts
  qa-core/src/internal-api/tests/applications/update.spec.ts
  qa-core/src/internal-api/tests/screens/screens.spec.ts
  qa-core/src/internal-api/tests/tables/tables.spec.ts
  qa-core/src/internal-api/tests/users/appSpecificRoles.spec.ts
  qa-core/src/internal-api/tests/users/userManagement.spec.ts
  qa-core/src/public-api/tests/applications/applications.spec.ts
  qa-core/src/public-api/tests/tables/rows.spec.ts
  qa-core/src/public-api/tests/tables/tables.spec.ts
  qa-core/src/public-api/tests/users/users.spec.ts
Labels: account-portal

#13368 Split build for account portal/monorepo
  .github/workflows/budibase_ci.yml
  package.json
Labels: firestorm

#13372 Better datasource default hosts
  packages/server/src/integrations/couchdb.ts
  packages/server/src/integrations/elasticsearch.ts
  packages/server/src/integrations/microsoftSqlServer.ts
  packages/server/src/integrations/mongodb.ts
  packages/server/src/integrations/mysql.ts
  packages/server/src/integrations/oracle.ts
  packages/server/src/integrations/postgres.ts
  packages/server/src/integrations/redis.ts
  packages/server/src/integrations/utils.ts
Labels: firestorm

#13371 [Added] POST /api/global/users/sso endpoint
  packages/backend-core/src/platform/users.ts
  packages/types/src/api/web/user.ts
  packages/worker/src/api/controllers/global/users.ts
  packages/worker/src/api/index.ts
  packages/worker/src/api/routes/global/tests/users.spec.ts
  packages/worker/src/api/routes/global/users.ts
  packages/worker/src/api/routes/validation/users.ts
  packages/worker/src/tests/api/users.ts
Labels: enhancement
