Repository Budibase/budibase, pull requests merged in 2024-12, with the labels that each got.

#15102 Enrich the datasource when not passing the datasource ID.
  packages/server/src/sdk/app/rows/utils.ts
Labels: firestorm, size/xs

#15086 Migrate / add some more automation tests
  packages/server/src/automations/actions.ts
  packages/server/src/automations/tests/bash.spec.ts
  packages/server/src/automations/tests/openai.spec.ts
  packages/server/src/automations/tests/queryRows.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
Labels: firestorm, size/m

#15100 API typing - app service A -> D
  packages/server/src/api/controllers/analytics.ts
  packages/server/src/api/controllers/apikeys.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/auth.ts
  packages/server/src/api/controllers/automation.ts
  packages/server/src/api/controllers/backup.ts
  packages/server/src/api/controllers/component.ts
  packages/server/src/api/controllers/datasource.ts
  packages/server/src/api/controllers/deploy/Deployment.ts
  packages/server/src/api/controllers/deploy/index.ts
  packages/server/src/api/controllers/dev.ts
  packages/server/src/api/controllers/webhook.ts
  packages/server/src/automations/actions.ts
  packages/server/src/automations/steps/triggerAutomationRun.ts
  packages/server/src/automations/tests/loop.spec.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/automations/utils.ts
  packages/server/src/definitions/automations.ts
  packages/server/src/sdk/app/applications/sync.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/threads/automation.ts
  packages/types/src/api/web/analytics.ts
  packages/types/src/api/web/apikeys.ts
  packages/types/src/api/web/app/automation.ts
  packages/types/src/api/web/app/component.ts
  packages/types/src/api/web/app/datasource.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/app/user.ts
  packages/types/src/api/web/application.ts
  packages/types/src/api/web/automation.ts
  packages/types/src/api/web/deployment.ts
  packages/types/src/api/web/dev.ts
  packages/types/src/api/web/index.ts
  packages/types/src/documents/app/automation/schema.ts
  packages/types/src/documents/app/deployment.ts
  packages/types/src/documents/app/index.ts
  packages/types/src/documents/global/apikeys.ts
  packages/types/src/documents/global/index.ts
Labels: firestorm, size/l

#15106 Fix MySQL options column imports that have commas or other type names in them.
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/integrations/mysql.ts
  packages/server/src/integrations/utils/utils.ts
Labels: firestorm, size/l

#15111 adding buffer settings for single image
  hosting/single/nginx/nginx-default-site.conf
Labels: size/xs

#15114 prevent empty snippets being saved, don't crash for old empty snippets
  packages/builder/src/components/common/bindings/SnippetDrawer.svelte
  packages/builder/src/components/common/bindings/SnippetSidePanel.svelte
Labels: size/s

#15110 sort table names alphabetically when selecting data source
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
Labels: size/s

#15112 App service API typing - D -> R
  packages/backend-core/src/security/permissions.ts
  packages/backend-core/src/security/tests/permissions.spec.ts
  packages/server/src/api/controllers/integration.ts
  packages/server/src/api/controllers/layout.ts
  packages/server/src/api/controllers/metadata.ts
  packages/server/src/api/controllers/migrations.ts
  packages/server/src/api/controllers/ops.ts
  packages/server/src/api/controllers/permission.ts
  packages/server/src/api/controllers/plugin/file.ts
  packages/server/src/api/controllers/plugin/index.ts
  packages/server/src/api/controllers/query/index.ts
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/controllers/routing.ts
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/routes/query.ts
  packages/server/src/api/routes/tests/metadata.spec.ts
  packages/server/src/automations/steps/executeQuery.ts
  packages/server/src/automations/utils.ts
  packages/server/src/constants/index.ts
  packages/server/src/sdk/app/automations/crud.ts
  packages/server/src/sdk/plugins/plugins.ts
  packages/server/src/tests/utilities/api/query.ts
  packages/server/src/tests/utilities/api/row.ts
  packages/server/src/utilities/index.ts
  packages/server/src/utilities/routing/index.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/app/integration.ts
  packages/types/src/api/web/app/metadata.ts
  packages/types/src/api/web/app/permission.ts
  packages/types/src/api/web/app/query.ts
  packages/types/src/api/web/app/row.ts
  packages/types/src/api/web/app/rows/index.ts
  packages/types/src/api/web/app/screen.ts
  packages/types/src/api/web/global/index.ts
  packages/types/src/api/web/global/oldMigration.ts
  packages/types/src/api/web/index.ts
  packages/types/src/api/web/layout.ts
  packages/types/src/api/web/plugins.ts
  packages/types/src/api/web/query.ts
  packages/types/src/api/web/role.ts
  packages/types/src/api/web/system/index.ts
  packages/types/src/api/web/system/ops.ts
  packages/types/src/documents/app/index.ts
  packages/types/src/documents/app/metadata.ts
  packages/types/src/documents/app/screen.ts
  packages/types/src/documents/global/plugin.ts
  packages/types/src/sdk/permissions.ts
Labels: firestorm, size/l

#15119 Add automation survey popup
  packages/builder/src/pages/builder/app/[application]/automation/_layout.svelte
Labels: size/s

#15123 Fix schema exporting.
  .github/workflows/budibase_ci.yml
  packages/server/src/api/controllers/datasource.ts
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/integrations/microsoftSqlServer.ts
  packages/server/src/integrations/mysql.ts
  packages/server/src/integrations/postgres.ts
  packages/server/src/integrations/tests/utils/index.ts
  packages/server/src/integrations/tests/utils/mssql.ts
  packages/server/src/integrations/tests/utils/mysql.ts
  packages/server/src/integrations/tests/utils/oracle.ts
  packages/server/src/integrations/tests/utils/postgres.ts
  packages/server/src/tests/utilities/api/datasource.ts
Labels: firestorm, size/m

#15120 Final app service API typing
  packages/backend-core/package.json
  packages/backend-core/src/middleware/auditLog.ts
  packages/backend-core/src/middleware/authenticated.ts
  packages/backend-core/src/middleware/csrf.ts
  packages/backend-core/src/middleware/internalApi.ts
  packages/backend-core/src/middleware/matchers.ts
  packages/backend-core/src/middleware/passport/local.ts
  packages/backend-core/src/middleware/tenancy.ts
  packages/backend-core/src/security/roles.ts
  packages/backend-core/src/tenancy/tenancy.ts
  packages/backend-core/src/utils/tests/utils.spec.ts
  packages/backend-core/tests/core/utilities/structures/koa.ts
  packages/server/src/api/controllers/screen.ts
  packages/server/src/api/controllers/script.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/controllers/templates.ts
  packages/server/src/api/controllers/user.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/controllers/webhook.ts
  packages/server/src/api/index.ts
  packages/server/src/api/routes/script.ts
  packages/server/src/middleware/appInfo.ts
  packages/server/src/middleware/appMigrations.ts
  packages/server/src/middleware/cleanup.ts
  packages/server/src/middleware/currentapp.ts
  packages/server/src/middleware/joi-validator.ts
  packages/server/src/middleware/resourceId.ts
  packages/server/src/middleware/selfhost.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/tests/utilities/api/table.ts
  packages/types/src/api/web/app/application.ts
  packages/types/src/api/web/app/automation.ts
  packages/types/src/api/web/app/deployment.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/app/layout.ts
  packages/types/src/api/web/app/role.ts
  packages/types/src/api/web/app/screen.ts
  packages/types/src/api/web/app/static.ts
  packages/types/src/api/web/app/table.ts
  packages/types/src/api/web/app/user.ts
  packages/types/src/api/web/app/view.ts
  packages/types/src/api/web/app/webhook.ts
  packages/types/src/api/web/automation.ts
  packages/types/src/api/web/index.ts
  packages/types/src/api/web/template.ts
  packages/types/src/sdk/auth.ts
Labels: firestorm, size/l

#15129 Worker service API typing
  packages/backend-core/src/cache/invite.ts
  packages/server/src/api/controllers/templates.ts
  packages/types/src/api/web/auth.ts
  packages/types/src/api/web/global/configs.ts
  packages/types/src/api/web/global/email.ts
  packages/types/src/api/web/global/index.ts
  packages/types/src/api/web/global/license.ts
  packages/types/src/api/web/global/role.ts
  packages/types/src/api/web/global/self.ts
  packages/types/src/api/web/global/template.ts
  packages/types/src/api/web/system/account.ts
  packages/types/src/api/web/system/environment.ts
  packages/types/src/api/web/system/index.ts
  packages/types/src/api/web/system/log.ts
  packages/types/src/api/web/system/migration.ts
  packages/types/src/api/web/system/restore.ts
  packages/types/src/api/web/system/tenant.ts
  packages/types/src/api/web/user.ts
  packages/types/src/documents/global/devInfo.ts
  packages/types/src/documents/global/index.ts
  packages/worker/src/api/controllers/global/auth.ts
  packages/worker/src/api/controllers/global/configs.ts
  packages/worker/src/api/controllers/global/email.ts
  packages/worker/src/api/controllers/global/license.ts
  packages/worker/src/api/controllers/global/roles.ts
  packages/worker/src/api/controllers/global/self.ts
  packages/worker/src/api/controllers/global/templates.ts
  packages/worker/src/api/controllers/global/users.ts
  packages/worker/src/api/controllers/global/workspaces.ts
  packages/worker/src/api/controllers/system/accounts.ts
  packages/worker/src/api/controllers/system/environment.ts
  packages/worker/src/api/controllers/system/logs.ts
  packages/worker/src/api/controllers/system/migrations.ts
  packages/worker/src/api/controllers/system/restore.ts
  packages/worker/src/api/controllers/system/tenants.ts
  packages/worker/src/api/routes/global/email.ts
  packages/worker/src/api/routes/global/tests/email.spec.ts
  packages/worker/src/api/routes/global/tests/realEmail.spec.ts
  packages/worker/src/api/routes/global/tests/templates.spec.ts
  packages/worker/src/api/routes/global/workspaces.ts
  packages/worker/src/api/routes/index.ts
  packages/worker/src/api/routes/system/tests/environment.spec.ts
  packages/worker/src/constants/index.ts
  packages/worker/src/constants/templates/index.ts
  packages/worker/src/middleware/cloudRestricted.ts
  packages/worker/src/sdk/auth/auth.ts
  packages/worker/src/sdk/users/users.ts
  packages/worker/src/tests/controllers.ts
  packages/worker/src/utilities/email.ts
  packages/worker/src/utilities/templates.ts
Labels: firestorm, size/l

#15140 handle cases where datasourceName is undefined when sorting datasources
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
Labels: size/xs

#15081 Automation fixes
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/stores/builder/automations.js
Labels: size/s

#15118 3.0 metrics
  packages/backend-core/src/events/processors/posthog/PosthogProcessor.ts
  packages/backend-core/src/events/publishers/index.ts
  packages/backend-core/src/events/publishers/rowAction.ts
  packages/backend-core/src/events/publishers/table.ts
  packages/backend-core/src/events/publishers/view.ts
  packages/backend-core/tests/core/utilities/mocks/events.ts
  packages/server/src/api/controllers/rowAction/crud.ts
  packages/server/src/api/controllers/table/external.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/controllers/table/internal.ts
  packages/server/src/api/controllers/view/views.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/api/routes/tests/view.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/migrations/functions/backfill/app/tables.ts
  packages/server/src/migrations/tests/index.spec.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/server/src/sdk/app/tables/internal/index.ts
  packages/server/src/sdk/app/views/external.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/sdk/app/views/internal.ts
  packages/types/src/sdk/events/event.ts
  packages/types/src/sdk/events/index.ts
  packages/types/src/sdk/events/rowAction.ts
  packages/types/src/sdk/events/table.ts
  packages/types/src/sdk/events/view.ts
Labels: size/m

#15142 Get us much closer to using the recommended set of lints.
  eslint.config.mjs
  hosting/scripts/setup.js
  package.json
  packages/backend-core/tests/core/users/users.spec.js
  packages/server/src/api/controllers/query/import/tests/index.spec.js
  packages/server/src/api/routes/tests/analytics.spec.js
  packages/server/src/api/routes/tests/dev.spec.js
  packages/server/src/api/routes/tests/layout.spec.js
  packages/server/src/integrations/tests/googlesheets.spec.ts
  packages/server/src/integrations/tests/rest.spec.ts
  yarn.lock
Labels: firestorm, size/m

#15143 Enable a variety of useful looking lints.
  eslint.config.mjs
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/couch/utils.ts
  packages/backend-core/src/db/lucene.ts
  packages/backend-core/src/events/processors/Processors.ts
  packages/backend-core/src/middleware/authenticated.ts
  packages/backend-core/src/middleware/passport/sso/sso.ts
  packages/backend-core/src/objectStore/objectStore.ts
  packages/backend-core/src/redis/redlockImpl.ts
  packages/backend-core/tests/core/utilities/structures/quotas.ts
  packages/bbui/src/Form/Core/Signature.svelte
  packages/builder/src/components/backend/RoleEditor/BracketEdge.svelte
  packages/client/src/components/app/embedded-map/EmbeddedMapControls.js
  packages/client/src/stores/theme.js
  packages/server/src/api/controllers/dev.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/api/controllers/view/exporters.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/integrations/microsoftSqlServer.ts
  packages/server/src/integrations/oracle.ts
  packages/server/src/integrations/postgres.ts
  packages/server/src/integrations/rest.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/middleware/builder.ts
  packages/server/src/sdk/app/permissions/index.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/utilities/retry.ts
  packages/server/src/websockets/websocket.ts
  packages/shared-core/src/helpers/cron.ts
  packages/string-templates/test/hbsToJs.spec.ts
  packages/string-templates/test/utils.ts
  packages/types/src/sdk/db.ts
  packages/worker/src/sdk/accounts/metadata.ts
  packages/worker/src/tests/api/accounts.ts
  packages/worker/src/tests/api/auditLogs.ts
  packages/worker/src/tests/api/auth.ts
  packages/worker/src/tests/api/base.ts
  packages/worker/src/tests/api/configs.ts
  packages/worker/src/tests/api/email.ts
  packages/worker/src/tests/api/environment.ts
  packages/worker/src/tests/api/groups.ts
  packages/worker/src/tests/api/license.ts
  packages/worker/src/tests/api/migrations.ts
  packages/worker/src/tests/api/restore.ts
  packages/worker/src/tests/api/roles.ts
  packages/worker/src/tests/api/scim/groups.ts
  packages/worker/src/tests/api/scim/shared.ts
  packages/worker/src/tests/api/scim/users.ts
  packages/worker/src/tests/api/self.ts
  packages/worker/src/tests/api/status.ts
  packages/worker/src/tests/api/templates.ts
  packages/worker/src/tests/api/users.ts
  scripts/build.js
Labels: firestorm, size/m

#15136 Stop coercing all values to strings when using CoreCheckboxGroup
  packages/bbui/src/Form/Core/CheckboxGroup.svelte
Labels: size/xs

#15147 Disable filter value binding input when no column is selected in filter screen
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/BranchNode.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/backend/DataTable/buttons/TableFilterButton.svelte
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterEditor.svelte
  packages/client/src/components/app/dynamic-filter/DynamicFilter.svelte
  packages/frontend-core/src/components/CoreFilterBuilder.svelte
  packages/frontend-core/src/utils/utils.js
  packages/shared-core/src/filters.ts
Labels: size/s

#15151 Update outdated rollup deps
  packages/string-templates/package.json
  packages/string-templates/rollup.config.js
  yarn.lock
Labels: firestorm, size/s

#15159 Fix string-templates on dev
  packages/string-templates/rollup.config.js
Labels: firestorm, size/xs

#15155 Fix for fetching schemas in Postgres 9.5
  .github/workflows/budibase_ci.yml
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/postgres.ts
  packages/server/src/integrations/tests/utils/images.ts
  packages/server/src/integrations/tests/utils/index.ts
  packages/server/src/integrations/tests/utils/postgres.ts
Labels: firestorm, size/s

#15161 Fix client error SVG
  packages/client/src/components/ClientApp.svelte
Labels: size/xs

#15001 Automation Branching UX updates
  packages/builder/src/components/automation/AutomationBuilder/DraggableCanvas.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/BranchNode.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItem.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItemActions.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/StepNode.svelte
  packages/builder/src/stores/builder/automations.js
Labels: size/l

#15171 API typing fixes
  packages/server/src/api/controllers/permission.ts
  packages/types/src/api/web/app/permission.ts
  packages/types/src/api/web/global/self.ts
  packages/types/src/documents/app/app.ts
Labels: firestorm, size/xs

#15163 Prevent syncing row changes between users for views filtered by current user
  packages/bbui/src/Layout/Page.svelte
  packages/builder/src/global.css
  packages/server/src/websockets/grid.ts
Labels: size/s

#15182 API typing fixes
  packages/server/src/api/controllers/analytics.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/automation.ts
  packages/server/src/api/controllers/datasource.ts
  packages/server/src/api/controllers/layout.ts
  packages/server/src/api/controllers/migrations.ts
  packages/server/src/api/controllers/permission.ts
  packages/server/src/api/controllers/query/index.ts
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/controllers/rowAction/run.ts
  packages/server/src/api/controllers/screen.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/automations/steps/createRow.ts
  packages/server/src/automations/steps/deleteRow.ts
  packages/server/src/automations/steps/queryRows.ts
  packages/server/src/automations/steps/updateRow.ts
  packages/server/src/automations/tests/queryRows.spec.ts
  packages/server/src/tests/utilities/api/application.ts
  packages/types/src/api/web/analytics.ts
  packages/types/src/api/web/app/application.ts
  packages/types/src/api/web/app/permission.ts
  packages/types/src/api/web/app/rowAction.ts
  packages/types/src/api/web/auth.ts
  packages/types/src/api/web/global/environmentVariables.ts
  packages/types/src/api/web/global/events.ts
  packages/types/src/api/web/global/license.ts
  packages/types/src/api/web/global/oldMigration.ts
  packages/types/src/api/web/system/migration.ts
  packages/types/src/api/web/user.ts
  packages/worker/src/api/controllers/global/auth.ts
  packages/worker/src/api/controllers/global/events.ts
  packages/worker/src/api/controllers/global/license.ts
  packages/worker/src/api/controllers/global/users.ts
  packages/worker/src/api/controllers/system/accounts.ts
  packages/worker/src/api/controllers/system/migrations.ts
  packages/worker/src/api/routes/system/tests/migrations.spec.ts
Labels: firestorm, size/m

#15191 Remove stopped containers
  .github/workflows/budibase_ci.yml
  yarn.lock
Labels: firestorm, size/s

#15170 Convert portal admin store to typescript
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/ActionModal.svelte
  packages/builder/src/pages/builder/admin/_layout.svelte
  packages/builder/src/pages/builder/portal/settings/email/index.svelte
  packages/builder/src/stores/portal/admin.test.js
  packages/builder/src/stores/portal/admin.ts
Labels: size/s

#15174 Convert portal apps store to typescript
  packages/builder/src/stores/BudiStore.ts
  packages/builder/src/stores/portal/apps.ts
Labels: size/m

#15178 Convert portal audit logs store to typescript
  packages/builder/src/pages/builder/portal/account/auditLogs/index.svelte
  packages/builder/src/stores/BudiStore.ts
  packages/builder/src/stores/portal/auditLogs.js
  packages/builder/src/stores/portal/auditLogs.ts
  packages/builder/src/stores/portal/licensing.js
Labels: size/s

#15181 Convert portal auth store to typescript
  packages/builder/src/pages/builder/admin/index.svelte
  packages/builder/src/pages/builder/auth/login.svelte
  packages/builder/src/pages/builder/invite/index.svelte
  packages/builder/src/stores/portal/apps.ts
  packages/builder/src/stores/portal/auth.js
  packages/builder/src/stores/portal/auth.ts
  packages/types/src/documents/global/user.ts
Labels: size/m

#15184 Automation webhook binding fixes
  packages/server/src/api/controllers/webhook.ts
  packages/server/src/automations/tests/scenarios/webhook.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/webhook.ts
  packages/shared-core/src/sdk/documents/automations.ts
  packages/types/package.json
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
  packages/types/src/documents/app/webhook.ts
  yarn.lock
Labels: firestorm, size/m

#15195 UI - always ask for password with encrypted app exports
  packages/builder/src/components/start/CreateAppModal.svelte
  packages/builder/src/pages/builder/portal/apps/index.svelte
  packages/server/src/sdk/app/backups/imports.ts
Labels: firestorm, size/s

#15196 Reject plugins when importing apps
  packages/server/src/sdk/app/backups/imports.ts
Labels: firestorm, size/s

#15197 Datasource fetch schema fix
  packages/builder/src/stores/builder/datasources.js
Labels: firestorm, size/s

#15198 Typing datasource and sorted integration stores
  packages/builder/src/stores/builder/datasources.ts
  packages/builder/src/stores/builder/sortedIntegrations.js
  packages/builder/src/stores/builder/sortedIntegrations.ts
  packages/server/scripts/integrations/mysql/init.sql
  packages/types/src/api/web/app/datasource.ts
  packages/types/src/index.ts
  packages/types/src/ui/index.ts
  packages/types/src/ui/stores/index.ts
  packages/types/src/ui/stores/integration.ts
Labels: firestorm, size/m

#15194 Remove automations survey
  packages/builder/src/pages/builder/app/[application]/automation/_layout.svelte
Labels: size/s

#15204 Allow views and tables with whitespaces
  packages/backend-core/src/sql/utils.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/db/utils.ts
  packages/server/src/tests/utilities/api/viewV2.ts
Labels: firestorm, size/s

#15203 Build builder in dev mode while on dev
  packages/builder/package.json
Labels: firestorm, size/xs

#15201 Fix patching rows from views with hidden relationships
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/s

#15212 Fix onboarding users
  packages/builder/src/pages/builder/app/[application]/_components/BuilderSidePanel.svelte
Labels: size/s

#15213 Fix datasource validity checking
  packages/builder/src/stores/BudiStore.ts
  packages/builder/src/stores/builder/app.js
  packages/builder/src/stores/builder/builder.js
  packages/builder/src/stores/builder/components.js
  packages/builder/src/stores/builder/datasources.ts
  packages/builder/src/stores/builder/hover.js
  packages/builder/src/stores/builder/layouts.js
  packages/builder/src/stores/builder/navigation.js
  packages/builder/src/stores/builder/rowActions.js
  packages/builder/src/stores/builder/screens.js
  packages/builder/src/stores/builder/sortedIntegrations.ts
  packages/builder/src/stores/portal/apps.ts
  packages/builder/src/stores/portal/auditLogs.ts
  packages/builder/src/stores/portal/auth.ts
Labels: size/m

#15209 Guard display column in the api
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/shared-core/src/table.ts
Labels: firestorm, size/m

#15221 allow users to select firestore databases other than the default
  packages/builder/src/components/backend/Datasources/ConfigEditor/ConfigInput.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/fields/LongForm.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/fields/Select.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/fields/String.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/index.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/stores/validatedConfig.js
  packages/server/src/integrations/firebase.ts
  packages/types/src/sdk/datasources.ts
Labels: size/s

#15220 Typing the table store
  packages/builder/src/stores/builder/tables.ts
Labels: firestorm, size/m

#15224 Typing viewV2 store
  packages/builder/src/stores/builder/viewsV2.js
  packages/builder/src/stores/builder/viewsV2.ts
  packages/server/src/sdk/app/views/index.ts
  packages/shared-core/src/helpers/views.ts
Labels: firestorm, size/m

#15228 Typing grid columns store
  packages/builder/tsconfig.json
  packages/frontend-core/src/components/grid/stores/columns.ts
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/types/src/ui/stores/grid/columns.ts
  packages/types/src/ui/stores/grid/index.ts
  packages/types/src/ui/stores/index.ts
Labels: size/s

#15229 Typing grid datasources store
  packages/frontend-core/src/components/grid/stores/datasources/nonPlus.ts
  packages/frontend-core/src/components/grid/stores/datasources/table.ts
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.ts
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/types/src/ui/stores/grid/datasource.ts
  packages/types/src/ui/stores/grid/index.ts
Labels: firestorm, size/m

#15235 Configure frontend-core
  packages/frontend-core/package.json
  packages/frontend-core/tsconfig.json
Labels: firestorm, size/s

#15227 Typing automation store
  packages/builder/package.json
  packages/builder/src/dataBinding.js
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/stores/portal/licensing.js
  packages/server/src/tests/utilities/structures.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/types/src/documents/app/automation/schema.ts
  packages/types/src/ui/stores/automations.ts
  packages/types/src/ui/stores/index.ts
  yarn.lock
Labels: firestorm, size/xl

#15236 Typing grid datasources stores
  packages/frontend-core/src/components/grid/stores/datasource.ts
  packages/frontend-core/src/components/grid/stores/datasources/index.ts
  packages/frontend-core/src/components/grid/stores/datasources/nonPlus.ts
  packages/frontend-core/src/components/grid/stores/datasources/table.ts
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.ts
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/utils/index.ts
  packages/frontend-core/src/utils/relatedColumns.js
  packages/frontend-core/src/utils/relatedColumns.ts
  packages/types/src/ui/stores/grid/datasource.ts
  packages/types/src/ui/stores/grid/index.ts
  packages/types/src/ui/stores/grid/table.ts
  packages/types/src/ui/stores/grid/view.ts
Labels: firestorm, size/m

#15261 Fix wrong datasource typing
  packages/frontend-core/src/components/grid/stores/datasource.ts
Labels: firestorm, size/xs

#15256 Fix svelte warnings
  packages/bbui/src/Form/Core/DatePicker/NumberInput.svelte
  packages/bbui/src/Form/Core/Slider.svelte
  packages/bbui/src/Tabs/Tabs.svelte
  packages/bbui/src/Tooltip/AbsTooltip.svelte
  packages/frontend-core/src/components/grid/cells/AICell.svelte
  packages/frontend-core/src/components/grid/cells/LongFormCell.svelte
  packages/frontend-core/src/components/grid/cells/TextCell.svelte
Labels: firestorm, size/s

#15238 Typing grid validation stores
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/components/grid/stores/validation.ts
Labels: firestorm, size/s

#15262 Builder store typescript conversions
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/builder/builder.ts
  packages/builder/src/stores/builder/contextMenu.js
  packages/builder/src/stores/builder/contextMenu.ts
  packages/builder/src/stores/builder/deployments.ts
  packages/builder/src/stores/builder/tests/builder.test.js
Labels: firestorm, size/m

#15239 Typing grid users stores
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/components/grid/stores/users.ts
  packages/types/src/ui/stores/grid/index.ts
  packages/types/src/ui/stores/grid/user.ts
Labels: firestorm, size/s

#15240 Typing grid menu store
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/components/grid/stores/menu.ts
Labels: firestorm, size/s

#15250 Typing grid clipboard store
  packages/frontend-core/src/components/grid/stores/clipboard.ts
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/components/grid/stores/ui.ts
Labels: firestorm, size/s

#15251 Typing grid scroll store
  packages/frontend-core/src/components/grid/stores/columns.ts
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/components/grid/stores/scroll.ts
  packages/frontend-core/src/components/grid/stores/ui.ts
  packages/types/src/ui/stores/grid/columns.ts
Labels: firestorm, size/s

#15271 Typing grid reorder store
  packages/frontend-core/src/components/grid/lib/utils.ts
  packages/frontend-core/src/components/grid/stores/columns.ts
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/components/grid/stores/reorder.ts
  packages/types/src/ui/stores/grid/columns.ts
  packages/types/src/ui/stores/grid/datasource.ts
Labels: size/s

#15272 Typing grid resize store
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/components/grid/stores/resize.ts
  packages/frontend-core/src/components/grid/stores/ui.ts
Labels: size/s

#15264 Typing grid config store
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/GridColumnConfiguration.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/frontend-core/src/components/grid/stores/columns.ts
  packages/frontend-core/src/components/grid/stores/config.ts
  packages/frontend-core/src/components/grid/stores/datasource.ts
  packages/frontend-core/src/components/grid/stores/datasources/nonPlus.ts
  packages/frontend-core/src/components/grid/stores/datasources/table.ts
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.ts
  packages/frontend-core/src/components/grid/stores/filter.ts
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/utils/memo.d.ts
  packages/frontend-core/src/utils/relatedColumns.ts
  packages/types/src/ui/stores/grid/table.ts
Labels: firestorm, size/m

#15265 Typing grid conditions store
  packages/frontend-core/src/components/grid/stores/conditions.ts
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/types/src/ui/stores/grid/condition.ts
  packages/types/src/ui/stores/grid/index.ts
Labels: firestorm, size/s

#15266 Typing remaining grid stores
  packages/bbui/src/ProgressCircle/ProgressCircle.svelte
  packages/client/svelte.config.mjs
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/frontend-core/src/components/grid/lib/events.ts
  packages/frontend-core/src/components/grid/stores/bounds.js
  packages/frontend-core/src/components/grid/stores/bounds.ts
  packages/frontend-core/src/components/grid/stores/cache.ts
  packages/frontend-core/src/components/grid/stores/datasources/nonPlus.ts
  packages/frontend-core/src/components/grid/stores/datasources/table.ts
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.ts
  packages/frontend-core/src/components/grid/stores/index.ts
  packages/frontend-core/src/components/grid/stores/notifications.ts
  packages/frontend-core/src/components/grid/stores/pagination.ts
  packages/frontend-core/src/components/grid/stores/sort.ts
  packages/frontend-core/src/components/grid/stores/viewport.ts
  packages/server/package.json
  tsconfig.build.json
  yarn.lock
Labels: firestorm, size/m

#15273 Respect grid config in builder
  packages/frontend-core/src/components/grid/stores/columns.ts
Labels: firestorm, size/xs

#15267 Component, Integrations and componentTreeNode stores converted to typescript
  packages/builder/src/dataBinding.js
  packages/builder/src/stores/BudiStore.ts
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/builder/builder.ts
  packages/builder/src/stores/builder/componentTreeNodes.js
  packages/builder/src/stores/builder/componentTreeNodes.ts
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/integrations.js
  packages/builder/src/stores/builder/integrations.ts
  packages/builder/src/stores/builder/screens.js
Labels: firestorm, size/l

#15268 Plugin author enhancements
  packages/client/src/components/preview/SettingsBar.svelte
  packages/client/src/components/preview/SettingsButton.svelte
  packages/client/src/components/preview/SettingsColorPicker.svelte
  packages/client/src/components/preview/SettingsPicker.svelte
  packages/client/src/sdk.js
  packages/frontend-core/src/components/grid/lib/constants.js
Labels: size/s
