Repository Budibase/budibase, pull requests merged in 2024-05, with the labels that each got.

#13579 [Fix] Schema panel null references
  packages/builder/src/components/integration/QueryViewerSidePanel/SchemaPanel.svelte
  packages/builder/src/components/integration/RestQueryViewer.svelte
  packages/builder/src/constants/backend/index.js
Labels: firestorm

#13601 Correct types for application updating.
  packages/server/src/api/controllers/application.ts
  packages/server/src/tests/utilities/api/application.ts
  packages/types/src/api/web/application.ts
Labels: firestorm

#13543 Single user column type
  .eslintrc.json
  packages/backend-core/src/cache/user.ts
  packages/backend-core/src/middleware/authenticated.ts
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/backend/DataTable/formula.js
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/components/backend/DataTable/modals/grid/GridEditColumnModal.svelte
  packages/builder/src/components/backend/TableNavigator/ExistingTableDataImport.svelte
  packages/builder/src/components/design/settings/controls/FieldConfiguration/utils.js
  packages/builder/src/constants/backend/index.js
  packages/builder/src/dataBinding.js
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/manifest.json
  packages/client/src/components/app/blocks/FormBlockComponent.svelte
  packages/client/src/components/app/forms/BBReferenceField.svelte
  packages/client/src/components/app/forms/BBReferenceSingleField.svelte
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/client/src/components/app/forms/index.js
  packages/frontend-core/src/components/grid/cells/BBReferenceCell.svelte
  packages/frontend-core/src/components/grid/cells/BBReferenceSingleCell.svelte
  packages/frontend-core/src/components/grid/cells/RelationshipCell.svelte
  packages/frontend-core/src/components/grid/lib/renderers.js
  packages/frontend-core/src/constants.js
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/integrations/base/sqlTable.ts
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/sdk/app/rows/search/tests/utils.spec.ts
  packages/server/src/sdk/app/rows/search/utils.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/server/src/utilities/rowProcessor/bbReferenceProcessor.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/tests/bbReferenceProcessor.spec.ts
  packages/server/src/utilities/rowProcessor/tests/inputProcessing.spec.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
  packages/server/src/utilities/schema.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/table.ts
  packages/types/src/documents/app/row.ts
  packages/types/src/documents/app/table/constants.ts
  packages/types/src/documents/app/table/schema.ts
Labels: do not merge, firestorm, feature-branch

#13613 Updating SQS server connection address
  hosting/couchdb/runner.v2.sh
Labels: firestorm

#13633 Fix behaviour of 'when filter empty' for empty and notEmpty filter types.
  packages/backend-core/src/db/lucene.ts
  packages/server/src/api/routes/tests/search.spec.ts
Labels: firestorm

#13637 Remove aws sdk global mock and update tests
  .github/workflows/budibase_ci.yml
  globalSetup.ts
  packages/backend-core/src/objectStore/objectStore.ts
  packages/backend-core/tests/core/utilities/index.ts
  packages/backend-core/tests/core/utilities/minio.ts
  packages/backend-core/tests/core/utilities/testContainerUtils.ts
  packages/server/src/api/routes/tests/attachment.spec.ts
  packages/server/src/api/routes/tests/backup.spec.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/static.spec.js
  packages/server/src/integrations/tests/aws-sdk.mock.ts
  packages/server/src/integrations/tests/dynamodb.spec.ts
  packages/server/src/integrations/tests/rest.spec.ts
  packages/server/src/integrations/tests/s3.spec.ts
  packages/server/src/tests/jestEnv.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
  packages/worker/src/api/routes/global/tests/realEmail.spec.ts
Labels: firestorm

#13614 Tests for searching boolean fields, including fixes for various bugs.
  packages/backend-core/src/db/lucene.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/automations/tests/queryRows.spec.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/sdk/app/rows/search/internalSearch.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
Labels: firestorm

#13640 Typing improvements for REST integration - fixing no responses
  packages/server/src/integrations/rest.ts
  packages/server/src/integrations/tests/rest.spec.ts
Labels: firestorm

#13645 Disable autocolumn addition to external tables (API validation)
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/sdk/app/tables/external/index.ts
Labels: firestorm

#13567 Support attachment columns in Automations
  packages/backend-core/src/objectStore/objectStore.ts
  packages/backend-core/src/objectStore/utils.ts
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/builder/src/components/common/bindings/DrawerBindableSlot.svelte
  packages/builder/src/components/integration/KeyValueBuilder.svelte
  packages/server/src/automations/automationUtils.ts
  packages/server/src/automations/steps/createRow.ts
  packages/server/src/automations/steps/updateRow.ts
  packages/server/src/automations/tests/createRow.spec.ts
  packages/server/src/integrations/rest.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/types/src/documents/app/automation.ts
  packages/worker/src/utilities/email.ts
Labels: firestorm, feature-branch

#13648 Improving binary column support
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/utils/utils.ts
Labels: firestorm

#13594 Fix user relationship to user column migration
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/components/backend/TableNavigator/ExistingTableDataImport.svelte
  packages/builder/src/constants/backend/index.js
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/frontend-core/src/components/grid/cells/BBReferenceCell.svelte
  packages/frontend-core/src/components/grid/controls/MigrationModal.svelte
  packages/frontend-core/src/components/grid/lib/utils.js
  packages/frontend-core/src/constants.js
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/base/sqlTable.ts
  packages/server/src/sdk/app/rows/search/utils.ts
  packages/server/src/sdk/app/tables/migration.ts
  packages/server/src/utilities/schema.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/helpers/index.ts
  packages/shared-core/src/helpers/schema.ts
  packages/types/src/api/web/app/table.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm

#13668 Fix tests depending on date
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/automations/tests/executeQuery.spec.ts
Labels: firestorm

#13650 Fixing issue with grid not allowing copying external ID
  packages/frontend-core/src/components/grid/layout/GridRow.svelte
  packages/frontend-core/src/components/grid/layout/NewRow.svelte
  packages/frontend-core/src/components/grid/layout/StickyColumn.svelte
  packages/frontend-core/src/components/grid/lib/utils.js
  packages/frontend-core/src/components/grid/overlays/KeyboardManager.svelte
  packages/frontend-core/src/components/grid/overlays/MenuOverlay.svelte
  packages/frontend-core/src/components/grid/stores/rows.js
  packages/frontend-core/src/components/grid/stores/scroll.js
  packages/frontend-core/src/components/grid/stores/ui.js
  packages/frontend-core/src/components/grid/stores/validation.js
Labels: firestorm

#13604 [Feat] Single user column
  .eslintrc.json
  packages/backend-core/src/cache/user.ts
  packages/backend-core/src/middleware/authenticated.ts
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/backend/DataTable/formula.js
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/components/backend/DataTable/modals/grid/GridEditColumnModal.svelte
  packages/builder/src/components/backend/TableNavigator/ExistingTableDataImport.svelte
  packages/builder/src/components/design/settings/controls/FieldConfiguration/utils.js
  packages/builder/src/constants/backend/index.js
  packages/builder/src/dataBinding.js
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/manifest.json
  packages/client/src/components/app/blocks/FormBlockComponent.svelte
  packages/client/src/components/app/forms/BBReferenceField.svelte
  packages/client/src/components/app/forms/BBReferenceSingleField.svelte
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/client/src/components/app/forms/index.js
  packages/frontend-core/src/components/FilterBuilder.svelte
  packages/frontend-core/src/components/grid/cells/BBReferenceCell.svelte
  packages/frontend-core/src/components/grid/cells/BBReferenceSingleCell.svelte
  packages/frontend-core/src/components/grid/cells/RelationshipCell.svelte
  packages/frontend-core/src/components/grid/controls/MigrationModal.svelte
  packages/frontend-core/src/components/grid/lib/renderers.js
  packages/frontend-core/src/components/grid/lib/utils.js
  packages/frontend-core/src/constants.js
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/base/sqlTable.ts
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/tests/utils.spec.ts
  packages/server/src/sdk/app/rows/search/utils.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/server/src/sdk/app/tables/migration.ts
  packages/server/src/utilities/rowProcessor/bbReferenceProcessor.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/tests/bbReferenceProcessor.spec.ts
  packages/server/src/utilities/rowProcessor/tests/inputProcessing.spec.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
  packages/server/src/utilities/schema.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/helpers/index.ts
  packages/shared-core/src/helpers/schema.ts
  packages/shared-core/src/table.ts
  packages/types/src/api/web/app/table.ts
  packages/types/src/documents/app/row.ts
  packages/types/src/documents/app/table/constants.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm, feature-branch

#13670 Fixing `AUTOMATION_THREAD_TIMEOUT` environment variable
  packages/builder/src/stores/builder/automations.js
  packages/server/src/api/controllers/automation.ts
  packages/server/src/environment.ts
Labels: firestorm

#13426 Selected row + export data support for grid blocks (new table component)
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/ExportData.svelte
  packages/client/manifest.json
  packages/client/src/components/app/GridBlock.svelte
  packages/client/src/stores/rowSelection.js
  packages/client/src/utils/buttonActions.js
  packages/frontend-core/src/components/grid/cells/GutterCell.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/frontend-core/src/components/grid/stores/ui.js
Labels: feature-branch

#13676 Fixes for update row action in automations and attachments
  packages/backend-core/src/objectStore/utils.ts
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/server/src/automations/automationUtils.ts
  packages/server/src/automations/steps/updateRow.ts
  packages/server/src/utilities/rowProcessor/attachments.ts
  packages/server/src/utilities/rowProcessor/index.ts
Labels: firestorm

#13693 Quick fix for worker/server tests expecting missing messaging
  packages/server/src/automations/tests/executeQuery.spec.ts
  packages/worker/src/api/routes/global/tests/scim.spec.ts
Labels: firestorm

#13395 Add support for file uploads with custom S3 endpoints
  .github/AUTHORS.md
  packages/builder/src/components/design/settings/controls/S3DataSourceSelect.svelte
  packages/server/src/api/controllers/static/index.ts
Labels: stale

#13694 Handle invalid content-dispositions, still allow REST download
  packages/server/__mocks__/node-fetch.ts
  packages/server/src/integrations/rest.ts
  packages/server/src/integrations/tests/rest.spec.ts
  packages/server/src/integrations/tests/restUtils.spec.ts
  packages/server/src/integrations/utils/restUtils.ts
  yarn.lock
Labels: firestorm

#13689 SQS cleanup (tables and apps)
  .eslintrc.json
  packages/backend-core/src/db/Replication.ts
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/couch/utils.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/backend-core/src/environment.ts
  packages/backend-core/src/users/db.ts
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/tables/internal/index.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/types/src/documents/app/sqlite.ts
  packages/types/src/sdk/db.ts
Labels: firestorm

#13704 Reduce googleapi calls
  packages/backend-core/src/context/types.ts
  packages/server/package.json
  packages/server/src/integrations/googlesheets.ts
  yarn.lock
Labels: feature-branch

#13716 Fixing CLI logging
  packages/cli/src/environment.ts
  packages/cli/src/index.ts
  packages/cli/start.sh
Labels: firestorm

#13717 Disallowing arrays for single types (attachment and user)
  packages/server/src/sdk/app/rows/utils.ts
Labels: firestorm

#13667 Added the ability to disable automations
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
  packages/builder/src/components/automation/AutomationPanel/EditAutomationPopover.svelte
  packages/builder/src/components/common/NavItem.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/TriggerAutomation.svelte
  packages/builder/src/stores/builder/automations.js
  packages/server/src/api/controllers/automation.ts
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/automations/utils.ts
  packages/types/src/documents/app/automation.ts
Labels: bb-automations

#13714 Unable to load grid when using external postgres
  packages/bbui/src/Form/Core/DatePicker/NumberInput.svelte
  packages/bbui/src/Form/Core/DatePicker/TimePicker.svelte
  packages/bbui/src/helpers.js
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/base/sqlTable.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/utilities/schema.ts
Labels: feature-branch

#13740 Move more tests out of `sql.spec.ts`
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/tests/utilities/structures.ts
Labels: firestorm

#13728 Search tests for user relationship columns.
  lerna.json
  packages/server/src/api/controllers/view/exporters.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/base/sql.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
Labels: firestorm

#13764 Changing REST content response processing
  packages/server/src/api/routes/tests/queries/rest.spec.ts
  packages/server/src/integrations/rest.ts
  packages/server/src/integrations/tests/rest.spec.ts
  packages/server/src/integrations/utils/utils.ts
Labels: firestorm

#13771 Update package.json to publish CouchDB with 3.3.3 tag
  package.json
Labels: firestorm

#13793 Allow production SQS
  packages/server/src/startup/index.ts
Labels: firestorm

#13803 Fix for knex build issue
  scripts/build.js
Labels: firestorm

#13795 Fix for template apps (old rows/views) in SQS
  package.json
  packages/backend-core/src/sql/sql.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/types/src/sdk/search.ts
Labels: firestorm

#13810 Update view column UI
  packages/bbui/src/ActionButton/ActionButton.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/frontend-core/src/components/grid/controls/ToggleActionButtonGroup.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
Labels: firestorm

#13814 Add tests for creating apps from templates.
  packages/server/src/api/routes/tests/data/agency-client-portal.tar.gz
  packages/server/src/api/routes/tests/templates.spec.js
  packages/server/src/api/routes/tests/templates.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/template.ts
Labels: firestorm

#13830 Readonly columns in forms in the client
  packages/client/src/components/app/forms/InnerForm.svelte
Labels: firestorm
