Repository Budibase/budibase, pull requests merged in 2024-02, with the labels that each got.

#12769 Migrate from `vm` to `isolated-vm`
  hosting/single/Dockerfile
  packages/backend-core/package.json
  packages/backend-core/src/context/types.ts
  packages/backend-core/src/timers/timers.ts
  packages/bbui/src/Form/Core/EnvDropdown.svelte
  packages/server/Dockerfile
  packages/server/nodemon.json
  packages/server/package.json
  packages/server/scripts/test.sh
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/db/newid.ts
  packages/server/src/environment.ts
  packages/server/src/jsRunner.ts
  packages/server/src/jsRunner/index.ts
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
  packages/server/src/utilities/fileSystem/filesystem.ts
  packages/server/src/utilities/scriptRunner.ts
  packages/string-templates/package.json
  packages/string-templates/src/errors.js
  packages/string-templates/src/helpers/javascript.js
  packages/string-templates/src/helpers/list.js
  packages/string-templates/src/index-helpers.js
  packages/string-templates/src/index.cjs
  packages/string-templates/src/index.js
  packages/string-templates/src/index.mjs
  packages/string-templates/test/manifest.spec.js
  packages/string-templates/test/utils.js
  packages/worker/Dockerfile
  packages/worker/nodemon.json
  yarn.lock
Labels: feature-branch

#12932 Fix automation JS scripts
  packages/server/src/api/controllers/script.ts
  packages/server/src/automations/tests/executeScript.spec.js
  packages/server/src/utilities/scriptRunner.ts
Labels: firestorm

#12930 Migrate from `vm` to `isolated-vm`
  hosting/single/Dockerfile
  packages/backend-core/package.json
  packages/backend-core/src/context/types.ts
  packages/backend-core/src/timers/timers.ts
  packages/bbui/src/Form/Core/EnvDropdown.svelte
  packages/server/Dockerfile
  packages/server/nodemon.json
  packages/server/package.json
  packages/server/scripts/test.sh
  packages/server/src/api/controllers/script.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/automations/tests/executeScript.spec.js
  packages/server/src/db/newid.ts
  packages/server/src/environment.ts
  packages/server/src/jsRunner.ts
  packages/server/src/jsRunner/index.ts
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
  packages/server/src/utilities/fileSystem/filesystem.ts
  packages/server/src/utilities/scriptRunner.ts
  packages/string-templates/package.json
  packages/string-templates/src/errors.js
  packages/string-templates/src/helpers/javascript.js
  packages/string-templates/src/helpers/list.js
  packages/string-templates/src/index-helpers.js
  packages/string-templates/src/index.cjs
  packages/string-templates/src/index.js
  packages/string-templates/src/index.mjs
  packages/string-templates/test/manifest.spec.js
  packages/string-templates/test/utils.js
  packages/worker/Dockerfile
  packages/worker/nodemon.json
  yarn.lock
Labels: feature-branch

#12939 A small UX improvement to the automation scripting system
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/CodeEditor/index.js
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/BindingPicker.svelte
  packages/builder/src/components/common/bindings/utils.js
Labels: firestorm

#12931 Remove proxying of context changes up the chain
  packages/builder/src/builderStore/componentUtils.js
  packages/builder/src/builderStore/dataBinding.js
  packages/client/manifest.json
  packages/client/src/components/app/Repeater.svelte
  packages/client/src/components/context/Provider.svelte
  packages/client/src/constants.js
  packages/client/src/sdk.js
  packages/client/src/stores/context.js
  packages/frontend-core/src/constants.js
Labels: feature-branch

#12963 Move bundle responsibility from string-templates to server
  .eslintignore
  .prettierignore
  packages/server/package.json
  packages/server/src/jsRunner/bundles/README.md
  packages/server/src/jsRunner/bundles/index-helpers.ivm.bundle.js
  packages/server/src/jsRunner/bundles/index-helpers.ts
  packages/server/src/jsRunner/bundles/index.ts
  packages/server/src/jsRunner/index.ts
  packages/server/src/utilities/scriptRunner.ts
  packages/string-templates/package.json
  scripts/build.js
Labels: firestorm

#12868 Allow logo in top navigation to be a link
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/index.svelte
  packages/client/src/components/app/Layout.svelte
Labels: feature-branch

#12979 Improve asserts in mongodb tess
  packages/server/src/api/routes/tests/queries/mongodb.spec.ts
Labels: firestorm

#12984 Fixing an issue with 1000+ attachments being backed up
  packages/backend-core/src/objectStore/objectStore.ts
  packages/backend-core/src/queue/queue.ts
  yarn.lock
Labels: firestorm

#12964 Fix BSON usage for isolated-vm
  packages/builder/src/components/integration/QueryViewerSidePanel/JSONPanel.svelte
  packages/builder/src/components/integration/QueryViewerSidePanel/PreviewPanel.svelte
  packages/builder/src/components/integration/QueryViewerSidePanel/index.svelte
  packages/server/package.json
  packages/server/scripts/integrations/mongo/docker-compose.yaml
  packages/server/src/integrations/mongodb.ts
  packages/server/src/integrations/tests/mongo.spec.ts
  packages/server/src/jsRunner/bundles/bson.ivm.bundle.js
  packages/server/src/jsRunner/bundles/bsonPackage.ts
  packages/server/src/jsRunner/bundles/index.ts
  packages/server/src/jsRunner/vm/index.ts
  packages/server/src/threads/definitions.ts
  packages/server/src/threads/query.ts
  packages/server/src/utilities/scriptRunner.ts
  yarn.lock
Labels: firestorm, feature-branch

#12938 Migrate from `vm` to `isolated-vm`
  .eslintignore
  .prettierignore
  hosting/single/Dockerfile
  package.json
  packages/backend-core/package.json
  packages/backend-core/src/context/types.ts
  packages/backend-core/src/timers/timers.ts
  packages/bbui/src/Form/Core/EnvDropdown.svelte
  packages/builder/src/components/integration/QueryViewer.svelte
  packages/builder/src/components/integration/QueryViewerSidePanel/JSONPanel.svelte
  packages/builder/src/components/integration/QueryViewerSidePanel/PreviewPanel.svelte
  packages/builder/src/components/integration/QueryViewerSidePanel/index.svelte
  packages/server/Dockerfile
  packages/server/nodemon.json
  packages/server/package.json
  packages/server/scripts/integrations/mongo/docker-compose.yaml
  packages/server/scripts/test.sh
  packages/server/src/api/controllers/script.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/automations/tests/executeScript.spec.js
  packages/server/src/db/newid.ts
  packages/server/src/environment.ts
  packages/server/src/integrations/mongodb.ts
  packages/server/src/integrations/tests/mongo.spec.ts
  packages/server/src/jsRunner.ts
  packages/server/src/jsRunner/bundles/README.md
  packages/server/src/jsRunner/bundles/bson.ivm.bundle.js
  packages/server/src/jsRunner/bundles/bsonPackage.ts
  packages/server/src/jsRunner/bundles/index-helpers.ivm.bundle.js
  packages/server/src/jsRunner/bundles/index-helpers.ts
  packages/server/src/jsRunner/bundles/index.ts
  packages/server/src/jsRunner/index.ts
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
  packages/server/src/jsRunner/vm/index.ts
  packages/server/src/threads/definitions.ts
  packages/server/src/threads/query.ts
  packages/server/src/utilities/fileSystem/filesystem.ts
  packages/server/src/utilities/scriptRunner.ts
  packages/string-templates/package.json
  packages/string-templates/src/errors.js
  packages/string-templates/src/helpers/javascript.js
  packages/string-templates/src/helpers/list.js
  packages/string-templates/src/index.cjs
  packages/string-templates/src/index.js
  packages/string-templates/src/index.mjs
  packages/string-templates/test/manifest.spec.js
  packages/string-templates/test/utils.js
  packages/types/src/sdk/index.ts
  packages/types/src/sdk/vm.ts
  packages/worker/Dockerfile
  packages/worker/nodemon.json
  packages/worker/package.json
  scripts/build.js
  yarn.lock
Labels: feature-branch

#12996 Make import/export fs calls as async as possible.
  packages/server/src/sdk/app/backups/exports.ts
  packages/server/src/sdk/app/backups/imports.ts
Labels: firestorm

#12998 Trace scriptRunner
  packages/server/src/utilities/scriptRunner.ts
Labels: feature-branch

#12994 Remove vm2 from stringtemplates
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
  packages/string-templates/package.json
  packages/string-templates/src/helpers/javascript.js
  packages/string-templates/src/index.cjs
  packages/string-templates/test/basic.spec.js
  packages/string-templates/test/escapes.spec.js
  packages/string-templates/test/hbsToJs.spec.js
  packages/string-templates/test/helpers.spec.js
  packages/string-templates/test/javascript.spec.js
  packages/string-templates/test/manifest.spec.js
  packages/string-templates/test/renderApp.spec.js
  packages/string-templates/test/utils.js
  yarn.lock
Labels: firestorm, feature-branch

#13005 Frontend + Backend CRON validation
  packages/builder/src/components/automation/SetupPanel/CronBuilder.svelte
  packages/builder/src/components/deploy/AppActions.svelte
  packages/server/src/automations/utils.ts
  packages/shared-core/package.json
  packages/shared-core/src/constants/index.ts
  packages/shared-core/src/helpers/cron.ts
  packages/shared-core/src/helpers/index.ts
  packages/shared-core/src/tests/cron.test.ts
  yarn.lock
Labels: firestorm

#13030 Enable threading in development for queries and automations
  packages/server/scripts/dev/manage.js
  packages/server/src/environment.ts
Labels: firestorm

#13009 Remove 'got' from resolutions
  package.json
  yarn.lock
Labels: bug

#12764 Allow Collapsing Selected Components, Add Hotkeys for Collapsing Components
  package.json
  packages/builder/src/builderStore/store/frontend.js
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/ComponentDropdownMenu.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/ComponentKeyHandler.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/ComponentTree.svelte
  packages/builder/src/stores/portal/componentTreeNodesStore.js
  packages/frontend-core/src/stores/index.js
  packages/frontend-core/src/stores/sessionStorage.js
Labels: feature-branch

#13043 Fix updating users via cross-service comms (public API)
  packages/server/src/utilities/workerRequests.ts
Labels: firestorm

#13051 Quick fix for builder store initialise on app creation
  packages/builder/src/stores/builder/index.js
Labels: firestorm

#13049 Type workerRequests.ts
  packages/backend-core/src/logging/correlation/correlation.ts
  packages/server/src/api/controllers/dev.ts
  packages/server/src/utilities/workerRequests.ts
Labels: firestorm

#13048 Fix updating users via cross-service comms (public API)
  packages/backend-core/src/logging/correlation/correlation.ts
  packages/server/src/api/controllers/dev.ts
  packages/server/src/utilities/workerRequests.ts
  packages/shared-core/src/constants/api.ts
Labels: firestorm

#13053 Remove CouchDB pull policy and update Budi CLI to handle couchdb service
  hosting/docker-compose.yaml
  packages/cli/src/hosting/update.ts
Labels: firestorm

#13056 Fix invalid version crashes server startup
  packages/backend-core/src/installation.ts
Labels: firestorm

#13027 Enable non-strict js
  packages/server/package.json
  packages/server/src/jsRunner/bundles/bson.ivm.bundle.js
  packages/server/src/jsRunner/bundles/bsonPackage.ts
  packages/server/src/jsRunner/bundles/index-helpers.ivm.bundle.js
  packages/server/src/jsRunner/bundles/index-helpers.ts
  packages/server/src/jsRunner/bundles/index.ts
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
  packages/server/src/jsRunner/vm/isolated-vm.ts
  scripts/build.js
Labels: feature-branch

#13029 Create isolated-vm toggle
  packages/server/package.json
  packages/server/src/environment.ts
  packages/server/src/jsRunner/bundles/bson.ivm.bundle.js
  packages/server/src/jsRunner/bundles/bsonPackage.ts
  packages/server/src/jsRunner/bundles/index-helpers.ivm.bundle.js
  packages/server/src/jsRunner/bundles/index-helpers.ts
  packages/server/src/jsRunner/bundles/index.ts
  packages/server/src/jsRunner/index.ts
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
  packages/server/src/jsRunner/vm/isolated-vm.ts
  packages/server/src/threads/query.ts
  scripts/build.js
Labels: do not merge, feature-branch

#13026 Update CouchDB image to bookworm and couchdb 3.3.3.
  hosting/couchdb/Dockerfile
  hosting/couchdb/clouseau/clouseau.ini
  hosting/couchdb/couch/10-docker-default.ini
  hosting/couchdb/couch/vm.args
  hosting/couchdb/docker-entrypoint.sh
  hosting/couchdb/runner.sh
  hosting/single/Dockerfile
  hosting/single/runner.sh
  packages/server/src/app.ts
  scripts/install-node.sh
Labels: firestorm

#13080 Ensure a backup is complete before attempting to import it.
  packages/server/src/api/routes/tests/backup.spec.ts
  packages/server/src/tests/utilities/api/backup.ts
Labels: firestorm

#13085 Disable string-templates JS runner if not set in backend-services
  packages/string-templates/src/helpers/javascript.js
  packages/string-templates/src/index.js
  packages/string-templates/src/utilities.js
  packages/string-templates/test/vm.spec.js
Labels: firestorm

#13121 Upping query timeout slightly
  packages/server/src/environment.ts
Labels: firestorm

#13112 Remove Airtable from data source ui
  packages/server/src/api/controllers/integration.ts
Labels: bb-datasource

#13127 [Added] Specific Redis DB to handle events from BPM processes
  packages/backend-core/src/redis/utils.ts
Labels: enhancement

#12898 App Preview Skeleton
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPreview.svelte
  packages/builder/src/pages/builder/portal/apps/[appId]/index.svelte
  packages/client/src/components/ClientApp.svelte
  packages/client/src/components/FreeFooter.svelte
  packages/frontend-core/src/components/ClientAppSkeleton.svelte
  packages/frontend-core/src/components/index.js
  packages/frontend-core/src/themes/midnight.css
  packages/frontend-core/src/themes/nord.css
  packages/server/package.json
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/controllers/static/templates/BudibaseApp.svelte
  packages/server/src/api/controllers/static/templates/app.hbs
  packages/server/src/api/routes/static.ts
  scripts/build.js
Labels: feature-branch

#13166 Updating datasource controller typing
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/server/src/api/controllers/datasource.ts
  packages/server/src/api/controllers/integration.ts
  packages/server/src/db/defaultData/datasource_bb_default.ts
  packages/server/src/db/utils.ts
  packages/server/src/integrations/index.ts
  packages/server/src/sdk/app/applications/import.ts
  packages/server/src/sdk/app/datasources/datasources.ts
  packages/types/src/api/web/app/datasource.ts
  packages/types/src/documents/app/datasource.ts
  packages/types/src/documents/pouch.ts
  packages/types/src/sdk/datasources.ts
  packages/types/src/sdk/db.ts
Labels: firestorm
