Repository Budibase/budibase, pull requests merged in 2024-10, with the labels that each got.

#14660 View security allow filters specified on view to use any
  .tool-versions
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/users/utils.ts
Labels: firestorm, size/m

#14676 Fix the binding drawer for default values.
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
Labels: firestorm, size/s

#14680 Refresh data when adding columns
  packages/builder/src/components/backend/DataTable/modals/grid/GridCreateColumnModal.svelte
Labels: size/xs

#14663 Add the ability to look up context by ID in automation thread
  packages/server/src/automations/tests/scenarios/branching.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/definitions/automations.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/m

#14678 Implement `GROUP BY` for calculation views.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/utils.ts
Labels: firestorm, size/m

#14679 Test all aggregation types.
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
Labels: firestorm, size/s

#14688 Update yarn.lock
  yarn.lock
Labels: firestorm, size/xs

#14685 Symbolise the special __bb_total count field name.
  packages/backend-core/src/sql/index.ts
  packages/backend-core/src/sql/sql.ts
  packages/server/src/sdk/app/rows/utils.ts
Labels: firestorm, size/s

#14689 Fix browser crash under certain circumstances with forms
  packages/client/src/components/app/forms/Form.svelte
Labels: size/xs

#14691 Default values for options and array types (backend)
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/shared-core/src/table.ts
  packages/types/src/documents/app/table/schema.ts
Labels: size/s

#14690 Adapt the payloads for a change in the feature branches deployment pipeline
  .github/workflows/deploy-featurebranch.yml
Labels: size/xs

#14681 Make sure calculation views are created and returned correctly from the API.
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/m

#14687 Search tests from views
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/tests/utilities/api/row.ts
  packages/types/src/documents/app/view.ts
Labels: firestorm, size/xl

#14635 Default values for options and array types (frontend)
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/frontend-core/src/components/grid/stores/datasource.js
Labels: size/m

#14694 View changes - merge to V3 UI branch
  packages/builder/src/stores/builder/viewsV2.js
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.js
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/utils.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/utils.ts
  packages/types/src/api/web/searchFilter.ts
  packages/types/src/documents/app/view.ts
Labels: firestorm, size/m

#14673 Backport V3 backend view change
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/utils.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/utils.ts
  packages/types/src/api/web/searchFilter.ts
  packages/types/src/documents/app/view.ts
  packages/types/src/sdk/search.ts
Labels: do not merge, firestorm, size/m

#14696 Feature branch deployment job expects boolean as payload
  .github/workflows/deploy-featurebranch.yml
Labels: size/xs

#14692 More view calculation tests, and COUNT(DISTINCT ...) implementation.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/server/src/sdk/app/views/index.ts
  packages/types/src/documents/app/view.ts
  packages/types/src/sdk/row.ts
Labels: firestorm, size/l

#14693 Pull the error object out of isolated-vm when a user script throws an error.
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/EvaluationSidePanel.svelte
  packages/server/src/api/controllers/script.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/jsRunner/index.ts
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
  packages/server/src/jsRunner/vm/isolated-vm.ts
  packages/server/src/utilities/rowProcessor/utils.ts
  packages/string-templates/src/errors.ts
  packages/string-templates/src/helpers/javascript.ts
  packages/string-templates/src/index.ts
Labels: firestorm, size/m

#14705 Make the new throwing behaviour of `processStringSync` opt-in.
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
  packages/server/src/utilities/rowProcessor/utils.ts
  packages/string-templates/src/helpers/javascript.ts
  packages/string-templates/src/index.ts
  packages/string-templates/src/types.ts
Labels: firestorm, size/s

#14703 persist app sort method selection by saving it against the user
  packages/builder/src/pages/builder/portal/apps/index.svelte
  packages/builder/src/stores/portal/apps.js
  packages/builder/src/stores/portal/index.js
  packages/types/src/api/web/auth.ts
  packages/types/src/documents/global/user.ts
  packages/worker/src/api/routes/validation/users.ts
Labels: size/s

#14707 Row action/set table permission
  packages/server/src/api/controllers/rowAction/crud.ts
  packages/server/src/api/routes/rowAction.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/server/src/tests/utilities/api/rowAction.ts
  packages/types/src/api/web/app/rowAction.ts
  packages/types/src/documents/app/rowAction.ts
Labels: firestorm, size/m

#14706 Run rowAction from table only if allowed
  packages/builder/src/components/backend/DataTable/buttons/grid/GridRowActionsButton.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/index.svelte
  packages/builder/src/stores/builder/rowActions.js
Labels: firestorm, size/s

#14702 Validate that you cannot create a calculation view with more than 5 calculation fields.
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/s

#14724 Fix enterprise vulns
  charts/budibase/templates/app-service-deployment.yaml
  packages/server/src/environment.ts
  packages/server/src/sdk/app/rows/tests/utils.spec.ts
  packages/server/src/sdk/app/rows/utils.ts
Labels: size/s

#14704 Validate that there are no duplicate calculations in calculation views.
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/m

#14723 Mark calculation views explicitly instead of figuring it out implicitly.
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/external.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/sdk/app/views/internal.ts
  packages/shared-core/src/helpers/views.ts
  packages/types/src/documents/app/view.ts
Labels: firestorm, size/m

#14732 Remove unused properties
  packages/backend-core/src/middleware/passport/sso/sso.ts
  packages/backend-core/tests/core/utilities/structures/accounts.ts
  packages/backend-core/tests/core/utilities/structures/users.ts
  packages/types/src/api/account/accounts.ts
  packages/types/src/documents/account/account.ts
  packages/types/src/documents/global/user.ts
Labels: size/s

#14725 Test helper for setting feature flags.
  packages/backend-core/src/features/features.ts
  packages/backend-core/src/features/index.ts
  packages/backend-core/src/features/tests/utils.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/templates.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/appMigrations/migrations/tests/20240604153647_initial_sqs.spec.ts
  packages/server/src/sdk/app/rows/search/tests/search.spec.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
  packages/worker/src/api/routes/global/tests/auditLogs.spec.ts
Labels: firestorm, size/l

#14738 Allow empty queries when searching tables
  packages/frontend-core/src/api/tables.js
Labels: size/xs

#14741 Allow conditional search for users
  packages/backend-core/src/users/users.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/utils.ts
  packages/worker/src/api/routes/global/tests/users.spec.ts
Labels: firestorm, size/s

#14695 Handle internal relationships referencing rows that don't exist
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/server/src/db/linkedRows/LinkController.ts
  packages/types/src/sdk/db.ts
Labels: firestorm, size/s

#14745 Fix exporting internal rows
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/sdk/app/rows/search/internal/internal.ts
  packages/server/src/tests/utilities/api/row.ts
Labels: firestorm, size/s

#14699 Postgres - newlines between JSON aggregations
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/integrations/postgres.ts
Labels: firestorm, size/s

#14743 Move table creation to sdk
  packages/server/src/api/controllers/table/external.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/controllers/table/internal.ts
  packages/server/src/api/controllers/table/tests/utils.spec.ts
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/sdk/app/tables/create.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/server/src/sdk/app/tables/index.ts
  packages/server/src/sdk/app/tables/internal/index.ts
Labels: firestorm, size/m

#14733 Ensure we only allow grouping by simple fields.
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
  packages/types/src/documents/app/row.ts
Labels: firestorm, size/s

#14734 Add a test to make sure 'shadowing' a field works as expected in calculation views.
  packages/server/src/api/routes/tests/viewV2.spec.ts
Labels: firestorm, size/s

#14735 Make sure calculation views cannot be used to write or modify rows.
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/external.ts
  packages/server/src/sdk/app/rows/internal.ts
Labels: firestorm, size/s

#14744 Still fetch flags when the user is not logged in.
  packages/backend-core/src/context/mainContext.ts
  packages/backend-core/src/context/types.ts
  packages/backend-core/src/features/features.ts
  packages/backend-core/src/features/tests/features.spec.ts
  packages/backend-core/src/middleware/index.ts
  packages/backend-core/src/middleware/ip.ts
  packages/server/src/koa.ts
  packages/worker/src/index.ts
Labels: firestorm, feature-branch, size/m

#14709 Make new tables require ADMIN permissions to read and write.
  packages/backend-core/src/security/permissions.ts
  packages/builder/src/components/backend/DataTable/modals/ManageAccessModal.svelte
  packages/server/src/api/controllers/permission.ts
  packages/server/src/api/routes/tests/permissions.spec.ts
  packages/server/src/migrations/tests/index.spec.ts
  packages/server/src/sdk/app/permissions/index.ts
  packages/server/src/sdk/app/tables/create.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/tests/utilities/api/permission.ts
  packages/server/src/utilities/security.ts
  packages/types/src/api/web/app/permission.ts
  packages/types/src/documents/document.ts
Labels: firestorm, feature-branch, size/m

#14749 Fix SQL removing related row from many side
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/s

#14753 Only check visible fields when checking group by view calculations.
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/shared-core/src/helpers/views.ts
Labels: firestorm, size/s

#14754 Feature flag default roles to admin
  packages/backend-core/src/features/features.ts
  packages/server/src/sdk/app/tables/create.ts
  packages/server/src/sdk/app/views/index.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/s

#14750 Test calculation view searching.
  packages/server/src/api/routes/tests/viewV2.spec.ts
Labels: firestorm, size/m

#14756 Fix table updates wiping out view calculation fields.
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/m

#14748 Prevent deleting rows through a calculation view.
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
Labels: firestorm, size/s

#14758 Properly clean up row actions on table deletion.
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/server/src/api/controllers/rowAction/crud.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/sdk/app/automations/utils.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/server/src/tests/utilities/api/automation.ts
  packages/types/src/sdk/db.ts
Labels: firestorm, size/m

#14762 Fix for an issue found with custom role naming
  packages/backend-core/src/security/roles.ts
  packages/server/src/api/routes/tests/role.spec.js
Labels: firestorm, size/s

#14764 UI tweak for days remaining banner of free trial
  packages/builder/src/components/portal/licensing/EnterpriseBasicTrialBanner.svelte
Labels: size/s

#14759 View joins - allow related required columns' visibility to be changed
  packages/frontend-core/src/components/grid/controls/ColumnsSettingContent.svelte
  packages/frontend-core/src/components/grid/lib/utils.js
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/sdk/app/views/tests/views.spec.ts
  packages/types/src/sdk/view.ts
Labels: firestorm, size/s

#14761 Remove related fields popover
  packages/frontend-core/src/components/grid/cells/RelationshipCell.svelte
Labels: firestorm, size/s

#14773 Extend available labels for feature branch deployments
  .github/workflows/deploy-featurebranch.yml
Labels: size/s

#14774 Fix all or property
  packages/shared-core/src/utils.ts
Labels: firestorm, size/xs

#14763 Allow sorting by calculation fields.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
Labels: firestorm, size/m

#14772 Allow BB_REFERNCE_SINGLE to have default values.
  packages/server/src/api/routes/tests/row.spec.ts
  packages/shared-core/src/table.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm, size/s

#14775 Fix searching by bindings when those bindings have been stored in the `view.query` field.
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/utils.ts
Labels: firestorm, size/m

#14779 Fixing issue with base permissions of tables
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/sdk/app/permissions/index.ts
  packages/server/src/utilities/security.ts
Labels: firestorm, size/s

#14787 Changes to support processing bindings on both sides of branch condition evaluation
  packages/server/src/automations/tests/scenarios/branching.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/m

#14768 Add on click events for grid layout containers
  packages/client/src/components/app/container/GridContainer.svelte
Labels: size/xs

#14789 Support default values on multi-user columns.
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/shared-core/src/table.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm, size/s

#14792 Prevent view queryUI transforms mutating state
  packages/builder/src/stores/builder/viewsV2.js
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.js
Labels: size/s

#14777 Add default value toggle for both single and multi user columns
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
Labels: size/s

#14791 Fixing inconsistent column schemas
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/_components/panels/Tables/CreateExternalTableModal.svelte
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/sdk/app/tables/getters.ts
Labels: firestorm, size/s

#14790 Fix view join parser for non-array values any "many" types
  packages/frontend-core/src/utils/relatedColumns.js
Labels: size/s

#14770 View joins with any and all not working correctly
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
Labels: firestorm, size/m

#13999 Release SQS for self-host users (single image, docker compose, Kubernetes)
  charts/budibase/templates/app-service-deployment.yaml
  charts/budibase/templates/automation-worker-service-deployment.yaml
  charts/budibase/templates/worker-service-deployment.yaml
  charts/budibase/values.yaml
  hosting/docker-compose.yaml
  packages/backend-core/src/features/features.ts
  packages/backend-core/src/features/tests/features.spec.ts
  packages/frontend-core/src/components/Updating.svelte
Labels: firestorm, size/s

#14788 Move conditionals to env section
  .github/workflows/deploy-featurebranch.yml
Labels: size/s

#14805 Fix filter drawer visibility in component popovers
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterEditor.svelte
Labels: size/xs

#14798 Fix multiple relationships same table
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/sdk/app/rows/index.ts
  packages/server/src/sdk/app/rows/search/filters.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
Labels: firestorm, size/m

#14795 Fix negated join filters on relationships
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
Labels: size/m

#14804 Don't extend dataprovider queries when no extensions are in use
  packages/client/src/components/app/DataProvider.svelte
Labels: size/xs

#14813 Hide power role for v3 apps
  packages/backend-core/src/environment.ts
  packages/backend-core/src/security/roles.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/sdk/app/applications/index.ts
  packages/server/src/sdk/app/applications/metadata.ts
  packages/types/src/documents/app/app.ts
  packages/worker/src/api/routes/global/tests/roles.spec.ts
Labels: firestorm, size/m

#14821 Display numbers using locale format in tables
  packages/frontend-core/src/components/grid/cells/NumberCell.svelte
  packages/frontend-core/src/components/grid/cells/TextCell.svelte
Labels: size/s

#14816 Multi-inheritance RBAC (backend)
  packages/backend-core/src/security/roles.ts
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/routes/tests/permissions.spec.ts
  packages/server/src/api/routes/tests/role.spec.js
  packages/server/src/api/routes/tests/role.spec.ts
  packages/server/src/api/routes/tests/screen.spec.js
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/middleware/currentapp.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/role.ts
  packages/server/src/tests/utilities/api/screen.ts
  packages/server/src/tests/utilities/structures.ts
  packages/shared-core/src/helpers/index.ts
  packages/shared-core/src/helpers/roles.ts
  packages/shared-core/src/helpers/tests/roles.spec.ts
  packages/types/src/api/web/role.ts
  packages/types/src/documents/app/role.ts
  packages/types/src/sdk/events/role.ts
Labels: firestorm, size/xl

#14822 Allow passing test to row action test
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/constants/backend/automations.js
Labels: size/xs

#14826 Release v3 to QA
  .github/workflows/budibase_ci.yml
Labels: firestorm, size/xs

#14827 Release v3 to QA
  .github/workflows/budibase_ci.yml
  .github/workflows/deploy-qa.yml
Labels: firestorm, size/xs

#14829 Backporting types from v3 to support updating pro submodule.
  packages/backend-core/src/sql/sqlTable.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/server/src/tests/utilities/structures.ts
  packages/shared-core/src/table.ts
  packages/types/src/documents/app/row.ts
  packages/types/src/documents/app/table/constants.ts
  packages/types/src/documents/app/table/schema.ts
  packages/types/src/sdk/ai.ts
  packages/types/src/sdk/index.ts
Labels: firestorm, size/m

#14837 deprecates Section component
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/src/components/app/deprecated/Section.svelte
  packages/client/src/components/app/forms/FieldGroup.svelte
  packages/client/src/components/app/index.js
Labels: size/xs

#14842 Navigate to automation on creation
  packages/builder/src/components/automation/AutomationPanel/CreateAutomationModal.svelte
Labels: firestorm, size/xs

#14839 Default user columns to current user for templates
  packages/builder/src/components/start/CreateAppModal.svelte
  packages/server/scripts/load/utils.js
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/tests/utilities/api/application.ts
  packages/server/src/utilities/index.ts
  packages/types/src/api/web/application.ts
Labels: firestorm, size/m

#14844 Preview role - multi-inheritance fixes
  packages/backend-core/src/security/roles.ts
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/routes/tests/role.spec.ts
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/middleware/currentapp.ts
  packages/server/src/tests/utilities/structures.ts
Labels: firestorm, size/m

#14845 Allow serving old apps on local dev
  packages/backend-core/src/environment.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/constants/index.ts
  packages/server/src/utilities/fileSystem/app.ts
  packages/server/src/utilities/fileSystem/clientLibrary.ts
Labels: firestorm, size/s

#14577 New RBAC UI
  packages/backend-core/src/security/roles.ts
  packages/bbui/src/InlineAlert/InlineAlert.svelte
  packages/bbui/src/List/ListItem.svelte
  packages/bbui/src/index.js
  packages/builder/package.json
  packages/builder/src/components/backend/DataTable/buttons/EditRolesButton.svelte
  packages/builder/src/components/backend/DataTable/buttons/ManageAccessButton.svelte
  packages/builder/src/components/backend/DataTable/buttons/grid/GridAutomationsButton.svelte
  packages/builder/src/components/backend/DataTable/buttons/grid/GridGenerateButton.svelte
  packages/builder/src/components/backend/DataTable/buttons/grid/GridScreensButton.svelte
  packages/builder/src/components/backend/DataTable/modals/CreateEditUser.svelte
  packages/builder/src/components/backend/DataTable/modals/EditRoles.svelte
  packages/builder/src/components/backend/DataTable/modals/ManageAccessModal.svelte
  packages/builder/src/components/backend/DatasourceNavigator/DatasourceNavigator.svelte
  packages/builder/src/components/backend/RoleEditor/BracketEdge.svelte
  packages/builder/src/components/backend/RoleEditor/Controls.svelte
  packages/builder/src/components/backend/RoleEditor/EmptyStateNode.svelte
  packages/builder/src/components/backend/RoleEditor/RoleEdge.svelte
  packages/builder/src/components/backend/RoleEditor/RoleEditor.svelte
  packages/builder/src/components/backend/RoleEditor/RoleFlow.svelte
  packages/builder/src/components/backend/RoleEditor/RoleNode.svelte
  packages/builder/src/components/backend/RoleEditor/constants.js
  packages/builder/src/components/backend/RoleEditor/utils.js
  packages/builder/src/components/common/RoleIcon.svelte
  packages/builder/src/components/common/RoleSelect.svelte
  packages/builder/src/components/design/settings/controls/RoleSelect.svelte
  packages/builder/src/components/integration/AccessLevelSelect.svelte
  packages/builder/src/components/integration/RestQueryViewer.svelte
  packages/builder/src/dataBinding.js
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/data/roles.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/[viewId]/index.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/InfoDisplay.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/RoleIndicator.svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/GroupAppsTableRenderer.svelte
  packages/builder/src/pages/builder/portal/users/users/_components/AppRoleTableRenderer.svelte
  packages/builder/src/pages/builder/portal/users/users/_components/RolesTagsTableRenderer.svelte
  packages/builder/src/pages/builder/portal/users/users/_components/TagsTableRenderer.svelte
  packages/builder/src/pages/builder/portal/users/users/_components/UpdateRolesModal.svelte
  packages/builder/src/stores/builder/roles.js
  packages/builder/src/stores/builder/websocket.js
  packages/client/src/components/devtools/DevToolsHeader.svelte
  packages/frontend-core/src/components/grid/cells/DataCell.svelte
  packages/frontend-core/src/components/grid/cells/RoleCell.svelte
  packages/frontend-core/src/components/grid/lib/renderers.js
  packages/frontend-core/src/utils/roles.js
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/routes/tests/role.spec.ts
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/middleware/currentapp.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/websockets/builder.ts
  packages/shared-core/src/constants/index.ts
  yarn.lock
Labels: size/xl, feature-branch-enterprise

#14849 Row action name cleanup
  packages/builder/src/components/automation/AutomationPanel/AutomationNavItem.svelte
  packages/builder/src/components/automation/AutomationPanel/UpdateRowActionModal.svelte
  packages/server/src/api/controllers/rowAction/crud.ts
  packages/server/src/api/routes/rowAction.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/sdk/app/automations/crud.ts
  packages/server/src/sdk/app/automations/tests/index.spec.ts
  packages/server/src/sdk/app/automations/utils.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/server/src/tests/utilities/api/rowAction.ts
  packages/types/src/api/web/app/rowAction.ts
  packages/types/src/documents/app/rowAction.ts
Labels: firestorm, size/m

#14818 Make `queryUI` on `ViewV2` something you can write on its own, and `query` gets filled in for you
  packages/builder/src/components/backend/DataTable/modals/ExportModal.test.js
  packages/builder/src/stores/builder/viewsV2.js
  packages/frontend-core/src/components/CoreFilterBuilder.svelte
  packages/frontend-core/src/components/grid/stores/filter.js
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/sdk/app/views/external.ts
  packages/server/src/sdk/app/views/internal.ts
  packages/server/src/sdk/app/views/utils.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/utils.ts
  packages/types/src/api/web/searchFilter.ts
  packages/types/src/documents/app/view.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, feature-branch, size/xl

#14853 Role validation - allow permissionId to be optional
  packages/backend-core/src/security/permissions.ts
  packages/backend-core/src/security/roles.ts
  packages/backend-core/src/security/tests/permissions.spec.ts
  packages/server/src/api/controllers/role.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/tests/permissions.spec.ts
  packages/server/src/api/routes/tests/role.spec.ts
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/tests/utilities/structures.ts
  packages/shared-core/src/helpers/tests/roles.spec.ts
  packages/types/src/api/web/role.ts
  packages/types/src/documents/app/role.ts
  packages/types/src/sdk/permissions.ts
  packages/worker/src/api/routes/global/tests/roles.spec.ts
Labels: firestorm, size/m

#14852 Make sure processSearchFilters handles an undefined input.
  packages/shared-core/src/filters.ts
  packages/shared-core/src/utils.ts
Labels: firestorm, size/s

#14854 Trigger info data in the frontend
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItem.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationNavItem.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
  packages/builder/src/stores/builder/automations.js
  packages/builder/src/stores/builder/index.js
  packages/frontend-core/src/api/automations.js
  packages/server/src/api/controllers/automation.ts
  packages/server/src/sdk/app/automations/utils.ts
  packages/types/src/api/web/automation.ts
Labels: firestorm, size/m

#14857 Frontend updates for storing view filters in `queryUI`
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/backend/DataTable/buttons/TableFilterButton.svelte
  packages/builder/src/components/backend/TableNavigator/modals/CreateTableModal.svelte
  packages/builder/src/stores/builder/components.js
  packages/builder/src/stores/builder/viewsV2.js
  packages/frontend-core/src/components/CoreFilterBuilder.svelte
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.js
Labels: size/s

#14778 Calculation Views UI
  .gitignore
  packages/bbui/src/List/ListItem.svelte
  packages/bbui/src/Modal/ModalContent.svelte
  packages/builder/src/components/backend/DataTable/buttons/grid/GridSortButton.svelte
  packages/builder/src/components/backend/DataTable/buttons/grid/GridViewCalculationButton.svelte
  packages/builder/src/components/common/DetailPopover.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/[viewId]/index.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/_components/CreateViewButton.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/InfoDisplay.svelte
  packages/frontend-core/src/components/CoreFilterBuilder.svelte
  packages/frontend-core/src/components/grid/cells/HeaderCell.svelte
  packages/frontend-core/src/components/grid/lib/renderers.js
  packages/frontend-core/src/components/grid/stores/columns.js
  packages/frontend-core/src/components/grid/stores/config.js
  packages/frontend-core/src/components/grid/stores/datasource.js
  packages/frontend-core/src/components/grid/stores/datasources/nonPlus.js
  packages/frontend-core/src/components/grid/stores/datasources/table.js
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.js
  packages/frontend-core/src/components/grid/stores/sort.js
  packages/frontend-core/src/fetch/DataFetch.js
  packages/frontend-core/src/fetch/TableFetch.js
  packages/frontend-core/src/fetch/ViewV2Fetch.js
  packages/frontend-core/src/utils/schema.js
  packages/frontend-core/src/utils/table.js
Labels: size/l

#14862 Missing old row on automations
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/events/AutomationEmitter.ts
  packages/server/src/events/BudibaseEmitter.ts
  packages/server/src/events/utils.ts
  packages/types/src/core/events.ts
  packages/types/src/core/index.ts
  packages/types/src/sdk/koa.ts
Labels: firestorm, size/m

#14864 Allow overriding the min version where we stop serving the power role
  packages/backend-core/src/environment.ts
  packages/backend-core/src/security/roles.ts
  packages/builder/src/components/backend/DataTable/buttons/ManageAccessButton.svelte
Labels: firestorm, size/s

#14865 Misc V3 improvements
  packages/builder/src/components/backend/DataTable/buttons/ManageAccessButton.svelte
  packages/builder/src/components/deploy/AppActions.svelte
  packages/builder/src/pages/builder/app/[application]/_components/BuilderSidePanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/InfoDisplay.svelte
  packages/builder/src/stores/builder/index.js
  packages/builder/src/stores/builder/published.js
Labels: size/s

#14859 Delete row actions when removing a datasource
  packages/server/src/api/controllers/datasource.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/sdk/app/rowActions/crud.ts
  packages/server/src/sdk/app/rowActions/index.ts
  packages/server/src/sdk/app/rowActions/utils.ts
  packages/server/src/tests/utilities/api/automation.ts
Labels: firestorm, size/m

#14861 Add tests for SQL injection attacks on table/view creation and search.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/l

#14868 Open API - security update
  packages/backend-core/src/context/identity.ts
  packages/backend-core/src/middleware/authenticated.ts
  packages/server/specs/generate.ts
  packages/server/specs/openapi.json
  packages/server/specs/openapi.yaml
  packages/server/specs/parameters.ts
  packages/server/src/api/routes/public/tests/Request.ts
  packages/server/src/api/routes/public/tests/metrics.spec.ts
  packages/server/src/api/routes/public/tests/security.spec.ts
  packages/server/src/api/routes/public/tests/utils.ts
  packages/server/src/api/routes/tests/routing.spec.ts
  packages/server/src/definitions/openapi.ts
  packages/server/src/middleware/currentapp.ts
  packages/server/src/middleware/tests/currentapp.spec.ts
  packages/server/src/middleware/utils.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/types/package.json
  packages/types/src/sdk/koa.ts
Labels: firestorm, size/m

#14858 Remove lightest and dark themes and add core types and utils for themes
  packages/builder/src/components/commandPalette/CommandPalette.svelte
  packages/builder/src/components/integration/QueryEditor.svelte
  packages/builder/src/components/settings/ThemeModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Screen/AppThemeSelect.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPreview.svelte
  packages/builder/src/pages/builder/portal/apps/[appId]/index.svelte
  packages/builder/src/stores/builder/theme.js
  packages/builder/src/stores/portal/theme.js
  packages/client/manifest.json
  packages/client/src/components/ClientApp.svelte
  packages/client/src/stores/theme.js
  packages/frontend-core/src/constants.js
  packages/frontend-core/src/utils/index.js
  packages/frontend-core/src/utils/theme.js
  packages/server/src/api/controllers/application.ts
  packages/server/src/constants/themes.ts
  packages/shared-core/src/constants/index.ts
  packages/shared-core/src/constants/themes.ts
  packages/shared-core/src/index.ts
  packages/shared-core/src/tests/themes.ts
  packages/shared-core/src/themes.ts
  packages/types/src/documents/app/index.ts
  packages/types/src/documents/app/theme.ts
Labels: size/m

#14874 Public API test changes
  packages/server/specs/openapi.json
  packages/server/specs/openapi.yaml
  packages/server/specs/resources/table.ts
  packages/server/src/api/routes/public/tests/Request.ts
  packages/server/src/api/routes/public/tests/security.spec.ts
  packages/server/src/definitions/openapi.ts
Labels: firestorm, size/s

#14876 Use account email instead of budibaseUserId
  packages/backend-core/src/events/identification.ts
Labels: size/s

#14878 Allow bigints in calculations
  packages/backend-core/src/sql/sql.ts
  packages/builder/src/components/backend/DataTable/buttons/grid/GridViewCalculationButton.svelte
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
Labels: firestorm, size/m

#14801 Add settings to automation context.
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/definitions/automations.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/s

#14877 Support multiple relationships same tables
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/m

#14889 Publish automation-branching-ux to QA
  .github/workflows/deploy-qa.yml
Labels: firestorm, size/xs

#14892 Add new bindings to drawer
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/StepNode.svelte
  packages/builder/src/dataBinding.js
  packages/builder/src/stores/builder/automations.js
Labels: firestorm, size/s

#14898 Public role access issue
  packages/backend-core/src/security/roles.ts
Labels: firestorm, size/s

#14896 Fix default values when using multi-option column and supplying empty array.
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
Labels: firestorm, size/s

#14897 Support boolean and bigint fields having default values.
  packages/server/src/api/routes/tests/row.spec.ts
  packages/shared-core/src/table.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm, size/s

#14879 Fix relationship field filter on change
  packages/client/src/components/app/forms/RelationshipField.svelte
Labels: size/xs

#14903 Updating yarn.lock
  yarn.lock
Labels: firestorm, size/xs

#14899 Support view RBAC with forms and cache view definitions
  packages/client/src/components/app/forms/Form.svelte
  packages/client/src/components/app/forms/InnerForm.svelte
  packages/client/src/components/app/forms/validation.js
  packages/client/src/sdk.js
  packages/client/src/utils/schema.js
  packages/frontend-core/src/api/viewsV2.js
Labels: size/s

#14871 Fix new filtering for with queries
  packages/frontend-core/src/fetch/DataFetch.js
Labels: firestorm, size/xs

#14910 Add network-concurrency option to yarn installs
  hosting/single/Dockerfile
  packages/server/Dockerfile
  packages/worker/Dockerfile
Labels: firestorm, size/xs

#14909 Revert yarn.lock to 2.33.4 state
  yarn.lock
Labels: firestorm, size/xs

#14914 Removing yarn caching from docker builds.
  packages/server/Dockerfile
  packages/worker/Dockerfile
Labels: firestorm, size/xs

#14919 Nodemon config update
  packages/server/nodemon.json
Labels: firestorm, size/xs

#14921 Conditions reactivity fix + row actions improvement
  packages/client/src/components/Component.svelte
  packages/client/src/utils/buttonActions.js
Labels: size/s

#14924 Fix view calculations with relationships
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
Labels: firestorm, size/m

#14923 Fix builder serve endpoint error rate
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/tests/static.spec.ts
  packages/server/src/sdk/app/applications/applications.ts
Labels: firestorm, size/s

#14894 Improve users sort
  packages/builder/src/pages/builder/portal/users/users/index.svelte
Labels: size/xs

#14926 Don't throw if no account-holder is found
  packages/worker/src/api/controllers/global/users.ts
Labels: size/s

#14927 Fix wrongly removing valueType=binding
  packages/frontend-core/src/components/CoreFilterBuilder.svelte
  packages/frontend-core/src/components/FilterField.svelte
Labels: firestorm, size/xs

#14928 Allow fields on count calculations.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/server/src/sdk/app/views/index.ts
  packages/types/src/documents/app/view.ts
  packages/types/src/sdk/row.ts
Labels: firestorm, size/m

#14931 Fix handling of the Postgres money field.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/integration-test/postgres.spec.ts
Labels: firestorm, size/s

#14925 Throw an error when attempting to bulkImport a relationship field into an internal table.
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/s

#14929 Allow tables to handle _id values in non DS+ rows
  packages/client/src/components/app/GridBlock.svelte
  packages/frontend-core/src/components/grid/lib/constants.js
  packages/frontend-core/src/components/grid/lib/utils.js
  packages/frontend-core/src/components/grid/stores/rows.js
Labels: size/s

#14930 Allow counting non-numeric fields in calculation views
  packages/builder/src/components/backend/DataTable/buttons/grid/GridViewCalculationButton.svelte
Labels: size/s

#14932 Fix flaky export test.
  packages/server/src/api/controllers/view/exporters.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/utilities/csv.ts
Labels: firestorm, size/s
