Repository Budibase/budibase, pull requests merged in 2024-07, with the labels that each got.

#14031 Added button options text to the prompt user action.
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/PromptUser.svelte
Labels: size/s

#14062 Fixing a date JS test case
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
Labels: firestorm, size/xs

#14059 Fix contains search on multi-user column.
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search.ts
Labels: firestorm, size/s

#14060 Add verify_sso_login flow
  packages/shared-core/src/constants/index.ts
  scripts/deploy-camunda.sh
  yarn.lock
Labels: size/xs

#14038 Initial implementation of solving SQS issue with case insensitivity
  packages/backend-core/src/sql/sql.ts
  packages/backend-core/src/sql/sqlStatements.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/appMigrations/migrations/tests/20240604153647_initial_sqs.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/shared-core/src/filters.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/m

#13828 BUDI-8312 -Bindings Menu shows behind the Add Test Data menu in automations
  packages/bbui/src/Drawer/Drawer.svelte
Labels: stale

#14063 Updating filter fields to use relationship name rather than related table name
  packages/frontend-core/src/utils/searchFields.js
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
Labels: size/s

#14068 Fix NX hiding test failures
  .github/workflows/budibase_ci.yml
  lerna.json
  nx.json
  package.json
  scripts/run-affected.js
  yarn.lock
Labels: firestorm, size/s

#14070 Update CouchDB Dockerfile to be SQS capable
  hosting/couchdb/Dockerfile
  hosting/couchdb/Dockerfile.v2
  hosting/couchdb/runner.sh
  hosting/couchdb/runner.v2.sh
  package.json
Labels: firestorm, size/m

#14073 Make the SQS environment check work off the SQS_SEARCH_ENABLE env var.
  packages/worker/src/api/controllers/system/environment.ts
Labels: firestorm, size/xs

#14072 Handle view visibility schema
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/s

#14076 App migration queue created consistently
  packages/server/src/appMigrations/index.ts
  packages/server/src/appMigrations/queue.ts
Labels: firestorm, size/s

#14078 Set `DISABLE_V8_COMPILE_CACHE` on build
  package.json
Labels: firestorm, size/xs

#14082 Update MongoDB.
  packages/server/package.json
  yarn.lock
Labels: firestorm, size/xs

#14083 Fix an issue where null values were causing an error in automation loops
  packages/server/src/automations/loopUtils.ts
  packages/server/src/automations/tests/loop.spec.ts
Labels: firestorm, size/m

#14084 Stripping credentials from Couch URLs + test cases
  packages/backend-core/src/db/couch/connections.ts
  packages/backend-core/src/db/tests/connections.spec.ts
Labels: firestorm, size/s

#14089 Separate SQS migration into another environment variable
  packages/server/src/appMigrations/migrations.ts
  packages/server/src/appMigrations/migrations/20240604153647_initial_sqs.ts
  packages/server/src/appMigrations/migrations/tests/20240604153647_initial_sqs.spec.ts
  packages/server/src/environment.ts
Labels: firestorm, size/m

#14091 Move secrets into backend-core.
  packages/backend-core/src/environment.ts
  packages/server/__mocks__/@sendgrid/mail.ts
  packages/server/src/automations/steps/openai.ts
  packages/server/src/automations/tests/openai.spec.ts
  packages/server/src/environment.ts
  packages/server/src/startup/index.ts
  packages/server/src/startup/tests/startup.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
Labels: firestorm, size/m

#14028 Row Step Automation UX updates and Automation refactoring
  packages/bbui/src/Tooltip/TooltipWrapper.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/FieldSelector.svelte
  packages/builder/src/components/automation/SetupPanel/PropField.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/builder/src/components/automation/SetupPanel/TableSelector.svelte
  packages/builder/src/components/common/bindings/DrawerBindableInput.svelte
  packages/builder/src/components/common/bindings/index.js
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/_components/panels/Authentication/RestAuthenticationModal.svelte
  packages/builder/src/stores/builder/automations.js
  packages/server/src/automations/automationUtils.ts
  packages/server/src/automations/steps/updateRow.ts
  packages/server/src/automations/triggerInfo/app.ts
  packages/server/src/automations/triggerInfo/cron.ts
  packages/server/src/automations/triggerInfo/rowDeleted.ts
  packages/server/src/automations/triggerInfo/rowSaved.ts
  packages/server/src/automations/triggerInfo/rowUpdated.ts
  packages/server/src/automations/triggerInfo/webhook.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/utilities/rowProcessor/map.ts
  packages/server/src/utilities/rowProcessor/tests/inputProcessing.spec.ts
  packages/types/src/documents/app/automation.ts
Labels: feature-branch, size/xl

#14086 Typescript improvements for CouchDB integration
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/server/src/integrations/couchdb.ts
  packages/server/src/integrations/tests/couchdb.spec.ts
Labels: firestorm, size/s

#14094 Support non-ascii column in SQS.
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
Labels: firestorm, size/s

#14098 Ellipsis on long emails
  packages/builder/src/pages/builder/portal/users/users/_components/EmailTableRenderer.svelte
Labels: firestorm, size/s

#14100 Fix gen-collection-info script, was invalid TS
  packages/string-templates/scripts/gen-collection-info.ts
Labels: firestorm, size/s

#14109 Fix for builder relationship picker
  packages/frontend-core/src/components/FilterBuilder.svelte
Labels: size/xs

#14097 Squash the oldRow prop in the external row controller
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/automations/triggers.ts
Labels: size/s

#14102 Handlebar helper lorem
  packages/server/src/jsRunner/bundles/index-helpers.ivm.bundle.js
  packages/string-templates/package.json
  packages/string-templates/src/manifest.json
  yarn.lock
Labels: size/s

#14101 Added new Generate automation button in the data section
  packages/builder/src/components/backend/DataTable/TableDataTable.svelte
  packages/builder/src/components/backend/DataTable/buttons/grid/GridCreateAutomationButton.svelte
Labels: size/m

#14104 Solving some invalid time filters
  packages/backend-core/src/db/constants.ts
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/couch/index.ts
  packages/backend-core/src/sql/sql.ts
  packages/backend-core/src/sql/utils.ts
  packages/backend-core/tests/core/utilities/jestUtils.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/internal.ts
  packages/server/src/sdk/app/tables/migration.ts
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/m

#14114 Adding default (sample) tables in SQS indexing
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/constants/index.ts
  packages/server/src/db/defaultData/datasource_bb_default.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/server/src/tests/utilities/api/application.ts
Labels: firestorm, size/s

#14125 Fix Client Modal Component `Ignore clicks outside` Setting
  packages/client/src/components/app/Modal.svelte
Labels: size/xs

#14124 Fix notification message from display the wrong phrasing
  packages/builder/src/stores/builder/automations.js
Labels: size/xs

#14129 Always allow creating views
  packages/builder/src/components/backend/DataTable/buttons/grid/GridCreateViewButton.svelte
Labels: firestorm, size/xs

#14120 CSV export fails for table with composite primary key
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/shared-core/src/filters.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/m

#14128 Fix bug in oneOf search.
  .github/workflows/budibase_ci.yml
  packages/backend-core/src/users/users.ts
  packages/frontend-core/src/components/FilterBuilder.svelte
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/shared-core/src/filters.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/m

#14116 Per-tenant enablement of SQS
  packages/backend-core/src/db/utils.ts
  packages/backend-core/src/environment.ts
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/templates.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/appMigrations/migrations.ts
  packages/server/src/appMigrations/migrations/20240604153647_initial_sqs.ts
  packages/server/src/appMigrations/migrations/tests/20240604153647_initial_sqs.spec.ts
  packages/server/src/environment.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/tests/search.spec.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/sdk/tests/attachments.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/worker/src/api/controllers/system/environment.ts
  packages/worker/src/api/index.ts
  packages/worker/src/environment.ts
Labels: firestorm, size/m

#14131 Fixing issue with multiple relations to same table
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/rows/sqlAlias.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
Labels: firestorm, size/m

#14135 Create a way to enable SQS for all tenants.
  packages/backend-core/src/db/utils.ts
Labels: firestorm, size/xs

#14111 Automation UX fixes
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
Labels: size/s

#14069 Automation grouping
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
Labels: size/s

#14137 Fix for default CouchDB SQL URL
  packages/backend-core/src/db/couch/connections.ts
  packages/backend-core/src/environment.ts
  packages/server/src/environment.ts
  packages/worker/src/api/controllers/system/environment.ts
Labels: firestorm, size/s

#14141 Re-enable SQS (when flag set) in development/self host
  packages/backend-core/src/db/utils.ts
Labels: firestorm, size/xs

#14140 When `return all table rows` is selected the is in filter returns nothing instead of all rows
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/constants/index.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/shared-core/src/filters.ts
Labels: firestorm, size/s

#14142 Fix a flake in the redis.spec.ts file.
  packages/backend-core/src/redis/tests/redis.spec.ts
Labels: firestorm, size/xs

#14143 Fix fun flake in MySQL / MariaDB.
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/xs

#14144 Re-sync SQS definitions consistently
  packages/server/src/sdk/app/rows/search/sqs.ts
Labels: firestorm, size/s

#14150 Fix a very rare flake in row.spec.ts.
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/s

#14133 Return 401 instead of 403
  packages/server/src/api/routes/tests/permissions.spec.ts
  packages/server/src/api/routes/tests/utilities/TestFunctions.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/middleware/authorized.ts
  packages/server/src/middleware/tests/authorized.spec.ts
Labels: firestorm, size/s

#14151 Unify duplicated newid utils
  packages/server/src/api/controllers/deploy/Deployment.ts
  packages/server/src/automations/utils.ts
  packages/server/src/db/inMemoryView.ts
  packages/server/src/db/newid.ts
  packages/server/src/db/utils.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
Labels: firestorm, size/s

#14157 Default table - in-memory/on-disk representation duplicates
  packages/server/src/sdk/app/tables/internal/sqs.ts
Labels: firestorm, size/xs

#14174 Fix for App title text alignment not persisting
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/index.svelte
Labels: size/xs

#14162 Less/Greater than or equal to search test cases
  packages/server/src/api/routes/tests/search.spec.ts
Labels: firestorm, size/s

#14037 Script to verify ethereal
  scripts/verifyEtherealSmtp.js
Labels: size/s

#14152 Row action CRUD endpoints
  packages/backend-core/src/middleware/joi-validator.ts
  packages/server/src/api/controllers/rowAction/crud.ts
  packages/server/src/api/controllers/rowAction/index.ts
  packages/server/src/api/controllers/rowAction/run.ts
  packages/server/src/api/routes/index.ts
  packages/server/src/api/routes/rowAction.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/db/utils.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/server/src/sdk/index.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/rowAction.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/app/rowAction.ts
  packages/types/src/documents/app/index.ts
  packages/types/src/documents/app/rowAction.ts
  packages/types/src/documents/document.ts
Labels: firestorm, size/l

#14190 Prevent duplicated names on row actions
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/sdk/app/rowActions.ts
Labels: size/m

#14191 Move automation code away from controller
  packages/server/src/api/controllers/automation.ts
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/utils.ts
  packages/server/src/sdk/app/automations/crud.ts
  packages/server/src/sdk/app/automations/index.ts
  packages/server/src/tests/utilities/structures.ts
Labels: firestorm, size/m

#14123 Automation trigger filtering
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItemHeader.svelte
  packages/builder/src/components/automation/AutomationBuilder/TestDisplay.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterBuilder.svelte
  packages/builder/src/stores/builder/automations.js
  packages/frontend-core/src/components/FilterBuilder.svelte
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/triggerInfo/rowSaved.ts
  packages/server/src/automations/triggerInfo/rowUpdated.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/tests/utilities/structures.ts
  packages/types/src/documents/app/automation.ts
  packages/types/src/sdk/automations/index.ts
Labels: firestorm, feature-branch, size/m

#14196 Fix Bug Preventing Deleting Multiple Apps in a Row
  packages/builder/src/components/deploy/DeleteModal.svelte
Labels: size/xs

#14198 Remove unnecessary save button for automation steps
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/ActionModal.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItem.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
Labels: firestorm, size/s

#14200 Create automation on adding new row action
  packages/server/src/api/controllers/rowAction/crud.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/sdk/app/automations/crud.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/server/src/tests/utilities/api/automation.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/types/src/api/web/app/rowAction.ts
  packages/types/src/documents/app/automation.ts
  packages/types/src/documents/app/rowAction.ts
Labels: firestorm, size/m

#14177 [BUDI-8434] Default value implementation on the backend.
  packages/backend-core/src/sql/utils.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/map.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm, size/m

#14186 [BUDI-8436] Make sure a field cannot both have a default value and be required.
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
Labels: firestorm, size/m

#14023 Multi-cell operations for tables
  packages/bbui/src/ProgressBar/ProgressBar.svelte
  packages/bbui/src/bbui.css
  packages/builder/src/components/design/settings/controls/EditComponentPopover.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/FieldSetting.svelte
  packages/client/src/components/app/GridBlock.svelte
  packages/frontend-core/src/components/grid/cells/DataCell.svelte
  packages/frontend-core/src/components/grid/cells/GridCell.svelte
  packages/frontend-core/src/components/grid/cells/GutterCell.svelte
  packages/frontend-core/src/components/grid/cells/HeaderCell.svelte
  packages/frontend-core/src/components/grid/controls/BulkDeleteHandler.svelte
  packages/frontend-core/src/components/grid/controls/BulkDuplicationHandler.svelte
  packages/frontend-core/src/components/grid/controls/ClipboardHandler.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/frontend-core/src/components/grid/controls/SizeButton.svelte
  packages/frontend-core/src/components/grid/controls/SortButton.svelte
  packages/frontend-core/src/components/grid/layout/ButtonColumn.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/frontend-core/src/components/grid/layout/GridBody.svelte
  packages/frontend-core/src/components/grid/layout/GridRow.svelte
  packages/frontend-core/src/components/grid/layout/GridScrollWrapper.svelte
  packages/frontend-core/src/components/grid/layout/HeaderRow.svelte
  packages/frontend-core/src/components/grid/layout/NewColumnButton.svelte
  packages/frontend-core/src/components/grid/layout/NewRow.svelte
  packages/frontend-core/src/components/grid/layout/StickyColumn.svelte
  packages/frontend-core/src/components/grid/lib/utils.js
  packages/frontend-core/src/components/grid/overlays/KeyboardManager.svelte
  packages/frontend-core/src/components/grid/overlays/MenuOverlay.svelte
  packages/frontend-core/src/components/grid/overlays/ReorderOverlay.svelte
  packages/frontend-core/src/components/grid/overlays/ResizeOverlay.svelte
  packages/frontend-core/src/components/grid/stores/clipboard.js
  packages/frontend-core/src/components/grid/stores/columns.js
  packages/frontend-core/src/components/grid/stores/datasources/nonPlus.js
  packages/frontend-core/src/components/grid/stores/datasources/table.js
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.js
  packages/frontend-core/src/components/grid/stores/index.js
  packages/frontend-core/src/components/grid/stores/menu.js
  packages/frontend-core/src/components/grid/stores/pagination.js
  packages/frontend-core/src/components/grid/stores/reorder.js
  packages/frontend-core/src/components/grid/stores/resize.js
  packages/frontend-core/src/components/grid/stores/rows.js
  packages/frontend-core/src/components/grid/stores/scroll.js
  packages/frontend-core/src/components/grid/stores/ui.js
  packages/frontend-core/src/components/grid/stores/users.js
  packages/frontend-core/src/components/grid/stores/validation.js
  packages/frontend-core/src/components/grid/stores/viewport.js
  packages/frontend-core/src/themes/midnight.css
  packages/frontend-core/src/themes/nord.css
  packages/frontend-core/src/utils/utils.js
Labels: feature-branch, size/xl

#14207 Fix Screen History Issue
  packages/builder/src/stores/builder/screens.js
Labels: size/s

#14195 Fix Automations Breaking When Their Datasource is Deleted
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
Labels: size/s

#14145 DynamicFilter fixes
  packages/builder/src/components/design/Panel.svelte
  packages/builder/src/constants/backend/index.js
  packages/client/src/components/app/dynamic-filter/DynamicFilter.svelte
  packages/frontend-core/src/components/FilterBuilder.svelte
  packages/frontend-core/src/constants.js
Labels: size/s

#14194 Improved handling around invalid relationship column
  packages/frontend-core/src/components/grid/cells/RelationshipCell.svelte
  packages/server/src/db/linkedRows/LinkController.ts
Labels: size/s

#14210 Fix to show Formula column type picker again
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/dataBinding.js
Labels: size/xs

#14185 Conditional table cell and row styles
  packages/bbui/src/ColorPicker/ColorPicker.svelte
  packages/bbui/src/Form/Core/Select.svelte
  packages/bbui/src/bbui.css
  packages/builder/src/components/common/bindings/ClientBindingPanel.svelte
  packages/builder/src/components/common/bindings/DrawerBindableInput.svelte
  packages/builder/src/components/design/settings/componentSettings.js
  packages/builder/src/components/design/settings/controls/DraggableList/DraggableList.svelte
  packages/builder/src/components/design/settings/controls/EditComponentPopover.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/FieldSetting.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/GridColumnConfiguration.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/getColumns.js
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/getColumns.test.js
  packages/builder/src/components/design/settings/controls/TableConditionEditor.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUISection.svelte
  packages/client/manifest.json
  packages/client/src/components/app/GridBlock.svelte
  packages/frontend-core/src/components/grid/cells/DataCell.svelte
  packages/frontend-core/src/components/grid/cells/GridCell.svelte
  packages/frontend-core/src/components/grid/cells/GutterCell.svelte
  packages/frontend-core/src/components/grid/layout/ButtonColumn.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/frontend-core/src/components/grid/layout/GridScrollWrapper.svelte
  packages/frontend-core/src/components/grid/layout/StickyColumn.svelte
  packages/frontend-core/src/components/grid/stores/columns.js
  packages/frontend-core/src/components/grid/stores/conditions.js
  packages/frontend-core/src/components/grid/stores/config.js
  packages/frontend-core/src/components/grid/stores/datasource.js
  packages/frontend-core/src/components/grid/stores/index.js
  packages/frontend-core/src/components/grid/stores/rows.js
  packages/frontend-core/src/components/grid/stores/viewport.js
  packages/frontend-core/src/components/index.js
  packages/frontend-core/src/constants.js
  packages/frontend-core/src/themes/midnight.css
  packages/frontend-core/src/themes/nord.css
Labels: feature-branch, size/l

#14212 Fix for duplicate columns in SQS
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
Labels: firestorm, size/s

#14211 Any type for createMockContext
  packages/backend-core/tests/core/utilities/structures/koa.ts
  scripts/deploy-camunda.sh
Labels: size/xs

#14218 Prevent edits and deletions for row action automations
  packages/builder/src/components/automation/AutomationPanel/AutomationNavItem.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
  packages/builder/src/stores/builder/automations.js
  packages/server/src/api/controllers/automation.ts
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/sdk/app/automations/crud.ts
  packages/server/src/sdk/app/automations/tests/index.spec.ts
  packages/server/src/sdk/app/automations/utils.ts
  packages/server/src/tests/utilities/structures.ts
  packages/shared-core/src/sdk/documents/automations.ts
  packages/shared-core/src/sdk/documents/index.ts
Labels: firestorm, size/m

#14215 Trim data on automation sdk
  packages/server/src/sdk/app/automations/crud.ts
Labels: firestorm, size/s

#14182 Add logic to prevent panel and modals from closing when screen load actions are available
  packages/client/src/components/ClientApp.svelte
Labels: size/s

#14225 Fix for ButtonGroup Bindings.
  packages/builder/src/components/design/settings/controls/DraggableList/DraggableList.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/GridColumnConfiguration.svelte
Labels: size/xs

#14214 Add all HBS helpers to manifest
  packages/string-templates/scripts/gen-collection-info.ts
  packages/string-templates/src/conversion/index.ts
  packages/string-templates/src/helpers/constants.ts
  packages/string-templates/src/helpers/external.ts
  packages/string-templates/src/manifest.json
  packages/string-templates/test/hbsToJs.spec.ts
Labels: firestorm, size/s

#14229 Fix failing test due testcontainer conflicts
  .github/workflows/budibase_ci.yml
  nx.json
  packages/server/src/integrations/tests/utils/mssql.ts
Labels: firestorm, size/s

#14235 Debugging output for startup of Budibase
  packages/server/src/startup/index.ts
Labels: firestorm, size/s

#14227 Polyfill for Buffer in isolated-vm
  packages/server/package.json
  packages/server/src/jsRunner/bundles/bson.ivm.bundle.js
  packages/server/src/jsRunner/bundles/buffer.ivm.bundle.js
  packages/server/src/jsRunner/bundles/buffer.ts
  packages/server/src/jsRunner/bundles/index.ts
  packages/server/src/jsRunner/index.ts
  packages/server/src/jsRunner/tests/jsRunner.spec.ts
  packages/server/src/jsRunner/vm/isolated-vm.ts
  yarn.lock
Labels: firestorm, size/s

#14237 Lock CI images to specific SHAs
  .github/workflows/budibase_ci.yml
  globalSetup.ts
  packages/server/datasource-sha.env
  packages/server/src/integrations/tests/utils/images.ts
  packages/server/src/integrations/tests/utils/index.ts
  packages/server/src/integrations/tests/utils/mariadb.ts
  packages/server/src/integrations/tests/utils/mongodb.ts
  packages/server/src/integrations/tests/utils/mssql.ts
  packages/server/src/integrations/tests/utils/mysql.ts
  packages/server/src/integrations/tests/utils/postgres.ts
Labels: size/s

#14231 Fix issue with trigger filters not saving
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/server/src/automations/triggerInfo/rowSaved.ts
Labels: firestorm, size/s

#14238 Expose row action definition
  packages/server/src/automations/triggerInfo/index.ts
  packages/server/src/automations/triggerInfo/rowAction.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/types/src/documents/app/automation.ts
Labels: firestorm, size/s

#14234 Fix issue with nulls in lucene isEmpty filter
  packages/shared-core/src/filters.ts
Labels: size/xs

#14228 Don't show datasource options for array bindings that lack table IDs
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
Labels: size/xs

#14239 Adding bulkRemove utility for CouchDB
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/backend-core/src/platform/users.ts
  packages/server/src/db/linkedRows/LinkController.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/db/linkedRows/linkUtils.ts
  packages/types/src/sdk/db.ts
Labels: firestorm, size/m

#14219 Row actions automation creation
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItem.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationNavItem.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/stores/builder/automations.js
  packages/builder/src/stores/builder/index.js
  packages/frontend-core/src/api/automations.js
  packages/server/src/api/controllers/automation.ts
  packages/server/src/api/controllers/rowAction/crud.ts
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/api/routes/tests/utilities/TestFunctions.ts
  packages/server/src/automations/triggerInfo/index.ts
  packages/server/src/automations/triggerInfo/rowAction.ts
  packages/server/src/sdk/app/automations/crud.ts
  packages/server/src/sdk/app/automations/tests/index.spec.ts
  packages/server/src/sdk/app/automations/utils.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/server/src/tests/utilities/api/automation.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/structures.ts
  packages/shared-core/src/sdk/documents/automations.ts
  packages/shared-core/src/sdk/documents/index.ts
  packages/types/src/api/web/app/rowAction.ts
  packages/types/src/api/web/automation.ts
  packages/types/src/documents/app/automation.ts
  packages/types/src/documents/app/rowAction.ts
Labels: firestorm, size/l

#14252 Fix importing internal tables
  packages/server/src/api/controllers/table/internal.ts
  packages/server/src/sdk/app/tables/internal/index.ts
  packages/shared-core/src/table.ts
Labels: firestorm, size/s

#14254 Renaming some js objects
  packages/backend-core/tests/core/utilities/jestUtils.ts
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/db/utils.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/internal.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/server/src/sdk/app/views/index.ts
  packages/shared-core/src/constants/rows.ts
  packages/shared-core/src/table.ts
Labels: firestorm, size/s

#14247 Row action run api
  packages/builder/src/pages/builder/app/[application]/settings/automations/index.svelte
  packages/server/src/api/controllers/rowAction/run.ts
  packages/server/src/api/routes/rowAction.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/automations/triggerInfo/rowAction.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/sdk/app/automations/tests/index.spec.ts
  packages/server/src/sdk/app/automations/utils.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/shared-core/src/sdk/documents/automations.ts
  packages/types/src/api/web/app/rowAction.ts
  packages/types/src/documents/app/automation.ts
Labels: firestorm, size/m

#14192 Form Screen Templates Generate Relevant Row Ids, Permission Roles are Automatically Generated
  packages/bbui/src/InlineAlert/InlineAlert.svelte
  packages/bbui/src/StatusLight/StatusLight.svelte
  packages/builder/src/components/backend/DatasourceNavigator/DatasourceNavItem/DeleteConfirmationModal.svelte
  packages/builder/src/components/backend/TableNavigator/TableNavItem/DeleteConfirmationModal.svelte
  packages/builder/src/components/common/RoleIcon.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/DatasourceModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/DatasourceTemplateRow.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/FormTypeModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/ScreenRoleModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/TableOrViewOption.svelte
  packages/builder/src/templates/Screen.js
  packages/builder/src/templates/blankScreen.js
  packages/builder/src/templates/createFromScratchScreen.js
  packages/builder/src/templates/formScreen.js
  packages/builder/src/templates/gridDetailsScreen.js
  packages/builder/src/templates/gridListScreen.js
  packages/builder/src/templates/gridScreen.js
  packages/builder/src/templates/index.js
Labels: size/xl

#14253 Fix/verify sso bug
  packages/backend-core/src/db/views.ts
  packages/backend-core/src/platform/users.ts
  packages/backend-core/src/users/db.ts
  packages/backend-core/src/users/lookup.ts
  packages/backend-core/src/users/utils.ts
  packages/builder/src/components/common/users/PasswordRepeatInput.svelte
  packages/builder/src/pages/builder/auth/reset.svelte
  packages/types/src/documents/platform/users.ts
  packages/worker/src/api/controllers/global/users.ts
  yarn.lock
Labels: size/m

#14265 Fix issue with stepId being undefined when importing app
  packages/shared-core/src/sdk/documents/automations.ts
Labels: firestorm, size/xs

#14268 Bundle pro to final bundles
  package.json
  scripts/bootstrap.sh
  scripts/build.js
  scripts/devDocker.sh
  yarn.lock
Labels: firestorm, feature-branch, size/s

#14257 Fix for searching by row ID (with a limit) when the row has many related rows
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/rows/search/utils.ts
Labels: firestorm, size/m

#14274 Fix to accomodate automations without triggers
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationNavItem.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
Labels: size/s

#14271 Reduce automation store updates and API fetches
  packages/builder/src/stores/builder/automations.js
Labels: size/s

#14279 Disallow adding row action automations
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
  packages/builder/src/components/automation/AutomationPanel/CreateAutomationModal.svelte
  packages/builder/src/components/backend/DataTable/buttons/grid/GridCreateAutomationButton.svelte
  packages/builder/src/stores/builder/automations.js
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/utils.ts
  packages/server/src/sdk/app/automations/crud.ts
  packages/server/src/sdk/app/automations/utils.ts
  packages/types/src/documents/app/automation.ts
Labels: firestorm, size/s

#14282 Prevent test container name conflicts
  packages/server/src/integrations/tests/utils/index.ts
Labels: firestorm, size/xs

#14280 Save autofields on bulksaves
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/couch/tests/DatabaseImpl.spec.ts
Labels: firestorm, size/m

#14281 Improve typings
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/db/defaultData/datasource_bb_default.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/sdk/app/rows/search/tests/search.spec.ts
  packages/types/src/api/web/app/rows.ts
  packages/types/src/api/web/app/table.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm, size/m

#14284 Fix issue selecting the same file multiple times while importing
  packages/builder/src/components/backend/TableNavigator/ExistingTableDataImport.svelte
Labels: firestorm, size/s

#14285 Fix for HTTP 400 issue seen in Datadog logs
  packages/server/src/sdk/app/rows/search/sqs.ts
Labels: firestorm, size/s

#14291 Record SQS queries in DataDog.
  packages/server/src/sdk/app/rows/search/sqs.ts
Labels: firestorm, size/xs

#14220 Add helper function / builder for creating Automations for tests and improved types
  packages/server/src/automations/actions.ts
  packages/server/src/automations/automationUtils.ts
  packages/server/src/automations/steps/bash.ts
  packages/server/src/automations/steps/collect.ts
  packages/server/src/automations/steps/createRow.ts
  packages/server/src/automations/steps/delay.ts
  packages/server/src/automations/steps/deleteRow.ts
  packages/server/src/automations/steps/discord.ts
  packages/server/src/automations/steps/executeQuery.ts
  packages/server/src/automations/steps/executeScript.ts
  packages/server/src/automations/steps/filter.ts
  packages/server/src/automations/steps/make.ts
  packages/server/src/automations/steps/n8n.ts
  packages/server/src/automations/steps/openai.ts
  packages/server/src/automations/steps/outgoingWebhook.ts
  packages/server/src/automations/steps/queryRows.ts
  packages/server/src/automations/steps/sendSmtpEmail.ts
  packages/server/src/automations/steps/serverLog.ts
  packages/server/src/automations/steps/slack.ts
  packages/server/src/automations/steps/triggerAutomationRun.ts
  packages/server/src/automations/steps/updateRow.ts
  packages/server/src/automations/steps/zapier.ts
  packages/server/src/automations/tests/loop.spec.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/automations/tests/utilities/AutomationBuilder.ts
  packages/server/src/automations/tests/utilities/index.ts
  packages/server/src/automations/triggerInfo/app.ts
  packages/server/src/automations/triggerInfo/cron.ts
  packages/server/src/automations/triggerInfo/rowDeleted.ts
  packages/server/src/automations/triggerInfo/rowSaved.ts
  packages/server/src/automations/triggerInfo/rowUpdated.ts
  packages/server/src/automations/unitTests/automationUtils.spec.ts
  packages/server/src/definitions/automations.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/threads/automation.ts
  packages/server/src/utilities/workerRequests.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/types/src/documents/app/automation/index.ts
  packages/types/src/documents/app/automation/schema.ts
Labels: firestorm, size/xl
