Repository Budibase/budibase, pull requests merged in 2024-01, with the labels that each got.

#12686 Remove CLI PKG build
  packages/cli/.gitignore
  packages/cli/package.json
  packages/cli/src/index.ts
  packages/cli/src/prebuilds.ts
  yarn.lock
Labels: firestorm

#12698 Fix local development of multi-tenancy apps
  packages/backend-core/src/context/mainContext.ts
  packages/backend-core/src/tenancy/tenancy.ts
  packages/backend-core/src/tenancy/tests/tenancy.spec.ts
  packages/backend-core/src/utils/utils.ts
Labels: firestorm

#12706 [Fix] Keep exisitng views when refetching tables
  packages/server/src/integrations/utils.ts
Labels: firestorm

#12585 Multi-step form block
  packages/bbui/src/ActionButton/ActionButton.svelte
  packages/bbui/src/DetailSummary/DetailSummary.svelte
  packages/bbui/src/Form/Field.svelte
  packages/builder/src/builderStore/dataBinding.js
  packages/builder/src/builderStore/store/frontend.js
  packages/builder/src/components/design/settings/componentSettings.js
  packages/builder/src/components/design/settings/controls/ButtonConfiguration/ButtonConfiguration.svelte
  packages/builder/src/components/design/settings/controls/DraggableList/DraggableList.svelte
  packages/builder/src/components/design/settings/controls/FieldConfiguration/FieldConfiguration.svelte
  packages/builder/src/components/design/settings/controls/FormStepConfiguration.svelte
  packages/builder/src/components/design/settings/controls/FormStepControls.svelte
  packages/builder/src/components/design/settings/controls/PropertyControl.svelte
  packages/builder/src/components/design/settings/controls/ValidationEditor/ValidationDrawer.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsSection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/manifest.json
  packages/client/src/components/app/blocks/MultiStepFormblock.svelte
  packages/client/src/components/app/blocks/TableBlock.svelte
  packages/client/src/components/app/blocks/form/FormBlock.svelte
  packages/client/src/components/app/blocks/form/FormBlockWrapper.svelte
  packages/client/src/components/app/blocks/index.js
  packages/client/src/components/app/forms/Field.svelte
  packages/client/src/components/app/forms/Form.svelte
  packages/client/src/components/app/forms/InnerForm.svelte
  packages/client/src/index.js
  packages/client/src/stores/builder.js
  packages/frontend-core/src/utils/utils.js
Labels: feature-branch

#12713 Remove password validation for admin user environment variables
  packages/backend-core/src/environment.ts
  packages/backend-core/src/security/auth.ts
  packages/backend-core/src/users/db.ts
  packages/server/src/startup.ts
  packages/types/src/sdk/user.ts
Labels: firestorm

#12716 Enable dd-trace logging in QA to try and figure out why user info isn't being added to traces.
  packages/server/src/ddApm.ts
Labels: firestorm

#12726 Set the CouchDB credentials in a safer way inside of runner.sh.
  hosting/couchdb/runner.sh
Labels: firestorm

#12581 App migration app frontend
  packages/client/package.json
  packages/client/src/api/api.js
  packages/client/src/components/UpdatingApp.svelte
  packages/client/src/index.js
  packages/server/nodemon.json
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/controllers/static/templates/BudibaseApp.svelte
  yarn.lock
Labels: firestorm, feature-branch

#12725 Add some more spans to the JS runner
  packages/server/src/jsRunner.ts
Labels: firestorm

#12727 Search path support for Postgres
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/postgres.ts
Labels: firestorm

#12742 Fix for Postgres schema loading
  packages/server/src/integrations/postgres.ts
Labels: firestorm

#12753 Update @budibase/handlebars-helpers package
  packages/string-templates/package.json
  packages/string-templates/src/helpers/javascript.js
  yarn.lock
Labels: feature-branch

#12765 Remove constant CouchDB HEAD requests
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/types/src/sdk/db.ts
  yarn.lock
Labels: firestorm

#12759 Automation UX updates for name sidebar and test output panel
  packages/builder/package.json
  packages/builder/src/components/automation/AutomationBuilder/TestDisplay.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
  packages/server/src/automations/steps/filter.ts
Labels: feature-branch

#11830 Global bindings
  packages/builder/src/builderStore/componentUtils.js
  packages/builder/src/builderStore/dataBinding.js
  packages/builder/src/builderStore/store/frontend.js
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/utils.js
  packages/builder/src/components/design/settings/controls/DataProviderSelect.svelte
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
  packages/client/manifest.json
  packages/client/src/components/Component.svelte
  packages/client/src/components/app/DataProvider.svelte
  packages/client/src/components/app/EmptyPlaceholder.svelte
  packages/client/src/components/app/GridBlock.svelte
  packages/client/src/components/app/Repeater.svelte
  packages/client/src/components/app/blocks/MultiStepFormblock.svelte
  packages/client/src/components/app/blocks/TableBlock.svelte
  packages/client/src/components/app/blocks/form/FormBlockWrapper.svelte
  packages/client/src/components/app/forms/Form.svelte
  packages/client/src/components/context/Provider.svelte
  packages/client/src/constants.js
  packages/client/src/sdk.js
  packages/client/src/stores/context.js
  packages/client/src/utils/buttonActions.js
  packages/client/src/utils/componentProps.js
  packages/frontend-core/src/api/rows.js
Labels: do not merge, feature-branch

#12827 Configure automation chaining
  packages/builder/src/pages/builder/app/[application]/settings/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/settings/automations/_components/HistoryDetailsPanel.svelte
  packages/builder/src/pages/builder/app/[application]/settings/automations/_components/StatusRenderer.svelte
  packages/builder/src/pages/builder/app/[application]/settings/automations/index.svelte
  packages/builder/src/pages/builder/app/[application]/settings/index.svelte
  packages/server/src/events/AutomationEmitter.ts
  packages/types/src/documents/app/app.ts
Labels: feature-branch

#12855 Add TARGETBUILD to single image build script
  scripts/build-single-image.sh
Labels: bug

#12861 Quick fix for Select compare functionality
  packages/bbui/src/Form/Core/Select.svelte
Labels: firestorm

#12865 Fixing issue with compare option of Select.svelte
  packages/bbui/src/Form/Core/Select.svelte
Labels: firestorm

#12879 Allowed typed user query to be passed into invite user form.
  packages/builder/src/pages/builder/app/[application]/_components/BuilderSidePanel.svelte
Labels: user management

#12862 Refactor - fully replace FieldTypes with newer FieldType
  packages/frontend-core/src/components/grid/cells/HeaderCell.svelte
  packages/server/specs/resources/table.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/controllers/row/staticFormula.ts
  packages/server/src/api/controllers/table/bulkFormula.ts
  packages/server/src/api/controllers/table/tests/utils.spec.ts
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/api/controllers/view/views.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/automations/steps/queryRows.ts
  packages/server/src/constants/index.ts
  packages/server/src/db/defaultData/datasource_bb_default.ts
  packages/server/src/db/linkedRows/LinkController.ts
  packages/server/src/db/linkedRows/LinkDocument.ts
  packages/server/src/db/linkedRows/linkUtils.ts
  packages/server/src/db/tests/linkController.spec.ts
  packages/server/src/db/tests/linkTests.spec.ts
  packages/server/src/db/utils.ts
  packages/server/src/integrations/base/sqlTable.ts
  packages/server/src/integrations/oracle.ts
  packages/server/src/sdk/app/rows/attachments.ts
  packages/server/src/sdk/app/rows/tests/internal.spec.ts
  packages/server/src/sdk/app/rows/utils.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/server/src/sdk/app/tables/external/utils.ts
  packages/server/src/sdk/app/tables/internal/index.ts
  packages/server/src/utilities/rowProcessor/attachments.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/map.ts
  packages/server/src/utilities/rowProcessor/tests/utils.spec.ts
  packages/server/src/utilities/rowProcessor/utils.ts
  packages/server/src/utilities/schema.ts
  packages/types/src/documents/app/table/constants.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm

#12881 Attempting to fix CI Postgres test failures
  packages/server/package.json
  packages/server/scripts/integrations/postgres/docker-compose.yml
  packages/server/src/integrations/tests/utils/postgres.ts
  packages/server/src/sdk/app/rows/search/tests/external.spec.ts
  yarn.lock
Labels: firestorm

#12897 Fix dev:noserver with account portal checked out
  package.json
Labels: firestorm

#12899 Removing old inaccurate documentation for development
  README.md
  docs/DEV-SETUP-DEBIAN.md
  docs/DEV-SETUP-MACOSX.md
  docs/DEV-SETUP-WINDOWS.md
  i18n/README.es.md
Labels: firestorm

#12908 Fix automation looping failing when binding returned an integer.
  packages/server/src/automations/tests/loop.spec.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/threads/automation.ts
Labels: firestorm

#12900 Add a check to stringSplit that gives a nicer error message if a non-string is passed.
  packages/server/src/automations/automationUtils.ts
Labels: firestorm

#12917 Update to @budibase/nano 10.1.5
  packages/backend-core/package.json
  packages/types/package.json
  yarn.lock
Labels: firestorm, feature-branch
