Repository Budibase/budibase, pull requests merged in 2024-06, with the labels that each got.

#13835 Fixing some REST file download issues
  packages/backend-core/src/objectStore/objectStore.ts
  packages/server/package.json
  packages/server/src/integrations/rest.ts
  packages/server/src/integrations/tests/rest.spec.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/threads/query.ts
  packages/types/src/documents/app/automation.ts
  yarn.lock
Labels: firestorm

#13844 Frontend validation
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/utilities/schema.ts
  packages/shared-core/src/helpers/schema.ts
  packages/shared-core/src/helpers/tests/schema.spec.ts
Labels: firestorm

#13852 Support existing view configurations
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
Labels: firestorm, size/l

#13824 [Feat] Readonly columns
  packages/backend-core/src/middleware/joi-validator.ts
  packages/builder/src/components/backend/DataTable/ViewV2DataTable.svelte
  packages/builder/src/stores/portal/licensing.js
  packages/client/src/components/app/forms/InnerForm.svelte
  packages/frontend-core/src/components/grid/cells/DataCell.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/frontend-core/src/components/grid/controls/ToggleActionButtonGroup.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/frontend-core/src/components/grid/stores/columns.js
  packages/frontend-core/src/components/grid/stores/datasource.js
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/utilities/schema.ts
  packages/shared-core/src/helpers/schema.ts
  packages/shared-core/src/helpers/tests/schema.spec.ts
Labels: firestorm, feature-branch, size/l

#13857 Quick fix for roles binding in JS
  packages/builder/src/dataBinding.js
  packages/string-templates/src/helpers/javascript.ts
  packages/string-templates/test/javascript.spec.ts
Labels: firestorm, size/s

#13829 Enhancement: add ability to set custom auto-dismissal duration for notifications
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/ShowNotification.svelte
  packages/client/src/stores/notification.js
  packages/client/src/utils/buttonActions.js
Labels: size/s

#13860 Prepare Helm chart for SQS.
  charts/budibase/Chart.lock
  charts/budibase/Chart.yaml
  charts/budibase/README.md
  charts/budibase/charts/couchdb-4.3.0.tgz
  charts/budibase/charts/couchdb-4.5.6.tgz
  charts/budibase/templates/app-service-deployment.yaml
  charts/budibase/templates/worker-service-deployment.yaml
  charts/budibase/values.yaml
Labels: firestorm, size/s

#13863 Adding current user global ID binding
  packages/builder/src/dataBinding.js
  packages/server/src/api/controllers/auth.ts
Labels: firestorm, size/xs

#13864 Adding test for globalId in self call
  packages/server/src/api/routes/tests/auth.spec.js
Labels: firestorm, size/s

#13865 Fix time-only form fields for internal db
  packages/client/src/components/app/blocks/FormBlockComponent.svelte
  packages/client/src/components/app/forms/DateTimeField.svelte
Labels: firestorm, size/s

#13867 Fix CI build flakiness
  package.json
Labels: firestorm, size/xs

#13868 Fix application deletion when SQS is enabled.
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/server/src/api/routes/tests/application.spec.ts
Labels: firestorm, size/s

#13872 Ignore SQS 500s on cleanup
  packages/backend-core/src/db/couch/DatabaseImpl.ts
Labels: firestorm, size/xs

#13819 Allow users to only specify a binding when adding attachments
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/server/src/automations/automationUtils.ts
  packages/server/src/automations/steps/createRow.ts
  packages/server/src/automations/steps/sendSmtpEmail.ts
  packages/server/src/automations/tests/createRow.spec.ts
Labels: firestorm, size/m

#13876 Fix key value updates in patch
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/s

#13854 SQS migrations/app migrations
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/migrations.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/appMigrations/appMigrationMetadata.ts
  packages/server/src/appMigrations/index.ts
  packages/server/src/appMigrations/migrations.ts
  packages/server/src/appMigrations/migrations/20240604153647_initial_sqs.ts
  packages/server/src/appMigrations/migrations/tests/20240604153647_initial_sqs.spec.ts
  packages/server/src/appMigrations/tests/migrations.spec.ts
  packages/server/src/db/linkedRows/LinkDocument.ts
  packages/server/src/db/utils.ts
  packages/server/src/environment.ts
  packages/server/src/middleware/appMigrations.ts
  packages/server/src/sdk/app/tables/internal/sqs.ts
  packages/types/src/documents/app/sqlite.ts
  packages/types/src/sdk/db.ts
  scripts/add-app-migration.js
Labels: firestorm, size/m

#13869 Enable SQS in dev 🎉
  packages/server/scripts/dev/manage.js
  packages/worker/scripts/dev/manage.js
Labels: firestorm, size/xs

#13880 Update CouchDB image from 3.2.1 to 3.3.3.
  charts/budibase/values.yaml
Labels: firestorm, size/xs

#13881 Remove rename test from mysql.spec.ts, it's covered in table.spec.ts
  packages/server/src/integration-test/mysql.spec.ts
Labels: firestorm, size/s

#13882 Modernise datasource.spec.ts
  packages/server/src/api/routes/tests/__snapshots__/datasource.spec.ts.snap
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/tests/utilities/api/datasource.ts
Labels: firestorm, size/l

#13883 Move some mysql.spec.ts and postgres.spec.ts tests into datasource.sp…
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/integration-test/mysql.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/tests/utilities/api/datasource.ts
Labels: firestorm, size/m

#13886 Make sure nullable can be updated and then re-fetched
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/tests/utilities/api/datasource.ts
Labels: firestorm, size/m

#13891 Fixing multi-tenant app migration issue
  packages/backend-core/src/queue/queue.ts
  packages/server/src/appMigrations/index.ts
  packages/server/src/appMigrations/migrationsProcessor.ts
  packages/server/src/appMigrations/queue.ts
Labels: firestorm, size/m

#13895 Slim down postgres.spec.ts, most of its content is tested elsewhere now across many datasources.
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
Labels: firestorm, size/xl

#13901 Enable DataDog test instrumentation.
  .github/workflows/budibase_ci.yml
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/xs

#13905 App migration - make sure any issue is logged
  packages/server/src/appMigrations/migrationsProcessor.ts
Labels: firestorm, size/s

#13906 Adding version to system status call
  packages/types/src/api/web/system/index.ts
  packages/types/src/api/web/system/status.ts
  packages/worker/src/api/controllers/system/status.ts
  packages/worker/src/api/routes/system/tests/status.spec.ts
Labels: firestorm, size/s

#13907 App migrations in API service
  packages/server/src/appMigrations/queue.ts
Labels: firestorm, size/xs

#13908 Better app migration queue startup process
  packages/server/src/appMigrations/index.ts
  packages/server/src/appMigrations/queue.ts
  packages/server/src/automations/bullboard.ts
  packages/server/src/startup/index.ts
Labels: firestorm, size/s

#13909 Some potential app migration failure causes
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/server/src/appMigrations/appMigrationMetadata.ts
  packages/server/src/appMigrations/index.ts
  packages/server/src/appMigrations/migrationsProcessor.ts
  packages/server/src/appMigrations/queue.ts
  packages/server/src/startup/index.ts
Labels: firestorm, size/m

#13902 Create Tenant endpoint + tenant_info doc
  packages/backend-core/src/tenancy/db.ts
  packages/types/src/documents/global/index.ts
  packages/types/src/documents/global/tenantInfo.ts
  packages/worker/src/api/controllers/global/tenant.ts
  packages/worker/src/api/index.ts
  packages/worker/src/api/routes/global/tenant.ts
  packages/worker/src/api/routes/global/tests/tenant.spec.ts
  packages/worker/src/api/routes/index.ts
  packages/worker/src/tests/api/tenants.ts
  yarn.lock
Labels: size/m

#13911 Disable app migration caching
  packages/backend-core/src/environment.ts
  packages/server/src/appMigrations/appMigrationMetadata.ts
  packages/server/src/startup/index.ts
  packages/worker/src/environment.ts
  packages/worker/src/index.ts
Labels: firestorm, size/s

#13916 Moving app migrations back to API service.
  packages/server/src/appMigrations/appMigrationMetadata.ts
  packages/server/src/startup/index.ts
Labels: firestorm, size/s

#13915 small change to ensure that name of datasources is available in dropd…
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceCategory.svelte
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
Labels: size/xs

#13914 Lock starting containers.
  .gitignore
  packages/server/specs/openapi.json
  packages/server/specs/openapi.yaml
  packages/server/src/integrations/tests/utils/index.ts
  packages/server/src/integrations/tests/utils/mssql.ts
  packages/server/src/integrations/tests/utils/mysql.ts
  packages/server/src/integrations/tests/utils/postgres.ts
Labels: firestorm, size/s

#13897 Allow using an AWS_SESSION_TOKEN for object storage with AWS S3
  packages/backend-core/src/environment.ts
  packages/backend-core/src/objectStore/objectStore.ts
  packages/server/src/environment.ts
  packages/worker/src/environment.ts
Labels: firestorm, size/xs

#13924 Remove deprecated unused endpoints
  packages/worker/src/api/routes/global/users.ts
Labels: size/xs

#13929 Remove the word 'lucene' from runLuceneQuery and buildLuceneQuery.
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/backend/DataTable/modals/ExportModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUIDrawer.svelte
  packages/client/src/components/app/DataProvider.svelte
  packages/client/src/components/app/dynamic-filter/DynamicFilter.svelte
  packages/client/src/sdk.js
  packages/client/src/utils/conditions.js
  packages/frontend-core/src/components/FilterBuilder.svelte
  packages/frontend-core/src/fetch/DataFetch.js
  packages/frontend-core/src/fetch/UserFetch.js
  packages/frontend-core/src/utils/index.js
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/integrations/googlesheets.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/tests/filters.test.ts
Labels: firestorm, size/m

#13930 Moving app migrations back to automation worker service
  packages/server/src/appMigrations/appMigrationMetadata.ts
  packages/server/src/startup/index.ts
Labels: firestorm, size/xs

#13922 Chart Component and Explanation Modal Fixes and Improvements
  packages/builder/src/components/design/settings/controls/Explanation/Explanation.svelte
  packages/builder/src/components/design/settings/controls/Explanation/lines/Column.svelte
  packages/builder/src/components/design/settings/controls/Explanation/lines/Support.svelte
  packages/builder/src/components/design/settings/controls/FieldSelect.svelte
  packages/builder/src/components/design/settings/controls/MultiFieldSelect.svelte
  packages/client/manifest.json
  packages/client/src/components/app/blocks/ChartBlock.svelte
  packages/client/src/components/app/charts/AreaChart.svelte
  packages/client/src/components/app/charts/BarChart.svelte
  packages/client/src/components/app/charts/LineChart.svelte
Labels: size/m

#13942 Migration documentation + caching fix
  packages/builder/src/pages/builder/maintenance/index.svelte
  packages/frontend-core/src/components/Updating.svelte
  packages/server/src/appMigrations/appMigrationMetadata.ts
  yarn.lock
Labels: firestorm, size/s

#13921 UX Changes to Component Name Editing Flow
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsPanel.svelte
Labels: size/s

#13944 Add function to close side panel based on the browser's history.
  packages/client/src/components/ClientApp.svelte
  packages/client/src/components/app/SidePanel.svelte
Labels: size/s

#13923 Add endpoint to GET tenant info from tenant global DB.
  .github/workflows/budibase_ci.yml
  package.json
  packages/backend-core/src/tenancy/db.ts
  packages/types/src/documents/global/tenantInfo.ts
  packages/worker/src/api/controllers/global/tenant.ts
  packages/worker/src/api/index.ts
  packages/worker/src/api/routes/global/tenant.ts
  packages/worker/src/api/routes/global/tests/tenant.spec.ts
Labels: size/s

#13948 Solve all remaining TODOs in search.spec.ts.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/m

#13960 Use `knex` instead of `rawQuery` everywhere, remove `rawQuery` from codebase.
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/integration-test/mysql.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/tests/utils/index.ts
  packages/server/src/integrations/tests/utils/mariadb.ts
  packages/server/src/integrations/tests/utils/mssql.ts
  packages/server/src/integrations/tests/utils/mysql.ts
  packages/server/src/integrations/tests/utils/postgres.ts
Labels: firestorm, size/l

#13848 Modal component
  packages/bbui/src/Modal/Modal.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/CloseModal.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/OpenModal.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/index.js
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/manifest.json
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/NewComponentPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/builder/src/stores/builder/screens.js
  packages/client/manifest.json
  packages/client/src/components/ClientApp.svelte
  packages/client/src/components/app/Layout.svelte
  packages/client/src/components/app/Link.svelte
  packages/client/src/components/app/Modal.svelte
  packages/client/src/components/app/blocks/form/FormBlock.svelte
  packages/client/src/components/app/blocks/form/InnerFormBlock.svelte
  packages/client/src/components/app/index.js
  packages/client/src/components/preview/IndicatorSet.svelte
  packages/client/src/sdk.js
  packages/client/src/stores/index.js
  packages/client/src/stores/modal.js
  packages/client/src/utils/buttonActions.js
  packages/frontend-core/src/utils/utils.js
Labels: size/m

#13931 Expose old row through the emitter
  .eslintrc.json
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/utilities/TestFunctions.ts
  packages/server/src/automations/triggerInfo/rowUpdated.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/events/BudibaseEmitter.ts
  packages/server/src/events/utils.ts
  packages/server/src/tests/utilities/structures.ts
  packages/types/src/documents/app/automation.ts
Labels: firestorm, size/m

#13968 Support external datasources in the bulkImport endpoint.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/table/external.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/types/src/sdk/datasources.ts
Labels: firestorm, size/m

#13969 Counting total rows in query (Datasource+)
  packages/backend-core/src/sql/sql.ts
  packages/server/scripts/integrations/postgres/init.sql
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/routes/row.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/integrations/base/query.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/rows/sqlAlias.ts
  packages/server/src/sdk/app/rows/utils.ts
  packages/shared-core/src/filters.ts
  packages/types/src/api/web/app/rows.ts
  packages/types/src/sdk/datasources.ts
  packages/types/src/sdk/row.ts
  yarn.lock
Labels: firestorm, size/xl

#13993 Disallow prohibited columns
  packages/backend-core/src/db/constants.ts
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/sdk/app/tables/internal/index.ts
  packages/shared-core/src/constants/index.ts
  packages/shared-core/src/constants/rows.ts
  packages/shared-core/src/table.ts
Labels: firestorm, size/m

#13966 Add the option to change the confirm and cancel button texts within the confirmation modals
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/DeleteRow.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/DuplicateRow.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/ExecuteQuery.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/SaveRow.svelte
  packages/client/src/components/overlay/ConfirmationDisplay.svelte
  packages/client/src/stores/confirmation.js
  packages/client/src/utils/buttonActions.js
Labels: size/s

#13977 Adds _id and _rev back to internal datasource filter options
  packages/backend-core/src/constants/db.ts
  packages/frontend-core/src/components/FilterBuilder.svelte
  packages/frontend-core/src/constants.js
  packages/shared-core/src/constants/index.ts
Labels: firestorm, size/s

#13998 Allow filtering on relationship column, or related table name
  packages/backend-core/src/sql/sqlTable.ts
  packages/backend-core/src/sql/utils.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/controllers/table/external.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/index.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/filters.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/sdk/app/views/external.ts
Labels: firestorm, size/l

#13979 [BUDI-8220] Support updating existing rows for external databases using CSV import
  packages/backend-core/src/sql/sql.ts
  packages/builder/src/components/backend/TableNavigator/ExistingTableDataImport.svelte
  packages/server/scripts/integrations/mssql/data/Dockerfile
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/table/external.ts
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/utilities/schema.ts
Labels: firestorm, size/m

#14008 [BUDI-8390] Fix primary key appearing twice in the SQL ORDER BY clause.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/routes/tests/search.spec.ts
Labels: firestorm, size/s

#14004 fix issue where schema wasn't updating types when a query was run
  packages/builder/src/components/integration/RestQueryViewer.svelte
  packages/server/src/api/controllers/query/index.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/api/routes/tests/queries/mongodb.spec.ts
  packages/server/src/api/routes/tests/queries/rest.spec.ts
Labels: firestorm, size/m

#14013 Run account portal unit tests
  .github/workflows/budibase_ci.yml
Labels: size/xs

#14022 Don't show hidden settings in the settings bar
  packages/client/manifest.json
  packages/client/src/components/preview/SettingsBar.svelte
Labels: size/s

#14027 Fixing pro submodule check (no merge issue)
  .github/workflows/budibase_ci.yml
Labels: firestorm, size/xs

#13961 Remove DD CI visibility
  .github/workflows/budibase_ci.yml
Labels: firestorm, size/xs

#13965 Table UI changes
  packages/frontend-core/src/components/grid/layout/ButtonColumn.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/frontend-core/src/components/grid/layout/GridBody.svelte
  packages/frontend-core/src/components/grid/layout/NewRow.svelte
  packages/frontend-core/src/components/grid/layout/StickyColumn.svelte
  packages/frontend-core/src/components/grid/lib/constants.js
  packages/frontend-core/src/components/grid/stores/scroll.js
Labels: size/m

#14026 Bringing back backend column validation
  packages/backend-core/src/db/constants.ts
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/sdk/app/tables/internal/index.ts
  packages/shared-core/src/constants/index.ts
  packages/shared-core/src/constants/rows.ts
  packages/shared-core/src/table.ts
Labels: firestorm, size/m

#14044 Fix weird behaviour when adding rows if you have multiple pages of data
  packages/frontend-core/src/components/grid/layout/NewRow.svelte
Labels: size/xs

#14045 Frontend - allow prohibited columns, case sensitive
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
Labels: firestorm, size/xs

#14018 Replace multiple spaces in bindings with one space
  packages/string-templates/src/processors/preprocessor.ts
  packages/string-templates/test/basic.spec.ts
Labels: firestorm, size/s
