Repository Budibase/budibase, pull requests merged in 2024-11, with the labels that each got.

#14937 Sample data fix
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/api/routes/tests/application.spec.ts
Labels: firestorm, size/s

#14939 Minor OpenAPI updates
  packages/server/specs/parameters.ts
  packages/server/specs/resources/index.ts
  packages/server/src/api/routes/public/index.ts
Labels: firestorm, size/xs

#14938 Switch QA to v3-ui
  .github/workflows/deploy-qa.yml
Labels: firestorm, size/xs

#14945 Update color picker to account for new theme values
  packages/bbui/src/ColorPicker/ColorPicker.svelte
Labels: size/s

#14946 Fix issue with branch step bindings
  packages/server/src/automations/steps/branch.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/s

#14936 Deploy all camunda processes
  .vscode/launch.json
  scripts/deploy-camunda.sh
Labels: size/s

#14951 Fix enrichment when having AI columns
  packages/server/src/api/controllers/row/staticFormula.ts
Labels: firestorm, size/xs

#14957 Add USE_DEFAULT_REDIS_CONFIG environment variable to single image to disable our config customisations.
  hosting/single/runner.sh
Labels: firestorm, size/s

#14954 Fix issue counting number of filters when legacy structure is used
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterEditor.svelte
Labels: size/s

#14959 Flag ai correctly for premium
  packages/builder/src/components/automation/SetupPanel/CronBuilder.svelte
  packages/builder/src/pages/builder/portal/settings/ai/AISettings.spec.js
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
  packages/builder/src/pages/builder/portal/settings/index.svelte
  packages/server/src/api/controllers/row/staticFormula.ts
  packages/server/src/automations/steps/openai.ts
Labels: size/s

#14956 Disable major update from actions
  .github/workflows/tag-release.yml
Labels: firestorm, size/xs

#14953 Remove TABLES_DEFAULT_ADMIN flag
  packages/backend-core/src/features/features.ts
  packages/server/src/sdk/app/tables/create.ts
  packages/server/src/sdk/app/views/index.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/s

#14966 Support setting multiple many to many relationships between two tables
  packages/builder/src/components/backend/Datasources/CreateEditRelationship.svelte
  packages/builder/src/components/backend/Datasources/relationshipErrors.js
Labels: firestorm, size/s

#14968 fix for conditional automation step options always showing
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
Labels: size/xs

#14783 Automation Branching UX
  packages/builder/src/components/automation/AutomationBuilder/AutomationBuilder.svelte
  packages/builder/src/components/automation/AutomationBuilder/DraggableCanvas.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/ActionModal.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/BranchNode.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/DragZone.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItem.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItemActions.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItemHeader.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/StepNode.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
  packages/builder/src/components/automation/AutomationBuilder/TestDisplay.svelte
  packages/builder/src/components/automation/AutomationBuilder/TestPanel.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationNavItem.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationSelector.svelte
  packages/builder/src/components/automation/Shared/CreateWebhookModal.svelte
  packages/builder/src/components/common/UndoRedoControl.svelte
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterBuilder.svelte
  packages/builder/src/dataBinding.js
  packages/builder/src/pages/builder/app/[application]/automation/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/settings/automations/_components/HistoryDetailsPanel.svelte
  packages/builder/src/stores/builder/automations.js
  packages/frontend-core/src/components/ConditionField.svelte
  packages/frontend-core/src/components/CoreFilterBuilder.svelte
  packages/frontend-core/src/components/FilterField.svelte
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/automations/steps/branch.ts
  packages/server/src/automations/tests/scenarios/branching.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/threads/automation.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/utils.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
Labels: do not merge, size/xl, feature-branch-enterprise

#14976 Self host feature flags
  packages/backend-core/src/features/features.ts
Labels: firestorm, size/xs

#14969 Log SQS connection errors, and retry connection a few times before giving up.
  packages/shared-core/src/helpers/async.ts
  packages/shared-core/src/helpers/index.ts
  packages/shared-core/src/helpers/retry.ts
  packages/worker/src/api/controllers/system/environment.ts
Labels: firestorm, size/s

#14989 Remove watchtower
  hosting/.env
  hosting/docker-compose.build.yaml
  hosting/docker-compose.yaml
  hosting/envoy.yaml
  hosting/hosting.properties
  hosting/portainer/template.json
  hosting/proxy/Dockerfile
  hosting/proxy/nginx.prod.conf
  hosting/scripts/airgapped/airgappedDockerBuild.js
  packages/builder/src/pages/builder/portal/settings/version.svelte
Labels: firestorm, size/m

#14991 Issue where looping wasn't working due to missing context
  packages/server/src/automations/tests/scenarios/looping.spec.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/s

#14990 turning on AI flags
  packages/backend-core/src/features/features.ts
Labels: size/xs

#14979 Correct automation cron server timestamp
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/server/src/automations/tests/cron-automations.spec.ts
  packages/server/src/automations/utils.ts
  packages/server/src/tests/utilities/structures.ts
  packages/types/src/sdk/automations/index.ts
Labels: firestorm, size/s

#15000 prevent attachment column updates when importing budibase templates
  packages/server/src/api/controllers/application.ts
  packages/server/src/sdk/app/applications/import.ts
  packages/server/src/sdk/app/backups/imports.ts
Labels: size/s

#15014 Allow December in cron validation
  packages/shared-core/src/helpers/cron.ts
Labels: firestorm, size/xs

#15003 Csp updates
  hosting/nginx.dev.conf
  hosting/proxy/nginx.prod.conf
  packages/backend-core/src/environment.ts
  packages/backend-core/src/middleware/contentSecurityPolicy.ts
  packages/backend-core/src/middleware/index.ts
  packages/backend-core/src/middleware/tests/contentSecurityPolicy.spec.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/controllers/static/templates/BudibaseApp.svelte
  packages/server/src/api/controllers/static/templates/app.hbs
  packages/server/src/api/controllers/static/templates/preview.hbs
  packages/server/src/koa.ts
  packages/types/src/sdk/koa.ts
  packages/worker/src/index.ts
  yarn.lock
Labels: size/m

#15015 enable proxy buffering for calls to OIDC endpoints
  hosting/proxy/nginx.prod.conf
Labels: size/xs

#15018 remove CSP from dev
  hosting/nginx.dev.conf
Labels: size/s

#15017 Clean enriched relationships flag
  packages/backend-core/src/features/features.ts
  packages/builder/src/components/backend/DataTable/buttons/grid/ColumnsSettingContent.svelte
  packages/builder/src/components/backend/DataTable/buttons/grid/GridColumnsSettingButton.svelte
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/db/linkedRows/index.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/m

#15021 fix dnd handlers
  packages/backend-core/src/environment.ts
  packages/backend-core/src/middleware/contentSecurityPolicy.ts
  packages/builder/src/components/common/NavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/ComponentScrollWrapper.svelte
Labels: size/s

#15022 Fix the NX check that looks for only affected packages when running tests in CI
  .github/workflows/budibase_ci.yml
Labels: firestorm, size/s

#14967 Fix race conditions between automation test data and runs
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
Labels: do not merge, firestorm, size/s

#15020 Move dependency
  packages/bbui/package.json
  packages/client/package.json
Labels: firestorm, size/xs

#15002 Formula response types
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/frontend-core/src/components/grid/cells/FormulaCell.svelte
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/utils.ts
  packages/types/src/documents/app/row.ts
  packages/types/src/documents/app/table/schema.ts
Labels: firestorm, size/m

#15026 Fix block native search
  packages/client/src/utils/blocks.js
Labels: size/s

#15032 Bypass transformers that are trivial, allow users to configure bson buffer size.
  packages/backend-core/src/environment.ts
  packages/server/src/api/controllers/query/index.ts
  packages/server/src/startup/index.ts
  packages/server/src/threads/query.ts
  packages/worker/src/index.ts
Labels: firestorm, size/s

#15034 Remove bson call from worker.
  packages/worker/src/index.ts
Labels: firestorm, size/xs

#15036 Dependency checking as part of package build
  package.json
  packages/backend-core/package.json
  packages/server/package.json
  packages/worker/package.json
  scripts/depcheck.js
  yarn.lock
Labels: firestorm, size/s

#15039 Add sqs to the datasource test matrix.
  .github/workflows/budibase_ci.yml
Labels: firestorm, size/xs

#15040 Add github-actions Jest reporter.
  .github/workflows/budibase_ci.yml
  package.json
  scripts/run-affected.js
Labels: firestorm, size/s

#15027 Direct describe rather than datasourceDescribe
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/api/routes/tests/queries/mongodb.spec.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/rowAction.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/automations/tests/executeQuery.spec.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/integration-test/mysql.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/tests/utils/index.ts
  packages/server/src/sdk/app/rows/search/tests/search.spec.ts
Labels: firestorm, size/xl

#15044 Fix test-libraries yarn invocation.
  .github/workflows/budibase_ci.yml
Labels: firestorm, size/xs

#15052 Additional instrumentation for DD around CouchDB.
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/types/src/documents/pouch.ts
  packages/types/src/sdk/db.ts
Labels: firestorm, size/m

#15055 OpenAPI for Views
  packages/server/package.json
  packages/server/specs/openapi.json
  packages/server/specs/openapi.yaml
  packages/server/specs/parameters.ts
  packages/server/specs/resources/index.ts
  packages/server/specs/resources/misc.ts
  packages/server/specs/resources/view.ts
  packages/server/src/api/controllers/public/mapping/applications.ts
  packages/server/src/api/controllers/public/mapping/index.ts
  packages/server/src/api/controllers/public/mapping/queries.ts
  packages/server/src/api/controllers/public/mapping/rows.ts
  packages/server/src/api/controllers/public/mapping/tables.ts
  packages/server/src/api/controllers/public/mapping/types.ts
  packages/server/src/api/controllers/public/mapping/users.ts
  packages/server/src/api/controllers/public/mapping/views.ts
  packages/server/src/api/controllers/public/rows.ts
  packages/server/src/api/controllers/public/views.ts
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/public/index.ts
  packages/server/src/api/routes/public/middleware/mapper.ts
  packages/server/src/api/routes/public/rows.ts
  packages/server/src/api/routes/public/tests/Request.ts
  packages/server/src/api/routes/public/tests/cors.spec.ts
  packages/server/src/api/routes/public/tests/views.spec.ts
  packages/server/src/api/routes/public/views.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/api/routes/view.ts
  packages/server/src/definitions/openapi.ts
  packages/server/src/middleware/publicApi.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/tests/utilities/api/viewV2.ts
  packages/types/src/api/web/app/view.ts
  packages/types/src/documents/app/view.ts
  yarn.lock
Labels: firestorm, size/xl

#15066 Adding svelte checks to validate ts on build
  packages/builder/package.json
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/DNDPositionIndicator.svelte
  yarn.lock
Labels: firestorm, size/xs

#15063 Typescript in svelte in builder
  .eslintrc.json
  packages/bbui/src/Button/Button.svelte
  packages/bbui/src/Form/Core/DateRangePicker.svelte
  packages/bbui/src/Form/Search.svelte
  packages/bbui/src/Form/Select.svelte
  packages/bbui/src/Table/Table.svelte
  packages/bbui/src/Typography/Heading.svelte
  packages/builder/.gitignore
  packages/builder/package.json
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/DNDPositionIndicator.svelte
  packages/builder/src/pages/builder/portal/plugins/index.svelte
  packages/builder/svelte.config.js
  packages/client/src/components/app/charts/AreaChart.svelte
  yarn.lock
Labels: firestorm, feature-branch, size/s

#14999 Allow standalone field components without forms
  packages/builder/src/dataBinding.js
  packages/client/manifest.json
  packages/client/src/components/app/forms/Field.svelte
  packages/client/src/components/app/forms/Form.svelte
  packages/client/src/components/app/forms/InnerForm.svelte
Labels: size/m

#15054 Some automation bugs
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/stores/builder/automations.js
  packages/server/src/automations/steps/serverLog.ts
  packages/server/src/automations/tests/executeScript.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, feature-branch, size/m

#15073 Update automation tests to use the new test builder
  packages/server/src/automations/tests/createRow.spec.ts
  packages/server/src/automations/tests/deleteRow.spec.ts
  packages/server/src/automations/tests/updateRow.spec.ts
Labels: firestorm, size/m

#15075 Automate Readme OpenAPI updates
  .github/workflows/readme-openapi.yml
  packages/server/specs/openapi.json
  packages/server/specs/openapi.yaml
  packages/server/specs/resources/view.ts
Labels: firestorm, size/s

#15072 Convert client to use vite instead of rollup
  packages/client/package.json
  packages/client/rollup.config.js
  packages/client/src/index.js
  packages/client/tsconfig.json
  packages/client/vite.config.mjs
  yarn.lock
Labels: size/m

#15085 Removing Datasource plus query API
  packages/server/src/api/controllers/datasource.ts
  packages/server/src/api/routes/datasource.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/constants/index.ts
  packages/server/src/tests/utilities/api/datasource.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/m

#15089 Remove exited containers when running tests.
  packages/backend-core/tests/core/utilities/testContainerUtils.ts
Labels: firestorm, size/s

#15090 Always use the current docker context.
  globalSetup.ts
  packages/backend-core/tests/core/utilities/testContainerUtils.ts
Labels: firestorm, size/s

#15080 Clean unused scripts
  package.json
  scripts/buildx-multiarch.sh
  scripts/pinVersions.js
  scripts/releaseHelmChart.js
  scripts/resetVersions.sh
  scripts/syncLocalDependencies.js
  scripts/updateVersions.sh
Labels: firestorm, size/m

#15074 Remove rollup from bbui
  packages/bbui/package.json
  packages/bbui/rollup.config.js
  packages/bbui/vite.config.js
  yarn.lock
Labels: firestorm, feature-branch, size/s

#15095 Feature flag zod
  packages/backend-core/src/features/features.ts
  packages/server/src/middleware/zod-validator.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/s

#14757 Validation for search api
  packages/backend-core/src/features/features.ts
  packages/server/package.json
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/routes/row.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/middleware/zod-validator.ts
  packages/types/package.json
  packages/types/src/api/web/app/rows.ts
  packages/types/src/api/web/app/rows/index.ts
  packages/types/src/api/web/app/rows/search.ts
  packages/types/src/sdk/featureFlag.ts
  yarn.lock
Labels: do not merge, firestorm, size/m

#15092 Don't fetch account for identifyTenantGroup posthog event
  packages/backend-core/src/events/identification.ts
  packages/server/src/migrations/functions/backfill/global.ts
  packages/worker/src/api/controllers/global/users.ts
Labels: size/s

#14949 Patch row improvements
  packages/server/src/api/controllers/row/staticFormula.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/integrations/tests/utils/index.ts
  packages/server/src/integrations/tests/utils/oracle.ts
  packages/server/src/utilities/rowProcessor/bbReferenceProcessor.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/shared-core/src/constants/rows.ts
Labels: firestorm, size/s
