Repository Budibase/budibase, pull requests merged in 2024-08, with the labels that each got.

#14286 Unify types
  packages/builder/src/constants/backend/index.js
  packages/server/src/api/controllers/view/exporters.ts
  packages/server/src/tests/utilities/api/legacyView.ts
  packages/types/src/sdk/row.ts
Labels: firestorm, size/s

#14290 Handle `_id` when reimporting internal rows
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/controllers/table/internal.ts
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/db/defaultData/datasource_bb_default.ts
  packages/server/src/tests/utilities/api/table.ts
Labels: firestorm, size/m

#14296 Fix MS-SQL client timeout
  packages/server/scripts/integrations/mssql/data/Dockerfile
  packages/server/src/integrations/microsoftSqlServer.ts
Labels: firestorm, size/xs

#14294 Dont allow protected column names on import
  packages/builder/src/components/backend/TableNavigator/TableDataImport.svelte
  packages/builder/src/components/backend/TableNavigator/modals/CreateTableModal.svelte
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/sdk/app/tables/internal/index.ts
  packages/server/src/utilities/schema.ts
  packages/shared-core/src/table.ts
  packages/shared-core/src/utils.ts
Labels: firestorm, size/m

#14297 Remove global node-fetch mock.
  packages/server/__mocks__/node-fetch.ts
  packages/server/src/api/controllers/plugin/index.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/api/routes/tests/plugin.spec.ts
  packages/server/src/automations/tests/discord.spec.js
  packages/server/src/automations/tests/discord.spec.ts
  packages/server/src/automations/tests/make.spec.ts
  packages/server/src/automations/tests/n8n.spec.ts
  packages/server/src/automations/tests/outgoingWebhook.spec.js
  packages/server/src/automations/tests/outgoingWebhook.spec.ts
  packages/server/src/automations/tests/zapier.spec.ts
  packages/server/src/integrations/tests/googlesheets.spec.ts
  packages/server/src/startup/tests/startup.spec.ts
  packages/server/src/tests/jestSetup.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/plugin.ts
  packages/types/src/api/web/index.ts
  packages/types/src/api/web/plugins.ts
Labels: firestorm, size/l

#14301 Remove all mocking from rest.spec.ts.
  packages/server/src/api/routes/tests/queries/rest.spec.ts
  packages/server/src/integrations/rest.ts
  packages/server/src/integrations/tests/rest.spec.ts
  packages/types/src/documents/app/datasource.ts
  packages/types/src/documents/app/query.ts
  yarn.lock
Labels: firestorm, size/l

#14302 User column csv import error
  packages/server/src/api/controllers/view/exporters.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/server/src/tests/utilities/api/row.ts
  packages/server/src/tests/utilities/api/table.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/utilities/schema.ts
Labels: firestorm, feature-branch, size/l

#14292 SQL pagination improvements
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/sdk/app/rows/external.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/sqs.ts
Labels: firestorm, size/m

#14305 Fixing export rows to use correct search
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/internal/index.ts
  packages/server/src/sdk/app/rows/search/internal/internal.ts
  packages/server/src/sdk/app/rows/search/internal/lucene.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
Labels: firestorm, size/m

#14307 Make sure to delete SSO ID doc as well
  packages/worker/src/sdk/tenants/tenants.ts
Labels: size/xs

#14329 Update packages/server to use new larger runners.
  .github/workflows/budibase_ci.yml
Labels: firestorm, size/xs

#14320 Updating google-spreadsheet version
  packages/server/package.json
  yarn.lock
Labels: firestorm, size/xs

#14325 Add Oracle to datasource.spec.ts.
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/integrations/oracle.ts
Labels: firestorm, size/s

#14328 Fix tables showing up multiple times for Oracle in the datasource info endpoint.
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/integrations/oracle.ts
Labels: firestorm, size/s

#14331 In-memory support for logical operators
  packages/server/src/api/routes/tests/search.spec.ts
  packages/shared-core/src/filters.ts
Labels: firestorm, size/s

#14333 Add detailed tracing to searches.
  packages/server/src/sdk/app/rows/search.ts
Labels: firestorm, size/s

#14336 Add search filter api validation
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/utils/validators.ts
Labels: firestorm, size/s

#14335 Support filtering views
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/shared-core/src/filters.ts
  packages/types/src/sdk/search.ts
Labels: firestorm, size/m

#14316 SQL support for logical operators in search
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/api/routes/utils/validators.ts
  packages/server/src/automations/steps/queryRows.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/tsconfig.build.json
  packages/shared-core/tsconfig.json
  packages/types/src/sdk/search.ts
Labels: firestorm, feature-branch, size/l

#14319 Follow-up to Oracle fix PR
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/integrations/oracle.ts
Labels: firestorm, size/s

#14334 Add BpmStatusValue failed
  packages/shared-core/src/constants/index.ts
Labels: size/xs

#14341 fix AWS datasource when endpoint is unspecified
  packages/server/src/api/controllers/static/index.ts
Labels: size/xs

#14345 feat: only use requirepass if password's set
  hosting/single/runner.sh
Labels: size/xs

#14315 Assorted builder fixes and a fix for Google sheets filtering
  packages/bbui/src/Form/Core/Select.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/builder/src/components/backend/DataTable/RowFieldControl.svelte
  packages/builder/src/components/common/LinkedRowSelector.svelte
  packages/builder/src/components/common/bindings/DrawerBindableSlot.svelte
  packages/builder/src/components/design/settings/componentSettings.js
  packages/frontend-core/src/components/grid/cells/SignatureCell.svelte
  packages/server/src/integrations/googlesheets.ts
  packages/shared-core/src/filters.ts
Labels: feature-branch, size/s

#14350 Fix for SQL composite key table `_id` search
  packages/backend-core/src/sql/sqlTable.ts
  packages/server/package.json
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/utils/basic.ts
  packages/server/src/api/routes/tests/datasource.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/api/routes/tests/utilities/TestFunctions.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/server/src/sdk/app/rows/utils.ts
  packages/server/src/tests/jestSetup.ts
  packages/server/src/utilities/schema.ts
  yarn.lock
Labels: firestorm, size/m

#14363 Posthog logging
  packages/backend-core/src/features/index.ts
Labels: firestorm, size/s

#14364 Disable PostHog feature flags in prod.
  packages/backend-core/src/environment.ts
  packages/backend-core/src/features/index.ts
  packages/backend-core/src/features/tests/features.spec.ts
Labels: firestorm, size/s

#14362 Make generated passwords longer
  packages/builder/src/pages/builder/portal/users/users/_components/AddUserModal.svelte
  packages/builder/src/pages/builder/portal/users/users/index.svelte
  packages/worker/src/api/controllers/global/users.ts
Labels: size/s

#14369 Add more automation tests
  packages/server/src/automations/tests/executeQuery.spec.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/automations/tests/utilities/AutomationBuilder.ts
  packages/server/src/automations/tests/utilities/index.ts
  packages/types/src/documents/app/automation/schema.ts
Labels: firestorm, size/m

#14342 Fixes + table native paste
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/utils.js
  packages/builder/src/dataBinding.js
  packages/builder/src/helpers/components.js
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUIDrawer.svelte
  packages/frontend-core/src/components/grid/controls/ClipboardHandler.svelte
  packages/frontend-core/src/components/grid/overlays/KeyboardManager.svelte
Labels: size/m

#14370 Binding Drawer and CodeEditor fixes
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/bindings/DrawerBindableSlot.svelte
Labels: size/m

#14371 Update types and fix ts issues
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/loopUtils.ts
  packages/server/src/automations/tests/utilities/AutomationBuilder.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/sdk/app/automations/crud.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/threads/automation.ts
  packages/types/src/documents/app/automation/schema.ts
Labels: firestorm, size/m

#14376 Setup DEFAULT_VALUES feature flag.
  packages/backend-core/src/features/index.ts
Labels: firestorm, size/xs

#14366 CouchDB SQS 2.0 image
  hosting/couchdb/runner.sh
  hosting/docker-compose.dev.yaml
Labels: firestorm, size/xs

#14378 More automation typing in preparation for branching
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/actions.ts
  packages/server/src/automations/automationUtils.ts
  packages/server/src/automations/loopUtils.ts
  packages/server/src/automations/steps/bash.ts
  packages/server/src/automations/steps/collect.ts
  packages/server/src/automations/steps/createRow.ts
  packages/server/src/automations/steps/delay.ts
  packages/server/src/automations/steps/deleteRow.ts
  packages/server/src/automations/steps/discord.ts
  packages/server/src/automations/steps/executeQuery.ts
  packages/server/src/automations/steps/executeScript.ts
  packages/server/src/automations/steps/filter.ts
  packages/server/src/automations/steps/loop.ts
  packages/server/src/automations/steps/make.ts
  packages/server/src/automations/steps/n8n.ts
  packages/server/src/automations/steps/openai.ts
  packages/server/src/automations/steps/outgoingWebhook.ts
  packages/server/src/automations/steps/queryRows.ts
  packages/server/src/automations/steps/sendSmtpEmail.ts
  packages/server/src/automations/steps/serverLog.ts
  packages/server/src/automations/steps/slack.ts
  packages/server/src/automations/steps/triggerAutomationRun.ts
  packages/server/src/automations/steps/updateRow.ts
  packages/server/src/automations/steps/zapier.ts
  packages/server/src/automations/tests/utilities/AutomationBuilder.ts
  packages/server/src/automations/triggerInfo/app.ts
  packages/server/src/automations/triggerInfo/cron.ts
  packages/server/src/automations/triggerInfo/index.ts
  packages/server/src/automations/triggerInfo/rowAction.ts
  packages/server/src/automations/triggerInfo/rowDeleted.ts
  packages/server/src/automations/triggerInfo/rowSaved.ts
  packages/server/src/automations/triggerInfo/rowUpdated.ts
  packages/server/src/automations/triggerInfo/webhook.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/automations/unitTests/automationUtils.spec.ts
  packages/server/src/automations/utils.ts
  packages/server/src/definitions/automations.ts
  packages/server/src/sdk/app/rowActions.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/threads/automation.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/types/src/documents/app/automation/index.ts
  packages/types/src/documents/app/automation/schema.ts
Labels: size/xl

#14381 Use HBS context over helpers when names overlap (formulas)
  packages/string-templates/src/index.ts
  packages/string-templates/src/processors/index.ts
  packages/string-templates/src/processors/postprocessor.ts
  packages/string-templates/src/processors/preprocessor.ts
  packages/string-templates/src/types.ts
  packages/string-templates/src/utilities.ts
  packages/string-templates/test/helpers.spec.ts
Labels: firestorm, size/m

#14385 App import issue (invalid attachments)
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/sdk/app/backups/imports.ts
  packages/server/src/utilities/rowProcessor/attachments.ts
  packages/types/src/documents/app/row.ts
Labels: firestorm, size/s

#14388 Disallow importing backend-core barrel file
  .eslintrc.json
  eslint-local-rules/index.js
  packages/backend-core/src/context/tests/index.spec.ts
  packages/backend-core/src/features/tests/features.spec.ts
  packages/backend-core/src/redis/tests/redis.spec.ts
Labels: firestorm, size/s

#14387 Update automation test builder to support branching
  packages/server/src/automations/steps/branch.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
Labels: firestorm, size/m

#14395 allow a custom docker registry to be passed if required to helm chart
  charts/budibase/templates/app-service-deployment.yaml
  charts/budibase/templates/automation-worker-service-deployment.yaml
  charts/budibase/templates/minio-service-deployment.yaml
  charts/budibase/templates/proxy-service-deployment.yaml
  charts/budibase/templates/redis-service-deployment.yaml
  charts/budibase/templates/worker-service-deployment.yaml
Labels: size/s

#14405 auto generate encryption key, and use secrets
  charts/budibase/templates/app-service-deployment.yaml
  charts/budibase/templates/automation-worker-service-deployment.yaml
  charts/budibase/templates/secrets.yaml
  charts/budibase/templates/worker-service-deployment.yaml
Labels: size/s

#14347 Fix: Handle setting of env vars in .env gracefully
  hosting/single/runner.sh
Labels: size/xs

#14203 [BUDI-8460] Add New Step to Table Screen Template
  packages/builder/src/components/design/ScreenDetailsModal.svelte
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
  packages/builder/src/components/design/settings/controls/TableSelect.svelte
  packages/builder/src/helpers/data/format.js
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/ScreenNavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/DatasourceModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/FormTypeModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/TableOrViewOption.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/TypeModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/formTypes.js
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/blank.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/blank.svg
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/form.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/formCreate.svg
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/formUpdate.svg
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/formView.svg
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/grid.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/table.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/tableDetails.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/tableInline.png
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/tableInline.svg
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/tableModal.svg
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/tableNewScreen.svg
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/tableSidePanel.svg
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/tableTypes.js
  packages/builder/src/stores/builder/tests/fixtures/index.js
  packages/builder/src/templates/Component.js
  packages/builder/src/templates/blankScreen.js
  packages/builder/src/templates/formScreen.js
  packages/builder/src/templates/gridScreen.js
  packages/builder/src/templates/screenTemplating/Screen.js
  packages/builder/src/templates/screenTemplating/blank.js
  packages/builder/src/templates/screenTemplating/form.js
  packages/builder/src/templates/screenTemplating/getValidRoute.js
  packages/builder/src/templates/screenTemplating/index.js
  packages/builder/src/templates/screenTemplating/table/index.js
  packages/builder/src/templates/screenTemplating/table/inline.js
  packages/builder/src/templates/screenTemplating/table/modal.js
  packages/builder/src/templates/screenTemplating/table/newScreen.js
  packages/builder/src/templates/screenTemplating/table/sidePanel.js
  packages/frontend-core/src/utils/utils.js
Labels: size/xl

#14407 allow values to be passed in secrets
  charts/budibase/templates/secrets.yaml
Labels: size/xs

#14406 Split columns setting button/content
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingContent.svelte
Labels: firestorm, size/m

#14351 Honor table and view schema on query
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/rows/queryUtils.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/tests/search.spec.ts
  packages/server/src/sdk/app/rows/tests/queryUtils.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
Labels: firestorm, feature-branch, size/l

#14413 SQS - broken relationship fix
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/sdk/app/rows/queryUtils.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
Labels: firestorm, size/s

#14418 Invalid primary display setting (no relationship columns)
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/db/linkedRows/index.ts
Labels: firestorm, size/m

#14419 Tiny fix for memo stores
  packages/frontend-core/src/utils/memo.js
Labels: size/xs

#14422 Fix saving huge amounts of unnecessary data in settings
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceCategory.svelte
  packages/builder/src/helpers/data/format.js
Labels: size/s

#14394 Search logical operator fixes
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/integrations/tests/sql.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/sdk/app/rows/search/filters.ts
  packages/server/src/sdk/app/rows/sqlAlias.ts
  packages/shared-core/src/filters.ts
Labels: firestorm, size/m

#14423 Fix query conditions on views
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
Labels: firestorm, size/m

#14429 Ensure autoscreens use a specific component order to look better on old clients
  packages/builder/src/templates/screenTemplating/table/modal.js
  packages/builder/src/templates/screenTemplating/table/newScreen.js
Labels: size/xs

#14427 Persist view related schemas
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
  packages/types/src/documents/app/table/schema.ts
  packages/types/src/documents/app/view.ts
Labels: firestorm, size/s

#14425 View UI ability to pick relationships on columns
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingButton.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingContent.svelte
  packages/frontend-core/src/components/grid/stores/cache.js
  packages/frontend-core/src/components/grid/stores/datasource.js
  packages/frontend-core/src/constants.js
Labels: firestorm, size/m

#14433 Display relationship header on column picker
  packages/frontend-core/src/components/grid/controls/ColumnsSettingContent.svelte
Labels: firestorm, size/s

#14441 Change Automations CodeEditorModal to update on close
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/CodeEditorModal.svelte
Labels: size/s

#14439 Enrich on squashing
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
Labels: firestorm, size/m

#14459 Feature flagging pick relationship fields
  packages/backend-core/src/features/index.ts
  packages/builder/src/components/backend/DataTable/TableDataTable.svelte
  packages/builder/src/components/backend/DataTable/ViewV2DataTable.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingContent.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/db/linkedRows/index.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/m

#14467 Refactor view usage
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/controllers/row/utils/utils.ts
  packages/server/src/api/controllers/view/views.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/view.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/db/linkedRows/linkUtils.ts
  packages/server/src/db/tests/linkTests.spec.ts
  packages/server/src/middleware/trimViewRowInfo.ts
  packages/server/src/sdk/app/rows/search.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/internal/internal.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
  packages/server/src/websockets/grid.ts
Labels: firestorm, size/m

#14468 Trimming views
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/middleware/trimViewRowInfo.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/sdk/app/views/tests/views.spec.ts
Labels: firestorm, size/xl

#14475 Reduced the Modal z-index to 1001
  packages/bbui/src/Modal/Modal.svelte
Labels: size/xs

#14478 Fix for force password reset
  packages/builder/src/pages/builder/portal/users/users/_components/ForceResetPasswordModal.svelte
Labels: size/s

#14473 Picker only for views
  packages/builder/src/components/backend/DataTable/TableDataTable.svelte
  packages/frontend-core/src/components/grid/controls/ColumnsSettingContent.svelte
  packages/frontend-core/src/components/grid/stores/datasource.js
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/controllers/row/internal.ts
  packages/server/src/api/controllers/row/staticFormula.ts
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/api/controllers/table/index.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/db/linkedRows/index.ts
  packages/server/src/middleware/trimViewRowInfo.ts
  packages/server/src/sdk/app/rows/external.ts
  packages/server/src/sdk/app/rows/internal.ts
  packages/server/src/sdk/app/rows/rows.ts
  packages/server/src/sdk/app/rows/search/external.ts
  packages/server/src/sdk/app/rows/search/internal/internal.ts
  packages/server/src/sdk/app/rows/search/internal/lucene.ts
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/server/src/sdk/app/rows/utils.ts
  packages/server/src/sdk/app/tables/getters.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/sdk/app/views/tests/views.spec.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/types/src/documents/app/table/schema.ts
  packages/types/src/documents/app/view.ts
  packages/types/src/sdk/row.ts
  packages/types/src/sdk/view.ts
Labels: firestorm, size/l

#14487 Pro submodule check issue
  .github/workflows/budibase_ci.yml
Labels: firestorm, size/xs

#14470 The UI should indicate who the account holder is
  packages/backend-core/src/tenancy/db.ts
  packages/bbui/src/Table/SelectEditRenderer.svelte
  packages/bbui/src/Table/Table.svelte
  packages/builder/src/pages/builder/portal/users/users/[userId].svelte
  packages/builder/src/pages/builder/portal/users/users/_components/RoleTableRenderer.svelte
  packages/builder/src/pages/builder/portal/users/users/index.svelte
  packages/builder/src/stores/portal/licensing.js
  packages/builder/src/stores/portal/users.js
  packages/frontend-core/src/api/user.js
  packages/frontend-core/src/constants.js
  packages/worker/src/api/controllers/global/users.ts
  packages/worker/src/api/routes/global/tenant.ts
  packages/worker/src/api/routes/global/tests/users.spec.ts
Labels: size/m

#14491 Make sure setEnrichedUsers is called when tenantOwnerLoaded
  packages/builder/src/pages/builder/portal/users/users/index.svelte
Labels: size/xs
