Repository Budibase/budibase, pull requests merged in 2025-06, with the labels that each got.

#16208 New API Request Step
  packages/backend-core/src/context/mainContext.ts
  packages/bbui/src/DetailSummary/DetailSummary.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/SelectStepSidePanel.svelte
  packages/builder/src/components/automation/AutomationBuilder/StepPanel.svelte
  packages/builder/src/components/automation/SetupPanel/QueryParamSelector.svelte
  packages/builder/src/components/automation/SetupPanel/layouts/APIParamSelector.svelte
  packages/builder/src/components/automation/SetupPanel/layouts/APIRequest.svelte
  packages/builder/src/components/automation/SetupPanel/layouts/index.ts
  packages/builder/src/components/common/bindings/DrawerBindableInput.svelte
  packages/builder/src/constants/backend/automations.ts
  packages/builder/src/pages/builder/app/[application]/settings/embed.svelte
  packages/server/src/api/controllers/row/index.ts
  packages/server/src/api/controllers/row/views.ts
  packages/server/src/automations/actions.ts
  packages/server/src/automations/steps/apiRequest.ts
  packages/server/src/automations/tests/steps/apiRequest.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/automations/tests/utilities/index.ts
  packages/shared-core/src/automations/steps/apiRequest.ts
  packages/shared-core/src/automations/steps/index.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/types/src/documents/app/automation/schema.ts
Labels: size/xl

#16243 Centralise `.env` for worker/server
  package.json
  packages/backend-core/src/environment.ts
  packages/server/nodemon.json
  packages/server/package.json
  packages/server/scripts/dev/manage.js
  packages/server/src/environment.ts
  packages/server/src/utilities/fileSystem/filesystem.ts
  packages/worker/nodemon.json
  packages/worker/package.json
  packages/worker/scripts/account.js
  packages/worker/scripts/localdomain.js
  packages/worker/scripts/multiTenancy.js
  packages/worker/scripts/selfhost.js
  packages/worker/src/environment.ts
  scripts/dev/account.js
  scripts/dev/localdomain.js
  scripts/dev/manage.js
  scripts/dev/multiTenancy.js
  scripts/dev/selfhost.js
Labels: firestorm, size/m

#16244 Allow filtering barcode columns.
  packages/frontend-core/src/components/FilterField.svelte
  packages/server/src/api/routes/tests/search.spec.ts
  packages/shared-core/src/filters.ts
Labels: firestorm, size/s

#16252 Fixing memory issue and "redis" issue
  packages/backend-core/src/events/index.ts
  packages/backend-core/src/events/processors/AnalyticsProcessor.ts
  packages/backend-core/src/events/processors/AuditLogsProcessor.ts
  packages/backend-core/src/events/processors/LoggingProcessor.ts
  packages/backend-core/src/events/processors/Processors.ts
  packages/backend-core/src/events/processors/posthog/PosthogProcessor.ts
  packages/server/src/koa.ts
  packages/types/src/sdk/events/event.ts
  packages/worker/src/index.ts
  packages/worker/src/tests/TestConfiguration.ts
  scripts/build.js
Labels: firestorm, size/s

#16258 Fix broken Dropzone test
  packages/builder/src/components/common/Dropzone.spec.js
Labels: firestorm, size/xs

#16257 Google sheet improvements
  packages/builder/src/components/backend/Datasources/TableImportSelection/index.svelte
  packages/builder/src/components/backend/Datasources/TableImportSelection/tableSelectionStore.ts
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/_components/panels/Tables/Controls.svelte
  packages/server/nodemon.json
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/sdk/app/datasources/plus.ts
  packages/types/src/sdk/datasources.ts
  packages/worker/nodemon.json
Labels: firestorm, size/s

#16268 Add CLAUDE.md
  CLAUDE.md
Labels: firestorm, size/s

#16221 Handle screen conflicts between workspace apps
  packages/builder/src/components/design/ScreenDetailsModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Screen/GeneralPanel.svelte
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/builder/screens.ts
  packages/builder/src/stores/builder/tests/screens.test.js
  packages/builder/src/templates/screenTemplating/blank.ts
  packages/builder/src/templates/screenTemplating/form.ts
  packages/builder/src/templates/screenTemplating/getValidRoute.ts
  packages/builder/src/templates/screenTemplating/pdf.ts
  packages/builder/src/templates/screenTemplating/table/inline.ts
  packages/builder/src/templates/screenTemplating/table/modal.ts
  packages/builder/src/templates/screenTemplating/table/newScreen.ts
  packages/builder/src/templates/screenTemplating/table/sidePanel.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/routing.ts
  packages/server/src/api/controllers/screen.ts
  packages/server/src/appMigrations/migrations/20250514133719_workspace_apps.ts
  packages/server/src/db/views/staticViews.ts
  packages/server/src/sdk/app/screens/index.ts
  packages/server/src/sdk/app/screens/utils.ts
  packages/server/src/sdk/app/workspaceApps/utils.ts
  packages/server/src/utilities/routing/index.ts
  packages/types/src/sdk/db.ts
Labels: firestorm, size/m

#16264 Behaviour when deleting all workspace apps
  packages/builder/src/components/ContextMenu.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/ScreenNavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/WorkspaceAppNavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/index.svelte
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/builder/contextMenu.ts
  packages/builder/src/stores/builder/screens.ts
  packages/builder/src/stores/builder/workspaceApps.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/screen.ts
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/sdk/app/workspaceApps/index.ts
Labels: firestorm, size/s, size/m

#16275 Adding some directions around pull requests to CLAUDE.md
  CLAUDE.md
Labels: firestorm, size/s, size/xs

#16203 Navigation per workspace app
  packages/backend-core/tests/core/utilities/structures/workspaceApp.ts
  packages/builder/src/components/common/Dropzone.spec.js
  packages/builder/src/components/common/NavItem.svelte
  packages/builder/src/components/design/ScreenDetailsModal.svelte
  packages/builder/src/dataBinding.test.js
  packages/builder/src/pages/builder/app/[application]/_components/PreviewOverlay.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Screen/GeneralPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/WorkspaceApp/WorkspaceAppModal.svelte
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/builder/appUrls.ts
  packages/builder/src/stores/builder/deployment.ts
  packages/builder/src/stores/builder/index.ts
  packages/builder/src/stores/builder/navigation.ts
  packages/builder/src/stores/builder/screens.ts
  packages/builder/src/stores/builder/tests/app.test.js
  packages/builder/src/stores/builder/tests/builder.test.js
  packages/builder/src/stores/builder/tests/navigation.test.js
  packages/builder/src/stores/builder/tests/screens.test.js
  packages/builder/src/stores/builder/workspaceApps.ts
  packages/builder/src/templates/screenTemplating/blank.ts
  packages/builder/src/templates/screenTemplating/form.ts
  packages/builder/src/templates/screenTemplating/getValidRoute.ts
  packages/builder/src/templates/screenTemplating/pdf.ts
  packages/builder/src/templates/screenTemplating/table/inline.ts
  packages/builder/src/templates/screenTemplating/table/modal.ts
  packages/builder/src/templates/screenTemplating/table/newScreen.ts
  packages/builder/src/templates/screenTemplating/table/sidePanel.ts
  packages/client/src/components/devtools/DevToolsHeader.svelte
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/routing.ts
  packages/server/src/api/controllers/screen.ts
  packages/server/src/api/controllers/workspaceApp.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/api/routes/workspaceApp.ts
  packages/server/src/appMigrations/migrations/20250514133719_workspace_apps.ts
  packages/server/src/constants/definitions.ts
  packages/server/src/db/views/staticViews.ts
  packages/server/src/sdk/app/navigation/index.ts
  packages/server/src/sdk/app/screens/index.ts
  packages/server/src/sdk/app/screens/screens.ts
  packages/server/src/sdk/app/screens/utils.ts
  packages/server/src/sdk/app/workspaceApps/crud.ts
  packages/server/src/sdk/app/workspaceApps/index.ts
  packages/server/src/sdk/app/workspaceApps/tests/utils.spec.ts
  packages/server/src/sdk/app/workspaceApps/utils.ts
  packages/server/src/utilities/routing/index.ts
  packages/types/src/api/web/app/workspaceApp.ts
  packages/types/src/documents/app/app.ts
  packages/types/src/documents/app/workspaceApp.ts
  packages/types/src/sdk/db.ts
Labels: firestorm, feature-branch, size/l, size/xl

#16281 Ensure flag reverts
  packages/backend-core/tests/core/utilities/structures/workspaceApp.ts
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/WorkspaceApp/WorkspaceAppModal.svelte
  packages/builder/src/stores/builder/navigation.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/workspaceApp.ts
  packages/server/src/api/routes/navigation.ts
  packages/server/src/appMigrations/migrations/20250514133719_workspace_apps.ts
  packages/server/src/sdk/app/navigation/index.ts
  packages/server/src/sdk/app/workspaceApps/crud.ts
  packages/types/src/api/web/app/workspaceApp.ts
  packages/types/src/documents/app/workspaceApp.ts
Labels: firestorm, size/m

#16280 Make sure Google Sheets can handle the columns of the sheet being re-ordered outside of Budibase.
  packages/server/src/integrations/googlesheets.ts
  packages/server/src/integrations/tests/googlesheets.spec.ts
  packages/server/src/integrations/tests/utils/googlesheets.ts
Labels: firestorm, size/m

#16259 Fix timeout errors causing step history to be lost.
  packages/server/src/automations/tests/steps/triggerAutomationRun.spec.ts
  packages/server/src/definitions/automations.ts
  packages/server/src/threads/automation.ts
Labels: size/m

#16274 [BUDI-9382] Fix SSO enforcement preventing bulk user imports
  packages/backend-core/src/users/db.ts
  packages/backend-core/src/users/test/db.spec.ts
  packages/builder/src/stores/portal/users.ts
Labels: firestorm, size/m

#16266 Allow selection of relationship fields in junction tables when using the Create Row automation step.
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
Labels: firestorm, size/s

#16242 Fixes condition checking if a column can be hidden
  packages/client/src/components/app/GridBlock.svelte
  packages/frontend-core/src/components/grid/cells/HeaderCell.svelte
Labels: size/xs

#16315 Set actionsLimit to unlimited for now
  packages/builder/src/stores/portal/licensing.ts
Labels: size/xs

#16316 Support importing workspaces
  packages/backend-core/src/constants/db.ts
  packages/server/src/appMigrations/appMigrationMetadata.ts
  packages/server/src/appMigrations/migrationsProcessor.ts
  packages/server/src/appMigrations/queue.ts
  packages/server/src/sdk/app/applications/import.ts
  packages/server/src/utilities/fileSystem/clientLibrary.ts
  packages/types/src/documents/document.ts
Labels: firestorm, size/s

#16295 16282 expand visible text when resizing panel width
  packages/builder/src/components/common/NavItem.svelte
Labels: size/xs

#16319 Adding some notes about building test cases for Claude
  CLAUDE.md
Labels: firestorm, size/s, size/xs

#16320 Remove TODO comment actionsQuota
  packages/builder/src/stores/portal/licensing.ts
Labels: size/xs

#16318 Consider apps with future migrations as fully migrated, and fix migrations UI
  packages/client/src/components/UpdatingApp.svelte
  packages/client/src/index.ts
  packages/frontend-core/src/components/Updating.svelte
  packages/server/src/api/controllers/migrations.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/appMigrations/index.ts
Labels: size/s

#16204 16080 enhance the navigation settings area and include some more features
  packages/bbui/src/Typography/Heading.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUIDrawer.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUISection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/CustomStylesSection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/EditNavItemPopover.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Navigation/index.svelte
  packages/client/src/components/app/Layout.svelte
  packages/client/src/components/app/Logo.svelte
  packages/client/src/components/app/NavItem.svelte
Labels: size/m

#16321 Support workspaces when using templates
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/routes/tests/templates.spec.ts
Labels: firestorm, size/s

#16327 Apps to workspaces in account
  packages/builder/src/components/usage/index.ts
  packages/worker/src/api/controllers/global/self.ts
Labels: firestorm, size/s

#16330 Fix app creation after some refactors
  packages/builder/src/pages/builder/portal/apps/index.svelte
  packages/builder/src/pages/builder/portal/apps/onboarding/index.svelte
Labels: firestorm, size/s

#16331 Fix importing app
  packages/builder/src/components/start/CreateAppModal.svelte
  packages/frontend-core/src/api/app.ts
Labels: firestorm, size/s

#16333 Allowing admins and builders to access agent chat/history
  packages/server/src/api/routes/ai.ts
  packages/server/src/api/routes/utils/validators/agent.ts
Labels: firestorm, size/xs

#16340 PublishModal empty state improvements
  packages/builder/src/components/deploy/PublishModal.svelte
Labels: firestorm, size/s

#16345 Improvements to Publish Modal design
  packages/bbui/src/Accordion/Accordion.svelte
  packages/builder/src/components/deploy/AppActions.svelte
  packages/builder/src/components/deploy/PublishModal.svelte
Labels: firestorm, size/m

#16344 Internal urls for api calls to account-portal
  charts/budibase/templates/app-service-deployment.yaml
  charts/budibase/templates/automation-worker-service-deployment.yaml
  charts/budibase/templates/worker-service-deployment.yaml
  charts/budibase/values.yaml
  packages/backend-core/src/accounts/accounts.ts
  packages/backend-core/src/environment.ts
  packages/server/src/environment.ts
  packages/worker/src/environment.ts
Labels: size/s

#16347 [BUDI-9220] Allow uploading attachments to anyone with table write permissions, not just creators.
  packages/frontend-core/src/components/grid/cells/AttachmentCell.svelte
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/attachment.ts
Labels: firestorm, size/m

#16350 Fixes on migration processor
  packages/server/src/appMigrations/index.ts
  packages/server/src/appMigrations/migrationsProcessor.ts
  packages/server/src/appMigrations/tests/migrations.spec.ts
  packages/server/src/appMigrations/tests/migrationsProcessor.spec.ts
Labels: firestorm, size/m

#16351 Rename workspace app url
  packages/backend-core/tests/core/utilities/structures/workspaceApp.ts
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/WorkspaceApp/WorkspaceAppModal.svelte
  packages/builder/src/stores/builder/appUrls.ts
  packages/builder/src/stores/builder/workspaceApps.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/workspaceApp.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/workspaceApp.ts
  packages/server/src/appMigrations/migrations.ts
  packages/server/src/appMigrations/migrations/20250514133719_workspace_apps.ts
  packages/server/src/appMigrations/migrations/20250612150000_workspace_apps.ts
  packages/server/src/sdk/app/workspaceApps/tests/utils.spec.ts
  packages/server/src/sdk/app/workspaceApps/utils.ts
  packages/types/src/api/web/app/workspaceApp.ts
  packages/types/src/documents/app/workspaceApp.ts
Labels: firestorm, size/m

#16369 Default to public URL to address typing issue
  packages/backend-core/src/environment.ts
Labels: size/xs

#16323 Set maximum number of active sessions per user to 3 (from 1)
  packages/backend-core/src/security/sessions.ts
  packages/backend-core/src/security/tests/sessions.spec.ts
  packages/builder/src/pages/builder/_layout.svelte
  packages/builder/src/pages/builder/auth/login.svelte
  packages/builder/src/stores/portal/auth.ts
  packages/client/src/components/ClientApp.svelte
  packages/frontend-core/src/api/auth.ts
  packages/frontend-core/src/utils/index.ts
  packages/frontend-core/src/utils/login.ts
  packages/shared-core/src/index.ts
  packages/shared-core/src/login.ts
  packages/worker/src/api/controllers/global/auth.ts
  packages/worker/src/sdk/auth/auth.ts
  packages/worker/src/sdk/auth/tests/auth.spec.ts
Labels: firestorm, size/m

#16363 Add DataDog instrumentation to Google Sheets reads.
  packages/server/src/integrations/googlesheets.ts
Labels: firestorm, size/s

#16342 Agent UI tweaks
  packages/builder/src/components/common/NavHeader.svelte
  packages/builder/src/components/common/NavItem.svelte
  packages/builder/src/components/design/Panel.svelte
  packages/builder/src/pages/builder/app/[application]/agent/index.svelte
  packages/builder/src/stores/portal/agents.ts
Labels: size/l

#16370 Database find function
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/db.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/backend-core/src/users/users.ts
  packages/server/src/sdk/app/rows/attachments.ts
  packages/types/src/sdk/db.ts
Labels: firestorm, size/s

#16373 Don't return any workspace app is flag is not enabled
  packages/server/src/sdk/app/workspaceApps/crud.ts
Labels: size/xs

#16375 Never run disabled migrations
  packages/server/src/appMigrations/migrationsProcessor.ts
  packages/server/src/appMigrations/tests/migrationsProcessor.spec.ts
Labels: firestorm, size/s

#16341 Render apps on builder index
  packages/builder/src/pages/builder/portal/apps/[appId]/index.svelte
  packages/builder/src/stores/portal/apps.ts
  packages/builder/src/types/app.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/sdk/app/applications/applications.ts
  packages/types/src/api/web/app/application.ts
Labels: firestorm, size/s

#16386 Icon fixes
  packages/bbui/src/Icon/IconAvatar.svelte
  packages/bbui/src/Table/Table.svelte
  packages/builder/src/pages/builder/portal/users/groups/[groupId].svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/GroupUsers.svelte
  packages/builder/src/pages/builder/portal/users/users/[userId].svelte
  packages/client/src/components/app/Button.svelte
Labels: size/s

#16392 Removing codemirror whitespace highlighting
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
Labels: firestorm, size/xs

#16372 New machine, new dependencies
  packages/cli/package.json
  packages/server/package.json
  packages/string-templates/package.json
  yarn.lock
Labels: firestorm, size/xs

#16413 Treat citext as string
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/postgres.ts
  packages/server/src/integrations/utils/utils.ts
Labels: size/s

#16415 Typing improvements around query thread events
  packages/backend-core/src/cache/user.ts
  packages/backend-core/src/middleware/tests/builder.spec.ts
  packages/server/src/api/controllers/query/index.ts
  packages/server/src/threads/definitions.ts
  packages/server/src/threads/query.ts
  packages/types/src/sdk/koa.ts
Labels: firestorm, size/s

#16194 Charts on click
  packages/client/manifest.json
  packages/client/src/components/app/charts/AreaChart.svelte
  packages/client/src/components/app/charts/BarChart.svelte
  packages/client/src/components/app/charts/CandleStickChart.svelte
  packages/client/src/components/app/charts/DonutChart.svelte
  packages/client/src/components/app/charts/HistogramChart.svelte
  packages/client/src/components/app/charts/LineChart.svelte
  packages/client/src/components/app/charts/PieChart.svelte
Labels: size/m

#16425 Improves visibility of data labels in charts
  packages/client/src/components/app/charts/BarChart.svelte
  packages/client/src/components/app/charts/HistogramChart.svelte
Labels: size/xs

#16433 Fixing undo/redo
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/builder/screens.ts
  packages/builder/src/stores/builder/tests/screens.test.js
Labels: firestorm, size/s

#16436 Fix: removing misleading error notification
  packages/builder/src/pages/builder/apps/index.svelte
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/routes/tests/application.spec.ts
Labels: firestorm, size/s, size/m

#16440 Fix: migration related issues
  packages/backend-core/src/constants/db.ts
  packages/server/src/appMigrations/migrations/20250618162639_workspace_apps.ts
Labels: firestorm, size/s, size/xs

#16200 Builder nav updates
  packages/bbui/src/ActionMenu/ActionMenu.svelte
  packages/bbui/src/Divider/Divider.svelte
  packages/bbui/src/Modal/Modal.svelte
  packages/builder/src/components/common/TopBar.svelte
  packages/builder/src/pages/builder/app/[application]/_components/SideNav/SideNav.svelte
  packages/builder/src/pages/builder/app/[application]/_components/SideNav/SideNavLink.svelte
  packages/builder/src/pages/builder/app/[application]/_components/SideNav/SideNavUserSettings.svelte
  packages/builder/src/pages/builder/app/[application]/_flagged/layout.new.svelte
  packages/builder/src/pages/builder/app/[application]/_flagged/layout.old.svelte
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/agent/index.svelte
  packages/builder/src/pages/builder/app/[application]/automation/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/automation/index.svelte
  packages/builder/src/pages/builder/app/[application]/data/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/design/index.svelte
  packages/builder/src/pages/builder/app/[application]/settings/general.svelte
  packages/builder/src/pages/builder/portal/_components/UserDropdown.svelte
  packages/builder/src/pages/builder/portal/apps/_components/PortalSideBar.svelte
Labels: feature-branch, size/xl

#16446 Fix TS not liking a missing prop injected by routify
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
Labels: size/s

#16443 Fix issue with creating new screens with polluted databases
  packages/server/src/sdk/app/workspaceApps/crud.ts
Labels: firestorm, size/s, size/xs

#16447 Fix: handle issues with duplicated workspaceapps
  packages/server/src/api/controllers/application.ts
  packages/server/src/sdk/app/workspaceApps/tests/utils.spec.ts
  packages/server/src/sdk/app/workspaceApps/utils.ts
  packages/server/src/utilities/routing/index.ts
Labels: firestorm, size/s

#16434 Allow skipping migration redirects
  packages/server/src/api/routes/application.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/middleware/appMigrations.ts
  packages/server/src/middleware/tests/appMigrations.spec.ts
Labels: firestorm, size/s

#16449 Check for /embed url when matching workspace apps for routing
  packages/server/src/sdk/app/workspaceApps/utils.ts
Labels: size/xs

#16457 Make apps list context menus visible again.
  packages/builder/src/components/start/AppRow.svelte
  packages/builder/src/pages/builder/portal/apps/[appId]/index.svelte
  packages/builder/src/pages/builder/portal/apps/_components/AppNavItem.svelte
Labels: size/xs

#16445 Support for viewing Automation logs with branches.
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/AutomationStepHelpers.ts
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/BranchNode.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItem.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/LogDetailsPanel.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/StepNode.svelte
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/types/automations.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/types/src/documents/app/automation/schema.ts
Labels: firestorm, size/m
