Repository Budibase/budibase, pull requests merged in 2025-09, with the labels that each got.

#16861 Don't include query params if the binding value is empty
  packages/server/src/api/routes/tests/queries/rest.spec.ts
  packages/server/src/integrations/rest.ts
  packages/server/src/integrations/tests/rest.spec.ts
Labels: size/m

#16871 fix: Proxy isn't stripping headers for apps service
  hosting/proxy/nginx.prod.conf
Labels: size/s

#16882 Unify client bundle usage
  packages/backend-core/src/objectStore/objectStore.ts
  packages/builder/src/components/start/ExportAppModal.svelte
  packages/builder/src/pages/builder/workspace/[application]/design/index.svelte
  packages/builder/src/pages/builder/workspace/[application]/settings/general.svelte
  packages/builder/src/stores/portal/admin.test.js
  packages/builder/src/stores/portal/admin.ts
  packages/client/src/stores/environment.ts
  packages/server/package.json
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/tests/component.spec.ts
  packages/server/src/environment.ts
  packages/server/src/utilities/fileSystem/app.ts
  packages/server/src/utilities/fileSystem/clientLibrary.ts
  packages/types/src/api/web/system/environment.ts
  packages/worker/src/api/controllers/system/environment.ts
  packages/worker/src/api/routes/system/tests/environment.spec.ts
  packages/worker/src/environment.ts
Labels: firestorm, size/l, size/m

#16897 adds better icon for closing sidepanel
  packages/client/src/components/app/Layout.svelte
Labels: size/xs

#16911 Fix redirect from apps to workspaces
  hosting/proxy/nginx.prod.conf
Labels: firestorm, size/xs

#16912 fix: update copy app -> workspace
  packages/builder/src/pages/builder/portal/workspaces/onboarding/_components/NamePanel.svelte
  packages/builder/src/pages/builder/portal/workspaces/onboarding/index.svelte
Labels: size/xs

#16913 Revert "fix: update copy app -> workspace"
  packages/builder/src/pages/builder/portal/workspaces/onboarding/_components/NamePanel.svelte
  packages/builder/src/pages/builder/portal/workspaces/onboarding/index.svelte
Labels: size/xs

#16914 Fix wrongly cached 301
  packages/builder/src/pages/builder/workspaces.svelte
Labels: firestorm, size/xs

#16920 Update openapi specs
  .github/workflows/budibase_ci.yml
  packages/server/specs/openapi.json
  packages/server/specs/openapi.yaml
  packages/server/src/definitions/openapi.ts
Labels: firestorm, size/s, size/m

#16939 Revert "Update resolutions for critical dependencies (#16867)"
  package.json
  packages/backend-core/package.json
  packages/cli/package.json
  packages/cli/src/environment.ts
  packages/cli/src/plugins/index.ts
  packages/cli/src/plugins/skeleton.ts
  packages/client/package.json
  packages/server/src/api/routes/public/tests/compare.spec.ts
  packages/server/src/types/jest.d.ts
  packages/upgrade-tests/package.json
  packages/upgrade-tests/src/cli/appImport.ts
  packages/upgrade-tests/src/cli/docker.ts
  packages/worker/package.json
  yarn.lock
Labels: size/s

#16933 Fix nx wrong caching
  .husky/pre-push
  packages/server/package.json
Labels: firestorm, size/xs

#16958 Fix exporting exporting apps from the portal
  packages/builder/src/components/start/AppContextMenuModals.svelte
Labels: firestorm, size/xs

#16878 Dynamic dependency loading
  .prettierignore
  eslint.config.mjs
  packages/backend-core/src/objectStore/buckets/app.ts
  packages/backend-core/src/objectStore/buckets/tests/app.spec.ts
  packages/backend-core/src/objectStore/buckets/tests/clientLibraryPath.spec.ts
  packages/backend-core/src/objectStore/objectStore.ts
  packages/backend-core/src/objectStore/tests/objectExists.spec.ts
  packages/builder/src/components/deploy/VersionModal.svelte
  packages/builder/src/settings/pages/general.svelte
  packages/builder/src/stores/portal/admin.test.js
  packages/builder/src/stores/portal/admin.ts
  packages/client/package.json
  packages/client/scripts/build.mjs
  packages/client/src/build.d.ts
  packages/client/src/components/app/charts/ApexChart.svelte
  packages/client/src/components/app/forms/CodeScanner.svelte
  packages/client/src/dependencies/apexcharts.ts
  packages/client/src/dependencies/html5-qrcode.ts
  packages/client/src/dependencies/window.d.ts
  packages/client/src/stores/app.ts
  packages/client/src/utils/dependencies.ts
  packages/client/tsconfig.json
  packages/client/vite.config.mjs
  packages/server/package.json
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/controllers/static/templates/BudibaseApp.svelte
  packages/server/src/api/controllers/workspace.ts
  packages/server/src/api/routes/static.ts
  packages/server/src/constants/index.ts
  packages/server/src/utilities/fileSystem/clientLibrary.ts
  packages/server/src/utilities/fileSystem/tests/clientLibrary.spec.ts
  packages/types/src/api/web/workspace/workspace.ts
  packages/types/src/client/dependencies.ts
  packages/types/src/client/index.ts
  packages/types/src/index.ts
  packages/types/src/sdk/featureFlag.ts
  packages/types/src/ui/BudibaseApp.ts
  yarn.lock
Labels: firestorm, feature-branch, size/l, size/m, size/xl

#16989 Fix wrong asset path
  packages/server/src/utilities/fileSystem/clientLibrary.ts
Labels: firestorm, size/xs

#17013 Fix importing workspace into existing ones
  packages/backend-core/src/objectStore/objectStore.ts
  packages/bbui/src/Form/Core/Dropzone.svelte
  packages/bbui/src/Form/Dropzone.svelte
  packages/builder/src/components/start/ImportAppModal.svelte
  packages/frontend-core/src/api/app.ts
  packages/server/src/api/controllers/public/workspaces.ts
  packages/server/src/api/controllers/workspace.ts
  packages/server/src/api/routes/tests/workspaceImport.spec.ts
  packages/server/src/api/routes/workspace.ts
  packages/server/src/sdk/workspace/backups/imports.ts
  packages/server/src/sdk/workspace/workspaces/import.ts
  packages/server/src/tests/utilities/objectStore.ts
Labels: firestorm, size/m

#17014 Fix deleting workspaces for builders
  packages/backend-core/src/auth/auth.ts
  packages/backend-core/src/middleware/index.ts
  packages/backend-core/src/middleware/workspaceBuilderOrAdmin.ts
  packages/backend-core/src/users/utils.ts
  packages/server/src/api/controllers/workspace.ts
  packages/server/src/api/routes/public/tests/compare.spec.ts
  packages/server/src/api/routes/tests/workspace.spec.ts
  packages/server/src/utilities/workerRequests.ts
  packages/shared-core/src/sdk/documents/users.ts
  packages/worker/src/api/routes/endpointGroups/standard.ts
  packages/worker/src/api/routes/global/roles.ts
  packages/worker/src/api/routes/global/tests/roles.spec.ts
  packages/worker/src/api/routes/global/tests/users.spec.ts
Labels: firestorm, size/s, size/xs, size/m

#17020 fix link
  packages/builder/src/components/portal/licensing/EnterpriseBasicTrialBanner.svelte
Labels: size/xs

#17030 BUDI-9693 - Quick fix for select fields issue in Create Row automation
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
Labels: size/s

#17027 fix: Always pass conf when running redis-server in singleimage
  hosting/single/redis-runner.sh
Labels: size/s

#17039 Ensure JSON fields are re-rendered when the block id changes.
  packages/builder/src/components/automation/SetupPanel/AutomationSchemaLayout.svelte
Labels: size/s

#17046 Feature/new onboarding
  packages/builder/index.html
  packages/builder/src/helpers/index.ts
  packages/builder/src/helpers/routes.ts
  packages/builder/src/helpers/tests/routes.spec.ts
  packages/builder/src/pages/builder/portal/workspaces/onboarding/_components/ExampleApp.svelte
  packages/builder/src/pages/builder/portal/workspaces/onboarding/_components/NamePanel.svelte
  packages/builder/src/pages/builder/portal/workspaces/onboarding/_components/PanelHeader.svelte
  packages/builder/src/pages/builder/portal/workspaces/onboarding/index.svelte
  packages/builder/src/pages/builder/workspace/[application]/design/[workspaceAppId]/[screenId]/_components/AppPanel.svelte
  packages/server/src/api/controllers/workspace.ts
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/constants/screens.ts
Labels: size/xl

#17050 fix: openapi readme version pin
  packages/server/specs/generate.ts
  packages/server/specs/openapi.json
  packages/server/specs/openapi.yaml
Labels: size/s, size/m
