Repository Budibase/budibase, pull requests merged in 2025-01, with the labels that each got.

#15278 Ignore default values for view sort
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.ts
Labels: firestorm, size/s

#15279 Automation test details fix
  packages/builder/src/stores/builder/automations.ts
Labels: size/xs

#15284 Fix user search
  packages/frontend-core/src/components/grid/cells/BBReferenceCell.svelte
Labels: firestorm, size/xs

#15281 Flags / Layout / Preview stores to TS
  packages/builder/src/stores/builder/flags.js
  packages/builder/src/stores/builder/flags.ts
  packages/builder/src/stores/builder/layouts.ts
  packages/builder/src/stores/builder/preview.js
  packages/builder/src/stores/builder/preview.ts
  packages/types/src/ui/stores/index.ts
  packages/types/src/ui/stores/preview.ts
Labels: firestorm, size/m

#15290 Fix queries when returning nulls
  packages/server/src/threads/query.ts
Labels: firestorm, size/xs

#15291 User and websocket stores converted to typescript
  packages/builder/src/stores/builder/users.js
  packages/builder/src/stores/builder/users.ts
  packages/builder/src/stores/builder/websocket.js
  packages/builder/src/stores/builder/websocket.ts
  packages/frontend-core/src/utils/websocket.ts
  packages/types/src/ui/stores/grid/user.ts
Labels: firestorm, size/m

#15280 Convert portal backups store to TS
  packages/builder/src/stores/portal/backups.js
  packages/builder/src/stores/portal/backups.test.js
  packages/builder/src/stores/portal/backups.ts
Labels: size/s

#15282 Convert portal email store to TS
  packages/builder/src/pages/builder/portal/settings/email/[template].svelte
  packages/builder/src/pages/builder/portal/settings/email/_layout.svelte
  packages/builder/src/stores/portal/email.js
  packages/builder/src/stores/portal/email.ts
Labels: size/s

#15285 Convert portal environment store to TS
  packages/builder/src/pages/builder/portal/settings/environment/_components/EditVariableColumn.svelte
  packages/builder/src/stores/portal/environment.js
  packages/builder/src/stores/portal/environment.ts
Labels: size/m

#15299 Theme / Row actions / Snippers stores converted to typescript.
  packages/builder/src/stores/builder/rowActions.ts
  packages/builder/src/stores/builder/snippets.js
  packages/builder/src/stores/builder/snippets.ts
  packages/builder/src/stores/builder/theme.js
  packages/builder/src/stores/builder/theme.ts
  packages/types/src/documents/app/app.ts
Labels: firestorm, size/m

#15230 Typescript hover + navigation stores
  packages/builder/src/stores/builder/hover.ts
  packages/builder/src/stores/builder/navigation.ts
  packages/types/src/documents/app/app.ts
  packages/types/src/ui/stores/index.ts
  packages/types/src/ui/stores/misc.ts
Labels: firestorm, size/s

#15286 Convert portal feature flags store to TS
  packages/builder/src/stores/portal/auth.ts
  packages/builder/src/stores/portal/featureFlags.js
  packages/builder/src/stores/portal/featureFlags.ts
Labels: size/s

#15292 Convert portal feature store to TS
  packages/builder/src/stores/BudiStore.ts
  packages/builder/src/stores/portal/features.js
  packages/builder/src/stores/portal/features.ts
  packages/types/src/documents/global/config.ts
Labels: size/m

#15312 Offer option to open Budibase via CLI
  packages/cli/package.json
  packages/cli/src/hosting/start.ts
  yarn.lock
Labels: size/xs

#15310 Convert role and published store to TS
  packages/builder/src/stores/builder/published.ts
  packages/builder/src/stores/builder/roles.js
  packages/builder/src/stores/builder/roles.ts
Labels: firestorm, size/m

#15305 Fix triggering automations
  packages/client/src/utils/buttonActions.js
Labels: size/xs

#15294 Convert portal groups store to TS
  packages/builder/src/pages/builder/app/[application]/_components/BuilderSidePanel.svelte
  packages/builder/src/pages/builder/apps/index.svelte
  packages/builder/src/pages/builder/portal/apps/_layout.svelte
  packages/builder/src/pages/builder/portal/users/groups/[groupId].svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/AppAddModal.svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/EditUserPicker.svelte
  packages/builder/src/pages/builder/portal/users/groups/index.svelte
  packages/builder/src/pages/builder/portal/users/users/[userId].svelte
  packages/builder/src/pages/builder/portal/users/users/index.svelte
  packages/builder/src/stores/portal/groups.js
  packages/builder/src/stores/portal/groups.ts
  packages/frontend-core/src/api/groups.ts
Labels: size/m

#15297 Convert portal licensing store to TS
  packages/builder/src/stores/portal/licensing.js
  packages/builder/src/stores/portal/licensing.ts
  packages/types/src/api/web/global/self.ts
  packages/worker/src/api/controllers/global/self.ts
Labels: size/l

#15319 Fix enrich endpoint in client
  packages/client/src/api/patches.js
Labels: size/xs

#15318 Fix issues when fetching view v1 data
  packages/client/src/api/patches.js
  packages/frontend-core/src/fetch/ViewFetch.js
Labels: firestorm, size/s

#15215 Update AWS SDK to V3
  packages/backend-core/__mocks__/@aws-sdk/client-s3.ts
  packages/backend-core/__mocks__/@aws-sdk/s3-request-presigner.ts
  packages/backend-core/__mocks__/aws-sdk.ts
  packages/backend-core/package.json
  packages/backend-core/src/environment.ts
  packages/backend-core/src/objectStore/buckets/app.ts
  packages/backend-core/src/objectStore/buckets/global.ts
  packages/backend-core/src/objectStore/buckets/plugins.ts
  packages/backend-core/src/objectStore/buckets/tests/app.spec.ts
  packages/backend-core/src/objectStore/buckets/tests/global.spec.ts
  packages/backend-core/src/objectStore/buckets/tests/plugins.spec.ts
  packages/backend-core/src/objectStore/objectStore.ts
  packages/backend-core/src/objectStore/utils.ts
  packages/cli/src/backups/objectStore.ts
  packages/server/package.json
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/tests/static.spec.ts
  packages/server/src/automations/tests/createRow.spec.ts
  packages/server/src/integrations/dynamodb.ts
  packages/server/src/integrations/s3.ts
  packages/server/src/integrations/tests/aws-sdk.mock.ts
  packages/server/src/integrations/tests/dynamodb.spec.ts
  packages/server/src/integrations/tests/s3.spec.ts
  packages/server/src/integrations/utils/utils.ts
  packages/server/src/sdk/plugins/plugins.ts
  packages/server/src/utilities/fileSystem/app.ts
  packages/server/src/utilities/fileSystem/plugin.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/worker/src/api/controllers/global/configs.ts
  yarn.lock
Labels: firestorm, size/l

#15322 Fix usage calculations
  packages/builder/src/stores/portal/licensing.ts
Labels: size/xs

#15304 Convert portal menu store to TS
  packages/builder/src/stores/portal/menu.js
  packages/builder/src/stores/portal/menu.ts
Labels: size/m

#15306 Convert portal OIDC store to TS
  packages/builder/src/stores/portal/oidc.js
  packages/builder/src/stores/portal/oidc.ts
  packages/frontend-core/src/api/configs.ts
Labels: size/s

#15332 Fix issue with forms after cleanup
  packages/client/src/utils/schema.js
Labels: firestorm, size/xs

#15336 Explicitly fetch the data from fetch
  packages/client/src/utils/schema.js
  packages/frontend-core/src/fetch/DataFetch.ts
  packages/frontend-core/src/fetch/index.ts
Labels: firestorm, size/s

#15341 Fix close modal on grid+modal generation
  packages/frontend-core/src/utils/utils.js
Labels: firestorm, size/xs

#15331 Typing notification store
  packages/client/src/api/api.ts
  packages/client/src/api/index.js
  packages/client/src/index.d.ts
  packages/client/src/stores/auth.ts
  packages/client/src/stores/derived/currentRole.js
  packages/client/src/stores/notification.ts
  packages/client/src/stores/routes.ts
  packages/frontend-core/src/api/index.ts
  packages/frontend-core/src/api/types.ts
  packages/types/src/api/web/global/self.ts
  packages/types/src/documents/app/screen.ts
Labels: firestorm, size/s

#15338 Typification of util schema
  packages/client/src/sdk.js
  packages/client/src/utils/schema.ts
  packages/frontend-core/src/fetch/CustomFetch.ts
  packages/frontend-core/src/fetch/DataFetch.ts
  packages/frontend-core/src/fetch/FieldFetch.ts
  packages/frontend-core/src/fetch/GroupUserFetch.ts
  packages/frontend-core/src/fetch/JSONArrayFetch.ts
  packages/frontend-core/src/fetch/NestedProviderFetch.ts
  packages/frontend-core/src/fetch/QueryArrayFetch.ts
  packages/frontend-core/src/fetch/QueryFetch.ts
  packages/frontend-core/src/fetch/RelationshipFetch.ts
  packages/frontend-core/src/fetch/TableFetch.ts
  packages/frontend-core/src/fetch/UserFetch.ts
  packages/frontend-core/src/fetch/ViewFetch.ts
  packages/frontend-core/src/fetch/ViewV2Fetch.ts
  packages/frontend-core/src/fetch/index.ts
  packages/frontend-core/src/index.ts
Labels: size/m

#15340 Convert queries store to typescript
  packages/builder/src/stores/builder/queries.js
  packages/builder/src/stores/builder/queries.ts
Labels: firestorm, size/m

#15343 account-portal login v2 feature flag
  packages/types/src/sdk/featureFlag.ts
Labels: size/xs

#15344 Fix wrong conversion for UserFetch
  packages/frontend-core/src/fetch/UserFetch.ts
Labels: firestorm, size/xs

#15327 Convert portal user store to TS
  packages/builder/src/pages/builder/app/[application]/_components/BuilderSidePanel.svelte
  packages/builder/src/pages/builder/portal/apps/index.svelte
  packages/builder/src/pages/builder/portal/users/groups/_components/GroupUsers.svelte
  packages/builder/src/pages/builder/portal/users/users/index.svelte
  packages/builder/src/stores/portal/users.ts
  packages/frontend-core/src/api/user.ts
  packages/types/src/api/web/user.ts
  packages/worker/src/api/controllers/global/users.ts
Labels: size/m

#15169 Only select required columns from sql databases
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/external.ts
  packages/server/src/api/controllers/row/utils/sqlUtils.ts
  packages/server/src/api/controllers/row/utils/tests/sqlUtils.spec.ts
  packages/server/src/integration-test/postgres.spec.ts
  packages/server/src/integrations/tests/sqlAlias.spec.ts
  packages/server/src/integrations/tests/sqlQueryJson/basicFetch.json
  packages/server/src/sdk/app/rows/search/internal/sqs.ts
  packages/server/src/sdk/app/rows/search/internal/test/sqs.spec.ts
Labels: do not merge, firestorm, size/xl

#15354 Typing client api patches overrides
  packages/client/src/api/index.ts
  packages/client/src/api/patches.ts
  packages/client/src/components/Block.svelte
  packages/client/src/components/app/blocks/CardsBlock.svelte
  packages/client/src/components/app/deprecated/TableBlock.svelte
  packages/client/src/utils/blocks.js
  packages/frontend-core/src/api/index.ts
  packages/frontend-core/src/api/self.ts
  packages/frontend-core/src/index.ts
Labels: firestorm, size/s

#15346 Fix query rows step when querying a table containing spaces in the name
  packages/server/src/automations/steps/createRow.ts
  packages/server/src/automations/steps/deleteRow.ts
  packages/server/src/automations/steps/queryRows.ts
  packages/server/src/automations/steps/updateRow.ts
  packages/server/src/automations/tests/queryRows.spec.ts
Labels: firestorm, size/s

#15179 S3Upload UI fixes
  packages/client/manifest.json
  packages/client/src/components/app/forms/S3Upload.svelte
  packages/frontend-core/src/api/attachments.ts
Labels: size/s

#15359 Add dummy action buttons for new panels
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/BindingsPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/StatePanel.svelte
Labels: size/s

#15353 Type client utils
  packages/client/src/components/Component.svelte
  packages/client/src/sdk.js
  packages/client/src/utils/blocks.ts
  packages/client/src/utils/grid.ts
  packages/client/src/utils/linkable.ts
  packages/client/tsconfig.json
  packages/client/vite.config.mjs
Labels: size/s

#15360 Remove DEFAULT_VALUES flag check
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/helpers/utils.js
Labels: firestorm, size/m

#15362 Typing builder helpers
  packages/builder/src/components/common/bindings/SnippetDrawer.svelte
  packages/builder/src/constants/backend/automations.ts
  packages/builder/src/constants/backend/backups.ts
  packages/builder/src/constants/backend/index.ts
  packages/builder/src/constants/index.ts
  packages/builder/src/helpers/duplicate.ts
  packages/builder/src/helpers/featureFlags.ts
  packages/builder/src/helpers/fetchData.ts
  packages/builder/src/helpers/helpers.js
  packages/builder/src/helpers/helpers.ts
  packages/builder/src/helpers/index.ts
  packages/builder/src/helpers/keyUtils.js
  packages/builder/src/helpers/keyUtils.ts
  packages/builder/src/helpers/pagination.ts
  packages/builder/src/helpers/planTitle.ts
  packages/builder/src/helpers/sanitizeUrl.ts
  packages/builder/src/helpers/tests/duplicate.test.ts
  packages/builder/src/helpers/tests/nameHelpers.spec.ts
  packages/builder/src/helpers/utils.js
  packages/builder/src/helpers/utils.ts
  packages/builder/src/helpers/warnings.ts
  packages/builder/src/stores/builder/rowActions.ts
Labels: size/m

#15364 Re-add tests files in backend-core/dist
  packages/backend-core/package.json
  packages/backend-core/tsconfig.test.json
Labels: firestorm, size/s

#15330 Convert views and published stores to TS
  packages/builder/src/stores/builder/permissions.js
  packages/builder/src/stores/builder/permissions.ts
  packages/builder/src/stores/builder/views.js
  packages/builder/src/stores/builder/views.ts
Labels: firestorm, size/m

#15358 Add tests to ensure date sorting works, and you can't bulk import dates in an invalid format.
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/utilities/schema.ts
Labels: firestorm, size/m

#15363 Type fetch data usages
  packages/client/src/components/app/DataProvider.svelte
  packages/client/src/constants.ts
  packages/client/src/index.ts
  packages/client/src/stores/components.js
  packages/frontend-core/src/components/grid/stores/datasource.ts
  packages/frontend-core/src/components/grid/stores/datasources/table.ts
  packages/frontend-core/src/components/grid/stores/datasources/viewV2.ts
  packages/frontend-core/src/components/grid/stores/rows.ts
  packages/frontend-core/src/fetch/CustomFetch.ts
  packages/frontend-core/src/fetch/DataFetch.ts
  packages/frontend-core/src/fetch/FieldFetch.ts
  packages/frontend-core/src/fetch/GroupUserFetch.ts
  packages/frontend-core/src/fetch/JSONArrayFetch.ts
  packages/frontend-core/src/fetch/NestedProviderFetch.ts
  packages/frontend-core/src/fetch/QueryArrayFetch.ts
  packages/frontend-core/src/fetch/QueryFetch.ts
  packages/frontend-core/src/fetch/RelationshipFetch.ts
  packages/frontend-core/src/fetch/TableFetch.ts
  packages/frontend-core/src/fetch/UserFetch.ts
  packages/frontend-core/src/fetch/ViewFetch.ts
  packages/frontend-core/src/fetch/ViewV2Fetch.ts
  packages/frontend-core/src/fetch/index.ts
  packages/frontend-core/src/index.ts
  packages/types/src/ui/dataFetch/datasources.ts
  packages/types/src/ui/dataFetch/index.ts
  packages/types/src/ui/index.ts
  packages/types/src/ui/stores/grid/datasource.ts
  packages/types/src/ui/stores/grid/table.ts
Labels: firestorm, size/l

#15378 Convert curl.spec.js and openapi2.spec.js to TypeScript
  packages/server/src/api/controllers/query/import/sources/tests/curl/curl.spec.ts
  packages/server/src/api/controllers/query/import/sources/tests/openapi2/openapi2.spec.js
  packages/server/src/api/controllers/query/import/sources/tests/openapi2/openapi2.spec.ts
Labels: firestorm, size/m

#15375 Convert last few .js files in backend-core to .ts
  packages/backend-core/src/db/couch/connections.ts
  packages/backend-core/src/db/tests/pouch.spec.ts
  packages/backend-core/tests/core/users/users.spec.ts
Labels: firestorm, size/s

#15372 `BindingPanel` typing improvements
  packages/bbui/src/Icon/Icon.svelte
  packages/bbui/src/Label/Label.svelte
  packages/bbui/src/helpers.d.ts
  packages/builder/package.json
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/CodeEditor/index.ts
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/EvaluationSidePanel.svelte
  packages/frontend-core/src/utils/index.ts
  packages/frontend-core/src/utils/jsonFormatter.ts
  packages/frontend-core/src/utils/utils.js
  packages/types/src/core/common.ts
  packages/types/src/core/index.ts
  packages/types/src/ui/bindings/binding.ts
  packages/types/src/ui/bindings/helper.ts
  packages/types/src/ui/bindings/index.ts
  packages/types/src/ui/components/codeEditor.ts
  packages/types/src/ui/components/index.ts
  packages/types/src/ui/components/sidepanel.ts
  packages/types/src/ui/index.ts
  yarn.lock
Labels: firestorm, size/l

#15388 Fix AI column licensing in UI
  packages/builder/src/components/automation/SetupPanel/CronBuilder.svelte
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/[viewId]/index.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/index.svelte
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
  packages/builder/src/pages/builder/portal/settings/index.svelte
Labels: size/s

#15390 Add side nav tabs for bindings and state
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/LeftPanel.svelte
Labels: size/s

#15382 Convert viewBuilder.spec.js to ts
  packages/server/src/api/controllers/view/tests/__snapshots__/viewBuilder.spec.js.snap
  packages/server/src/api/controllers/view/tests/viewBuilder.spec.js
  packages/server/src/api/controllers/view/tests/viewBuilder.spec.ts
  packages/server/src/api/controllers/view/viewBuilder.ts
  packages/types/src/documents/app/view.ts
Labels: size/m

#15384 Typing some components and returning 404 for views not found
  packages/bbui/src/Icon/Icon.svelte
  packages/bbui/src/Tooltip/AbsTooltip.svelte
  packages/client/src/components/app/DataProvider.svelte
  packages/client/src/components/app/blocks/form/FormBlock.svelte
  packages/client/src/components/error-states/ComponentErrorState.svelte
  packages/client/src/context.d.ts
  packages/client/src/index.ts
  packages/client/src/utils/schema.ts
  packages/server/src/api/controllers/view/viewsV2.ts
  packages/server/src/sdk/app/views/external.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/sdk/app/views/internal.ts
Labels: size/m

#15383 Extract automation step definitions out into shared-core.
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/actions.ts
  packages/server/src/automations/steps/bash.ts
  packages/server/src/automations/steps/collect.ts
  packages/server/src/automations/steps/createRow.ts
  packages/server/src/automations/steps/delay.ts
  packages/server/src/automations/steps/deleteRow.ts
  packages/server/src/automations/steps/discord.ts
  packages/server/src/automations/steps/executeQuery.ts
  packages/server/src/automations/steps/executeScript.ts
  packages/server/src/automations/steps/filter.ts
  packages/server/src/automations/steps/make.ts
  packages/server/src/automations/steps/n8n.ts
  packages/server/src/automations/steps/openai.ts
  packages/server/src/automations/steps/outgoingWebhook.ts
  packages/server/src/automations/steps/queryRows.ts
  packages/server/src/automations/steps/sendSmtpEmail.ts
  packages/server/src/automations/steps/serverLog.ts
  packages/server/src/automations/steps/slack.ts
  packages/server/src/automations/steps/triggerAutomationRun.ts
  packages/server/src/automations/steps/updateRow.ts
  packages/server/src/automations/steps/zapier.ts
  packages/server/src/automations/tests/filter.spec.ts
  packages/server/src/automations/tests/scenarios/scenarios.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/shared-core/src/automations/index.ts
  packages/shared-core/src/automations/steps/bash.ts
  packages/shared-core/src/automations/steps/branch.ts
  packages/shared-core/src/automations/steps/collect.ts
  packages/shared-core/src/automations/steps/createRow.ts
  packages/shared-core/src/automations/steps/delay.ts
  packages/shared-core/src/automations/steps/deleteRow.ts
  packages/shared-core/src/automations/steps/discord.ts
  packages/shared-core/src/automations/steps/executeQuery.ts
  packages/shared-core/src/automations/steps/executeScript.ts
  packages/shared-core/src/automations/steps/filter.ts
  packages/shared-core/src/automations/steps/index.ts
  packages/shared-core/src/automations/steps/loop.ts
  packages/shared-core/src/automations/steps/make.ts
  packages/shared-core/src/automations/steps/n8n.ts
  packages/shared-core/src/automations/steps/openai.ts
  packages/shared-core/src/automations/steps/outgoingWebhook.ts
  packages/shared-core/src/automations/steps/queryRows.ts
  packages/shared-core/src/automations/steps/sendSmtpEmail.ts
  packages/shared-core/src/automations/steps/serverLog.ts
  packages/shared-core/src/automations/steps/slack.ts
  packages/shared-core/src/automations/steps/triggerAutomationRun.ts
  packages/shared-core/src/automations/steps/updateRow.ts
  packages/shared-core/src/automations/steps/zapier.ts
  packages/shared-core/src/index.ts
Labels: firestorm, size/xl

#15406 login platform user after forced password reset
  packages/builder/src/pages/builder/auth/reset.svelte
  packages/builder/src/stores/portal/auth.ts
Labels: size/s

#15404 Redirect to account page for account password reset
  packages/builder/src/pages/builder/apps/index.svelte
  packages/builder/src/pages/builder/portal/_components/UserDropdown.svelte
Labels: size/s

#15413 Aligning the way that tableselector and datasourceselector display
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceCategory.svelte
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
  packages/builder/src/components/design/settings/controls/TableSelect.svelte
  packages/builder/src/helpers/data/format.js
Labels: firestorm, size/m

#15407 Improve typing around automations and automation testing
  packages/server/src/api/controllers/automation.ts
  packages/server/src/automations/steps/createRow.ts
  packages/server/src/automations/steps/deleteRow.ts
  packages/server/src/automations/steps/executeQuery.ts
  packages/server/src/automations/steps/executeScript.ts
  packages/server/src/automations/steps/updateRow.ts
  packages/server/src/automations/steps/utils.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/tests/utilities/api/automation.ts
  packages/server/src/threads/automation.ts
  packages/server/src/utilities/index.ts
  packages/server/src/utilities/redis.ts
  packages/types/src/api/web/app/automation.ts
  packages/types/src/documents/app/automation/automation.ts
Labels: firestorm, size/m

#15422 Fix an issue that broke creating new table screen modal
  packages/builder/src/helpers/data/format.js
Labels: firestorm, size/xs

#15356 Convert remaining portal stores to TS
  packages/builder/src/components/portal/licensing/LicensingOverlays.svelte
  packages/builder/src/components/portal/licensing/licensingBanners.js
  packages/builder/src/pages/builder/_layout.svelte
  packages/builder/src/stores/portal/admin.test.js
  packages/builder/src/stores/portal/admin.ts
  packages/builder/src/stores/portal/auditLogs.ts
  packages/builder/src/stores/portal/index.ts
  packages/builder/src/stores/portal/navigation.ts
  packages/builder/src/stores/portal/templates.js
  packages/builder/src/stores/portal/templates.ts
  packages/builder/src/stores/portal/temporal.js
  packages/builder/src/stores/portal/temporal.ts
  packages/builder/src/stores/portal/theme.js
  packages/builder/src/stores/portal/theme.ts
Labels: size/m

#15414 Validate datasource setting on components
  eslint-local-rules/index.js
  packages/builder/src/helpers/screen.ts
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPreview.svelte
  packages/builder/src/stores/builder/index.js
  packages/builder/src/stores/builder/screenComponent.ts
  packages/client/src/components/Component.svelte
  packages/client/src/components/error-states/ComponentErrorState.svelte
  packages/client/src/index.js
  packages/client/src/stores/builder.js
  packages/client/src/stores/screens.js
  packages/server/nodemon.json
  packages/server/src/api/controllers/static/templates/preview.hbs
Labels: do not merge, firestorm, size/m

#15430 Fix datasource picker selected option
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceCategory.svelte
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
Labels: firestorm, size/s

#15403 Bindings explorer panel
  packages/bbui/package.json
  packages/bbui/src/Actions/click_outside.ts
  packages/bbui/src/Actions/position_dropdown.js
  packages/bbui/src/Icon/Icon.svelte
  packages/bbui/src/Link/Link.svelte
  packages/bbui/src/Popover/Popover.svelte
  packages/bbui/src/Tooltip/AbsTooltip.svelte
  packages/bbui/src/constants.ts
  packages/bbui/src/index.ts
  packages/bbui/tsconfig.json
  packages/builder/package.json
  packages/builder/src/components/common/DetailPopover.svelte
  packages/builder/src/components/common/JSONViewer.svelte
  packages/builder/src/components/common/UpdateAppTopNav.svelte
  packages/builder/src/components/portal/onboarding/TourPopover.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/BindingsPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentKeyHandler.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/LeftPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/StatePanel.svelte
  packages/builder/src/pages/builder/portal/settings/ai/AISettings.spec.js
  yarn.lock
Labels: feature-branch, size/l

#15432 Fix selecting 'old row' in row updated trigger.
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
Labels: firestorm, size/xs

#15434 Add feature flag for datasource setting checks
  packages/builder/src/helpers/index.ts
  packages/builder/src/stores/builder/screenComponent.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/xs

#15433 Validate datasource setting on tables
  packages/builder/src/helpers/screen.ts
  packages/builder/src/stores/builder/screenComponent.ts
  packages/client/src/components/error-states/ComponentErrorState.svelte
  packages/types/src/ui/datasource.ts
  packages/types/src/ui/index.ts
Labels: firestorm, size/m

#15431 Improving design section JS binding performance
  packages/string-templates/package.json
  packages/string-templates/src/index.ts
  packages/string-templates/test/javascript.spec.ts
  yarn.lock
Labels: firestorm, size/s

#15439 Validate screen relationship datasource settings
  packages/builder/src/components/design/settings/controls/DataSourceSelect/DataSourceSelect.svelte
  packages/builder/src/helpers/bindings.ts
  packages/builder/src/helpers/index.ts
  packages/builder/src/stores/builder/screenComponent.ts
  packages/types/src/ui/bindings/binding.ts
  packages/types/src/ui/datasource.ts
Labels: firestorm, size/m

#15440 Validate screen field datasource settings
  packages/builder/src/stores/builder/screenComponent.ts
  packages/types/src/ui/datasource.ts
Labels: firestorm, size/xs

#15441 Validate screen json array datasource settings
  packages/builder/src/stores/builder/screenComponent.ts
  packages/types/src/ui/datasource.ts
Labels: size/xs

#15313 Screen store TS conversion
  packages/builder/src/stores/builder/componentTreeNodes.ts
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/index.js
  packages/builder/src/stores/builder/screenComponent.ts
  packages/builder/src/stores/builder/screens.ts
  packages/builder/src/stores/builder/tests/screens.test.js
  packages/builder/src/stores/builder/websocket.ts
  packages/frontend-core/src/utils/utils.js
Labels: size/l

#15447 Type Checkbox.svelte, CheckboxGroup.svelte, and Combobox.svelte.
  packages/bbui/src/Actions/position_dropdown.ts
  packages/bbui/src/Form/Core/Checkbox.svelte
  packages/bbui/src/Form/Core/CheckboxGroup.svelte
  packages/bbui/src/Form/Core/Combobox.svelte
  packages/bbui/src/Popover/Popover.svelte
Labels: firestorm, size/m

#15448 Fix applying styles to Popover.
  packages/bbui/src/Actions/position_dropdown.ts
Labels: firestorm, size/xs

#15454 Fix adding component after undo
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/history.js
  packages/builder/src/stores/builder/screens.ts
Labels: firestorm, size/s

#15453 Do a typing pass on automation.spec.ts
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/api/routes/tests/utilities/TestFunctions.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/automation.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/structures.ts
  packages/types/src/api/web/app/automation.ts
Labels: firestorm, size/l

#15435 JS Console log UX improvements
  packages/builder/src/components/common/bindings/EvaluationSidePanel.svelte
Labels: firestorm, size/s

#15365 State explorer panel
  packages/bbui/src/Form/Core/Combobox.svelte
  packages/bbui/src/Form/Core/Picker.svelte
  packages/bbui/src/Form/Core/Search.svelte
  packages/bbui/src/Form/Core/Select.svelte
  packages/bbui/src/Form/Core/TextField.svelte
  packages/bbui/src/Form/Field.svelte
  packages/bbui/src/Form/Input.svelte
  packages/bbui/src/Form/Select.svelte
  packages/bbui/src/StatusLight/StatusLight.svelte
  packages/builder/src/components/common/bindings/DrawerBindableInput.svelte
  packages/builder/src/components/design/settings/controls/PropertyControl.svelte
  packages/builder/src/dataBinding.js
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUISection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/CustomStylesSection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/LeftPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/StatePanel.svelte
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/preview.ts
  packages/client/src/index.js
  packages/types/src/documents/app/screen.ts
Labels: firestorm, feature-branch, size/l

#15408 Convert history store
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/stores/builder/componentTreeNodes.ts
  packages/builder/src/stores/builder/history.ts
  packages/builder/src/stores/builder/screens.ts
  packages/frontend-core/src/utils/utils.ts
Labels: size/m

#15460 Fix isolatedvm query issues
  .prettierignore
  packages/server/src/api/routes/tests/queries/mongodb.spec.ts
  packages/server/src/jsRunner/bundles/bson-polyfills.ivm.bundle.js
  packages/server/src/jsRunner/bundles/index.ts
  packages/server/src/jsRunner/bundles/snippets.ts
  packages/server/src/jsRunner/vm/isolated-vm.ts
  packages/string-templates/package.json
Labels: firestorm, size/m

#15465 Avoid duplicated names on creating components
  packages/builder/src/helpers/duplicate.ts
  packages/builder/src/helpers/tests/duplicate.test.ts
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/index.js
  packages/builder/src/stores/builder/screenComponent.ts
Labels: firestorm, size/s

#15469 Validate custom components
  eslint-local-rules/index.js
  packages/builder/src/helpers/screen.ts
  packages/builder/src/stores/builder/screenComponent.ts
Labels: size/m

#15458 Adds handling for more delimiters when importing .CSVs
  packages/server/src/utilities/csv.ts
  packages/server/src/utilities/tests/csv.spec.ts
Labels: size/s

#15472 clear results context on every run
  packages/server/src/jsRunner/tests/isolatedVM.spec.ts
  packages/server/src/jsRunner/vm/isolated-vm.ts
Labels: size/s
