Repository Budibase/budibase, pull requests merged in 2025-02, with the labels that each got.

#15464 Fixes to address state usage misses
  packages/builder/src/components/design/settings/controls/PropertyControl.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUIDrawer.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUISection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/CustomStylesSection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Screen/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/StatePanel.svelte
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/index.js
  packages/builder/src/stores/builder/screenComponent.ts
  packages/types/src/documents/app/component.ts
  packages/types/src/documents/app/screen.ts
Labels: firestorm, size/m

#15426 State and bindings panels
  packages/bbui/package.json
  packages/bbui/src/Actions/click_outside.ts
  packages/bbui/src/Actions/position_dropdown.ts
  packages/bbui/src/Form/Core/Combobox.svelte
  packages/bbui/src/Form/Core/Picker.svelte
  packages/bbui/src/Form/Core/Search.svelte
  packages/bbui/src/Form/Core/Select.svelte
  packages/bbui/src/Form/Core/TextField.svelte
  packages/bbui/src/Form/Field.svelte
  packages/bbui/src/Form/Input.svelte
  packages/bbui/src/Form/Select.svelte
  packages/bbui/src/Icon/Icon.svelte
  packages/bbui/src/Link/Link.svelte
  packages/bbui/src/Popover/Popover.svelte
  packages/bbui/src/Popover/Popover.svench
  packages/bbui/src/StatusLight/StatusLight.svelte
  packages/bbui/src/Tooltip/AbsTooltip.svelte
  packages/bbui/src/constants.ts
  packages/bbui/src/index.ts
  packages/bbui/tsconfig.json
  packages/builder/package.json
  packages/builder/src/components/common/DetailPopover.svelte
  packages/builder/src/components/common/JSONViewer.svelte
  packages/builder/src/components/common/UpdateAppTopNav.svelte
  packages/builder/src/components/common/bindings/DrawerBindableInput.svelte
  packages/builder/src/components/design/settings/controls/PropertyControl.svelte
  packages/builder/src/components/portal/onboarding/TourPopover.svelte
  packages/builder/src/dataBinding.js
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUIDrawer.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUISection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/CustomStylesSection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Screen/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/BindingsPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentKeyHandler.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/LeftPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/StatePanel.svelte
  packages/builder/src/pages/builder/portal/settings/ai/AISettings.spec.js
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/index.js
  packages/builder/src/stores/builder/preview.ts
  packages/builder/src/stores/builder/screenComponent.ts
  packages/client/src/constants.ts
  packages/client/src/index.js
  packages/client/src/stores/components.js
  packages/client/src/stores/screens.js
  packages/types/src/documents/app/component.ts
  packages/types/src/documents/app/screen.ts
  yarn.lock
Labels: feature-branch, size/xl

#15457 Table column "format" setting
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/GridColumnConfiguration.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/PrimaryColumnFieldSetting.svelte
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/getColumns.js
  packages/builder/src/components/design/settings/controls/PropertyControl.svelte
  packages/client/manifest.json
  packages/client/src/components/app/GridBlock.svelte
  packages/frontend-core/src/components/grid/cells/DataCell.svelte
  packages/frontend-core/src/components/grid/lib/renderers.ts
  packages/frontend-core/src/components/grid/stores/columns.ts
  packages/frontend-core/src/components/grid/stores/rows.ts
  packages/types/src/ui/stores/grid/columns.ts
  packages/types/src/ui/stores/grid/table.ts
Labels: feature-branch, size/m

#15445 Extract componenterrors from client
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/StatePanel.svelte
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/screenComponent.ts
  packages/builder/src/stores/builder/screens.ts
  packages/client/src/components/Component.svelte
  packages/client/src/components/devtools/DevToolsComponentSettingsTab.svelte
  packages/client/src/components/error-states/ComponentErrorState.svelte
  packages/client/src/components/error-states/ComponentErrorStateCTA.svelte
  packages/client/src/components/error-states/MissingRequiredAncestor.svelte
  packages/client/src/components/error-states/MissingRequiredSetting.svelte
  packages/client/src/index.ts
  packages/client/src/utils/componentProps.js
  packages/frontend-core/src/utils/components.ts
  packages/frontend-core/src/utils/index.ts
  packages/types/src/sdk/featureFlag.ts
  packages/types/src/ui/components/errors.ts
  packages/types/src/ui/components/index.ts
Labels: size/l

#15481 Picker bug fix
  packages/bbui/src/Form/Core/Picker.svelte
  packages/bbui/src/Form/Core/Select.svelte
Labels: firestorm, size/s

#15478 Modernise automation step tests.
  packages/backend-core/tests/core/utilities/mocks/licenses.ts
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/automations/tests/automation.spec.ts
  packages/server/src/automations/tests/branching.spec.ts
  packages/server/src/automations/tests/delay.spec.ts
  packages/server/src/automations/tests/discord.spec.ts
  packages/server/src/automations/tests/filter.spec.ts
  packages/server/src/automations/tests/loop.spec.ts
  packages/server/src/automations/tests/make.spec.ts
  packages/server/src/automations/tests/n8n.spec.ts
  packages/server/src/automations/tests/openai.spec.ts
  packages/server/src/automations/tests/outgoingWebhook.spec.ts
  packages/server/src/automations/tests/scenarios.spec.ts
  packages/server/src/automations/tests/serverLog.spec.ts
  packages/server/src/automations/tests/steps/bash.spec.ts
  packages/server/src/automations/tests/steps/createRow.spec.ts
  packages/server/src/automations/tests/steps/cron-automations.spec.ts
  packages/server/src/automations/tests/steps/delay.spec.ts
  packages/server/src/automations/tests/steps/deleteRow.spec.ts
  packages/server/src/automations/tests/steps/discord.spec.ts
  packages/server/src/automations/tests/steps/executeQuery.spec.ts
  packages/server/src/automations/tests/steps/executeScript.spec.ts
  packages/server/src/automations/tests/steps/filter.spec.ts
  packages/server/src/automations/tests/steps/loop.spec.ts
  packages/server/src/automations/tests/steps/make.spec.ts
  packages/server/src/automations/tests/steps/n8n.spec.ts
  packages/server/src/automations/tests/steps/openai.spec.ts
  packages/server/src/automations/tests/steps/outgoingWebhook.spec.ts
  packages/server/src/automations/tests/steps/queryRows.spec.ts
  packages/server/src/automations/tests/steps/sendSmtpEmail.spec.ts
  packages/server/src/automations/tests/steps/serverLog.spec.ts
  packages/server/src/automations/tests/steps/triggerAutomationRun.spec.ts
  packages/server/src/automations/tests/steps/updateRow.spec.ts
  packages/server/src/automations/tests/steps/zapier.spec.ts
  packages/server/src/automations/tests/triggerAutomationRun.spec.ts
  packages/server/src/automations/tests/triggers/webhook.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/automations/tests/zapier.spec.ts
  packages/server/src/tests/utilities/mocks/openai.ts
  packages/server/src/tests/utilities/structures.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
Labels: firestorm, size/xl

#15483 Detect iframe clicks via loss of focus
  packages/bbui/src/Actions/click_outside.ts
Labels: size/s

#15489 Fix searching for a date on a string field.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/routes/tests/search.spec.ts
Labels: firestorm, size/xs

#15488 Create an automation cron trigger test.
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/server/src/automations/bullboard.ts
  packages/server/src/automations/index.ts
  packages/server/src/automations/tests/triggers/cron.spec.ts
  packages/server/src/automations/utils.ts
  packages/server/src/tests/utilities/api/application.ts
Labels: firestorm, size/m

#15491 Flesh out Google Sheets errors in testing to try and find a flake.
  packages/server/src/integrations/tests/utils/googlesheets.ts
Labels: size/s

#15494 Refactor automation builder.
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/tests/branching.spec.ts
  packages/server/src/automations/tests/scenarios.spec.ts
  packages/server/src/automations/tests/steps/bash.spec.ts
  packages/server/src/automations/tests/steps/createRow.spec.ts
  packages/server/src/automations/tests/steps/cron-automations.spec.ts
  packages/server/src/automations/tests/steps/delay.spec.ts
  packages/server/src/automations/tests/steps/deleteRow.spec.ts
  packages/server/src/automations/tests/steps/discord.spec.ts
  packages/server/src/automations/tests/steps/executeScript.spec.ts
  packages/server/src/automations/tests/steps/filter.spec.ts
  packages/server/src/automations/tests/steps/loop.spec.ts
  packages/server/src/automations/tests/steps/make.spec.ts
  packages/server/src/automations/tests/steps/n8n.spec.ts
  packages/server/src/automations/tests/steps/openai.spec.ts
  packages/server/src/automations/tests/steps/outgoingWebhook.spec.ts
  packages/server/src/automations/tests/steps/queryRows.spec.ts
  packages/server/src/automations/tests/steps/serverLog.spec.ts
  packages/server/src/automations/tests/steps/triggerAutomationRun.spec.ts
  packages/server/src/automations/tests/steps/updateRow.spec.ts
  packages/server/src/automations/tests/steps/zapier.spec.ts
  packages/server/src/automations/tests/triggers/cron.spec.ts
  packages/server/src/automations/tests/triggers/webhook.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/types/src/documents/app/automation/schema.ts
Labels: firestorm, size/l

#15471 replaces broken link
  README.md
Labels: size/s

#15499 Data section resource deletion warning
  packages/backend-core/src/docIds/params.ts
  packages/bbui/src/Form/Core/TextField.svelte
  packages/builder/src/components/backend/DatasourceNavigator/DatasourceNavItem/DatasourceNavItem.svelte
  packages/builder/src/components/backend/DatasourceNavigator/DatasourceNavItem/DeleteConfirmationModal.svelte
  packages/builder/src/components/backend/DatasourceNavigator/QueryNavItem.svelte
  packages/builder/src/components/backend/TableNavigator/TableNavItem/DeleteConfirmationModal.svelte
  packages/builder/src/components/backend/TableNavigator/TableNavItem/TableNavItem.svelte
  packages/builder/src/components/backend/modals/DeleteDataConfirmationModal.svelte
  packages/builder/src/components/common/ConfirmDialog.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/_components/DeleteViewModal.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/_components/ViewNavBar.svelte
  packages/builder/src/stores/builder/screens.ts
  packages/frontend-core/src/api/screens.ts
  packages/server/src/api/controllers/screen.ts
  packages/server/src/api/routes/screen.ts
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/constants/screens.ts
  packages/server/src/sdk/app/common/index.ts
  packages/server/src/sdk/app/common/utils.ts
  packages/server/src/sdk/app/screens/index.ts
  packages/server/src/sdk/app/screens/screens.ts
  packages/server/src/sdk/app/tables/utils.ts
  packages/server/src/sdk/app/views/index.ts
  packages/server/src/sdk/index.ts
  packages/server/src/tests/utilities/api/screen.ts
  packages/server/src/tests/utilities/structures.ts
  packages/shared-core/src/sdk/documents/index.ts
  packages/shared-core/src/sdk/documents/screens.ts
  packages/types/src/api/web/app/screen.ts
  packages/types/src/documents/app/datasource.ts
  packages/types/src/ui/common.ts
  packages/types/src/ui/index.ts
Labels: firestorm, size/xl

#15505 Disabling grid cell formatting
  packages/client/manifest.json
  packages/client/src/components/app/GridBlock.svelte
Labels: firestorm, size/s

#15487 Show screens that are linked to the selected query
  packages/bbui/src/ActionButton/ActionButton.svelte
  packages/bbui/src/List/ListItem.svelte
  packages/builder/src/components/backend/DataTable/buttons/grid/GridScreensButton.svelte
  packages/builder/src/components/common/ScreensPopover.svelte
  packages/builder/src/components/integration/ConnectedQueryScreens.svelte
  packages/builder/src/components/integration/QueryViewer.svelte
  packages/builder/src/components/integration/RestQueryViewer.svelte
Labels: size/m

#15477 Design errors popover
  packages/bbui/src/Divider/Divider.svelte
  packages/bbui/src/Link/Link.svelte
  packages/builder/src/components/common/Icons/CircleIndicator.svelte
  packages/builder/src/components/design/settings/controls/PropertyControl.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPreview.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenErrorsButton.svelte
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/index.js
  packages/builder/src/stores/builder/screenComponent.ts
  packages/types/src/ui/components/errors.ts
  packages/types/src/ui/components/index.ts
Labels: firestorm, feature-branch, size/l

#15512 Create tests for the row saved trigger.
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/automations/tests/triggers/cron.spec.ts
  packages/server/src/automations/tests/triggers/rowSaved.spec.ts
  packages/server/src/automations/tests/utilities/index.ts
  packages/server/src/tests/utilities/api/application.ts
Labels: firestorm, size/m

#15513 Allow multiple tenant users to be created for account holders
  packages/backend-core/src/users/db.ts
  packages/types/src/sdk/user.ts
Labels: size/xs

#15515 Add tests for the row updated trigger.
  packages/server/src/automations/tests/triggers/rowUpdated.spec.ts
Labels: firestorm, size/s

#15517 Fix clickoutside on firefox
  packages/bbui/src/Actions/click_outside.ts
Labels: firestorm, size/xs

#15516 Remove runStep from the codebase.
  packages/server/src/automations/tests/steps/executeQuery.spec.ts
  packages/server/src/automations/tests/steps/sendSmtpEmail.spec.ts
  packages/server/src/automations/tests/utilities/index.ts
Labels: firestorm, size/m

#15538 update testimonial for rebranded client
  packages/frontend-core/assets/covanta.png
  packages/frontend-core/assets/reworld.png
  packages/frontend-core/src/components/Testimonial.svelte
Labels: size/xs

#15533 Fix plugin loading in production apps
  package.json
  packages/frontend-core/src/components/ClientAppSkeleton.svelte
  packages/server/jest.config.ts
  packages/server/package.json
  packages/server/scripts/svelteTransformer.js
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/controllers/static/templates/BudibaseApp.svelte
  packages/server/svelte.config.js
  packages/types/src/ui/BudibaseApp.ts
  packages/types/src/ui/index.ts
  scripts/build.js
  yarn.lock
Labels: firestorm, size/m

#15535 App action tests
  packages/server/src/automations/tests/triggers/appAction.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
Labels: firestorm, size/s

#15537 Fixing app export
  packages/backend-core/src/objectStore/objectStore.ts
Labels: firestorm, size/xs

#15536 Cleaning up loop.spec.ts, moved tests from automation.spec.ts to more appropriate places.
  packages/server/src/automations/tests/automation.spec.ts
  packages/server/src/automations/tests/automationUtils.spec.ts
  packages/server/src/automations/tests/steps/loop.spec.ts
  packages/server/src/automations/tests/triggers/appAction.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/types/src/sdk/automations/index.ts
Labels: firestorm, size/m

#15529 Correctly types gen-collection-info.ts
  packages/string-templates/package.json
  packages/string-templates/scripts/gen-collection-info.ts
  yarn.lock
Labels: size/s

#15540 Remove typescript from SSR app - fix app preview
  packages/server/jest.config.ts
  packages/server/package.json
  packages/server/scripts/svelteTransformer.js
  packages/server/src/api/controllers/static/templates/BudibaseApp.svelte
  packages/server/svelte.config.js
  yarn.lock
Labels: firestorm, size/s

#15521 Fix js completions
  packages/builder/package.json
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/CodeEditor/index.ts
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/SnippetDrawer.svelte
  packages/builder/src/types/bindings.ts
  packages/builder/src/types/index.ts
  packages/types/src/ui/bindings/binding.ts
  yarn.lock
Labels: firestorm, size/m

#15545 Pull out new code editor field and drawer bindable slot into single component
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/CodeEditorField.svelte
  packages/builder/src/components/common/bindings/DrawerBindableCodeEditorField.svelte
  packages/builder/src/components/common/bindings/DrawerBindableSlot.svelte
Labels: size/m

#15548 Revert setting a default icon
  packages/builder/src/stores/builder/components.ts
  packages/client/manifest.json
Labels: size/xs

#15550 Fix S3 datasource upload and read
  packages/backend-core/src/utils/utils.ts
  packages/server/package.json
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/integrations/s3.ts
  packages/server/src/sdk/app/datasources/datasources.ts
  packages/types/src/sdk/datasources.ts
Labels: firestorm, size/s

#15551 Removing smithy package
  packages/server/package.json
  packages/server/src/integrations/s3.ts
Labels: firestorm, size/xs

#15543 Convert client builder store
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ComponentList/dndStore.js
  packages/builder/src/stores/builder/index.js
  packages/client/src/components/Block.svelte
  packages/client/src/components/BlockComponent.svelte
  packages/client/src/components/app/forms/S3Upload.svelte
  packages/client/src/index.ts
  packages/client/src/stores/builder.ts
  packages/client/src/stores/derived/devToolsEnabled.js
  packages/client/src/stores/derived/snippets.js
  packages/client/src/stores/screens.js
  packages/server/src/api/controllers/static/templates/preview.hbs
  packages/types/src/ui/stores/misc.ts
Labels: size/m

#15556 ensure app ownership middleware
  packages/server/src/api/routes/backup.ts
  packages/server/src/middleware/ensureTenantAppOwnership.ts
  packages/server/src/middleware/tests/ensureTenantAppOwnership.spec.js
Labels: size/s

#15561 fix error message and extract tenantId from appId
  packages/backend-core/src/utils/tests/utils.spec.ts
  packages/backend-core/src/utils/utils.ts
  packages/server/src/middleware/ensureTenantAppOwnership.ts
  packages/server/src/middleware/tests/ensureTenantAppOwnership.spec.js
Labels: size/s

#15527 Table settings updates
  packages/builder/src/components/design/settings/controls/ButtonConfiguration/ButtonSetting.svelte
  packages/builder/src/components/design/settings/controls/EditComponentPopover.svelte
  packages/builder/src/components/design/settings/controls/FieldConfiguration/FieldSetting.svelte
  packages/builder/src/components/design/settings/controls/PropertyControl.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ComponentSettingsSection.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUIDrawer.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Component/ConditionalUISection.svelte
  packages/client/manifest.json
  packages/client/src/components/app/GridBlock.svelte
  packages/frontend-core/src/components/grid/stores/conditions.ts
  packages/types/src/ui/components/index.ts
  packages/types/src/ui/stores/grid/columns.ts
  packages/types/src/ui/stores/grid/condition.ts
Labels: size/m

#15552 Validate handlebars
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/CodeEditor/index.ts
  packages/builder/src/components/common/CodeEditor/validator/hbs.ts
  packages/builder/src/components/common/CodeEditor/validator/tests/hbs.spec.ts
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/types/bindings.ts
  packages/builder/tsconfig.json
  packages/types/src/ui/bindings/helper.ts
Labels: firestorm, size/m

#15553 Relationship field - make sure selected value correctly displays
  packages/bbui/src/Form/Core/Multiselect.svelte
  packages/client/src/components/app/Placeholder.svelte
  packages/client/src/components/app/forms/Field.svelte
  packages/client/src/components/app/forms/InnerForm.svelte
  packages/client/src/components/app/forms/RelationshipField.svelte
Labels: firestorm, size/m

#15566 Add tests for cron stopping.
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/server/src/automations/tests/steps/cron-automations.spec.ts
  packages/server/src/automations/tests/triggers/cron.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/automations/tests/utilities/index.ts
  packages/server/src/automations/utils.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/threads/automation.ts
  packages/types/src/api/web/app/automation.ts
Labels: firestorm, size/m

#15569 Test cron removal.
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/backend-core/src/queue/index.ts
  packages/server/src/automations/logging/index.ts
  packages/server/src/automations/tests/steps/loop.spec.ts
  packages/server/src/automations/tests/triggers/cron.spec.ts
  packages/server/src/automations/tests/utilities/index.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/m

#15564 Convert builder components helpers to ts
  packages/builder/src/components/design/settings/controls/URLVariableTestInput.svelte
  packages/builder/src/helpers/components.ts
  packages/builder/src/stores/builder/componentTreeNodes.ts
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/preview.ts
  packages/builder/src/stores/builder/screens.ts
  packages/frontend-core/src/constants.ts
  packages/types/src/ui/components/index.ts
  packages/types/src/ui/stores/preview.ts
Labels: firestorm, size/m

#15575 store koa sessions in redis instead of cookies
  hosting/nginx.dev.conf
  packages/worker/package.json
  packages/worker/src/api/routes/global/tests/auth.spec.ts
  packages/worker/src/index.ts
  packages/worker/src/koa-redis.d.ts
  yarn.lock
Labels: size/s

#15580 Fix getting proper contexts when validating datasources
  packages/builder/src/stores/builder/screenComponent.ts
Labels: firestorm, size/xs

#15584 Fix CouchDB datasource.
  packages/backend-core/src/sql/utils.ts
  packages/server/src/integrations/couchdb.ts
  packages/server/src/integrations/tests/couchdb.spec.ts
Labels: firestorm, size/m

#15589 Fix loops being given empty strings.
  packages/server/src/automations/tests/steps/loop.spec.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/s

#15596 [Revert] store koa sessions in redis instead of cookies
  hosting/nginx.dev.conf
  packages/worker/package.json
  packages/worker/src/api/routes/global/tests/auth.spec.ts
  packages/worker/src/index.ts
  packages/worker/src/koa-redis.d.ts
  yarn.lock
Labels: size/s

#15587 Ops/aas with minio gateway
  .gitattributes
  hosting/single/Dockerfile
  hosting/single/runner.sh
  scripts/install-minio.sh
  scripts/resources/minio
Labels: size/m

#15574 Remove mocking from sqlUtils.spec.ts.
  packages/server/src/api/controllers/row/utils/tests/sqlUtils.spec.ts
Labels: firestorm, size/l

#15605 Revert "[Revert] store koa sessions in redis instead of cookies"
  hosting/nginx.dev.conf
  packages/worker/package.json
  packages/worker/src/api/routes/global/tests/auth.spec.ts
  packages/worker/src/index.ts
  packages/worker/src/koa-redis.d.ts
  yarn.lock
Labels: size/s

#15611 Fix for automation traversal
  packages/builder/src/stores/builder/automations.ts
Labels: size/xs

#15612 Improve types around `nodemailer`
  packages/server/src/automations/tests/steps/sendSmtpEmail.spec.ts
  packages/server/src/utilities/workerRequests.ts
  packages/types/package.json
  packages/types/src/api/web/global/email.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/worker/package.json
  packages/worker/src/api/controllers/global/email.ts
  packages/worker/src/utilities/email.ts
  yarn.lock
Labels: firestorm, size/s

#15610 Remove view enrichment unit test, covered by integration tests.
  packages/server/src/sdk/app/tables/tests/tables.spec.ts
Labels: firestorm, size/m

#15627 QR Code scanner zoom capabilities
  packages/client/manifest.json
  packages/client/package.json
  packages/client/src/components/app/forms/CodeScanner.svelte
  packages/client/src/components/app/forms/CodeScannerField.svelte
  yarn.lock
Labels: firestorm, size/s

#15626 Remove mocks from static.spec.ts
  packages/server/src/api/routes/tests/static.spec.ts
Labels: firestorm, size/s

#15628 Fix for autocompletion evaluation in the builder
  packages/builder/src/components/common/bindings/BindingPanel.svelte
Labels: size/xs

#15636 Update apt cache before installing python3-certbot-nginx
  hosting/single/Dockerfile
Labels: size/xs

#15637 Revert "Improve types around `nodemailer`"
  packages/server/src/automations/tests/steps/sendSmtpEmail.spec.ts
  packages/server/src/utilities/workerRequests.ts
  packages/types/package.json
  packages/types/src/api/web/global/email.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/worker/package.json
  packages/worker/src/api/controllers/global/email.ts
  packages/worker/src/utilities/email.ts
  yarn.lock
Labels: firestorm, size/s

#15639 Fix MSSQL tests.
  .github/workflows/budibase_ci.yml
  packages/server/datasource-sha.env
  packages/server/src/integrations/tests/utils/mssql.ts
Labels: firestorm, size/s

#15641 Skip ancestors validation on plugins components
  packages/builder/src/stores/builder/screenComponent.ts
  packages/client/src/index.js
Labels: firestorm, size/m

#15638 Improve types around `nodemailer` (take 2)
  packages/server/src/automations/tests/steps/sendSmtpEmail.spec.ts
  packages/server/src/utilities/workerRequests.ts
  packages/types/package.json
  packages/types/src/api/web/global/email.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/worker/package.json
  packages/worker/src/api/controllers/global/email.ts
  packages/worker/src/api/routes/global/tests/email.spec.ts
  packages/worker/src/api/routes/global/tests/realEmail.spec.ts
  packages/worker/src/tests/TestConfiguration.ts
  packages/worker/src/tests/api/email.ts
  packages/worker/src/tests/mocks/email.ts
  packages/worker/src/utilities/email.ts
  yarn.lock
Labels: firestorm, feature-branch, size/l
