Repository Budibase/budibase, pull requests merged in 2025-08, with the labels that each got.

#16659 [BUDI-9399] Fixes columnar layout for Checkboxes in Form Blocks
  packages/client/src/components/app/forms/BooleanField.svelte
Labels: size/xs

#16666 Merge fixes
  packages/bbui/src/ActionButton/ActionButton.svelte
  packages/bbui/src/Button/Button.svelte
  packages/bbui/src/Modal/ModalContent.svelte
  packages/bbui/src/Popover/Popover.svelte
  packages/builder/src/components/common/TopBar.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
Labels: firestorm, size/s

#16670 Removing old "toggle UI" functionality
  packages/builder/src/stores/builder/flags.ts
  packages/frontend-core/src/api/flags.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/routes/static.ts
  packages/types/src/api/web/app/static.ts
Labels: firestorm, size/s

#16637 Deduplicate workspace apps
  packages/server/src/appMigrations/migrations.ts
  packages/server/src/appMigrations/migrations/20250729134531_workspace_cleanups.ts
  packages/server/src/appMigrations/migrations/tests/20250729134531_workspace_cleanups.spec.ts
  packages/server/src/sdk/app/workspaceApps/crud.ts
  packages/server/src/tests/utilities/api/workspaceApp.ts
Labels: firestorm, size/m

#16685 fixes mismatched border radiuses
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/index.svelte
Labels: size/xs

#16661 Remove portal side bar
  packages/builder/src/pages/builder/portal/apps/[appId]/ErrorSVG.svelte
  packages/builder/src/pages/builder/portal/apps/[appId]/_layout.svelte
  packages/builder/src/pages/builder/portal/apps/[appId]/index.svelte
  packages/builder/src/pages/builder/portal/apps/_components/PortalSideBar.svelte
  packages/builder/src/pages/builder/portal/apps/_layout.svelte
Labels: firestorm, size/m

#16686 No results
  packages/builder/src/pages/builder/app/[application]/_components/NoResults.svelte
  packages/builder/src/pages/builder/app/[application]/automation/_flagged/index.new.svelte
  packages/builder/src/pages/builder/app/[application]/design/_flagged/index.new.svelte
Labels: firestorm, size/s

#16699 Symlink to CLAUDE.md for codex AGENTS.md
  AGENTS.md
Labels: firestorm, size/xs

#16696 Remove unpublished state
  packages/builder/src/components/common/PublishStatusBadge.svelte
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/stores/builder/workspaceApps.ts
  packages/server/src/api/routes/tests/deploy.spec.ts
  packages/server/src/sdk/app/deployment/status.ts
  packages/types/src/api/web/app/deployment.ts
Labels: firestorm, size/s

#16688 Fix user CSV import to ignore empty lines
  packages/bbui/src/Form/RadioGroup.svelte
  packages/builder/src/helpers/csv.ts
  packages/builder/src/helpers/index.ts
  packages/builder/src/helpers/tests/csv.spec.ts
  packages/builder/src/pages/builder/portal/users/users/_components/ImportUsersModal.svelte
  packages/builder/src/pages/builder/portal/users/users/index.svelte
Labels: firestorm, size/m

#16704 Fix for workspace app url customisation on create
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/WorkspaceApp/WorkspaceAppModal.svelte
  packages/server/src/api/routes/workspaceApp.ts
Labels: size/s, size/xl

#16706 Revert "Automation Looping v2 backend"
  packages/server/src/automations/actions.ts
  packages/server/src/automations/automationUtils.ts
  packages/server/src/automations/tests/steps/loop.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/definitions/automations.ts
  packages/server/src/environment.ts
  packages/server/src/threads/automation.ts
  packages/shared-core/src/automations/steps/index.ts
  packages/shared-core/src/automations/steps/loopv2.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/types/src/documents/app/automation/schema.ts
Labels: firestorm, size/xl

#16710 Workspace apps bug
  packages/server/src/api/controllers/application.ts
Labels: firestorm, size/s, size/xs

#16709 Fix default app icon
  packages/builder/src/components/common/EditableIcon.svelte
Labels: firestorm, size/s

#16698 Navigation from workspace app
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/builder/screens.ts
  packages/frontend-core/src/api/workspaceApps.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/routes/navigation.ts
  packages/server/src/api/routes/tests/navigation.spec.ts
  packages/server/src/sdk/app/navigation/index.ts
  packages/types/src/documents/app/app.ts
Labels: firestorm, size/m

#16727 Fix issue where filter component hard crashes builder.
  packages/builder/src/components/design/settings/controls/DraggableList.svelte
Labels: firestorm, size/xs

#16728 Fix set logic in draggable list
  packages/builder/src/components/design/settings/controls/DraggableList.svelte
Labels: firestorm, size/xs

#16724 Honoring workspace app metadata
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/constants/themes.ts
  packages/types/src/api/web/app/static.ts
Labels: firestorm, size/s

#16735 Disable resources on unpublish
  packages/builder/src/pages/builder/app/[application]/settings/general.svelte
  packages/builder/src/stores/builder/deployment.ts
  packages/server/src/api/controllers/application.ts
Labels: firestorm, size/s

#16605 Automation State block
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/BranchNode.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/SelectStepSidePanel.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/StepNode.svelte
  packages/builder/src/components/automation/AutomationBuilder/StepPanel.svelte
  packages/builder/src/components/automation/SetupPanel/BlockData.svelte
  packages/builder/src/components/automation/SetupPanel/BlockProperties.svelte
  packages/builder/src/components/common/bindings/BindingSidePanel.svelte
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/stores/portal/environment.ts
  packages/server/src/automations/actions.ts
  packages/server/src/automations/steps/extractState.ts
  packages/server/src/automations/tests/steps/extractState.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/definitions/automations.ts
  packages/server/src/threads/automation.ts
  packages/shared-core/src/automations/steps/ai/classify.ts
  packages/shared-core/src/automations/steps/ai/extract.ts
  packages/shared-core/src/automations/steps/ai/generate.ts
  packages/shared-core/src/automations/steps/extractState.ts
  packages/shared-core/src/automations/steps/index.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/types/src/documents/app/automation/schema.ts
  packages/types/src/ui/bindings/binding.ts
Labels: size/l

#16740 feat: add health endpoint proxying for app server in singleimage
  hosting/single/nginx/nginx-default-site.conf
Labels: size/xs

#16742 Small tweaks
  packages/builder/src/components/common/PublishStatusBadge.svelte
  packages/builder/src/pages/builder/portal/apps/index.svelte
Labels: firestorm, size/xs

#16708 Add setting to change button - signature component
  packages/client/manifest.json
  packages/client/src/components/app/forms/SignatureField.svelte
Labels: size/s

#16743 chore: bump node version in Github Actions Readme workflow
  .github/workflows/readme-openapi.yml
Labels: size/xs

#16730 Automation unpublished changes notification
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/common/CtaNotification.svelte
  packages/builder/src/components/common/TopBar.svelte
  packages/builder/src/components/deploy/AppActions.svelte
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/stores/builder/deployment.ts
  packages/builder/src/stores/builder/workspaceDeployment.ts
Labels: firestorm, size/m

#16741 Workspace embed updates
  packages/builder/src/components/common/UpdateAppForm.svelte
  packages/builder/src/components/deploy/DeleteModal.svelte
  packages/builder/src/components/deploy/RevertModal.svelte
  packages/builder/src/components/deploy/VersionModal.svelte
  packages/builder/src/components/start/ImportAppModal.svelte
  packages/builder/src/pages/builder/app/[application]/settings/embed.svelte
  packages/builder/src/pages/builder/app/[application]/settings/general.svelte
  packages/builder/src/stores/builder/deployment.ts
Labels: size/m

#16771 [BUDI-16769] Fix "Visit the Docs" link to open in new tab
  packages/builder/src/components/backend/DataTable/alert/grid/GridDevWarning.svelte
Labels: size/xs

#16781 Rename flag
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/backend/DatasourceNavigator/QueryNavItem.svelte
  packages/builder/src/components/backend/TableNavigator/TableNavItem/TableNavItem.svelte
  packages/builder/src/components/common/PublishMenu.svelte
  packages/builder/src/components/common/UpdateAppForm.svelte
  packages/builder/src/components/deploy/DeleteModal.svelte
  packages/builder/src/components/deploy/RevertModal.svelte
  packages/builder/src/components/deploy/VersionModal.svelte
  packages/builder/src/components/design/ScreenDetailsModal.svelte
  packages/builder/src/components/start/CreateAppModal.svelte
  packages/builder/src/components/start/DuplicateAppModal.svelte
  packages/builder/src/components/start/ExportAppModal.svelte
  packages/builder/src/components/start/ImportAppModal.svelte
  packages/builder/src/components/start/getAppContextMenuItems.ts
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/agent/index.svelte
  packages/builder/src/pages/builder/app/[application]/automation/[automationId]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/automation/_flagged/layout.old.svelte
  packages/builder/src/pages/builder/app/[application]/automation/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/automation/index.svelte
  packages/builder/src/pages/builder/app/[application]/data/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/_components/ViewNavBar.svelte
  packages/builder/src/pages/builder/app/[application]/design/[workspaceAppId]/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[workspaceAppId]/[screenId]/_components/ScreenList/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[workspaceAppId]/[screenId]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/AppSelectionModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/index.svelte
  packages/builder/src/pages/builder/app/[application]/settings/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/settings/embed.svelte
  packages/builder/src/pages/builder/app/[application]/settings/general.svelte
  packages/builder/src/pages/builder/apps/index.svelte
  packages/builder/src/pages/builder/portal/apps/index.svelte
  packages/builder/src/pages/builder/portal/users/groups/[groupId].svelte
  packages/builder/src/pages/builder/portal/users/users/[userId].svelte
  packages/builder/src/pages/builder/portal/users/users/index.svelte
  packages/builder/src/stores/builder/appUrls.ts
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/stores/builder/deployment.ts
  packages/builder/src/stores/builder/navigation.ts
  packages/builder/src/stores/builder/routes.ts
  packages/builder/src/stores/portal/menu.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/deploy/index.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/tests/deploy.spec.ts
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/sdk/app/applications/applications.ts
  packages/server/src/sdk/app/workspaceApps/tests/utils.spec.ts
  packages/server/src/utilities/routing/index.ts
  packages/types/src/sdk/featureFlag.ts
  packages/worker/src/api/controllers/global/self.ts
Labels: firestorm, size/m

#16782 Fix role publishing
  packages/backend-core/src/constants/db.ts
  packages/backend-core/src/db/Replication.ts
  packages/server/src/api/controllers/deploy/index.ts
  packages/server/src/api/routes/tests/application.spec.ts
Labels: size/s

#16750 Budi 9569 upgrade to isolated vm 6
  packages/server/package.json
  packages/server/src/jsRunner/vm/isolated-vm.ts
  yarn.lock
Labels: size/xs

#16784 Workspace UI fixes
  packages/builder/src/pages/builder/app/[application]/design/_flagged/index.new.svelte
  packages/builder/src/pages/builder/portal/apps/index.svelte
Labels: size/s

#16787 Enrich data on posthog flags
  packages/backend-core/src/events/identification.ts
  packages/backend-core/src/features/features.ts
  packages/types/src/documents/global/config.ts
Labels: firestorm, size/s

#16720 Update api specs
  packages/server/specs/openapi.json
  packages/server/specs/openapi.yaml
  packages/server/specs/parameters.ts
  packages/server/specs/resources/application.ts
  packages/server/src/api/routes/public/applications.ts
  packages/server/src/api/routes/public/index.ts
  packages/server/src/api/routes/public/middleware/mapper.ts
  packages/server/src/api/routes/public/workspaces.ts
  packages/server/src/definitions/openapi.ts
Labels: stale, firestorm, size/xl

#16793 Budibase AI fix
  packages/backend-core/src/features/features.ts
  packages/server/src/api/routes/ai.ts
Labels: firestorm, size/s

#16789 Cleanup AI flags
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/pages/builder/app/[application]/data/new.svelte
  packages/server/src/api/controllers/ai/budibaseai.ts
  packages/server/src/api/controllers/ai/js.ts
  packages/server/src/api/routes/tests/ai.spec.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/s

#16799 switches column icons out for number-icons
  packages/client/manifest.json
Labels: size/m

#16811 Remove noise around app migrations for unexisting apps
  packages/server/src/appMigrations/index.ts
  packages/server/src/appMigrations/tests/migrations.spec.ts
Labels: firestorm, size/s

#16815 Workspace flag on by default
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/s, size/xs, size/m

#16820 fix for edit row modal not respecting prod/dev switcher setting
  packages/builder/src/components/backend/DataTable/modals/CreateEditRow.svelte
Labels: size/xs

#16846 Fix lodash issues on dev
  packages/shared-core/src/filters.ts
Labels: firestorm, size/xs
