Repository Budibase/budibase, pull requests merged in 2025-03, with the labels that each got.

#15642 Handle spaces on hbs binding validations
  packages/builder/src/components/backend/DataTable/formula.js
  packages/builder/src/components/common/CodeEditor/validator/hbs.ts
  packages/builder/src/components/common/CodeEditor/validator/tests/hbs.spec.ts
  packages/builder/src/dataBinding.js
  packages/string-templates/scripts/gen-collection-info.ts
  packages/string-templates/src/helpers/date.ts
  packages/string-templates/src/manifest.json
Labels: firestorm, feature-branch, size/m

#15653 Remove types
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/frontend-core/src/fetch/GroupUserFetch.ts
  packages/frontend-core/src/fetch/UserFetch.ts
Labels: firestorm, size/s

#15590 Type sidepanel
  eslint.config.mjs
  packages/bbui/src/Actions/position_dropdown.ts
  packages/bbui/src/Popover/Popover.svelte
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/BindingSidePanel.svelte
  packages/builder/src/constants/completions.ts
  packages/client/src/components/app/DataProvider.svelte
  packages/client/src/components/app/blocks/form/FormBlock.svelte
  packages/client/src/components/error-states/ComponentErrorState.svelte
  packages/client/src/components/error-states/ComponentErrorStateCTA.svelte
  packages/client/src/components/preview/DNDHandler.svelte
  packages/types/src/ui/bindings/binding.ts
  packages/types/src/ui/bindings/helper.ts
Labels: firestorm, size/m

#15657 Fix app deletion issue in development
  packages/backend-core/src/objectStore/objectStore.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/routes/tests/application.spec.ts
Labels: firestorm, size/s

#15595 Move snippets to sidepanel
  packages/bbui/src/Drawer/Drawer.svelte
  packages/bbui/src/Popover/Popover.svelte
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/BindingSidePanel.svelte
  packages/builder/src/components/common/bindings/SnippetDrawer.svelte
  packages/builder/src/components/common/bindings/SnippetSidePanel.svelte
  packages/builder/src/components/common/bindings/index.js
  packages/types/src/ui/components/index.ts
  packages/types/src/ui/components/sidepanel.ts
Labels: firestorm, feature-branch, size/l

#15629 Rewrite relationship field
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/frontend-core/src/fetch/GroupUserFetch.ts
  packages/frontend-core/src/fetch/UserFetch.ts
Labels: size/m

#15643 Remove mocks from public variant of `users.spec.ts`
  packages/server/package.json
  packages/server/specs/generate.ts
  packages/server/specs/resources/error.ts
  packages/server/src/api/controllers/public/users.ts
  packages/server/src/api/routes/public/index.ts
  packages/server/src/api/routes/public/middleware/testErrorHandling.ts
  packages/server/src/api/routes/public/tests/compare.spec.ts
  packages/server/src/api/routes/public/tests/users.spec.ts
  packages/server/src/api/routes/public/tests/utils.ts
  packages/server/src/api/routes/tests/utilities/index.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/tests/utilities/api/base.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/public/user.ts
  yarn.lock
Labels: firestorm, size/l

#15661 De-mock AI column search tests.
  packages/server/src/api/routes/tests/search.spec.ts
Labels: firestorm, size/s

#15662 Cleanup after automation tests.
  packages/server/src/automations/tests/steps/bash.spec.ts
  packages/server/src/automations/tests/steps/createRow.spec.ts
  packages/server/src/automations/tests/steps/delay.spec.ts
  packages/server/src/automations/tests/steps/deleteRow.spec.ts
  packages/server/src/automations/tests/steps/discord.spec.ts
  packages/server/src/automations/tests/steps/executeQuery.spec.ts
  packages/server/src/automations/tests/steps/executeScript.spec.ts
  packages/server/src/automations/tests/steps/filter.spec.ts
  packages/server/src/automations/tests/steps/loop.spec.ts
  packages/server/src/automations/tests/steps/make.spec.ts
  packages/server/src/automations/tests/steps/n8n.spec.ts
  packages/server/src/automations/tests/steps/openai.spec.ts
  packages/server/src/automations/tests/steps/outgoingWebhook.spec.ts
  packages/server/src/automations/tests/steps/queryRows.spec.ts
  packages/server/src/automations/tests/steps/sendSmtpEmail.spec.ts
  packages/server/src/automations/tests/steps/serverLog.spec.ts
  packages/server/src/automations/tests/steps/triggerAutomationRun.spec.ts
  packages/server/src/automations/tests/steps/updateRow.spec.ts
  packages/server/src/automations/tests/steps/zapier.spec.ts
  packages/server/src/automations/tests/triggers/appAction.spec.ts
  packages/server/src/automations/tests/triggers/cron.spec.ts
  packages/server/src/automations/tests/triggers/rowDeleted.spec.ts
  packages/server/src/automations/tests/triggers/rowSaved.spec.ts
  packages/server/src/automations/tests/triggers/rowUpdated.spec.ts
  packages/server/src/automations/tests/triggers/webhook.spec.ts
  packages/server/src/tests/utilities/api/automation.ts
Labels: firestorm, size/s

#15663 Disabling ArangoDB
  packages/server/src/api/controllers/integration.ts
  packages/server/src/integrations/arangodb.ts
  packages/server/src/integrations/index.ts
  packages/server/src/integrations/tests/arangodb.spec.ts
Labels: firestorm, size/s

#15656 Delete airtable.spec.ts.
  packages/server/src/integrations/tests/airtable.spec.ts
Labels: firestorm, size/s

#15660 Remove redis mock from application.spec.ts.
  packages/server/src/api/routes/tests/application.spec.ts
Labels: firestorm, size/s

#15666 Type BBUI multiselect
  packages/bbui/src/Form/Core/Multiselect.svelte
Labels: firestorm, size/s

#15667 Typing field
  packages/client/src/components/app/forms/Field.svelte
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/client/src/components/app/forms/index.ts
Labels: firestorm, size/s

#15673 Fixing BBReference field
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/shared-core/src/utils.ts
Labels: firestorm, size/s

#15675 Fix automation test output when loop max iterations or failure condition hit
  packages/server/src/automations/tests/steps/loop.spec.ts
  packages/server/src/threads/automation.ts
Labels: firestorm, size/s

#15549 Budi 9011 - DecodeId helper
  packages/string-templates/src/helpers/constants.ts
  packages/string-templates/src/helpers/index.ts
  packages/string-templates/test/helpers.spec.ts
Labels: size/s

#15677 Disable Posthog session recording
  packages/builder/src/analytics/PosthogClient.ts
  packages/builder/src/analytics/index.js
  packages/builder/src/stores/portal/admin.ts
Labels: firestorm, size/s

#15678 Fixing wrongly display bindings on JS
  packages/builder/src/components/common/bindings/BindingSidePanel.svelte
Labels: firestorm, size/s

#15664 De-mock dynamodb
  .github/workflows/budibase_ci.yml
  packages/server/datasource-sha.env
  packages/server/src/integrations/dynamodb.ts
  packages/server/src/integrations/tests/dynamodb.spec.ts
  packages/server/src/integrations/tests/utils/dynamodb.ts
  packages/server/src/integrations/tests/utils/images.ts
  packages/server/src/integrations/tests/utils/index.ts
  packages/worker/src/tests/jestSetup.ts
Labels: firestorm, size/m

#15671 Small fix to googlesheets mock.
  packages/server/src/integrations/tests/utils/googlesheets.ts
Labels: firestorm, size/s

#15682 Add extra date helpers
  packages/string-templates/scripts/gen-collection-info.ts
  packages/string-templates/src/helpers/date.ts
  packages/string-templates/src/helpers/external.ts
  packages/string-templates/src/manifest.json
  packages/string-templates/test/helpers/date.spec.ts
Labels: firestorm, size/m

#15442 [BUDI-9006] Allow automation test data modal to select real data
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
Labels: firestorm, feature-branch, size/m

#15461 Execute Script V2 - UX
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/BranchNode.svelte
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/builder/src/components/automation/SetupPanel/SchemaSetup.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/CodeEditorField.svelte
  packages/builder/src/components/common/bindings/DrawerBindableCodeEditorField.svelte
  packages/builder/src/components/common/bindings/DrawerBindableSlot.svelte
  packages/builder/src/components/common/bindings/ServerBindingPanel.svelte
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterBuilder.svelte
  packages/builder/src/components/integration/KeyValueBuilder.svelte
  packages/builder/src/pages/builder/app/[application]/automation/_layout.svelte
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/stores/builder/index.js
  packages/client/src/components/app/blocks/form/FormBlock.svelte
  packages/frontend-core/src/components/ConditionField.svelte
  packages/frontend-core/src/components/CoreFilterBuilder.svelte
  packages/frontend-core/src/components/FilterField.svelte
  packages/server/src/api/controllers/automation.ts
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/tests/triggers/webhook.spec.ts
  packages/server/src/automations/tests/utilities/AutomationTestBuilder.ts
  packages/server/src/automations/triggers.ts
  packages/types/src/api/web/app/automation.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
  packages/types/src/documents/app/automation/automation.ts
Labels: feature-branch, size/l

#15689 Copy to Clipboard button action
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/CopyToClipboard.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/index.js
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/manifest.json
  packages/client/src/utils/buttonActions.js
Labels: size/s

#15697 Fixes validation text in custom user roles
  packages/builder/src/components/backend/RoleEditor/RoleNode.svelte
Labels: size/xs

#15696 New automation JS editor fixes.
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
Labels: firestorm, size/s

#15698 Import OpenAPI fixes
  packages/bbui/src/Form/Core/TextArea.svelte
  packages/bbui/src/Form/TextArea.svelte
  packages/bbui/src/Tabs/Tab.svelte
  packages/builder/src/components/backend/DatasourceNavigator/modals/ImportRestQueriesModal.svelte
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/_components/panels/Queries/RestImportQueriesModal.svelte
  packages/types/src/api/web/app/query.ts
Labels: firestorm, size/m

#15684 Documentation link in App Action
  packages/bbui/src/InlineAlert/InlineAlert.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/ClearRowSelection.svelte
Labels: size/s

#15705 Check types in client
  package.json
  packages/builder/package.json
  packages/client/package.json
  packages/client/src/api/api.ts
  packages/client/src/components/app/SpectrumCard.svelte
  packages/client/src/components/preview/DNDHandler.svelte
  packages/client/src/components/preview/GridDNDHandler.svelte
  packages/client/src/stores/builder.ts
  packages/client/tsconfig.json
  packages/frontend-core/package.json
  packages/frontend-core/src/index.ts
  packages/frontend-core/svelte.config.mjs
  yarn.lock
Labels: firestorm, size/s

#15687 Migrate misc.spec.ts to TS.
  packages/server/src/api/routes/tests/misc.spec.ts
  packages/server/src/integrations/tests/TestConfiguration.js
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/misc.ts
Labels: firestorm, size/s

#15686 Convert middleware tests to TS, remove mocks.
  packages/server/src/api/routes/tests/misc.spec.ts
  packages/server/src/integrations/tests/TestConfiguration.js
  packages/server/src/middleware/selfhost.ts
  packages/server/src/middleware/tests/ensureTenantAppOwnership.spec.js
  packages/server/src/middleware/tests/ensureTenantAppOwnership.spec.ts
  packages/server/src/middleware/tests/resourceId.spec.js
  packages/server/src/middleware/tests/resourceId.spec.ts
  packages/server/src/middleware/tests/selfhost.spec.js
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/misc.ts
Labels: firestorm, size/m

#15679 Allow uploading attachments through views
  packages/client/src/components/app/forms/AttachmentField.svelte
Labels: size/xs

#15722 Allow uploading of signatures through views
  packages/client/src/components/app/forms/SignatureField.svelte
Labels: size/s

#15719 Don't show row test data selector outside of test modal.
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
Labels: firestorm, size/m

#15725 Remove on:focus event attribute from Icon
  packages/bbui/src/Icon/Icon.svelte
Labels: size/xs

#15732 Initial oAuth2 config crud
  packages/server/src/api/controllers/oauth2.ts
  packages/server/src/api/routes/index.ts
  packages/server/src/api/routes/oauth2.ts
  packages/server/src/api/routes/tests/oauth2.spec.ts
  packages/server/src/sdk/app/oauth2.ts
  packages/server/src/sdk/index.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/oauth2.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/app/oauth2.ts
  packages/types/src/documents/app/index.ts
  packages/types/src/documents/app/oauth2.ts
  packages/types/src/documents/document.ts
Labels: size/m

#15734 JS V2 Step bindings parsing and JS quote pattern update
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/dataBinding.js
Labels: size/s

#15706 Type fields
  packages/client/src/components/app/forms/BBReferenceField.svelte
  packages/client/src/components/app/forms/Field.svelte
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/client/src/components/app/forms/index.ts
  packages/client/src/context.d.ts
  packages/client/src/index.ts
  packages/client/src/types/components.ts
  packages/client/src/types/fields.ts
  packages/client/src/types/forms.ts
  packages/client/src/types/index.ts
  packages/client/src/types/sdk.ts
Labels: firestorm, size/m

#15737 Removing un-necessary log statement
  packages/backend-core/src/features/features.ts
Labels: firestorm, size/xs

#15738 JS V2 On blur update
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/common/bindings/CodeEditorField.svelte
Labels: size/s

#15728 Send context information to the JS generation endpoint.
  packages/bbui/src/Form/Core/TextArea.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationBlockSetup.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelectorTypes.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/CodeEditorField.svelte
  packages/types/src/api/web/ai.ts
Labels: firestorm, size/s

#15744 Fix save button state on rest
  packages/builder/src/components/common/inputs/EditableLabel.svelte
  packages/builder/src/components/integration/KeyValueBuilder.svelte
  packages/builder/src/components/integration/RestQueryViewer.svelte
Labels: firestorm, size/m

#15745 Autosave rest authentication settings
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/_components/panels/Authentication/index.svelte
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/_components/panels/SaveDatasourceButton.svelte
  packages/builder/src/stores/builder/integrations.ts
Labels: firestorm, size/s

#15748 Bind the password form
  packages/builder/src/pages/builder/auth/reset.svelte
  packages/frontend-core/src/components/PasswordRepeatInput.svelte
Labels: size/s

#15749 Filtering updates
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/frontend-core/src/utils/utils.ts
  packages/shared-core/src/filters.ts
  packages/shared-core/src/tests/filters.spec.ts
  packages/types/src/api/web/searchFilter.ts
Labels: size/m

#15750 Style tweaks
  packages/client/src/components/app/Text.svelte
  packages/frontend-core/src/components/grid/cells/HeaderCell.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/server/src/api/controllers/application.ts
Labels: size/s

#15752 Modal to prevent losing REST datasource changes
  packages/builder/src/components/common/ConfirmDialog.svelte
  packages/builder/src/components/integration/RestQueryViewer.svelte
  packages/builder/src/helpers/confirm.ts
  packages/builder/src/helpers/index.ts
Labels: firestorm, size/m

#15733 Use OAuth2 on rest
  .github/workflows/budibase_ci.yml
  packages/server/images-sha.env
  packages/server/src/api/controllers/oauth2.ts
  packages/server/src/api/routes/tests/oauth2.spec.ts
  packages/server/src/integrations/rest.ts
  packages/server/src/integrations/tests/rest.spec.ts
  packages/server/src/integrations/tests/utils/images.ts
  packages/server/src/sdk/app/oauth2.ts
  packages/server/src/sdk/app/oauth2/crud.ts
  packages/server/src/sdk/app/oauth2/index.ts
  packages/server/src/sdk/app/oauth2/tests/docker-volume/realm.json
  packages/server/src/sdk/app/oauth2/tests/utils.spec.ts
  packages/server/src/sdk/app/oauth2/utils.ts
  packages/server/src/tests/utilities/api/oauth2.ts
  packages/types/src/api/web/app/oauth2.ts
  packages/types/src/documents/app/datasource.ts
  packages/types/src/documents/app/oauth2.ts
  packages/types/src/documents/app/query.ts
  packages/types/src/documents/document.ts
Labels: firestorm, size/m

#15761 Enabling svelte generics support in eslint
  eslint.config.mjs
Labels: firestorm, size/xs

#15747 Typescript conversion of `CreateEditColumn.svelte`
  packages/bbui/src/Form/Core/Multiselect.svelte
  packages/bbui/src/Form/DatePicker.svelte
  packages/bbui/src/Form/Multiselect.svelte
  packages/bbui/src/Form/Toggle.svelte
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/components/common/RelationshipSelector.svelte
  packages/builder/src/constants/backend/index.ts
  packages/builder/src/stores/builder/tables.ts
  packages/client/src/components/app/forms/RelationshipField.svelte
  packages/types/src/documents/app/table/schema.ts
  packages/types/src/ui/fields.ts
  packages/types/src/ui/index.ts
Labels: feature-branch, size/l

#15740 OAuth2 configuration frontend
  packages/builder/src/components/portal/page/SideNav.svelte
  packages/builder/src/components/portal/page/SideNavItem.svelte
  packages/builder/src/pages/builder/app/[application]/settings/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/AddButton.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/MoreMenuRenderer.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/index.svelte
  packages/builder/src/stores/builder/index.ts
  packages/builder/src/stores/builder/navigation.ts
  packages/builder/src/stores/builder/oauth2.ts
  packages/builder/src/types/index.ts
  packages/builder/src/types/oauth2.ts
  packages/frontend-core/src/api/index.ts
  packages/frontend-core/src/api/oauth2.ts
  packages/frontend-core/src/api/types.ts
  packages/types/src/api/web/app/oauth2.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/m

#15753 OAuth2 config validation
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/AddButton.svelte
Labels: firestorm, size/s

#15755 Implement edit and delete config endpoints
  packages/builder/src/types/oauth2.ts
  packages/frontend-core/src/api/oauth2.ts
  packages/server/src/api/controllers/oauth2.ts
  packages/server/src/api/routes/oauth2.ts
  packages/server/src/api/routes/tests/oauth2.spec.ts
  packages/server/src/sdk/app/oauth2/crud.ts
  packages/server/src/tests/utilities/api/oauth2.ts
  packages/types/src/api/web/app/oauth2.ts
Labels: firestorm, size/m

#15765 Allow selecting oauth2 configs
  packages/builder/src/components/integration/RestQueryViewer.svelte
  packages/builder/src/components/integration/rest/AuthPicker.svelte
Labels: size/s

#15763 Edit/delete configs frontend implementation
  packages/builder/src/helpers/confirm.ts
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/AddButton.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/MoreMenuRenderer.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/OAuth2ConfigModalContent.svelte
  packages/builder/src/stores/builder/oauth2.ts
  packages/builder/src/types/oauth2.ts
  packages/frontend-core/src/api/oauth2.ts
  packages/server/src/api/controllers/oauth2.ts
  packages/server/src/api/routes/tests/oauth2.spec.ts
  packages/server/src/sdk/app/oauth2/crud.ts
  packages/types/src/api/web/app/oauth2.ts
Labels: firestorm, size/m

#15769 Validate config
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/MoreMenuRenderer.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/OAuth2ConfigModalContent.svelte
  packages/builder/src/stores/builder/oauth2.ts
  packages/frontend-core/src/api/oauth2.ts
  packages/server/src/api/controllers/oauth2.ts
  packages/server/src/api/routes/oauth2.ts
  packages/server/src/sdk/app/oauth2/utils.ts
  packages/types/src/api/web/app/oauth2.ts
Labels: firestorm, size/m

#15771 Support header and body method
  packages/bbui/src/Form/Select.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/OAuth2ConfigModalContent.svelte
  packages/builder/src/stores/builder/oauth2.ts
  packages/server/src/api/controllers/oauth2.ts
  packages/server/src/api/routes/oauth2.ts
  packages/server/src/api/routes/tests/oauth2.spec.ts
  packages/server/src/integrations/tests/rest.spec.ts
  packages/server/src/sdk/app/oauth2/tests/utils.spec.ts
  packages/server/src/sdk/app/oauth2/utils.ts
  packages/types/src/api/web/app/oauth2.ts
  packages/types/src/documents/app/oauth2.ts
Labels: firestorm, size/m

#15770 File component ts conversion
  packages/bbui/src/Form/Core/File.svelte
  packages/bbui/src/Form/File.svelte
Labels: firestorm, size/s

#15777 TS conversion for ColorPicker component
  packages/bbui/src/ColorPicker/ColorPicker.svelte
Labels: firestorm, size/s

#15655 Client form to TS
  packages/client/src/components/app/forms/Form.svelte
  packages/client/src/components/app/forms/InnerForm.svelte
  packages/client/src/components/app/forms/validation.ts
  packages/client/src/context.d.ts
  packages/client/src/index.ts
  packages/client/src/types/components.ts
  packages/client/src/types/index.ts
  packages/shared-core/src/helpers/helpers.ts
  packages/types/src/ui/fields/fields.ts
  packages/types/src/ui/fields/index.ts
  packages/types/src/ui/fields/validationRules.ts
Labels: firestorm, size/m

#15782 Split oauthconfig per document
  packages/backend-core/src/docIds/params.ts
  packages/builder/src/components/integration/rest/AuthPicker.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/MoreMenuRenderer.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/OAuth2ConfigModalContent.svelte
  packages/builder/src/stores/builder/oauth2.ts
  packages/builder/src/types/oauth2.ts
  packages/frontend-core/src/api/oauth2.ts
  packages/server/src/api/controllers/oauth2.ts
  packages/server/src/api/routes/oauth2.ts
  packages/server/src/api/routes/tests/oauth2.spec.ts
  packages/server/src/integrations/tests/rest.spec.ts
  packages/server/src/sdk/app/oauth2/crud.ts
  packages/server/src/sdk/app/oauth2/tests/utils.spec.ts
  packages/server/src/tests/utilities/api/oauth2.ts
  packages/types/src/api/web/app/oauth2.ts
  packages/types/src/documents/app/oauth2.ts
  packages/types/src/documents/document.ts
Labels: firestorm, size/m

#15786 Fix double "save" modal
  packages/builder/src/components/integration/RestQueryViewer.svelte
Labels: firestorm, size/xs

#15784 SMTP - Cloud send email issue
  packages/backend-core/src/configs/configs.ts
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/ActionModal.svelte
  packages/builder/src/stores/portal/licensing.ts
  packages/types/src/api/web/global/configs.ts
  packages/types/src/documents/global/config.ts
  packages/worker/src/api/controllers/global/configs.ts
  packages/worker/src/api/routes/global/tests/configs.spec.ts
Labels: firestorm, size/m

#15792 Add new pill to auth picker
  packages/builder/src/components/integration/rest/AuthPicker.svelte
Labels: firestorm, size/s

#15793 Display grant type field
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/OAuth2ConfigModalContent.svelte
  packages/builder/src/stores/builder/oauth2.ts
  packages/server/src/api/controllers/oauth2.ts
  packages/server/src/api/routes/oauth2.ts
  packages/server/src/api/routes/tests/oauth2.spec.ts
  packages/server/src/integrations/tests/rest.spec.ts
  packages/server/src/sdk/app/oauth2/tests/utils.spec.ts
  packages/server/src/sdk/app/oauth2/utils.ts
  packages/types/src/api/web/app/oauth2.ts
  packages/types/src/documents/app/oauth2.ts
Labels: firestorm, size/m

#15795 MySQL ANSI quotes support for queries
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/integrations/queries/sql.ts
  packages/server/src/threads/query.ts
Labels: firestorm, size/s

#15798 [Fixed] Wrong user/creator calculation on app init
  packages/backend-core/src/users/db.ts
Labels: enhancement, size/xs

#15762 Custom app scripts
  packages/builder/src/pages/builder/app/[application]/settings/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/settings/automations/index.svelte
  packages/builder/src/pages/builder/app/[application]/settings/backups/index.svelte
  packages/builder/src/pages/builder/app/[application]/settings/scripts.svelte
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/portal/licensing.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/controllers/static/templates/BudibaseApp.svelte
  packages/server/src/api/controllers/static/templates/app.hbs
  packages/server/src/api/controllers/static/templates/preview.hbs
  packages/types/src/documents/app/app.ts
  packages/types/src/sdk/licensing/feature.ts
  packages/types/src/ui/BudibaseApp.ts
Labels: feature-branch, size/m

#15794 Extract env input component
  .vscode/settings.json
  packages/bbui/src/Form/Core/EnvDropdown.svelte
  packages/bbui/src/Form/Core/TextField.svelte
  packages/bbui/src/Form/EnvDropdown.svelte
  packages/bbui/src/Form/Input.svelte
  packages/bbui/src/Menu/Item.svelte
  packages/bbui/src/context.d.ts
  packages/bbui/src/index.ts
  packages/bbui/src/types/actionMenu.ts
  packages/bbui/src/types/envDropdown.ts
  packages/bbui/src/types/index.ts
  packages/bbui/src/types/modalContext.ts
  packages/builder/src/components/backend/Datasources/ConfigEditor/ConfigInput.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/fields/String.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/index.svelte
  packages/builder/src/components/common/bindings/BindableCombobox.svelte
  packages/builder/src/components/integration/RestQueryViewer.svelte
  packages/builder/src/components/portal/environment/CreateEditVariableModal.svelte
  packages/builder/src/components/portal/environment/EnvVariableInput.svelte
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/_components/panels/Authentication/RestAuthenticationModal.svelte
  packages/builder/src/pages/builder/app/[application]/data/datasource/[datasourceId]/_components/panels/Variables/index.svelte
  packages/builder/src/pages/builder/portal/apps/index.svelte
Labels: firestorm, size/m

#15803 Allow using env secrets on oauth2
  packages/bbui/src/Form/Core/EnvDropdown.svelte
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/OAuth2ConfigModalContent.svelte
  packages/server/src/sdk/app/oauth2/utils.ts
  packages/server/src/sdk/utils/index.ts
Labels: firestorm, size/s

#15813 OAuth2 documentation links
  packages/builder/src/pages/builder/app/[application]/settings/oauth2/OAuth2ConfigModalContent.svelte
Labels: firestorm, size/xs

#15821 Dropping SCIM logs from writethrough cache queue.
  packages/backend-core/src/cache/docWritethrough.ts
Labels: firestorm, size/xs

#15831 SQL Server updating signatures support
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/integrations/microsoftSqlServer.ts
  packages/shared-core/src/constants/fields.ts
  packages/types/src/documents/app/row.ts
Labels: firestorm, size/s

#15814 Misc fixes
  packages/backend-core/src/sql/sql.ts
  packages/backend-core/src/sql/tests/utils.spec.ts
  packages/backend-core/src/sql/utils.ts
  packages/bbui/src/Form/Core/TextArea.svelte
  packages/bbui/src/Form/Core/TextField.svelte
  packages/bbui/src/Form/Input.svelte
  packages/bbui/src/Form/TextArea.svelte
  packages/builder/src/components/backend/TableNavigator/ExistingTableDataImport.svelte
  packages/builder/src/components/common/bindings/DrawerBindableInput.svelte
  packages/client/src/components/app/Text.svelte
  packages/frontend-core/src/components/grid/stores/config.ts
  packages/server/src/api/controllers/table/tests/utils.spec.ts
  packages/server/src/api/controllers/table/utils.ts
  packages/server/src/utilities/schema.ts
Labels: size/m

#15833 Load CSS/image assets without going through middlewares
  packages/server/src/api/controllers/assets.ts
  packages/server/src/api/controllers/static/index.ts
  packages/server/src/api/index.ts
  packages/server/src/api/routes/static.ts
Labels: firestorm, size/s

#15839 Test cases for asset API
  packages/server/src/api/controllers/assets.ts
  packages/server/src/api/index.ts
  packages/server/src/api/routes/assets.ts
  packages/server/src/api/routes/static.ts
  packages/server/src/api/routes/tests/assets.spec.ts
  packages/server/src/api/utils.ts
  packages/server/src/tests/utilities/api/assets.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/utilities/fileSystem/filesystem.ts
Labels: firestorm, size/m

#15781 Automation side bar
  packages/bbui/src/Form/Core/Select.svelte
  packages/bbui/src/Form/Select.svelte
  packages/bbui/src/Icon/Icon.svelte
  packages/builder/src/assets.d.ts
  packages/builder/src/components/automation/AutomationBuilder/DraggableCanvas.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/ActionModal.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/BranchNode.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/ExternalActions.js
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/ExternalActions.ts
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItem.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItemStatus.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/StepNode.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/TestDataModal.svelte
  packages/builder/src/components/automation/AutomationBuilder/StepPanel.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationCustomLayout.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationSchemaLayout.svelte
  packages/builder/src/components/automation/SetupPanel/AutomationSelector.svelte
  packages/builder/src/components/automation/SetupPanel/BlockData.svelte
  packages/builder/src/components/automation/SetupPanel/BlockHeader.svelte
  packages/builder/src/components/automation/SetupPanel/BlockProperties.svelte
  packages/builder/src/components/automation/SetupPanel/Count.svelte
  packages/builder/src/components/automation/SetupPanel/DateSelector.svelte
  packages/builder/src/components/automation/SetupPanel/ExecuteScript.svelte
  packages/builder/src/components/automation/SetupPanel/ExecuteScriptV2.svelte
  packages/builder/src/components/automation/SetupPanel/FileSelector.svelte
  packages/builder/src/components/automation/SetupPanel/FilterSelector.svelte
  packages/builder/src/components/automation/SetupPanel/PropField.svelte
  packages/builder/src/components/automation/SetupPanel/RowFetch.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
  packages/builder/src/components/automation/SetupPanel/TableSelector.svelte
  packages/builder/src/components/automation/SetupPanel/index.ts
  packages/builder/src/components/automation/SetupPanel/layouts.ts
  packages/builder/src/components/common/RoleSelect.svelte
  packages/builder/src/components/common/bindings/BindingPanel.svelte
  packages/builder/src/components/common/bindings/BindingSidePanel.svelte
  packages/builder/src/components/common/bindings/CodeEditorField.svelte
  packages/builder/src/components/common/bindings/DrawerBindableSlot.svelte
  packages/builder/src/components/design/settings/controls/FilterEditor/FilterBuilder.svelte
  packages/builder/src/components/integration/KeyValueBuilder.svelte
  packages/builder/src/components/integration/QueryViewerBindingBuilder.svelte
  packages/builder/src/components/integration/RestQueryViewer.svelte
  packages/builder/src/pages/builder/app/[application]/automation/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/settings/automations/index.svelte
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/types/automations.ts
  packages/builder/tsconfig.json
  packages/server/src/api/routes/tests/automation.spec.ts
  packages/server/src/automations/tests/triggers/appAction.spec.ts
  packages/server/src/automations/triggers.ts
  packages/server/src/automations/utils.ts
  packages/server/src/sdk/app/automations/crud.ts
  packages/server/src/sdk/app/backups/imports.ts
  packages/shared-core/src/automations/steps/triggerAutomationRun.ts
  packages/types/src/documents/app/automation/StepInputsOutputs.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/types/src/documents/app/automation/schema.ts
  packages/types/src/ui/stores/automations.ts
Labels: size/xl

#15847 Enable OAuth2 for all users
  packages/builder/src/components/integration/rest/AuthPicker.svelte
  packages/builder/src/pages/builder/app/[application]/settings/_layout.svelte
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/s
