Repository Budibase/budibase, pull requests merged in 2025-04, with the labels that each got.

#15855 Format the plan type label
  packages/builder/src/pages/builder/portal/account/upgrade.svelte
Labels: size/xs

#15856 Fix size of boilerplate screen components on mobile
  packages/server/src/constants/screens.ts
Labels: size/xs

#15852 Allow numeric static formulas to be used in view calculations
  packages/builder/src/components/backend/DataTable/buttons/grid/GridViewCalculationButton.svelte
  packages/server/src/api/routes/tests/viewV2.spec.ts
  packages/server/src/sdk/app/views/index.ts
  packages/types/src/documents/app/row.ts
Labels: firestorm, size/s

#15838 PDF table component
  packages/bbui/src/helpers.ts
  packages/builder/src/components/design/settings/componentSettings.js
  packages/builder/src/components/design/settings/controls/ColumnEditor/ColumnDrawer.svelte
  packages/builder/src/components/design/settings/controls/ColumnEditor/ColumnEditor.svelte
  packages/builder/src/components/design/settings/controls/ColumnEditor/TopLevelColumnEditor.svelte
  packages/builder/src/dataBinding.js
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/manifest.json
  packages/client/src/components/app/Text.svelte
  packages/client/src/components/app/index.js
  packages/client/src/components/app/pdf/PDFTable.svelte
  packages/client/src/components/app/pdf/index.ts
  packages/frontend-core/src/components/grid/cells/NumberCell.svelte
  packages/frontend-core/src/utils/formatting.ts
  packages/frontend-core/src/utils/index.ts
  packages/frontend-core/src/utils/schema.js
  packages/types/src/documents/app/table/schema.ts
Labels: size/l

#15844 Single row provider component
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/NewComponentPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/manifest.json
  packages/client/src/components/app/SingleRowProvider.svelte
  packages/client/src/components/app/index.js
  packages/server/src/api/controllers/row/index.ts
Labels: size/s

#15788 PDF screen template
  packages/bbui/src/helpers.ts
  packages/builder/src/components/design/ScreenDetailsModal.svelte
  packages/builder/src/components/design/settings/componentSettings.js
  packages/builder/src/components/design/settings/controls/ColumnEditor/ColumnDrawer.svelte
  packages/builder/src/components/design/settings/controls/ColumnEditor/ColumnEditor.svelte
  packages/builder/src/components/design/settings/controls/ColumnEditor/TopLevelColumnEditor.svelte
  packages/builder/src/constants/index.ts
  packages/builder/src/dataBinding.js
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Screen/GeneralPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/_components/Screen/ThemePanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/NewComponentPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/images/pdf.svg
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/index.svelte
  packages/builder/src/stores/builder/screens.ts
  packages/builder/src/templates/screenTemplating/Screen.js
  packages/builder/src/templates/screenTemplating/index.js
  packages/builder/src/templates/screenTemplating/pdf.js
  packages/client/manifest.json
  packages/client/package.json
  packages/client/src/components/BlockComponent.svelte
  packages/client/src/components/Component.svelte
  packages/client/src/components/CustomThemeWrapper.svelte
  packages/client/src/components/app/SingleRowProvider.svelte
  packages/client/src/components/app/Text.svelte
  packages/client/src/components/app/container/GridContainer.svelte
  packages/client/src/components/app/index.js
  packages/client/src/components/app/pdf/PDF.svelte
  packages/client/src/components/app/pdf/PDFTable.svelte
  packages/client/src/components/app/pdf/index.ts
  packages/client/src/components/app/pdf/pdf.ts
  packages/client/src/index.ts
  packages/client/src/stores/screens.js
  packages/client/src/utils/grid.ts
  packages/frontend-core/src/components/grid/cells/NumberCell.svelte
  packages/frontend-core/src/utils/formatting.ts
  packages/frontend-core/src/utils/index.ts
  packages/frontend-core/src/utils/schema.js
  packages/server/src/api/controllers/row/index.ts
  packages/types/src/documents/app/screen.ts
  packages/types/src/documents/app/table/schema.ts
  yarn.lock
Labels: size/xl, feature-branch-enterprise

#15868 Don't fall back on the PostHog decide endpoint.
  packages/backend-core/src/features/features.ts
  packages/backend-core/src/features/tests/features.spec.ts
Labels: firestorm, size/m

#15863 Fix for Automation bindings in Row actions
  packages/builder/src/components/automation/SetupPanel/ExecuteScriptV2.svelte
  packages/builder/src/components/automation/SetupPanel/RowSelector.svelte
  packages/builder/src/components/common/bindings/DrawerBindableCodeEditorField.svelte
  packages/builder/src/components/common/bindings/DrawerBindableSlot.svelte
Labels: size/m

#15882 Remove mysterious curly brace
  packages/client/src/components/preview/HoverIndicator.svelte
Labels: size/xs

#15869 `/api/global/configs/public` performance improvements
  packages/worker/src/api/controllers/global/configs.ts
Labels: firestorm, size/s

#15812 Some typings created during the oauth2 work
  packages/bbui/src/Form/Core/Switch.svelte
  packages/bbui/src/Form/Toggle.svelte
  packages/builder/src/components/design/settings/controls/RoleSelect.svelte
  packages/builder/src/components/integration/AccessLevelSelect.svelte
  packages/builder/src/components/integration/KeyValueBuilder.svelte
  packages/server/src/api/routes/tests/queries/mongodb.spec.ts
  packages/server/src/api/routes/tests/queries/rest.spec.ts
  packages/types/src/documents/app/query.ts
Labels: firestorm, size/m

#15908 Make Proxy Timeouts Configurable via PROXY_TIMEOUT_SECONDS
  hosting/proxy/Dockerfile
  hosting/proxy/nginx.prod.conf
Labels: size/s

#15905 updates column name in import modal
  packages/builder/src/components/backend/TableNavigator/TableDataImport.svelte
Labels: size/xs

#15898 Add CSP whitelist feature to custom app scripts
  packages/backend-core/package.json
  packages/backend-core/src/middleware/contentSecurityPolicy.ts
  packages/backend-core/src/middleware/tests/contentSecurityPolicy.spec.ts
  packages/builder/src/pages/builder/app/[application]/settings/scripts.svelte
  packages/server/src/api/index.ts
  packages/server/src/koa.ts
  packages/types/src/documents/app/app.ts
Labels: size/m

#15779 Add accordion component
  packages/bbui/src/Accordion/Accordion.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/NewComponentPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/manifest.json
  packages/client/src/components/app/Accordion.svelte
  packages/client/src/components/app/index.js
  packages/types/src/ui/components/index.ts
Labels: feature-branch, size/s

#15906 Rating Field Component
  packages/bbui/src/Icon/Icon.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/manifest.json
  packages/client/src/components/app/forms/RatingField.svelte
  packages/client/src/components/app/forms/index.ts
Labels: feature-branch, size/m

#15930 CSP whitelist validation
  packages/backend-core/src/middleware/contentSecurityPolicy.ts
  packages/backend-core/src/middleware/tests/contentSecurityPolicy.spec.ts
Labels: size/s

#15941 Posthog ts conversion
  packages/builder/src/analytics/constants.ts
  packages/builder/src/analytics/index.ts
  packages/builder/src/stores/portal/auth.ts
Labels: firestorm, size/s

#15954 Capture codegen accept/reject events in PostHog.
  packages/builder/src/analytics/constants.ts
  packages/builder/src/components/common/CodeEditor/AIGen.svelte
Labels: firestorm, size/s

#15958 Hide Day Passes
  packages/builder/src/pages/builder/portal/account/usage.svelte
Labels: size/xs

#15959 Further UX updates for the AI JS generation
  packages/builder/src/components/common/CodeEditor/AIGen.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/stores/portal/licensing.ts
Labels: firestorm, size/m

#15961 Typing of AI Configuration files
  packages/builder/src/pages/builder/portal/settings/ai/AIConfigTile.svelte
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
Labels: size/s

#15966 Show AI JS prompt in expanded state when in drawer
  packages/builder/src/components/common/CodeEditor/AIGen.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
Labels: firestorm, size/s

#15962 Binding fixes
  packages/builder/src/components/backend/DataTable/formula.js
  packages/builder/src/dataBinding.js
  packages/builder/src/dataBinding.test.js
Labels: size/s

#15968 Support LLM formats and structured outputs
  packages/server/src/api/routes/tests/ai.spec.ts
  packages/server/src/tests/utilities/mocks/ai/index.ts
  packages/server/src/tests/utilities/mocks/ai/openai.ts
  packages/types/src/api/web/ai.ts
Labels: size/s

#15975 AI table generation UI
  packages/bbui/src/Form/Core/TextField.svelte
  packages/bbui/src/Form/Input.svelte
  packages/builder/src/components/common/CodeEditor/AIGen.svelte
  packages/builder/src/components/common/ai/AIInput.svelte
  packages/builder/src/pages/builder/app/[application]/data/_components/AITableGeneration.svelte
  packages/builder/src/pages/builder/app/[application]/data/new.svelte
  packages/frontend-core/src/api/ai.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/l

#15991 Prefer get account by tenantId
  packages/backend-core/src/accounts/accounts.ts
  packages/backend-core/src/cache/user.ts
  packages/backend-core/src/users/db.ts
  packages/backend-core/src/users/utils.ts
  packages/backend-core/tests/core/utilities/structures/accounts.ts
  packages/types/src/documents/account/account.ts
  packages/worker/src/api/routes/global/tests/scim.spec.ts
  packages/worker/src/api/routes/global/tests/users.spec.ts
Labels: size/s

#15989 Safari fixes
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/data/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/_layout.svelte
  packages/frontend-core/src/components/grid/cells/GridCell.svelte
Labels: size/s

#15994 Need to match the account email
  packages/backend-core/src/cache/user.ts
Labels: size/xs

#15987 Markdown performance improvements
  packages/bbui/src/Markdown/MarkdownViewer.svelte
  packages/builder/package.json
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/NewComponentPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/manifest.json
  packages/client/src/components/app/Text.svelte
  packages/client/src/components/app/deprecated/MarkdownViewer.svelte
  packages/client/src/components/app/index.js
  yarn.lock
Labels: size/m

#15995 Move creator edit access to premium
  packages/builder/src/components/common/RoleSelect.svelte
Labels: size/s

#15998 Revert "Prefer get account by tenantId (#15991)"
  packages/backend-core/src/accounts/accounts.ts
  packages/backend-core/src/cache/user.ts
  packages/backend-core/src/users/db.ts
  packages/backend-core/src/users/utils.ts
  packages/backend-core/tests/core/utilities/structures/accounts.ts
  packages/types/src/documents/account/account.ts
  packages/worker/src/api/routes/global/tests/scim.spec.ts
  packages/worker/src/api/routes/global/tests/users.spec.ts
Labels: size/s

#16005 15974 add missing plan to creator check
  packages/builder/src/components/common/RoleSelect.svelte
  packages/frontend-core/src/constants.ts
Labels: size/xs

#15993 Updates for AI Configuration screen
  packages/builder/src/pages/builder/portal/settings/ai/AIConfigTile.svelte
  packages/builder/src/pages/builder/portal/settings/ai/AISettings.spec.js
  packages/builder/src/pages/builder/portal/settings/ai/ConfigModal.svelte
  packages/builder/src/pages/builder/portal/settings/ai/PortalModal.svelte
  packages/builder/src/pages/builder/portal/settings/ai/constants.js
  packages/builder/src/pages/builder/portal/settings/ai/constants.ts
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
  packages/builder/src/pages/builder/portal/settings/ai/logos/BBAI.svelte
  packages/types/src/documents/global/config.ts
Labels: firestorm, size/l

#16024 Fix the way that the AI settings page finds AI configs for a given provider
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
Labels: firestorm, size/s

#16032 Animate the BBAI logo when loading.
  packages/builder/src/components/common/ai/AIInput.svelte
Labels: firestorm, size/s

#16033 AI JS styling fixes
  packages/builder/src/components/common/CodeEditor/AIGen.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/ai/AIInput.svelte
Labels: size/m

#16010 Feature flag debug UI
  packages/backend-core/src/constants/misc.ts
  packages/backend-core/src/context/mainContext.ts
  packages/backend-core/src/context/types.ts
  packages/backend-core/src/features/features.ts
  packages/backend-core/src/middleware/featureFlagCookie.ts
  packages/backend-core/src/middleware/index.ts
  packages/builder/src/components/commandPalette/CommandPalette.svelte
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/pages/builder/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
  packages/builder/src/pages/builder/app/[application]/data/new.svelte
  packages/builder/src/stores/portal/featureFlags.ts
  packages/frontend-core/src/api/features.ts
  packages/frontend-core/src/api/index.ts
  packages/frontend-core/src/api/types.ts
  packages/server/src/api/controllers/features.ts
  packages/server/src/api/index.ts
  packages/server/src/api/routes/features.ts
  packages/server/src/api/routes/index.ts
  packages/types/src/api/web/app/features.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/cookies.ts
  packages/types/src/sdk/featureFlag.ts
  packages/worker/src/api/index.ts
Labels: firestorm, size/m

#16036 Check if license key exists on AI Config page
  packages/builder/src/pages/builder/portal/settings/ai/PortalModal.svelte
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
  packages/builder/src/stores/portal/licensing.ts
Labels: firestorm, size/s

#16037 Fix for enabling BBAI on selfhost
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
Labels: firestorm, size/xs

#16038 Budibase AI UI tweaks based on feedback from product.
  packages/builder/src/components/common/CodeEditor/AIGen.svelte
  packages/builder/src/components/common/ai/AIInput.svelte
Labels: firestorm, size/s

#16043 Fix AI settings page
  packages/builder/src/components/common/CodeEditor/AIGen.svelte
  packages/builder/src/pages/builder/portal/settings/ai/AIConfigTile.svelte
  packages/builder/src/pages/builder/portal/settings/ai/PortalModal.svelte
  packages/builder/src/pages/builder/portal/settings/ai/constants.ts
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
  packages/types/src/documents/global/config.ts
Labels: firestorm, size/m

#16047 Update copy for self-host Budibase AI flow.
  packages/builder/src/pages/builder/portal/settings/ai/PortalModal.svelte
Labels: size/s
