Repository Budibase/budibase, pull requests merged in 2025-07, with the labels that each got.

#16470 Filter down to primary key options
  packages/builder/src/components/backend/Datasources/CreateEditRelationship.svelte
Labels: firestorm, size/xs

#16484 [Fix] Autogenerate screens from data
  packages/bbui/src/context.d.ts
  packages/builder/src/components/backend/DataTable/buttons/grid/GridGenerateButton.svelte
  packages/builder/src/constants/backend/automations.ts
  packages/builder/src/stores/builder/automations.ts
Labels: firestorm, size/s

#16485 Change email endpoint for account holder tenant users
  packages/server/.gitignore
  packages/types/src/api/web/user.ts
  packages/types/src/documents/platform/users.ts
  packages/worker/src/api/controllers/global/users.ts
  packages/worker/src/api/index.ts
  packages/worker/src/api/routes/global/users.ts
Labels: size/s

#16488 Make azure OpenAI config more clear
  packages/builder/src/pages/builder/portal/settings/ai/ConfigModal.svelte
Labels: firestorm, size/s

#16414 Prevents columns in Data section from being hidden on base-tables
  packages/builder/src/pages/builder/app/[application]/data/table/[tableId]/index.svelte
  packages/frontend-core/src/components/grid/cells/HeaderCell.svelte
  packages/frontend-core/src/components/grid/layout/Grid.svelte
  packages/frontend-core/src/components/grid/stores/index.ts
Labels: size/s, size/xs, size/m

#16493 [BUDI-9478] Fix exporting and importing a CSV to the same table.
  packages/backend-core/src/sql/sql.ts
  packages/backend-core/src/sql/utils.ts
  packages/server/src/api/routes/tests/importExport.spec.ts
  packages/server/src/integrations/mysql.ts
  packages/server/src/integrations/postgres.ts
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/map.ts
  packages/server/src/utilities/rowProcessor/utils.ts
  packages/server/src/utilities/schema.ts
Labels: firestorm, size/l

#16482 [BUDI-9240] Propagate OAuth2 information to external data connector and API Request automation steps
  packages/server/src/automations/steps/apiRequest.ts
  packages/server/src/automations/steps/executeQuery.ts
  packages/server/src/automations/steps/utils.ts
  packages/server/src/automations/tests/oauth2.spec.ts
  packages/server/src/sdk/users/utils.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
  packages/server/src/threads/query.ts
  packages/types/src/documents/global/user.ts
Labels: firestorm, size/m

#16498 Fix for budi backups tool on WSL
  packages/cli/src/backups/index.ts
Labels: size/xs

#16502 CI check for client library size
  .github/workflows/budibase_ci.yml
Labels: firestorm, size/s

#16514 Fix updatedby relationship type direction
  packages/builder/src/helpers/utils.ts
Labels: firestorm, size/xs

#16521 [BUDI-9364] Give sorting in views better labels based on field type.
  packages/builder/src/components/backend/DataTable/buttons/grid/GridSortButton.svelte
Labels: firestorm, size/s

#16522 Make processDates more resilient to invalid dates, and improve error reporting.
  packages/server/src/utilities/rowProcessor/utils.ts
Labels: firestorm, size/s

#16526 Revert "Correctly add new columns to design section tables"
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/getColumns.js
  packages/builder/src/components/design/settings/controls/GridColumnConfiguration/getColumns.test.js
  packages/frontend-core/src/components/grid/stores/columns.ts
Labels: firestorm, size/s

#16527 docs(helm): warning on persistent admin password
  charts/budibase/values.yaml
Labels: size/xs

#16531 Fix issue with collect blocks in button actions
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/BranchNode.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/TriggerAutomation.svelte
  packages/server/src/sdk/app/automations/utils.ts
  packages/shared-core/src/sdk/documents/automations.ts
Labels: firestorm, size/s

#16499 Resilient revert
  packages/backend-core/src/queue/constants.ts
  packages/backend-core/src/queue/inMemoryQueue.ts
  packages/backend-core/src/queue/index.ts
  packages/backend-core/src/queue/listeners.ts
  packages/backend-core/src/queue/queue.ts
  packages/backend-core/src/queue/queuedProcessor.ts
  packages/backend-core/tests/queue/queuedProcessor.spec.ts
  packages/builder/src/components/deploy/RevertModal.svelte
  packages/server/src/api/controllers/dev.ts
  packages/server/src/sdk/dev/devRevertProcessor.spec.ts
  packages/server/src/sdk/dev/devRevertProcessor.ts
  packages/server/src/sdk/dev/index.ts
  packages/server/src/sdk/index.ts
  packages/server/src/startup/index.ts
  packages/shared-core/src/helpers/helpers.ts
  packages/types/src/api/web/dev.ts
  packages/types/src/documents/app/backup.ts
Labels: firestorm, size/l, size/m

#16517 Fix MSSQL config validation
  packages/bbui/src/Form/Core/EnvDropdown.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/ConfigInput.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/fields/FieldGroup.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/index.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/stores/validatedConfig.test.ts
  packages/builder/src/components/backend/Datasources/ConfigEditor/stores/validatedConfig.ts
  packages/builder/src/components/backend/Datasources/ConfigEditor/stores/validation.ts
  packages/server/src/integrations/microsoftSqlServer.ts
Labels: firestorm, size/s, size/l, size/m

#16547 Small fix: for REST textarea for raw and jsonpreview
  packages/builder/src/components/integration/RestQueryViewer.svelte
Labels: size/xs

#16552 Centre align login header whenever the text wraps
  packages/builder/src/pages/builder/auth/login.svelte
Labels: size/xs

#16546 Nav update conflicts
  packages/builder/src/stores/builder/navigation.ts
  packages/builder/src/stores/builder/tests/navigation.test.js
  packages/frontend-core/src/api/navigation.ts
  packages/server/src/api/controllers/navigation.ts
  packages/server/src/api/controllers/workspaceApp.ts
  packages/server/src/api/routes/navigation.ts
  packages/server/src/api/routes/tests/navigation.spec.ts
  packages/server/src/api/routes/workspaceApp.ts
  packages/server/src/sdk/app/navigation/index.ts
  packages/server/src/tests/utilities/api/index.ts
  packages/server/src/tests/utilities/api/navigation.ts
  packages/server/src/tests/utilities/api/workspaceApp.ts
  packages/types/src/api/web/app/workspaceApp.ts
  packages/types/src/sdk/koa.ts
Labels: firestorm, size/m

#16574 Fix Google Sheet datasource creation.
  packages/builder/src/components/automation/SetupPanel/layouts/APIRequest.svelte
  packages/builder/src/components/backend/Datasources/ConfigEditor/stores/validatedConfig.test.ts
  packages/builder/src/components/backend/Datasources/ConfigEditor/stores/validatedConfig.ts
  packages/builder/src/constants/backend/index.ts
  packages/builder/src/stores/builder/datasources.ts
  packages/builder/src/stores/builder/integrations.ts
  packages/builder/src/stores/builder/queries.ts
  packages/builder/src/stores/builder/sortedIntegrations.ts
  packages/types/src/sdk/datasources.ts
  packages/types/src/ui/stores/integration.ts
Labels: firestorm, size/s, size/xs

#16458 Dev & pro migration conflicts
  packages/backend-core/src/redis/redlockImpl.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/deploy/index.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/appMigrations/index.ts
  packages/server/src/appMigrations/migrationLock.ts
  packages/server/src/appMigrations/migrations.ts
  packages/server/src/appMigrations/migrations/tests/20240604153647_initial_sqs.spec.ts
  packages/server/src/appMigrations/migrations/tests/20250618162639_workspace_apps.spec.ts
  packages/server/src/appMigrations/migrationsProcessor.ts
  packages/server/src/appMigrations/tests/migrationsProcessor.spec.ts
Labels: firestorm, size/l, size/m, size/xl

#16576 Introduce a suite of tests that test upgrading between Budibase versions.
  .github/workflows/budibase_ci.yml
  .github/workflows/upgrade-tests.yml
  eslint.config.mjs
  packages/server/package.json
  packages/upgrade-tests/.gitignore
  packages/upgrade-tests/README.md
  packages/upgrade-tests/docs/error-formatting-example.md
  packages/upgrade-tests/jest.config.ts
  packages/upgrade-tests/package.json
  packages/upgrade-tests/src/api/BudibaseClient.ts
  packages/upgrade-tests/src/api/application.ts
  packages/upgrade-tests/src/api/automation.ts
  packages/upgrade-tests/src/api/row.ts
  packages/upgrade-tests/src/api/table.ts
  packages/upgrade-tests/src/api/view.ts
  packages/upgrade-tests/src/cli/appImport.ts
  packages/upgrade-tests/src/cli/docker.ts
  packages/upgrade-tests/src/cli/index.ts
  packages/upgrade-tests/src/cli/testRunner.ts
  packages/upgrade-tests/src/fixtures/car-rental.tar.gz
  packages/upgrade-tests/src/index.ts
  packages/upgrade-tests/src/setup.ts
  packages/upgrade-tests/src/tests/automations.upgrade.test.ts
  packages/upgrade-tests/src/tests/tables.upgrade.test.ts
  packages/upgrade-tests/src/utils/BudibaseError.ts
  packages/upgrade-tests/src/utils/dockerLogs.ts
  packages/upgrade-tests/src/utils/testHelpers.ts
  packages/upgrade-tests/src/utils/upgradeTest.ts
  packages/upgrade-tests/tsconfig.build.json
  packages/upgrade-tests/tsconfig.json
  yarn.lock
Labels: firestorm, size/xl

#16590 Remove a difficult-to-read nested ternary.
  packages/backend-core/src/middleware/builderOnly.ts
Labels: firestorm, size/s

#16589 Migration processor for corrupted prod apps
  packages/server/src/appMigrations/migrationsProcessor.ts
  packages/server/src/sdk/app/applications/applications.ts
  packages/server/src/sdk/app/applications/utils.ts
  packages/server/src/sdk/users/sessions.ts
Labels: firestorm, size/s

#16592 Fix migration issues
  packages/server/src/appMigrations/migrationsProcessor.ts
Labels: firestorm, size/m

#16599 Update form-data to 4.0.4
  packages/server/package.json
  yarn.lock
Labels: firestorm, size/xs

#16598 App id consistency
  packages/backend-core/src/utils/tests/utils.spec.ts
  packages/backend-core/src/utils/utils.ts
  packages/backend-core/tests/core/utilities/structures/koa.ts
  packages/server/src/api/routes/tests/application.spec.ts
  packages/server/src/api/routes/tests/screen.spec.ts
Labels: firestorm, size/m

#16602 Fix out of sync migrations
  packages/server/src/appMigrations/migrationsProcessor.ts
  packages/server/src/appMigrations/tests/migrationsProcessor.spec.ts
Labels: firestorm, size/l, size/m

#16577 Improve migration integrity tests
  packages/server/src/appMigrations/tests/migrations.integrity.spec.ts
  packages/server/src/sdk/users/tests/utils.spec.ts
  packages/server/src/sdk/users/utils.ts
Labels: firestorm, size/m

#16596 upgrade-tests: support running against multiple apps, support sending extra jest args
  .github/workflows/upgrade-tests.yml
  packages/upgrade-tests/package.json
  packages/upgrade-tests/src/cli/index.ts
  packages/upgrade-tests/src/cli/testRunner.ts
  packages/upgrade-tests/src/fixtures/risk-management.tar.gz
  packages/upgrade-tests/src/utils/upgradeTest.ts
  yarn.lock
Labels: firestorm, size/m

#16549 Fix: added check to ensure certain columns couldn't be added as the first column of a table
  packages/bbui/src/Form/Core/Picker.svelte
  packages/bbui/src/Form/Core/Select.svelte
  packages/bbui/src/Form/Select.svelte
  packages/bbui/src/Tooltip/AbsTooltip.svelte
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
  packages/builder/src/stores/builder/tables.ts
  packages/server/src/api/routes/tests/table.spec.ts
  packages/shared-core/src/table.ts
Labels: size/s, size/m

#16615 Fix scroll on automation side-bar-nav class.
  packages/builder/src/components/automation/AutomationPanel/AutomationPanel.svelte
Labels: size/xs

#16622 Move away from anonymous functions for middleware
  packages/backend-core/src/logging/correlation/middleware.ts
  packages/backend-core/src/logging/pino/middleware.ts
  packages/backend-core/src/middleware/adminOnly.ts
  packages/backend-core/src/middleware/auditLog.ts
  packages/backend-core/src/middleware/authenticated.ts
  packages/backend-core/src/middleware/builderOnly.ts
  packages/backend-core/src/middleware/builderOrAdmin.ts
  packages/backend-core/src/middleware/contentSecurityPolicy.ts
  packages/backend-core/src/middleware/csrf.ts
  packages/backend-core/src/middleware/errorHandling.ts
  packages/backend-core/src/middleware/featureFlagCookie.ts
  packages/backend-core/src/middleware/index.ts
  packages/backend-core/src/middleware/internalApi.ts
  packages/backend-core/src/middleware/ip.ts
  packages/backend-core/src/middleware/querystringToBody.ts
  packages/backend-core/src/middleware/tenancy.ts
  packages/backend-core/src/middleware/tests/builder.spec.ts
  packages/backend-core/src/middleware/tests/contentSecurityPolicy.spec.ts
  packages/server/src/api/index.ts
  packages/server/src/api/routes/automation.ts
  packages/server/src/api/routes/backup.ts
  packages/server/src/api/routes/datasource.ts
  packages/server/src/api/routes/endpointGroups/standard.ts
  packages/server/src/api/routes/metadata.ts
  packages/server/src/api/routes/public/index.ts
  packages/server/src/api/routes/query.ts
  packages/server/src/api/routes/row.ts
  packages/server/src/api/routes/static.ts
  packages/server/src/api/routes/table.ts
  packages/server/src/api/routes/user.ts
  packages/server/src/api/routes/view.ts
  packages/server/src/middleware/appMigrations.ts
  packages/server/src/middleware/authorized.ts
  packages/server/src/middleware/builder.ts
  packages/server/src/middleware/cleanup.ts
  packages/server/src/middleware/currentapp.ts
  packages/server/src/middleware/ensureTenantAppOwnership.ts
  packages/server/src/middleware/publicApi.ts
  packages/server/src/middleware/tests/authorized.spec.ts
  packages/server/src/middleware/tests/currentapp.spec.ts
  packages/server/src/middleware/tests/ensureTenantAppOwnership.spec.ts
  packages/server/src/middleware/tests/trimViewRowInfo.spec.ts
  packages/server/src/middleware/trimViewRowInfo.ts
  packages/server/src/websockets/builder.ts
  packages/server/src/websockets/client.ts
  packages/server/src/websockets/grid.ts
Labels: firestorm, size/m

#16623 Remove icons from workspace apps
  packages/backend-core/tests/core/utilities/structures/workspaceApp.ts
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/WorkspaceAppList.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/WorkspaceApp/WorkspaceAppModal.svelte
  packages/builder/src/stores/builder/workspaceApps.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/workspaceApp.ts
  packages/server/src/api/routes/workspaceApp.ts
  packages/server/src/appMigrations/migrations/20250618162639_workspace_apps.ts
  packages/server/src/sdk/app/workspaceApps/crud.ts
  packages/types/src/api/web/app/workspaceApp.ts
  packages/types/src/documents/app/workspaceApp.ts
Labels: size/s

#16624 Serialize the upload and download of directories to S3.
  packages/backend-core/src/objectStore/objectStore.ts
  packages/server/src/sdk/app/backups/exports.ts
Labels: firestorm, size/m

#16625 Return doc on db.put
  packages/backend-core/src/db/couch/DatabaseImpl.ts
  packages/backend-core/src/db/couch/tests/DatabaseImpl.spec.ts
  packages/backend-core/src/db/instrumentation.ts
  packages/server/src/sdk/app/workspaceApps/crud.ts
  packages/types/src/sdk/db.ts
Labels: firestorm, size/s, size/m

#16628 Use bounded concurrency for retrieveDirectory
  packages/backend-core/src/objectStore/objectStore.ts
  packages/shared-core/src/utils.ts
Labels: firestorm, size/s

#16629 Close banners
  packages/builder/src/components/common/HeroBanner.svelte
  packages/builder/src/constants/banners.ts
  packages/builder/src/pages/builder/app/[application]/automation/_flagged/index.new.svelte
  packages/builder/src/pages/builder/app/[application]/design/_flagged/index.new.svelte
  packages/builder/src/stores/portal/banners.test.ts
  packages/builder/src/stores/portal/banners.ts
  packages/builder/src/stores/portal/index.ts
Labels: firestorm, size/m

#16630 Bump export concurrency to 5 and make sure export modal shows loading state.
  packages/backend-core/src/objectStore/objectStore.ts
  packages/builder/src/components/start/ExportAppModal.svelte
Labels: firestorm, size/xs

#16632 Support status correctly on index pages
  packages/builder/src/components/common/PublishStatusBadge.svelte
  packages/builder/src/pages/builder/app/[application]/automation/_flagged/index.new.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/_flagged/index.new.svelte
  packages/server/src/api/controllers/workspaceApp.ts
  packages/types/src/api/web/app/workspaceApp.ts
Labels: firestorm, size/s

#16634 Revert "Navigation from workspace app"
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/builder/screens.ts
  packages/frontend-core/src/api/workspaceApps.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/routes/navigation.ts
  packages/server/src/api/routes/tests/navigation.spec.ts
  packages/server/src/sdk/app/navigation/index.ts
  packages/types/src/documents/app/app.ts
Labels: size/m

#16641 Make sure tooltip position is at the bottom for banners
  packages/bbui/src/Banner/BannerDisplay.svelte
  packages/bbui/src/Tooltip/TooltipWrapper.svelte
  packages/builder/src/components/portal/licensing/licensingBanners.js
Labels: size/s

#16643 Improve put retrievedoc typing
  packages/server/src/sdk/app/workspaceApps/crud.ts
  packages/types/src/sdk/db.ts
Labels: firestorm, size/xs

#16642 Index pages - automations
  packages/bbui/src/helpers.ts
  packages/builder/src/pages/builder/app/[application]/automation/_flagged/index.new.svelte
  packages/builder/src/stores/builder/automations.ts
  packages/types/src/documents/app/automation/automation.ts
Labels: firestorm, size/m

#16648 Index pages - apps
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/AppPanel.svelte
  packages/builder/src/pages/builder/app/[application]/design/_flagged/index.new.svelte
  packages/builder/src/stores/builder/workspaceApps.ts
  packages/types/src/ui/workspaceApps.ts
Labels: firestorm, size/m

#16656 Allow the user to see the install info
  packages/bbui/src/Layout/Layout.svelte
  packages/builder/src/pages/builder/portal/account/upgrade.svelte
  packages/frontend-core/src/api/licensing.ts
  packages/types/src/api/web/global/license.ts
  packages/worker/src/api/controllers/global/license.ts
  packages/worker/src/api/routes/global/license.ts
Labels: size/s
