Repository Budibase/budibase, pull requests merged in 2025-05, with the labels that each got.

#16044 Show evaluation side panel on AI suggestion
  packages/builder/src/components/common/CodeEditor/CodeEditor.svelte
  packages/builder/src/components/common/bindings/BindingPanel.svelte
Labels: firestorm, size/xs

#16050 Remove erroneous cast.
  packages/worker/src/api/controllers/global/configs.ts
Labels: firestorm, size/xs

#16051 Show disabled AI providers in cloud
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
Labels: firestorm, size/xs

#16053 Allow anyone to make an AI column.
  packages/builder/src/components/backend/DataTable/modals/CreateEditColumn.svelte
Labels: firestorm, size/xs

#16056 Fix issue with AI table generation styling
  packages/builder/src/pages/builder/app/[application]/data/_components/AITableGeneration.svelte
Labels: firestorm, size/xs

#16054 Don't default the OPENAI_API_KEY to an invalid value locally.
  packages/server/scripts/dev/manage.js
Labels: firestorm, size/xs

#16046 Remove VerificationPromptBanner
  packages/builder/src/components/common/VerificationPromptBanner.svelte
  packages/builder/src/pages/builder/app/[application]/_layout.svelte
  packages/builder/src/pages/builder/portal/_layout.svelte
Labels: size/m

#16064 Notify when a request to get a user fails
  packages/builder/src/stores/portal/users.ts
Labels: firestorm, size/xs

#16057 Add option to refresh all data providers
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/RefreshDataProvider.svelte
  packages/client/src/components/ClientApp.svelte
  packages/client/src/stores/dataSource.js
Labels: size/s

#16045 Typing builder screen components
  packages/bbui/src/Icon/Icon.svelte
  packages/bbui/src/Layout/Layout.svelte
  packages/bbui/src/context.d.ts
  packages/bbui/src/types/index.ts
  packages/bbui/src/types/scrollContext.ts
  packages/builder/src/components/common/NavHeader.svelte
  packages/builder/src/components/common/NavItem.svelte
  packages/builder/src/components/design/ScreenDetailsModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/ScreenNavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/index.svelte
  packages/builder/src/stores/builder/contextMenu.ts
  packages/client/src/components/app/UserMenu.svelte
  packages/frontend-core/src/components/UserAvatar.svelte
  packages/frontend-core/src/components/UserAvatars.svelte
Labels: firestorm, size/m

#16070 Enable adding oauth2 config when none is yet created
  packages/builder/src/components/integration/rest/AuthPicker.svelte
Labels: firestorm, size/s

#16075 Hide AI custom config quota.
  packages/builder/src/pages/builder/portal/account/usage.svelte
Labels: firestorm, size/xs

#16063 Fix AI Config screen UI issue and add some tests
  packages/builder/src/pages/builder/portal/settings/ai/AISettings.spec.js
  packages/builder/src/pages/builder/portal/settings/ai/index.svelte
  packages/builder/vite.config.mjs
Labels: firestorm, size/m

#16076 Fix issue where clicking icon was clearing ai prompt
  packages/builder/src/components/common/CodeEditor/AIGen.svelte
  packages/builder/src/components/common/ai/AIInput.svelte
Labels: firestorm, size/s

#16078 Remove db calls in favour of the sdk usage
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/layout.ts
  packages/server/src/sdk/app/backups/statistics.ts
  packages/server/src/sdk/app/screens/screens.ts
Labels: firestorm, size/s

#16077 Parallelise processAIColumn calls
  packages/server/src/api/routes/tests/search.spec.ts
  packages/server/src/db/utils.ts
  packages/server/src/utilities/rowProcessor/utils.ts
Labels: firestorm, size/s

#16062 Ensure primary display column is always required
  packages/server/src/api/routes/tests/row.spec.ts
  packages/server/src/sdk/app/rows/tests/utils.spec.ts
  packages/server/src/sdk/app/rows/utils.ts
Labels: size/m

#16085 Don't clear user prompt if the user rejects a suggestion
  packages/builder/src/components/common/CodeEditor/AIGen.svelte
Labels: firestorm, size/s

#16093 Potential fix for user screen not loading in certain situations
  packages/builder/src/pages/builder/portal/users/users/[userId].svelte
Labels: size/xs

#16083 Graceful termination of the worker/app servers
  charts/budibase/templates/app-service-deployment.yaml
  charts/budibase/templates/worker-service-deployment.yaml
  packages/server/package.json
  packages/server/src/koa.ts
  packages/worker/package.json
  packages/worker/src/index.ts
  yarn.lock
Labels: size/m

#16071 Convert "create screen frontend" to TS
  packages/builder/src/components/design/ScreenDetailsModal.svelte
  packages/builder/src/helpers/components.ts
  packages/builder/src/helpers/data/format.ts
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/RoleIndicator.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/DatasourceModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/TypeModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/formTypes.ts
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/tableTypes.ts
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/utils.ts
  packages/builder/src/stores/builder/datasources.ts
  packages/builder/src/templates/BaseStructure.js
  packages/builder/src/templates/BaseStructure.ts
  packages/builder/src/templates/Component.ts
  packages/builder/src/templates/rowActions.ts
  packages/builder/src/templates/screenTemplating/Screen.ts
  packages/builder/src/templates/screenTemplating/blank.ts
  packages/builder/src/templates/screenTemplating/form.ts
  packages/builder/src/templates/screenTemplating/getValidRoute.ts
  packages/builder/src/templates/screenTemplating/index.ts
  packages/builder/src/templates/screenTemplating/pdf.ts
  packages/builder/src/templates/screenTemplating/table/index.ts
  packages/builder/src/templates/screenTemplating/table/inline.ts
  packages/builder/src/templates/screenTemplating/table/modal.ts
  packages/builder/src/templates/screenTemplating/table/newScreen.ts
  packages/builder/src/templates/screenTemplating/table/sidePanel.ts
  packages/client/src/components/app/blocks/form/FormBlock.svelte
  packages/frontend-core/src/utils/utils.ts
  packages/types/src/ui/common.ts
  packages/types/src/ui/index.ts
  packages/types/src/ui/permissions.ts
  packages/types/src/ui/stores/grid/datasource.ts
Labels: firestorm, size/l

#16096 Account for null roles object in app access check
  packages/shared-core/src/sdk/documents/users.ts
Labels: firestorm, size/xs

#16087 Add step sidebar in Automations
  packages/bbui/src/Form/Search.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/ActionModal.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowItemActions.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/SelectStepSidePanel.svelte
  packages/builder/src/components/design/Panel.svelte
  packages/builder/src/pages/builder/app/[application]/automation/_layout.svelte
  packages/builder/src/stores/builder/automations.ts
  packages/builder/src/types/automations.ts
  packages/shared-core/src/automations/steps/executeScriptV2.ts
Labels: firestorm, feature-branch, size/l

#16104 Improve error message while publishing an app with wrong cron settings
  packages/server/src/api/controllers/deploy/index.ts
  packages/server/src/automations/tests/triggers/cron.spec.ts
  packages/server/src/automations/utils.ts
Labels: firestorm, size/s

#16114 Fix some issues with new automation step panel
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/FlowChart.svelte
  packages/builder/src/components/automation/AutomationBuilder/FlowChart/SelectStepSidePanel.svelte
Labels: firestorm, size/xs

#16105 Type client screen store
  packages/client/src/components/app/filter/Filter.svelte
  packages/client/src/components/preview/DNDHandler.svelte
  packages/client/src/index.ts
  packages/client/src/stores/app.ts
  packages/client/src/stores/builder.ts
  packages/client/src/stores/derived/devToolsEnabled.js
  packages/client/src/stores/derived/dndComponentPath.js
  packages/client/src/stores/derived/snippets.js
  packages/client/src/stores/dnd.ts
  packages/client/src/stores/org.ts
  packages/client/src/stores/screens.ts
  packages/client/src/utils/components.ts
  packages/types/src/documents/app/layout.ts
Labels: firestorm, size/m

#16095 Proxy the 'refresh all data providers' action across screen peek modals
  packages/client/src/components/overlay/PeekScreenDisplay.svelte
  packages/client/src/constants.ts
  packages/client/src/stores/dataSource.js
  packages/client/src/stores/notification.ts
  packages/client/src/utils/buttonActions.js
Labels: size/s

#16118 Make date-only fields a bit more clever in accepting input dates.
  packages/backend-core/src/sql/sql.ts
  packages/backend-core/src/sql/utils.ts
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/s

#16130 Don't disconnect on error.
  packages/backend-core/src/redis/redis.ts
Labels: firestorm, size/xs

#16131 Flag off the agent sidebar.
  packages/builder/src/pages/builder/portal/apps/_components/PortalSideBar.svelte
Labels: firestorm, size/s

#16134 Make pod termination grace period configurable.
  charts/budibase/README.md
  charts/budibase/templates/app-service-deployment.yaml
  charts/budibase/templates/automation-worker-service-deployment.yaml
  charts/budibase/templates/worker-service-deployment.yaml
  charts/budibase/values.yaml
Labels: firestorm, size/s

#16146 Update node image usage to 22
  hosting/single/Dockerfile
  packages/server/Dockerfile
  packages/worker/Dockerfile
Labels: firestorm, feature-branch, size/xs

#16147 Fix query parameter binding when passing a 0, it shouldn't fall back to the default value.
  packages/server/src/api/controllers/query/index.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
  packages/server/src/threads/definitions.ts
  packages/types/src/api/web/app/query.ts
Labels: firestorm, size/s

#16150 Protect against group.roles being undefined on the user details page.
  packages/builder/src/pages/builder/portal/users/users/[userId].svelte
Labels: firestorm, size/xs

#16151 Update node usage in bb/couchdb image
  hosting/couchdb/Dockerfile
Labels: firestorm, size/xs

#16145 Project apps feature flag
  packages/backend-core/src/features/features.ts
  packages/builder/src/stores/builder/screens.ts
  packages/builder/src/stores/builder/tests/screens.test.js
  packages/builder/src/templates/screenTemplating/Screen.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/appMigrations/migrations.ts
  packages/server/src/constants/screens.ts
  packages/types/src/api/web/app/application.ts
  packages/types/src/documents/app/screen.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/s

#16155 Fix flake in generic-sql.spec.ts.
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
Labels: firestorm, size/xs

#16154 Upgrade lerna from 7 -> 8
  .tool-versions
  package.json
  yarn.lock
Labels: size/xs

#16157 Revert "Upgrade lerna from 7 -> 8"
  .tool-versions
  package.json
  yarn.lock
Labels: firestorm, size/xs

#16106 Filter pill buttons are now resizable
  packages/client/manifest.json
  packages/client/src/components/app/filter/Filter.svelte
  packages/client/src/components/app/filter/FilterButton.svelte
Labels: size/s

#16103 Automation SMTP markdown support
  packages/builder/src/components/automation/SetupPanel/AutomationSchemaLayout.svelte
  packages/builder/src/components/automation/SetupPanel/BlockProperties.svelte
  packages/builder/src/types/automations.ts
  packages/shared-core/src/automations/steps/sendSmtpEmail.ts
  packages/types/src/documents/app/automation/automation.ts
  packages/worker/package.json
  packages/worker/src/api/routes/global/tests/email.spec.ts
  packages/worker/src/utilities/email.ts
  yarn.lock
Labels: feature-branch, size/m

#16015 Barcode QRcode
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/[componentId]/new/_components/componentStructure.json
  packages/client/manifest.json
  packages/client/package.json
  packages/client/src/components/app/CodeGenerator.svelte
  packages/client/src/components/app/index.js
  yarn.lock
Labels: size/m

#16163 adds new pill to Barcode/QR Generator
  packages/client/manifest.json
Labels: size/xs

#16090 Move from Source Sans Pro to variable weight Source Sans 3
  packages/bbui/src/bbui.css
  packages/builder/assets/source-sans-3/SourceSans3VF-Italic.ttf.woff2
  packages/builder/assets/source-sans-3/SourceSans3VF-Upright.ttf.woff2
  packages/builder/assets/source-sans-3/source-sans-3.css
  packages/builder/index.html
  packages/builder/package.json
  packages/builder/src/pages/builder/portal/apps/onboarding/_components/ExampleApp.svelte
  packages/builder/vite.config.mjs
  packages/frontend-core/src/components/ClientAppSkeleton.svelte
  packages/server/src/api/controllers/static/templates/BudibaseApp.svelte
  packages/server/src/api/controllers/static/templates/preview.hbs
  packages/worker/src/constants/templates/base.hbs
  yarn.lock
Labels: size/s

#16164 Rename project app to workspace app
  packages/backend-core/src/docIds/params.ts
  packages/builder/src/stores/builder/screens.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/projectApp.ts
  packages/server/src/api/controllers/workspaceApp.ts
  packages/server/src/api/routes/index.ts
  packages/server/src/api/routes/workspaceApp.ts
  packages/server/src/appMigrations/migrations.ts
  packages/server/src/appMigrations/migrations/20250514133719_workspace_apps.ts
  packages/server/src/constants/screens.ts
  packages/server/src/sdk/app/projectApps/index.ts
  packages/server/src/sdk/app/workspaceApps/index.ts
  packages/server/src/sdk/index.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/tests/utilities/structures/screens.ts
  packages/types/src/api/web/app/application.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/app/projectApp.ts
  packages/types/src/api/web/app/workspaceApp.ts
  packages/types/src/documents/app/index.ts
  packages/types/src/documents/app/screen.ts
  packages/types/src/documents/app/workspaceApp.ts
  packages/types/src/documents/document.ts
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/m

#16129 New project apps backend crud
  packages/backend-core/src/docIds/params.ts
  packages/backend-core/src/features/features.ts
  packages/builder/src/stores/builder/screens.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/workspaceApp.ts
  packages/server/src/api/routes/index.ts
  packages/server/src/api/routes/tests/screen.spec.ts
  packages/server/src/api/routes/workspaceApp.ts
  packages/server/src/appMigrations/migrations.ts
  packages/server/src/appMigrations/migrations/20250514133719_workspace_apps.ts
  packages/server/src/constants/screens.ts
  packages/server/src/sdk/app/oauth2/crud.ts
  packages/server/src/sdk/app/screens/screens.ts
  packages/server/src/sdk/app/tables/create.ts
  packages/server/src/sdk/app/tables/external/index.ts
  packages/server/src/sdk/app/tables/internal/index.ts
  packages/server/src/sdk/app/workspaceApps/index.ts
  packages/server/src/sdk/index.ts
  packages/server/src/tests/utilities/structures.ts
  packages/server/src/tests/utilities/structures/screens.ts
  packages/types/src/api/web/app/application.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/app/workspaceApp.ts
  packages/types/src/documents/app/index.ts
  packages/types/src/documents/app/screen.ts
  packages/types/src/documents/app/workspaceApp.ts
  packages/types/src/documents/document.ts
  packages/types/src/sdk/featureFlag.ts
  packages/types/src/shared/typeUtils.ts
  packages/worker/src/api/routes/global/tests/roles.spec.ts
Labels: firestorm, size/l

#16166 Rename workspace to tenant
  packages/builder/src/pages/builder/app/[application]/_components/BuilderSidePanel.svelte
  packages/frontend-core/src/constants.ts
Labels: size/xs

#16165 Always fetch a new presigned url for attachments
  packages/server/src/utilities/rowProcessor/index.ts
  packages/server/src/utilities/rowProcessor/tests/outputProcessing.spec.ts
Labels: firestorm, size/xs

#16175 Prepends Datasource to tables and views in App Actions
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/DeleteRow.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/DuplicateRow.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/FetchRow.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/RowAction.svelte
  packages/builder/src/components/design/settings/controls/ButtonActionEditor/actions/SaveRow.svelte
Labels: size/m

#16188 Fix for automation snippets
  packages/server/src/threads/automation.ts
Labels: size/xs

#16177 Move screen creation to sdk
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/screen.ts
  packages/server/src/sdk/app/screens/screens.ts
Labels: firestorm, size/s

#16193 Remove workspaceApps from appPackage response
  packages/builder/src/stores/builder/screens.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/controllers/workspaceApp.ts
  packages/server/src/api/routes/workspaceApp.ts
  packages/types/src/api/web/app/application.ts
  packages/types/src/api/web/app/workspaceApp.ts
Labels: firestorm, size/s

#16190 Manage navigation on the backend
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/ScreenNavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/stores/builder/app.ts
  packages/builder/src/stores/builder/navigation.ts
  packages/builder/src/stores/builder/screens.ts
  packages/builder/src/stores/builder/tests/app.test.js
  packages/builder/src/stores/builder/tests/navigation.test.js
  packages/builder/src/stores/builder/tests/screens.test.js
  packages/frontend-core/src/api/index.ts
  packages/frontend-core/src/api/navigation.ts
  packages/frontend-core/src/api/types.ts
  packages/server/src/api/controllers/navigation.ts
  packages/server/src/api/controllers/screen.ts
  packages/server/src/api/routes/index.ts
  packages/server/src/api/routes/navigation.ts
  packages/server/src/sdk/app/navigation/index.ts
  packages/server/src/sdk/index.ts
  packages/types/src/api/web/app/index.ts
  packages/types/src/api/web/app/navigation.ts
  packages/types/src/api/web/app/screen.ts
  packages/types/src/documents/app/app.ts
Labels: firestorm, size/m

#16201 Enable JS and table AI generation to self-hosters by default
  packages/types/src/sdk/featureFlag.ts
Labels: firestorm, size/xs

#16176 Fix for resetOn behaviour
  packages/builder/package.json
  packages/builder/src/stores/builder/components.ts
  packages/builder/src/stores/builder/tests/component.test.js
  packages/builder/src/stores/builder/tests/fixtures/index.js
Labels: size/l

#16191 Improve handling of app versions in dev mode
  .gitignore
  eslint.config.mjs
  package.json
  packages/builder/src/components/deploy/AppActions.svelte
  packages/builder/src/components/deploy/RevertModalVersionSelect.svelte
  packages/builder/src/components/deploy/VersionModal.svelte
  packages/builder/src/components/deploy/clientVersions.json
  packages/builder/src/pages/builder/app/[application]/settings/general.svelte
  packages/frontend-core/src/api/app.ts
  packages/server/src/api/controllers/application.ts
  packages/server/src/api/routes/application.ts
  packages/server/src/utilities/fileSystem/clientLibrary.ts
  packages/types/src/api/web/app/application.ts
  scripts/build.js
  scripts/getPastClientVersion.js
Labels: feature-branch, size/m

#16202 [BUDI-9179] Fix "duplicate key violation" errors when updating many-to-many fields.
  packages/backend-core/src/sql/sql.ts
  packages/server/src/api/controllers/row/ExternalRequest.ts
  packages/server/src/api/routes/tests/row.spec.ts
Labels: firestorm, size/m

#16127 Workspace apps frontend CRUD
  packages/bbui/src/Form/Input.svelte
  packages/bbui/src/Markdown/MarkdownViewer.svelte
  packages/builder/src/components/ContextMenu.svelte
  packages/builder/src/components/common/EditableIcon.svelte
  packages/builder/src/components/common/NavHeader.svelte
  packages/builder/src/components/common/NavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/RoleIndicator.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/ScreenNavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/WorkspaceAppList.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/WorkspaceAppNavItem.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/ScreenList/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/[screenId]/_components/WorkspaceApp/WorkspaceAppModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/CreateScreenModal.svelte
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/index.svelte
  packages/builder/src/pages/builder/app/[application]/design/new.svelte
  packages/builder/src/stores/builder/contextMenu.ts
  packages/builder/src/stores/builder/index.ts
  packages/builder/src/stores/builder/screens.ts
  packages/builder/src/stores/builder/tests/screens.test.js
  packages/builder/src/stores/builder/workspaceApps.ts
  packages/builder/src/templates/screenTemplating/Screen.ts
  packages/builder/src/templates/screenTemplating/blank.ts
  packages/builder/src/templates/screenTemplating/form.ts
  packages/builder/src/templates/screenTemplating/pdf.ts
  packages/builder/src/templates/screenTemplating/table/index.ts
  packages/builder/src/templates/screenTemplating/table/inline.ts
  packages/builder/src/templates/screenTemplating/table/modal.ts
  packages/builder/src/templates/screenTemplating/table/newScreen.ts
  packages/builder/src/templates/screenTemplating/table/sidePanel.ts
  packages/frontend-core/src/api/index.ts
  packages/frontend-core/src/api/screens.ts
  packages/frontend-core/src/api/types.ts
  packages/frontend-core/src/api/workspaceApps.ts
  packages/server/src/api/controllers/layout.ts
  packages/server/src/api/controllers/screen.ts
  packages/server/src/sdk/app/workspaceApps/index.ts
  packages/types/src/api/web/app/workspaceApp.ts
  packages/types/src/documents/app/app.ts
  packages/types/src/ui/index.ts
  packages/types/src/ui/workspaceApps.ts
Labels: firestorm, feature-branch, size/xs, size/xl

#16223 Fix undefined reference while adding your first screen
  packages/builder/src/pages/builder/app/[application]/design/_components/NewScreen/index.svelte
Labels: firestorm, size/xs

#16231 Some remaing test conversions to ts
  packages/server/src/api/controllers/query/import/tests/index.spec.ts
  packages/server/src/api/routes/tests/analytics.spec.ts
  packages/server/src/api/routes/tests/auth.spec.ts
  packages/server/src/api/routes/tests/dev.spec.ts
  packages/server/src/api/routes/tests/integration.spec.ts
  packages/server/src/api/routes/tests/layout.spec.ts
  packages/server/src/tests/utilities/TestConfiguration.ts
Labels: firestorm, size/s, size/m

#16216 Strip user information if the user does not need it
  packages/types/src/api/web/user.ts
  packages/types/src/documents/global/user.ts
  packages/worker/src/api/controllers/global/users.ts
  packages/worker/src/api/routes/global/tests/users.spec.ts
  packages/worker/src/tests/TestConfiguration.ts
  packages/worker/src/tests/api/users.ts
Labels: firestorm, size/m

#16233 Use default values when empty string is passed
  packages/server/src/api/controllers/query/index.ts
  packages/server/src/api/routes/tests/queries/generic-sql.spec.ts
Labels: firestorm, size/s, size/xs
